"use client";

import { useEffect, useState } from "react";

type Currency = "coins" | "gems" | "naira";
type Category = { id:string; name:string; slug:string; description:string; isActive:boolean; sortOrder:number };
type Avatar = { id:string; name:string; description:string; categoryId:string|null; category:string|null; rarity:string; currency:Currency; price:number; isPublished:boolean; sortOrder:number; hasImage:boolean; imageUrl:string|null; icon:string|null };

const currencies:[Currency,string][] = [["naira","₦ Naira"],["coins","🪙 Coins"],["gems","💎 Gems"]];
const rarities = ["COMMON","RARE","EPIC","LEGENDARY"];

export default function AvatarManager(){
  const [avatars,setAvatars]=useState<Avatar[]>([]),[categories,setCategories]=useState<Category[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[file,setFile]=useState<File|null>(null),[form,setForm]=useState({name:"",description:"",categoryId:"classic",rarity:"COMMON",currency:"coins" as Currency,price:"0"}),[editing,setEditing]=useState<string|null>(null);
  const load=async()=>{setNotice("");try{const r=await fetch("/api/admin/avatars",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load avatars");setAvatars(d.avatars||[]);setCategories(d.categories||[])}catch(e){setNotice(e instanceof Error?e.message:"Unable to load avatar manager.")}};
  useEffect(()=>{void load()},[]);
  const reset=()=>{setEditing(null);setFile(null);setForm({name:"",description:"",categoryId:"classic",rarity:"COMMON",currency:"coins",price:"0"});};
  const create=async()=>{if(!file){setNotice("Choose an avatar image first.");return}setBusy(true);setNotice("");try{const fd=new FormData();fd.set("name",form.name);fd.set("description",form.description);fd.set("categoryId",form.categoryId);fd.set("rarity",form.rarity);fd.set("currency",form.currency);fd.set("price",form.price);fd.set("image",file);const r=await fetch("/api/admin/avatars",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw Error(d.error||"Upload failed");setAvatars(d.avatars||[]);setCategories(d.categories||[]);setNotice("Avatar published successfully.");reset()}catch(e){setNotice(e instanceof Error?e.message:"Unable to publish avatar.")}finally{setBusy(false)}};
  const update=async(id:string,patch:Partial<Avatar>)=>{setBusy(true);setNotice("");try{const r=await fetch("/api/admin/avatars",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})});const d=await r.json();if(!r.ok)throw Error(d.error||"Update failed");setAvatars(d.avatars||[]);setCategories(d.categories||[]);setNotice("Avatar updated.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to update avatar.")}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!confirm("Delete this avatar permanently? Its stored artwork will also be removed."))return;setBusy(true);try{const r=await fetch("/api/admin/avatars",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw Error(d.error||"Delete failed");setAvatars(d.avatars||[]);setNotice("Avatar deleted.")}catch(e){setNotice(e instanceof Error?e.message:"Unable to delete avatar.")}finally{setBusy(false)}};
  return <main style={wrap}><header style={header}><div><div style={eyebrow}>LUDO LIVE • AVATAR CATALOGUE</div><h1>🧑‍🎨 Avatar Manager</h1><p style={muted}>Upload artwork, set identity, category, rarity and price. Changes are live in the player Shop.</p></div><button style={ghost} onClick={load}>↻ Refresh</button></header>{notice&&<div style={noticeStyle}>{notice}</div>}
  <section style={composer}><h2>{editing?"Edit Avatar":"Add Avatar"}</h2><div style={formGrid}><label>Avatar image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>PNG, JPEG or WebP • max 1.5 MB</small></label><label>Name<input value={form.name} maxLength={80} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}>{categories.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Rarity<select value={form.rarity} onChange={e=>setForm({...form,rarity:e.target.value})}>{rarities.map(x=><option key={x}>{x}</option>)}</select></label><label>Currency<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value as Currency})}>{currencies.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Price<input type="number" min="0" step="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label style={{gridColumn:"1/-1"}}>Description<textarea value={form.description} maxLength={300} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div style={actions}><button style={ghost} onClick={reset}>Clear</button>{editing?null:<button style={good} disabled={busy} onClick={create}>{busy?"Publishing…":"Publish Avatar"}</button>}</div></section>
  <section style={list}><div style={sectionHead}><h2>Published & Draft Avatars</h2><span>{avatars.length} managed</span></div>{avatars.length===0?<p style={muted}>No uploaded avatars yet. The original six built-in avatars remain available in the Shop.</p>:avatars.map(a=><article style={row} key={a.id}><div style={preview}>{a.imageUrl?<img src={a.imageUrl} alt=""/>:<span>{a.icon||"🧑‍🎮"}</span>}</div><div style={identity}><b>{a.name}</b><small>{a.category||"Uncategorized"} • {a.rarity}</small><small>{a.currency.toUpperCase()} {a.price.toLocaleString()}</small></div><select style={input} value={a.categoryId||""} onChange={e=>update(a.id,{categoryId:e.target.value||null})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button style={a.isPublished?good:ghost} disabled={busy} onClick={()=>update(a.id,{isPublished:!a.isPublished})}>{a.isPublished?"Published":"Hidden"}</button><button style={danger} disabled={busy} onClick={()=>remove(a.id)}>Delete</button></article>)}</section>
  <section style={note}><b>Categories</b><p>Built-in categories: {categories.map(c=>c.name).join(" • ")}. New category management can be added here without changing avatar records.</p></section></main>;
}
const wrap:any={minHeight:"100vh",background:"radial-gradient(circle at top,#102a55 0,#050b1d 42%,#020611 100%)",color:"#e8f0ff",padding:"28px clamp(14px,4vw,50px) 70px",fontFamily:"system-ui",maxWidth:1400,margin:"auto"};
const header:any={display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:18};const eyebrow:any={fontSize:11,color:"#69a8ff",fontWeight:900,letterSpacing:2};const muted:any={color:"#8fa5c5",fontSize:13};const composer:any={background:"rgba(8,19,42,.94)",border:"1px solid #29466f",borderRadius:20,padding:20,marginBottom:18};const formGrid:any={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12};const label:any={display:"grid",gap:6,color:"#b8c9e3",fontSize:12,fontWeight:800};const input:any={width:"100%",boxSizing:"border-box",background:"#071024",color:"white",border:"1px solid #2b466f",borderRadius:10,padding:"10px 11px"};const actions:any={display:"flex",justifyContent:"flex-end",gap:8,marginTop:15};const ghost:any={border:"1px solid #35527f",background:"#0a1731",color:"#dce9ff",padding:"9px 13px",borderRadius:9,fontWeight:850,cursor:"pointer"};const good:any={...ghost,background:"#116b42",borderColor:"#31b978",color:"white"};const danger:any={...ghost,background:"#6d1d2b",borderColor:"#d65a6d",color:"white"};const noticeStyle:any={padding:12,borderRadius:10,border:"1px solid #315b8d",background:"#0a1934",marginBottom:14};const list:any={background:"rgba(8,19,42,.94)",border:"1px solid #29466f",borderRadius:20,padding:20};const sectionHead:any={display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10};const row:any={display:"grid",gridTemplateColumns:"64px minmax(180px,1fr) 180px 110px 90px",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid #1a2b49"};const preview:any={width:64,height:64,borderRadius:12,overflow:"hidden",display:"grid",placeItems:"center",background:"transparent",fontSize:40};const identity:any={display:"grid",gap:3};const note:any={marginTop:18,padding:16,border:"1px solid #29466f",borderRadius:16,background:"#07142c"};
