"use client";

import { useEffect,useState } from "react";

type Currency="coins"|"gems"|"naira";
type Category={id:string;name:string;slug:string;description:string;isActive:boolean;sortOrder:number};
type Avatar={id:string;name:string;description:string;categoryId:string|null;category:string|null;rarity:string;currency:Currency;price:number;isPublished:boolean;sortOrder:number;hasImage:boolean;imageUrl:string|null;icon:string|null;isBuiltin:boolean};
const currencies:[Currency,string][]=[["naira","₦ Naira"],["coins","🪙 Coins"],["gems","💎 Gems"]];
const rarities=["COMMON","RARE","EPIC","LEGENDARY"];
const emptyForm={name:"",description:"",categoryId:"classic",rarity:"COMMON",currency:"coins" as Currency,price:"0",isPublished:true};

/** Converts any supported source artwork into a square avatar canvas without cropping it. */
async function prepareAvatarImage(file:File):Promise<File>{
  if(!["image/png","image/jpeg","image/webp"].includes(file.type))throw Error("Only PNG, JPEG and WebP images are supported.");
  const url=URL.createObjectURL(file);
  try{
    const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("The selected image could not be decoded."));img.src=url;});
    const sourceWidth=image.naturalWidth,sourceHeight=image.naturalHeight;
    if(!sourceWidth||!sourceHeight)throw Error("The selected image has invalid dimensions.");
    if(sourceWidth===sourceHeight&&sourceWidth>=128&&sourceWidth<=2048&&file.size<=1_500_000)return file;
    const side=Math.min(2048,Math.max(sourceWidth,sourceHeight));
    if(side<128)throw Error("Avatar artwork must be at least 128px on its longest side.");
    const canvas=document.createElement("canvas");canvas.width=side;canvas.height=side;
    const ctx=canvas.getContext("2d");if(!ctx)throw Error("Your browser could not prepare the avatar image.");
    ctx.clearRect(0,0,side,side);
    const scale=Math.min(side/sourceWidth,side/sourceHeight);
    const width=Math.round(sourceWidth*scale),height=Math.round(sourceHeight*scale);
    const x=Math.round((side-width)/2),y=Math.round((side-height)/2);
    ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(image,x,y,width,height);
    const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",0.92));
    if(!blob)throw Error("The browser could not encode the avatar image.");
    if(blob.size>1_500_000)throw Error("The prepared avatar image is larger than 1.5 MB. Please use a smaller or simpler source image.");
    return new File([blob],`avatar-${Date.now()}.webp`,{type:"image/webp",lastModified:Date.now()});
  }finally{URL.revokeObjectURL(url);}
}

export default function AvatarManager(){
 const[avatars,setAvatars]=useState<Avatar[]>([]),[categories,setCategories]=useState<Category[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[file,setFile]=useState<File|null>(null),[sourceName,setSourceName]=useState(""),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState<string|null>(null),[categoryName,setCategoryName]=useState(""),[categoryDescription,setCategoryDescription]=useState("");
 const load=async()=>{try{const r=await fetch("/api/admin/avatars",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load avatars");setAvatars(d.avatars||[]);setCategories(d.categories||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load avatar manager.")}};
 useEffect(()=>{void load()},[]);
 const reset=()=>{setEditing(null);setFile(null);setSourceName("");setForm({...emptyForm})};
 const chooseFile=async(raw:File|null)=>{setError("");setNotice("");setFile(null);setSourceName("");if(!raw)return;try{const prepared=await prepareAvatarImage(raw);setFile(prepared);setSourceName(raw.name);setNotice("Artwork prepared automatically: the full image will be preserved and fitted without cropping.")}catch(e){setError(e instanceof Error?e.message:"Unable to prepare avatar artwork.")}};
 const save=async()=>{setBusy(true);setNotice("");setError("");try{if(!editing&&!file)throw Error("Choose an avatar image first.");const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.set(k,String(v)));if(file)fd.set("image",file);let r;if(editing){fd.set("id",editing);r=await fetch("/api/admin/avatars",{method:"PATCH",body:fd})}else r=await fetch("/api/admin/avatars",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw Error(d.error||"Save failed");setAvatars(d.avatars||[]);setCategories(d.categories||[]);setNotice(editing?"Avatar updated successfully.":"Avatar published successfully.");reset()}catch(e){setError(e instanceof Error?e.message:"Unable to save avatar.")}finally{setBusy(false)}};
 const edit=(a:Avatar)=>{setEditing(a.id);setFile(null);setSourceName("");setForm({name:a.name,description:a.description,categoryId:a.categoryId||"classic",rarity:a.rarity,currency:a.currency,price:String(a.price),isPublished:a.isPublished});window.scrollTo({top:0,behavior:"smooth"})};
 const update=async(id:string,patch:any)=>{setBusy(true);try{const r=await fetch("/api/admin/avatars",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})}),d=await r.json();if(!r.ok)throw Error(d.error||"Update failed");setAvatars(d.avatars||[]);setCategories(d.categories||[]);setNotice("Avatar updated.")}catch(e){setError(e instanceof Error?e.message:"Unable to update avatar.")}finally{setBusy(false)}};
 const remove=async(id:string)=>{if(!confirm("Delete this avatar permanently?"))return;setBusy(true);try{const r=await fetch("/api/admin/avatars",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})}),d=await r.json();if(!r.ok)throw Error(d.error||"Delete failed");setAvatars(d.avatars||[]);setNotice("Avatar deleted.")}catch(e){setError(e instanceof Error?e.message:"Unable to delete avatar.")}finally{setBusy(false)}};
 const addCategory=async()=>{if(!categoryName.trim())return;setBusy(true);try{const fd=new FormData();fd.set("kind","category");fd.set("name",categoryName);fd.set("description",categoryDescription);const r=await fetch("/api/admin/avatars",{method:"POST",body:fd}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to create category");setCategories(d.categories||[]);setCategoryName("");setCategoryDescription("");setNotice("Category created.")}catch(e){setError(e instanceof Error?e.message:"Unable to create category.")}finally{setBusy(false)}};
 const updateCategory=async(c:Category)=>{const name=prompt("Category name",c.name);if(!name?.trim())return;await updateCategoryRequest({...c,name:name.trim()})};
 const updateCategoryRequest=async(c:any)=>{setBusy(true);try{const r=await fetch("/api/admin/avatars",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"category",id:c.id,name:c.name,description:c.description,isActive:c.isActive,sortOrder:c.sortOrder})}),d=await r.json();if(!r.ok)throw Error(d.error||"Category update failed");setCategories(d.categories||[]);setNotice("Category updated.")}catch(e){setError(e instanceof Error?e.message:"Unable to update category.")}finally{setBusy(false)}};
 const deleteCategory=async(c:Category)=>{if(c.id==="classic"||!confirm(`Delete ${c.name}? Avatars will become uncategorized.`))return;setBusy(true);try{const r=await fetch("/api/admin/avatars",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"category",id:c.id})}),d=await r.json();if(!r.ok)throw Error(d.error||"Category delete failed");setCategories(d.categories||[]);setAvatars(d.avatars||[]);setNotice("Category deleted.")}catch(e){setError(e instanceof Error?e.message:"Unable to delete category.")}finally{setBusy(false)}};
 return <main style={wrap}><header style={header}><div><div style={eyebrow}>LUDO LIVE • AVATAR CATALOGUE</div><h1>🧑‍🎨 Avatar Management</h1><p style={muted}>One database-backed avatar record drives Admin → Shop → Purchase → Inventory → Profile → Game.</p></div><button style={ghost} onClick={()=>void load()}>↻ Refresh</button></header>
 {notice&&<div style={noticeStyle}>{notice}</div>}{error&&<div style={errorStyle}>{error}</div>}
 <section style={composer}><h2>{editing?"Edit Avatar":"Create Avatar"}</h2><div style={formGrid}><label>Artwork<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void chooseFile(e.target.files?.[0]||null)}/><small>PNG/JPEG/WebP • any aspect ratio • max 2048px • max 1.5 MB source. Full artwork is automatically fitted into the avatar canvas — never cropped.{editing?" • leave empty to keep current artwork":""}</small>{sourceName&&<small>Prepared from: {sourceName} → {file?.type||"avatar image"}</small>}</label><label>Name<input value={form.name} maxLength={80} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}>{categories.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Rarity<select value={form.rarity} onChange={e=>setForm({...form,rarity:e.target.value})}>{rarities.map(x=><option key={x}>{x}</option>)}</select></label><label>Currency<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value as Currency})}>{currencies.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Price<input type="number" min="0" step="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label style={{gridColumn:"1/-1"}}>Description<textarea value={form.description} maxLength={300} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div style={actions}><button style={ghost} onClick={reset}>Clear</button><button style={good} disabled={busy} onClick={()=>void save()}>{busy?(editing?"Saving…":"Publishing…"):(editing?"Save Changes":"Publish Avatar")}</button></div></section>
 <section style={panel}><div style={sectionHead}><h2>Managed Avatars</h2><span>{avatars.length} records</span></div>{avatars.map(a=><article style={row} key={a.id}><div style={preview}>{a.imageUrl?<img src={a.imageUrl} alt="" style={{width:"100%",height:"100%",objectFit:"contain"}} onError={e=>{e.currentTarget.style.display="none"}}/>:<span>{a.icon||"🧑‍🎮"}</span>}</div><div style={identity}><b>{a.name}{a.isBuiltin?" · Built-in":""}</b><small>{a.category||"Uncategorized"} • {a.rarity}</small><small>{a.currency.toUpperCase()} {a.price.toLocaleString()} • order {a.sortOrder}</small></div><button style={ghost} disabled={busy} onClick={()=>edit(a)}>Edit</button><button style={a.isPublished?good:ghost} disabled={busy} onClick={()=>void update(a.id,{isPublished:!a.isPublished})}>{a.isPublished?"Published":"Hidden"}</button><button style={danger} disabled={busy||a.isBuiltin} onClick={()=>void remove(a.id)}>{a.isBuiltin?"Protected":"Delete"}</button><div style={reorder}><button style={mini} onClick={()=>void update(a.id,{sortOrder:a.sortOrder-1})}>↑</button><button style={mini} onClick={()=>void update(a.id,{sortOrder:a.sortOrder+1})}>↓</button></div></article>)}</section>
 <section style={panel}><h2>Categories</h2><div style={categoryComposer}><input placeholder="New category name" value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><input placeholder="Description" value={categoryDescription} onChange={e=>setCategoryDescription(e.target.value)}/><button style={good} disabled={busy} onClick={()=>void addCategory()}>+ Add</button></div><div style={categoryGrid}>{categories.map(c=><article key={c.id} style={categoryCard}><div><b>{c.name}</b><small>{c.description||"No description"}</small></div><span>{c.isActive?"Active":"Hidden"}</span><button style={ghost} disabled={busy} onClick={()=>void updateCategoryRequest({...c,isActive:!c.isActive})}>{c.isActive?"Hide":"Show"}</button><button style={ghost} disabled={busy} onClick={()=>void updateCategory(c)}>Rename</button>{c.id!=="classic"&&<button style={danger} disabled={busy} onClick={()=>void deleteCategory(c)}>Delete</button>}</article>)}</div></section>
 </main>;
}
const wrap:any={minHeight:"100vh",background:"radial-gradient(circle at top,#102a55 0,#050b1d 42%,#020611 100%)",color:"#e8f0ff",padding:"28px clamp(14px,4vw,50px) 70px",fontFamily:"system-ui",maxWidth:1400,margin:"auto"};const header:any={display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",marginBottom:18};const eyebrow:any={fontSize:11,color:"#69a8ff",fontWeight:900,letterSpacing:2};const muted:any={color:"#8fa5c5",fontSize:13};const panel:any={background:"rgba(8,19,42,.94)",border:"1px solid #29466f",borderRadius:20,padding:20,marginBottom:18};const composer:any={...panel};const formGrid:any={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12};const label:any={display:"grid",gap:6,color:"#b8c9e3",fontSize:12,fontWeight:800};const actions:any={display:"flex",justifyContent:"flex-end",gap:8,marginTop:15};const ghost:any={border:"1px solid #35527f",background:"#0a1731",color:"#dce9ff",padding:"9px 13px",borderRadius:9,fontWeight:850,cursor:"pointer"};const good:any={...ghost,background:"#116b42",borderColor:"#31b978",color:"white"};const danger:any={...ghost,background:"#6d1d2b",borderColor:"#d65a6d",color:"white"};const mini:any={...ghost,padding:"6px 9px"};const noticeStyle:any={padding:12,borderRadius:10,border:"1px solid #315b8d",background:"#0a1934",marginBottom:14};const errorStyle:any={...noticeStyle,background:"#351020",borderColor:"#8b3048"};const sectionHead:any={display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10};const row:any={display:"grid",gridTemplateColumns:"64px minmax(180px,1fr) auto auto auto auto",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid #1a2b49"};const preview:any={width:64,height:64,borderRadius:12,overflow:"hidden",display:"grid",placeItems:"center",background:"#071024",fontSize:40};const identity:any={display:"grid",gap:3};const reorder:any={display:"flex",gap:4};const categoryComposer:any={display:"grid",gridTemplateColumns:"1fr 2fr auto",gap:8,marginBottom:12};const categoryGrid:any={display:"grid",gap:8};const categoryCard:any={display:"grid",gridTemplateColumns:"minmax(180px,1fr) auto auto auto auto",gap:8,alignItems:"center",padding:10,border:"1px solid #1a2b49",borderRadius:12};