import { NextRequest, NextResponse } from "next/server";
import { pool, ensureAuthSchema } from "../../auth/_db";
import { currentUser } from "../../../lib/auth-session";
import { createHash } from "crypto";

type Kind = "play_games" | "win_games" | "roll_dice" | "move_tokens" | "send_messages" | "join_rooms" | "create_rooms" | "roll_sixes" | "move_home" | "complete_games";
type Difficulty = "easy" | "hard" | "very_hard";
type Seed = { id:string; title:string; description:string; target:number; kind:Kind; difficulty:Difficulty; rewardCoins:number; rewardGems:number };

const E = (id:number,title:string,description:string,target:number,kind:Kind,coins:number,gems:number):Seed=>({id:`weekly-${id}`,title,description,target,kind,difficulty:"easy",rewardCoins:coins,rewardGems:gems});
const H = (id:number,title:string,description:string,target:number,kind:Kind,coins:number,gems:number):Seed=>({...E(id,title,description,target,kind,coins,gems),difficulty:"hard"});
const V = (id:number,title:string,description:string,target:number,kind:Kind,coins:number,gems:number):Seed=>({...E(id,title,description,target,kind,coins,gems),difficulty:"very_hard"});
const CATALOG:Seed[]=[
E(1,"Play 5 Ludo games","Play 5 Ludo games this week.",5,"play_games",5000,10),E(2,"Win 2 Ludo games","Win 2 Ludo games this week.",2,"win_games",6500,10),E(3,"Roll 25 dice times","Make 25 dice rolls this week.",25,"roll_dice",4500,5),E(4,"Make 20 token moves","Make 20 legal token moves this week.",20,"move_tokens",5000,5),E(5,"Send 10 room messages","Send 10 messages in Ludo rooms this week.",10,"send_messages",4000,5),E(6,"Join 3 online rooms","Join 3 online Ludo rooms this week.",3,"join_rooms",4500,5),E(7,"Create 2 game rooms","Create 2 Ludo game rooms this week.",2,"create_rooms",5000,5),E(8,"Roll three sixes","Roll a 6 three times this week.",3,"roll_sixes",5500,10),E(9,"Bring 5 tokens home","Bring 5 of your tokens home this week.",5,"move_home",7000,10),E(10,"Finish 2 games","Finish 2 Ludo games this week.",2,"complete_games",6500,10),E(11,"Play 8 Ludo games","Play 8 Ludo games this week.",8,"play_games",7500,10),E(12,"Win 3 Ludo games","Win 3 Ludo games this week.",3,"win_games",8000,10),E(13,"Roll 40 dice times","Make 40 dice rolls this week.",40,"roll_dice",6000,5),E(14,"Make 35 token moves","Make 35 legal token moves this week.",35,"move_tokens",6500,5),E(15,"Send 20 room messages","Send 20 messages in Ludo rooms this week.",20,"send_messages",5500,5),E(16,"Join 5 online rooms","Join 5 online Ludo rooms this week.",5,"join_rooms",6000,5),E(17,"Create 3 game rooms","Create 3 Ludo game rooms this week.",3,"create_rooms",6500,5),E(18,"Roll five sixes","Roll a 6 five times this week.",5,"roll_sixes",7000,10),E(19,"Bring 8 tokens home","Bring 8 of your tokens home this week.",8,"move_home",9000,10),E(20,"Finish 3 games","Finish 3 Ludo games this week.",3,"complete_games",8000,10),E(21,"Play 10 Ludo games","Play 10 Ludo games this week.",10,"play_games",9000,10),E(22,"Win 4 Ludo games","Win 4 Ludo games this week.",4,"win_games",9500,10),E(23,"Roll 60 dice times","Make 60 dice rolls this week.",60,"roll_dice",7500,5),E(24,"Make 50 token moves","Make 50 legal token moves this week.",50,"move_tokens",8000,5),E(25,"Send 30 room messages","Send 30 messages in Ludo rooms this week.",30,"send_messages",7000,5),
H(26,"Play 15 Ludo games","Play 15 Ludo games this week.",15,"play_games",12000,15),H(27,"Win 6 Ludo games","Win 6 Ludo games this week.",6,"win_games",15000,20),H(28,"Roll 100 dice times","Make 100 dice rolls this week.",100,"roll_dice",10000,10),H(29,"Make 90 token moves","Make 90 legal token moves this week.",90,"move_tokens",11000,10),H(30,"Send 50 room messages","Send 50 messages in Ludo rooms this week.",50,"send_messages",9000,10),H(31,"Join 10 online rooms","Join 10 online Ludo rooms this week.",10,"join_rooms",10000,10),H(32,"Create 6 game rooms","Create 6 Ludo game rooms this week.",6,"create_rooms",11000,10),H(33,"Roll ten sixes","Roll a 6 ten times this week.",10,"roll_sixes",13000,20),H(34,"Bring 12 tokens home","Bring 12 of your tokens home this week.",12,"move_home",16000,20),H(35,"Finish 6 games","Finish 6 Ludo games this week.",6,"complete_games",15000,20),H(36,"Play 20 Ludo games","Play 20 Ludo games this week.",20,"play_games",15000,20),H(37,"Win 8 Ludo games","Win 8 Ludo games this week.",8,"win_games",18000,20),H(38,"Make 120 token moves","Make 120 legal token moves this week.",120,"move_tokens",14000,10),H(39,"Bring 16 tokens home","Bring 16 of your tokens home this week.",16,"move_home",19000,25),H(40,"Finish 8 games","Finish 8 Ludo games this week.",8,"complete_games",18000,25),
V(41,"Win 12 Ludo games","Win 12 Ludo games this week.",12,"win_games",25000,30),V(42,"Play 30 Ludo games","Play 30 Ludo games this week.",30,"play_games",22000,25),V(43,"Make 200 token moves","Make 200 legal token moves this week.",200,"move_tokens",22000,20),V(44,"Roll 200 dice times","Make 200 dice rolls this week.",200,"roll_dice",18000,15),V(45,"Bring 25 tokens home","Bring 25 of your tokens home this week.",25,"move_home",28000,35),V(46,"Finish 12 games","Finish 12 Ludo games this week.",12,"complete_games",25000,30),V(47,"Roll twenty sixes","Roll a 6 twenty times this week.",20,"roll_sixes",26000,35),V(48,"Create 12 game rooms","Create 12 Ludo game rooms this week.",12,"create_rooms",20000,20),V(49,"Join 20 online rooms","Join 20 online Ludo rooms this week.",20,"join_rooms",20000,20),V(50,"Send 100 room messages","Send 100 messages in Ludo rooms this week.",100,"send_messages",18000,20)
];
const DEFAULT_BONUS={coins:50000,gems:100};
const weekStart=()=>{const d=new Date();const day=d.getUTCDay();const diff=day===0?-6:1-day;d.setUTCDate(d.getUTCDate()+diff);return d.toISOString().slice(0,10)};
const weekEnd=(start:string)=>{const d=new Date(`${start}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+7);return d.toISOString().slice(0,10)};
const hash=(s:string)=>parseInt(createHash("sha256").update(s).digest("hex").slice(0,8),16);

async function setup(){await ensureAuthSchema();await pool.query(`CREATE TABLE IF NOT EXISTS ludo_weekly_mission_definitions(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',target INTEGER NOT NULL DEFAULT 1,reward_coins INTEGER NOT NULL DEFAULT 0,reward_gems INTEGER NOT NULL DEFAULT 0,kind TEXT NOT NULL DEFAULT 'play_games',difficulty TEXT NOT NULL DEFAULT 'easy',admin_created BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,scheduled_week DATE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS ludo_weekly_missions(user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,week_start DATE NOT NULL,slot INTEGER NOT NULL,mission_id TEXT NOT NULL REFERENCES ludo_weekly_mission_definitions(id) ON DELETE CASCADE,completed BOOLEAN NOT NULL DEFAULT FALSE,claimed BOOLEAN NOT NULL DEFAULT FALSE,claimed_at TIMESTAMPTZ,PRIMARY KEY(user_id,week_start,slot),UNIQUE(user_id,week_start,mission_id));CREATE TABLE IF NOT EXISTS ludo_weekly_assignment_bundles(user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,week_start DATE NOT NULL,signature TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,week_start),UNIQUE(week_start,signature));CREATE TABLE IF NOT EXISTS ludo_weekly_mission_bonus(user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,week_start DATE NOT NULL,unlocked BOOLEAN NOT NULL DEFAULT FALSE,claimed BOOLEAN NOT NULL DEFAULT FALSE,claimed_at TIMESTAMPTZ,PRIMARY KEY(user_id,week_start));CREATE TABLE IF NOT EXISTS ludo_weekly_mission_settings(week_start DATE PRIMARY KEY,bonus_coins INTEGER NOT NULL DEFAULT 50000,bonus_gems INTEGER NOT NULL DEFAULT 100,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);await pool.query(`INSERT INTO ludo_weekly_mission_definitions(id,title,description,target,reward_coins,reward_gems,kind,difficulty) SELECT id,title,description,target,reward_coins,reward_gems,kind,difficulty FROM jsonb_to_recordset($1::jsonb) AS x(id text,title text,description text,target integer,reward_coins integer,reward_gems integer,kind text,difficulty text) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,target=EXCLUDED.target,reward_coins=EXCLUDED.reward_coins,reward_gems=EXCLUDED.reward_gems,kind=EXCLUDED.kind,difficulty=EXCLUDED.difficulty WHERE ludo_weekly_mission_definitions.admin_created=FALSE`,[JSON.stringify(CATALOG)]);}
async function getBonus(week:string){const r=await pool.query(`SELECT bonus_coins,bonus_gems FROM ludo_weekly_mission_settings WHERE week_start=$1`,[week]);return r.rows[0]?{coins:Number(r.rows[0].bonus_coins),gems:Number(r.rows[0].bonus_gems)}:DEFAULT_BONUS;}
async function progressFor(uid:string,start:string){const end=weekEnd(start);const r=await pool.query(`SELECT kind,COALESCE(SUM(amount),0)::int AS progress FROM ludo_mission_events WHERE user_id=$1 AND event_day >= $2 AND event_day < $3 GROUP BY kind`,[uid,start,end]);return Object.fromEntries(r.rows.map((x:any)=>[x.kind,Number(x.progress)]));}
async function assign(uid:string){const week=weekStart();const existing=await pool.query(`SELECT wm.slot,wm.mission_id,wm.completed,wm.claimed,md.title,md.description,md.target,md.reward_coins,md.reward_gems,md.kind,md.difficulty,md.admin_created FROM ludo_weekly_missions wm JOIN ludo_weekly_mission_definitions md ON md.id=wm.mission_id WHERE wm.user_id=$1 AND wm.week_start=$2 ORDER BY wm.slot`,[uid,week]);if(existing.rowCount&&existing.rowCount>=10)return existing.rows.slice(0,10);
 const admin=await pool.query(`SELECT * FROM ludo_weekly_mission_definitions WHERE active=TRUE AND admin_created=TRUE AND scheduled_week=$1 ORDER BY created_at ASC`,[week]);
 const selected:Seed[]=[];const by=(difficulty:Difficulty)=>admin.rows.filter((x:any)=>x.difficulty===difficulty).slice(0,difficulty==="easy"?5:difficulty==="hard"?3:2).map((x:any)=>({id:x.id,title:x.title,description:x.description,target:Number(x.target),kind:x.kind,difficulty:x.difficulty,rewardCoins:Number(x.reward_coins),rewardGems:Number(x.reward_gems)}));
 selected.push(...by("easy"),...by("hard"),...by("very_hard"));
 const need={easy:5-selected.filter(x=>x.difficulty==="easy").length,hard:3-selected.filter(x=>x.difficulty==="hard").length,very_hard:2-selected.filter(x=>x.difficulty==="very_hard").length};
 const pools:any={easy:CATALOG.filter(x=>x.difficulty==="easy"),hard:CATALOG.filter(x=>x.difficulty==="hard"),very_hard:CATALOG.filter(x=>x.difficulty==="very_hard")};
 const base=hash(`${uid}:${week}`);for(const difficulty of ["easy","hard","very_hard"] as Difficulty[]){const poolRows=pools[difficulty] as Seed[];const used=new Set(selected.filter(x=>x.difficulty===difficulty).map(x=>x.id));let added=0;for(let i=0;i<poolRows.length&&added<need[difficulty];i++){const c=poolRows[(base+i*7)%poolRows.length];if(!used.has(c.id)){selected.push(c);used.add(c.id);added++;}}}
 let ordered=selected.slice(0,10);let signature=ordered.map(x=>x.id).sort().join(",");for(let salt=0;salt<100; salt++){const candidate=await pool.query(`INSERT INTO ludo_weekly_assignment_bundles(user_id,week_start,signature) VALUES($1,$2,$3) ON CONFLICT(week_start,signature) DO NOTHING RETURNING signature`,[uid,week,signature]);if(candidate.rowCount)break;const shift=salt+1;ordered=[];for(const difficulty of ["easy","hard","very_hard"] as Difficulty[]){const poolRows=pools[difficulty] as Seed[];const adminSelected=selected.filter(x=>x.difficulty===difficulty&&x.id.startsWith("admin-"));ordered.push(...adminSelected);const count=difficulty==="easy"?5:difficulty==="hard"?3:2;const used=new Set(adminSelected.map(x=>x.id));let i=0;while(ordered.filter(x=>x.difficulty===difficulty).length < (difficulty==="easy"?5:difficulty==="hard"?3:2)){const c=poolRows[(base+shift+i*7)%poolRows.length];i++;if(!used.has(c.id)){ordered.push(c);used.add(c.id);}}}signature=ordered.map(x=>x.id).sort().join(",");}
 const existingIds=new Set(existing.rows.map((x:any)=>x.mission_id));let slot=1;for(const m of ordered){if(existingIds.has(m.id))continue;await pool.query(`INSERT INTO ludo_weekly_missions(user_id,week_start,slot,mission_id) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[uid,week,slot++,m.id]);if(slot>10)break;}return (await pool.query(`SELECT wm.slot,wm.mission_id,wm.completed,wm.claimed,md.title,md.description,md.target,md.reward_coins,md.reward_gems,md.kind,md.difficulty,md.admin_created FROM ludo_weekly_missions wm JOIN ludo_weekly_mission_definitions md ON md.id=wm.mission_id WHERE wm.user_id=$1 AND wm.week_start=$2 ORDER BY wm.slot`,[uid,week])).rows.slice(0,10);
}
async function refreshCompletion(uid:string,week:string){const p=await progressFor(uid,week);const rows=await pool.query(`SELECT wm.mission_id,wm.completed,md.kind,md.target FROM ludo_weekly_missions wm JOIN ludo_weekly_mission_definitions md ON md.id=wm.mission_id WHERE wm.user_id=$1 AND wm.week_start=$2`,[uid,week]);for(const m of rows.rows)if(!m.completed&&Number(p[m.kind]||0)>=Number(m.target))await pool.query(`UPDATE ludo_weekly_missions SET completed=TRUE WHERE user_id=$1 AND week_start=$2 AND mission_id=$3`,[uid,week,m.mission_id]);const done=await pool.query(`SELECT COUNT(*)::int AS n FROM ludo_weekly_missions WHERE user_id=$1 AND week_start=$2 AND completed=TRUE`,[uid,week]);if(Number(done.rows[0]?.n||0)>=10)await pool.query(`INSERT INTO ludo_weekly_mission_bonus(user_id,week_start,unlocked) VALUES($1,$2,TRUE) ON CONFLICT(user_id,week_start) DO UPDATE SET unlocked=TRUE`,[uid,week]);}
export async function GET(q:NextRequest){try{await setup();const u=await currentUser(q);if(!u)return NextResponse.json({error:"Login required."},{status:401});const week=weekStart();await assign(u.id);await refreshCompletion(u.id,week);const missions=await pool.query(`SELECT wm.slot,wm.mission_id,wm.completed,wm.claimed,md.title,md.description,md.target,md.reward_coins,md.reward_gems,md.kind,md.difficulty,md.admin_created FROM ludo_weekly_missions wm JOIN ludo_weekly_mission_definitions md ON md.id=wm.mission_id WHERE wm.user_id=$1 AND wm.week_start=$2 ORDER BY wm.slot`,[u.id,week]);const bonus=await pool.query(`SELECT unlocked,claimed FROM ludo_weekly_mission_bonus WHERE user_id=$1 AND week_start=$2`,[u.id,week]);return NextResponse.json({weekStart:week,weekEnd:weekEnd(week),missions:missions.rows.slice(0,10),progress:await progressFor(u.id,week),bonus:bonus.rows[0]||{unlocked:false,claimed:false},weeklyBonus:await getBonus(week),counts:{easy:5,hard:3,very_hard:2}});}catch(e){console.error(e);return NextResponse.json({error:"Weekly mission service unavailable."},{status:500});}}
export async function POST(q:NextRequest){try{await setup();const u=await currentUser(q);if(!u)return NextResponse.json({error:"Login required."},{status:401});const b=await q.json(),action=String(b.action||"");const week=weekStart();if(action!=="claim_bonus"&&action!=="claim")return NextResponse.json({error:"Unknown weekly mission action."},{status:400});if(action==="claim"){const id=String(b.missionId||"");const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query(`SELECT wm.*,md.reward_coins,md.reward_gems FROM ludo_weekly_missions wm JOIN ludo_weekly_mission_definitions md ON md.id=wm.mission_id WHERE wm.user_id=$1 AND wm.week_start=$2 AND wm.mission_id=$3 FOR UPDATE`,[u.id,week,id]);const m=r.rows[0];if(!m||!m.completed||m.claimed)throw new Error("Weekly mission is not ready to claim.");await client.query(`UPDATE ludo_users SET coins=coins+$1,gems=gems+$2 WHERE id=$3`,[m.reward_coins||0,m.reward_gems||0,u.id]);await client.query(`UPDATE ludo_weekly_missions SET claimed=TRUE,claimed_at=NOW() WHERE user_id=$1 AND week_start=$2 AND mission_id=$3`,[u.id,week,id]);await client.query("COMMIT");return NextResponse.json({ok:true});}catch(e){await client.query("ROLLBACK");return NextResponse.json({error:e instanceof Error?e.message:"Claim failed."},{status:400});}finally{client.release()}}
 const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query(`SELECT * FROM ludo_weekly_mission_bonus WHERE user_id=$1 AND week_start=$2 FOR UPDATE`,[u.id,week]);const bonus=r.rows[0];if(!bonus||!bonus.unlocked||bonus.claimed)throw new Error("Weekly bonus is not ready to claim.");const prize=await getBonus(week);await client.query(`UPDATE ludo_users SET coins=coins+$1,gems=gems+$2 WHERE id=$3`,[prize.coins,prize.gems,u.id]);await client.query(`UPDATE ludo_weekly_mission_bonus SET claimed=TRUE,claimed_at=NOW() WHERE user_id=$1 AND week_start=$2`,[u.id,week]);await client.query("COMMIT");return NextResponse.json({ok:true,reward:prize});}catch(e){await client.query("ROLLBACK");return NextResponse.json({error:e instanceof Error?e.message:"Weekly bonus claim failed."},{status:400});}finally{client.release()}}catch(e){console.error(e);return NextResponse.json({error:"Weekly mission service unavailable."},{status:500});}}
