import {NextRequest,NextResponse} from "next/server";
import {pool,ensureAuthSchema} from "../auth/_db";
import {currentUser} from "../auth/route";

export const BOARDS=[
 {id:"classic",name:"Classic Ludo",currency:"coins",price:0,rarity:"COMMON"},{id:"golden",name:"Golden Royal",currency:"gems",price:50,rarity:"EPIC"},{id:"neon",name:"Neon Glow",currency:"gems",price:100,rarity:"LEGENDARY"},{id:"beach",name:"Beach Vibes",currency:"coins",price:3000,rarity:"RARE"},{id:"galaxy",name:"Galaxy Space",currency:"gems",price:75,rarity:"EPIC"},{id:"wood",name:"Wooden Classic",currency:"coins",price:1000,rarity:"COMMON"},{id:"dragon",name:"Dragon Theme",currency:"gems",price:80,rarity:"EPIC"},{id:"christmas",name:"Christmas Edition",currency:"coins",price:3500,rarity:"RARE"},{id:"football",name:"Football Arena",currency:"gems",price:70,rarity:"EPIC"},{id:"candy",name:"Candy Land",currency:"gems",price:120,rarity:"LEGENDARY"}
];
export const DICE=[
 {id:"classic",name:"Classic White",currency:"coins",price:0,rarity:"COMMON"},{id:"golden",name:"Golden Dice",currency:"coins",price:1500,rarity:"RARE"},{id:"crystal",name:"Crystal Blue",currency:"gems",price:40,rarity:"EPIC"},{id:"fire",name:"Fire Dice",currency:"gems",price:90,rarity:"LEGENDARY"},{id:"rainbow",name:"Rainbow Dice",currency:"gems",price:70,rarity:"EPIC"},{id:"diamond",name:"Diamond Dice",currency:"gems",price:120,rarity:"LEGENDARY"},{id:"skull",name:"Skull Dice",currency:"coins",price:2000,rarity:"RARE"},{id:"sports",name:"Sports Dice",currency:"coins",price:1000,rarity:"COMMON"}
];
const catalog=[...BOARDS.map(x=>({...x,type:"board"})),...DICE.map(x=>({...x,type:"dice"}))];
function clean(list:any){return Array.isArray(list)?list.map(String):[]}
export async function GET(q:NextRequest){try{await ensureAuthSchema();const u=await currentUser(q);if(!u)return NextResponse.json({error:"Sign in required."},{status:401});return NextResponse.json({coins:u.coins,gems:u.gems,ownedBoards:clean(u.owned_boards||["classic"]),ownedDice:clean(u.owned_dice||["classic"]),equippedBoard:u.equipped_board||"classic",equippedDice:u.equipped_dice||"classic",boards:BOARDS,dice:DICE})}catch(e){console.error(e);return NextResponse.json({error:"Customization service unavailable."},{status:500})}}
export async function POST(q:NextRequest){const client=await pool.connect();try{await ensureAuthSchema();const u=await currentUser(q);if(!u||u.is_guest)return NextResponse.json({error:"A registered account is required."},{status:403});const b=await q.json(),action=String(b.action||""),id=String(b.id||"");const item=catalog.find(x=>x.id===id&&x.type===String(b.type||""));if(!item)return NextResponse.json({error:"Item not found."},{status:404});await client.query("BEGIN");const row=await client.query<any>("SELECT coins,gems,owned_boards,owned_dice,equipped_board,equipped_dice FROM ludo_users WHERE id=$1 FOR UPDATE",[u.id]);const cur=row.rows[0];let boards=clean(cur.owned_boards||["classic"]),dice=clean(cur.owned_dice||["classic"]);
 if(action==="equip"){const owned=(item.type==="board"?boards:dice).includes(id);if(!owned)return NextResponse.json({error:"Purchase this item first."},{status:403});if(item.type==="board")await client.query("UPDATE ludo_users SET equipped_board=$1 WHERE id=$2",[id,u.id]);else await client.query("UPDATE ludo_users SET equipped_dice=$1 WHERE id=$2",[id,u.id]);await client.query("COMMIT");return NextResponse.json({ok:true,equippedBoard:item.type==="board"?id:cur.equipped_board,equippedDice:item.type==="dice"?id:cur.equipped_dice})}
 if(action!=="purchase")return NextResponse.json({error:"Unknown customization action."},{status:400});if((item.type==="board"?boards:dice).includes(id))return NextResponse.json({error:"You already own this item."},{status:409});const balance=Number(cur[item.currency]);if(balance<item.price)return NextResponse.json({error:`Not enough ${item.currency}.`},{status:400});const next=balance-item.price;await client.query(`UPDATE ludo_users SET ${item.currency}=$1, ${item.type==="board"?"owned_boards":"owned_dice"}=CASE WHEN $2 = ANY(${item.type==="board"?"owned_boards":"owned_dice"}) THEN ${item.type==="board"?"owned_boards":"owned_dice"} ELSE ${item.type==="board"?"owned_boards":"owned_dice"} || jsonb_build_array($2) END WHERE id=$3`,[next,id,u.id]);await client.query("INSERT INTO ludo_admin_ledger(user_id,currency,amount,balance_before,balance_after,reason,source) VALUES($1,$2,$3,$4,$5,$6,'shop')",[u.id,item.currency,-item.price,balance,next,`Purchased ${item.name}`]);await client.query("COMMIT");return NextResponse.json({ok:true,coins:item.currency==="coins"?next:cur.coins,gems:item.currency==="gems"?next:cur.gems,item})}catch(e){await client.query("ROLLBACK").catch(()=>{});console.error(e);return NextResponse.json({error:"Unable to update customization."},{status:500})}finally{client.release()}}
