"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import "../dbase.css";

 type R = Record<string, any>;
const fmt=(v:any)=>Number(v||0).toLocaleString();
const time=(v:any)=>v?new Date(v).toLocaleString():"—";

function Badge({value}:{value:string}){const v=String(value||"").toLowerCase();return <span className={`audit-badge ${v.includes("alert")||v.includes("review")||v.includes("blocked")?"bad":v.includes("protected")||v.includes("healthy")?"good":""}`}>{value}</span>}
function Card({title,value,sub}:{title:string;value:any;sub:string}){return <div className="audit-stat"><span>{title}</span><strong>{value}</strong><small>{sub}</small></div>}

export default function AuditPage(){
 const [data,setData]=useState<R|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState("all"); const [query,setQuery]=useState("");
 const load=useCallback(async()=>{try{setError("");const r=await fetch("/api/admin/security-audit",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load audit.");setData(j)}catch(e:any){setError(e?.message||"Unable to load audit.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[load]);
 const actions=useMemo(()=>{const rows=data?.actions||[];return rows.filter((r:R)=>{const text=`${r.action||""} ${r.target_username||""} ${r.admin_username||""} ${JSON.stringify(r.details||{})}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(filter==="all"||String(r.action||"").toLowerCase().includes(filter))})},[data,query,filter]);
 const suspicious=data?.suspiciousWallet||[];
 return <main className="dbase-page audit-page"><div className="dbase-wrap">
  <div className="panel-head audit-head"><div><span>SECURITY CENTER</span><h1>Audit Log</h1><p>Admin actions, wallet integrity and application security bridges.</p></div><button className="admin-btn" onClick={load}>↻ Refresh</button></div>
  {error&&<div className="audit-alert">{error}</div>}
  {loading&&!data?<div className="panel"><p>Loading security audit…</p></div>:data&&<>
   <div className="audit-grid"><Card title="Security bridges" value={data.summary.securityBridges} sub="Controls currently reported"/><Card title="Admin actions" value={fmt(data.summary.adminActions)} sub="Recent actions retained"/><Card title="Active sessions" value={fmt(data.summary.activeSessions)} sub={`${fmt(data.sessions?.expired)} expired records`}/><Card title="Banned accounts" value={fmt(data.summary.banned)} sub={`${fmt(data.summary.bannedWithActiveSessions)} active-session alerts`}/><Card title="Wallet review" value={fmt(data.summary.suspiciousWalletEvents)} sub="Unattributed/review events"/></div>
   <section className="panel"><div className="panel-head"><div><span>CONTROL MONITOR</span><h3>Security Bridges</h3></div><Badge value={data.summary.bannedWithActiveSessions||data.summary.suspiciousWalletEvents?"Attention required":"All monitored controls healthy"}/></div><div className="bridge-grid">{(data.bridges||[]).map((b:R)=><div className="bridge-card" key={b.id}><div className="bridge-top"><b>{b.name}</b><Badge value={b.status}/></div><small>{b.category}</small><p>{b.detail}</p></div>)}</div></section>
   <section className="panel"><div className="panel-head"><div><span>ADMIN ACTIVITY</span><h3>Admin Actions</h3></div><div className="audit-tools"><input placeholder="Search action, admin, target…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All actions</option><option value="balance">Wallet</option><option value="tournament">Tournament</option><option value="ban">Moderation</option><option value="delete">Deletion</option><option value="dispute">Support</option></select></div></div><div className="audit-list">{actions.length?actions.map((r:R)=><div className="audit-row" key={r.id}><div><b>{r.action}</b><span>{r.admin_username||r.admin_email||"Admin"} → {r.target_username||r.target_user_id||"System"}</span></div><div className="audit-details">{r.details&&Object.keys(r.details).length?<code>{JSON.stringify(r.details)}</code>:<span>—</span>}</div><time>{time(r.created_at)}</time></div>):<p className="empty">No matching admin actions.</p>}</div></section>
   <section className="panel"><div className="panel-head"><div><span>ECONOMY INTEGRITY</span><h3>Wallet Audit</h3></div><Badge value={suspicious.length?`${suspicious.length} review event${suspicious.length===1?"":"s"}`:"No review events"}/></div><div className="audit-list">{(data.wallet||[]).length?(data.wallet||[]).map((r:R)=><div className="audit-row" key={r.id}><div><b>{r.player_username||r.user_id||"Deleted account"} · {r.currency}</b><span>{r.source||"unknown"} · {r.reason||"No reason recorded"}</span></div><div><strong>{Number(r.amount)>=0?"+":""}{fmt(r.amount)}</strong><span>{fmt(r.balance_before)} → {fmt(r.balance_after)}</span></div><Badge value={r.status}/><time>{time(r.created_at)}</time></div>):<p className="empty">No wallet audit events recorded.</p>}</div></section>
  </>}
 </div><style jsx>{`.audit-page{padding-bottom:48px}.audit-head{align-items:flex-start}.audit-head h1{margin:4px 0;font-size:30px}.audit-head p{margin:0;opacity:.68}.audit-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:14px 0}.audit-stat{padding:16px;border:1px solid rgba(127,127,127,.18);border-radius:16px;background:rgba(127,127,127,.06)}.audit-stat span,.audit-stat small{display:block;opacity:.65}.audit-stat strong{display:block;font-size:26px;margin:6px 0}.audit-stat small{font-size:12px}.bridge-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.bridge-card{padding:15px;border:1px solid rgba(127,127,127,.16);border-radius:14px}.bridge-top{display:flex;justify-content:space-between;gap:10px}.bridge-card small{display:block;opacity:.58;margin-top:4px}.bridge-card p{margin:9px 0 0;opacity:.72;font-size:13px;line-height:1.45}.audit-badge{display:inline-flex;align-items:center;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:700;background:rgba(127,127,127,.12);white-space:nowrap}.audit-badge.good{background:rgba(46,160,67,.14);color:#2ea043}.audit-badge.bad{background:rgba(220,53,69,.14);color:#dc3545}.audit-tools{display:flex;gap:8px}.audit-tools input,.audit-tools select{min-height:38px;border:1px solid rgba(127,127,127,.2);border-radius:10px;padding:0 10px;background:transparent;color:inherit}.audit-list{display:grid}.audit-row{display:grid;grid-template-columns:minmax(180px,1fr) minmax(180px,1.6fr) auto auto;gap:14px;align-items:center;padding:13px 0;border-top:1px solid rgba(127,127,127,.12)}.audit-row b,.audit-row span{display:block}.audit-row span{font-size:12px;opacity:.62;margin-top:3px}.audit-row time{font-size:11px;opacity:.58;white-space:nowrap}.audit-details code{display:block;max-width:520px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;opacity:.7}.audit-alert{padding:12px 14px;margin:12px 0;border-radius:12px;background:rgba(220,53,69,.12);color:#dc3545}.empty{opacity:.6;padding:18px 0}@media(max-width:900px){.audit-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.bridge-grid{grid-template-columns:1fr}.audit-head{flex-direction:column}.audit-tools{width:100%;flex-wrap:wrap}.audit-tools input{flex:1;min-width:180px}.audit-row{grid-template-columns:1fr;gap:6px}.audit-row time{justify-self:start}}`}</style></main>
}