import {OnlinePlayer,OnlineLifecycleState,assignOnlineColors,canStartOnlineMatch,nextConnectedPlayer,markDisconnected,markReconnected,finishMatch,abandonMatch} from './multiplayerLifecycle';

export type MatchMode=2|4;
export type MatchEvent={type:'READY_CHANGED'|'MATCH_STARTING'|'MATCH_STARTED'|'PLAYER_DISCONNECTED'|'PLAYER_RECONNECTED'|'TURN_CHANGED'|'MATCH_FINISHED'|'MATCH_ABANDONED';payload:Record<string,unknown>};
export type MatchState=OnlineLifecycleState & {requiredPlayers:MatchMode;ready:Set<string>;startedAt:number|null;events:MatchEvent[]};

export function createMatch(requiredPlayers:MatchMode):MatchState{return {status:'waiting',players:[],currentPlayerId:null,winnerId:null,reconnectDeadline:null,requiredPlayers,ready:new Set(),startedAt:null,events:[]};}
export function addPlayer(state:MatchState,player:OnlinePlayer){if(state.status!=='waiting')throw new Error('MATCH_ALREADY_STARTED');if(state.players.some(p=>p.playerId===player.playerId))return state;if(state.players.length>=state.requiredPlayers)throw new Error('MATCH_FULL');state.players.push({...player,seat:state.players.length,connected:true});return state;}
export function setReady(state:MatchState,playerId:string,ready:boolean){if(state.status!=='waiting')throw new Error('MATCH_NOT_WAITING');if(!state.players.some(p=>p.playerId===playerId))throw new Error('PLAYER_NOT_FOUND');ready?state.ready.add(playerId):state.ready.delete(playerId);state.events.push({type:'READY_CHANGED',payload:{playerId,ready}});if(canStartOnlineMatch(state.players,state.requiredPlayers)&&state.players.every(p=>state.ready.has(p.playerId))){state.status='starting';state.startedAt=Date.now()+3000;state.events.push({type:'MATCH_STARTING',payload:{startsAt:state.startedAt}});}return state;}
export function startMatch(state:MatchState,startingPlayerId:string){if(state.status!=='starting')throw new Error('MATCH_NOT_STARTING');if(!state.players.some(p=>p.playerId===startingPlayerId&&p.connected))throw new Error('INVALID_STARTING_PLAYER');state.players.forEach((p,i)=>{p.seat=i;p.color=assignOnlineColors(state.requiredPlayers)[i][0];});state.status='playing';state.currentPlayerId=startingPlayerId;state.events.push({type:'MATCH_STARTED',payload:{currentPlayerId:startingPlayerId,players:state.players.map(p=>({playerId:p.playerId,seat:p.seat,color:p.color}))}});return state;}
export function changeTurn(state:MatchState){if(state.status!=='playing'||!state.currentPlayerId)return state;const next=nextConnectedPlayer(state.players,state.currentPlayerId);if(next){state.currentPlayerId=next;state.events.push({type:'TURN_CHANGED',payload:{currentPlayerId:next}});}return state;}
export function disconnectPlayer(state:MatchState,playerId:string){markDisconnected(state,playerId);state.events.push({type:'PLAYER_DISCONNECTED',payload:{playerId,reconnectDeadline:state.reconnectDeadline}});return state;}
export function reconnectPlayer(state:MatchState,playerId:string){markReconnected(state,playerId);state.events.push({type:'PLAYER_RECONNECTED',payload:{playerId}});return state;}
export function completeMatch(state:MatchState,winnerId:string){finishMatch(state,winnerId);state.events.push({type:'MATCH_FINISHED',payload:{winnerId}});return state;}
export function abandon(state:MatchState){abandonMatch(state);state.events.push({type:'MATCH_ABANDONED',payload:{}});return state;}
