const { Server } = require("socket.io");
const originalServerOn = Server.prototype.on;
const games = new Map();
const COLORS = ["red", "yellow", "green", "blue"];
const START = { red: 0, blue: 13, green: 26, yellow: 39 };
const SAFE = new Set([0, 8, 13, 21, 26, 34, 39, 47]);
const FINISH = 56;
const RECONNECT_MS = 30000;
function pid(s){return String(s.data.playerId||"").trim()} function code(s){return String(s.data.roomCode||"").trim().toUpperCase()}
function colors(seat){return seat===0?["red","yellow"]:["green","blue"]}
function globalPos(c,p){return p>=1&&p<=51?(START[c]+p-1)%52:null}
function tokens(){return Object.fromEntries(COLORS.map(c=>[c,Object.fromEntries([0,1,2,3].map(id=>[String(id),{position:0}]))]))}
function player(g,c){return g.players.find(p=>p.colors.includes(c))} function pos(g,c,id){return Number(g.tokens[c]?.[String(id)]?.position||0)}
function own(g,p,c,id){const x=player(g,c);return !!x&&x.playerId===p&&!!g.tokens[c]?.[String(id)]}
function occupants(g,global,except){const out=[];for(const c of COLORS){if(c===except)continue;for(let id=0;id<4;id++)if(globalPos(c,pos(g,c,id))===global)out.push({color:c,id})}return out}
function block(g,global,owner){for(const c of COLORS){const p=player(g,c);if(!p||p.playerId===owner)continue;let n=0;for(let id=0;id<4;id++)if(globalPos(c,pos(g,c,id))===global)n++;if(n>=2)return true}return false}
function pathClear(g,c,from,to){const start=globalPos(c,from);if(start===null)return true;for(let step=1;step<=to-from;step++){const q=(start+step)%52;if(block(g,q,player(g,c)?.playerId||""))return false}return true}
function legal(g,c,id,r){if(!Number.isInteger(r)||r<1||r>6)return false;const from=pos(g,c,id);if(from===FINISH)return false;const target=from===0?(r===6?1:-1):from+r;if(target<1||target>FINISH)return false;if(from===0&&r!==6)return false;if(!pathClear(g,c,from,Math.min(target,51)))return false;if(target>=52)return true;const q=globalPos(c,target);if(block(g,q,player(g,c)?.playerId||""))return false;const hits=occupants(g,q,c);return SAFE.has(q)||hits.length<=1}
function hasMove(g,p,r){const x=g.players.find(x=>x.playerId===p);return !!x&&x.colors.some(c=>[0,1,2,3].some(id=>legal(g,c,id,r)))}
function snapshot(g){return {status:g.status,currentPlayerId:g.currentPlayerId,dice:g.dice,pendingMove:g.pendingMove,sixStreak:g.sixStreak,players:g.players.map(p=>({playerId:p.playerId,name:p.name,seat:p.seat,connected:!!p.socket,colors:p.colors})),tokens:g.tokens,winnerId:g.winnerId||null,reconnectDeadline:g.reconnectDeadline||null}}
function emit(g,e,p){for(const x of g.players)if(x.socket?.connected)x.socket.emit(e,p)} function state(g){emit(g,"game-state",snapshot(g))}
function next(g){const i=g.players.findIndex(p=>p.playerId===g.currentPlayerId);if(i<0)return null;for(let n=1;n<=g.players.length;n++){const p=g.players[(i+n)%g.players.length];if(p.socket?.connected)return p}return null}
function init(g){g.status="playing";g.currentPlayerId=g.players[0]?.playerId||null;g.dice=null;g.pendingMove=null;g.sixStreak=0;g.winnerId=null;g.reconnectDeadline=null;g.tokens=tokens()}
function attach(s,payload){const room=String(payload?.roomCode||"").trim().toUpperCase(),pId=String(payload?.playerId||"").trim();if(!room||!pId||Number(payload?.roomSize)!==2)return;s.data.ludoV2=true;s.data.roomCode=room;s.data.playerId=pId;let g=games.get(room);if(!g)g={code:room,players:[],status:"waiting",currentPlayerId:null,dice:null,pendingMove:null,sixStreak:0,tokens:tokens(),winnerId:null,reconnectDeadline:null};let p=g.players.find(x=>x.playerId===pId);if(!p){if(g.players.length>=2)return;const seat=g.players.length;p={playerId:pId,name:String(payload?.name||"Player").slice(0,24),seat,colors:colors(seat),socket:s,ready:seat===0};g.players.push(p)}else{p.socket=s;p.name=String(payload?.name||p.name||"Player").slice(0,24);if(g.status==="paused"&&g.currentPlayerId===pId){g.status="playing";g.reconnectDeadline=null}}games.set(room,g);s.emit("game-state",snapshot(g));if(g.status==="playing")state(g)}
function ready(s,p){if(!s.data.ludoV2)return;const g=games.get(code(s));const x=g?.players.find(x=>x.playerId===pid(s));if(x)x.ready=!!p?.ready}
function start(s){if(!s.data.ludoV2)return;const g=games.get(code(s));if(!g||g.status==="playing")return;if(g.players[0]?.playerId!==pid(s)||g.players.length!==2||!g.players.every(p=>p.ready&&p.socket?.connected))return;init(g);for(const p of g.players){p.socket.data.ludoV2Started=true;p.socket.emit("start-game",{roomCode:g.code})}state(g)}
function roll(s){if(!s.data.ludoV2)return;const g=games.get(code(s));if(!g||g.status!=="playing")return;const id=pid(s);if(g.currentPlayerId!==id||g.pendingMove!==null)return;const value=1+Math.floor(Math.random()*6);g.dice=value;g.sixStreak=value===6?g.sixStreak+1:0;emit(g,"game-dice",{playerId:id,value});if(value===6&&g.sixStreak>=3){g.pendingMove=null;g.sixStreak=0;const n=next(g);g.currentPlayerId=n?.playerId||null;state(g);return}if(!hasMove(g,id,value)){g.pendingMove=null;g.sixStreak=0;const n=next(g);g.currentPlayerId=n?.playerId||null;state(g);return}g.pendingMove=value;state(g)}
function move(s,payload){if(!s.data.ludoV2)return;const g=games.get(code(s));if(!g||g.status!=="playing")return;const id=pid(s);if(g.currentPlayerId!==id||g.pendingMove===null)return;const token=String(payload?.tokenId||"");const [color,raw]=token.split(":");const tokenId=Number(raw),r=g.pendingMove;if(!COLORS.includes(color)||!Number.isInteger(tokenId)||tokenId<0||tokenId>3||!own(g,id,color,tokenId)||!legal(g,color,tokenId,r))return;const from=pos(g,color,tokenId),target=from===0?1:from+r;g.tokens[color][String(tokenId)].position=target;let captured=[];if(target<=51){const q=globalPos(color,target);if(!SAFE.has(q)){const hits=occupants(g,q,color);if(hits.length===1){const v=hits[0];g.tokens[v.color][String(v.id)].position=0;captured=hits}}}g.pendingMove=null;emit(g,"game-moved",{playerId:id,tokenId,to:target,captured});const me=g.players.find(p=>p.playerId===id);const won=me&&me.colors.every(c=>[0,1,2,3].every(n=>pos(g,c,n)===FINISH));if(won){g.status="finished";g.winnerId=id;g.currentPlayerId=null;state(g);return}if(r!==6){g.sixStreak=0;const n=next(g);g.currentPlayerId=n?.playerId||null}state(g)}
function disconnect(s){if(!s.data.ludoV2)return;const g=games.get(code(s));if(!g)return;const p=g.players.find(x=>x.playerId===pid(s));if(p&&p.socket===s)p.socket=null;if(g.status!=="playing"||g.currentPlayerId!==pid(s))return;g.status="paused";g.pendingMove=null;g.reconnectDeadline=Date.now()+RECONNECT_MS;state(g)}
if(!Server.prototype.__ludoV2Patched){Server.prototype.__ludoV2Patched=true;Server.prototype.on=function(event,listener){if(event!=="connection")return originalServerOn.call(this,event,listener);const wrapped=s=>{const original=s.on.bind(s);let boot=true;s.on=(name,...args)=>{if(boot&&["start-game","game-roll","game-move"].includes(name)){const fn=args[0];return original(name,(...a)=>{if(s.data.ludoV2)return;return fn(...a)})}if(boot&&name==="disconnect"){const fn=args[0];return original(name,(...a)=>{if(s.data.ludoV2Started)return;return fn(...a)})}return original(name,...args)};listener(s);boot=false;s.on=original;original("join-room",p=>attach(s,p));original("ready",p=>ready(s,p));original("start-game",()=>start(s));original("game-roll",()=>roll(s));original("game-move",p=>move(s,p||{}));original("disconnect",()=>disconnect(s))};return originalServerOn.call(this,event,wrapped)}}