"use client";
import { useEffect, useMemo, useState } from "react";
import AppFrame from "../_components/AppFrame";

type Stats={gameRoomsEntered:number;spinsUsed:number;messagesSent:number;chatRoomsJoined:number;chatRoomsCreated:number};
type Wallet={coins:number;gems:number;spins:number;mystery:number};
type Mission={id:string;title:string;target:number;rewardCoins:number;value:(s:Stats)=>number};
const defaults:Stats={gameRoomsEntered:0,spinsUsed:0,messagesSent:0,chatRoomsJoined:0,chatRoomsCreated:0};
const walletDefault:Wallet={coins:25680,gems:320,spins:0,mystery:0};
const daily:Mission[]=[
{id:"games",title:"Win 3 matches",target:3,rewardCoins:1000,value:s=>Math.min(3,s.gameRoomsEntered)},
{id:"play5",title:"Play 5 matches",target:5,rewardCoins:500,value:s=>Math.min(5,s.gameRoomsEntered)},
{id:"four",title:"Win a match with 4 players",target:1,rewardCoins:1000,value:()=>Math.min(1,Number(localStorage.getItem("ludo-four-player-wins")||0))},
{id:"coins500",title:"Collect 500 coins",target:500,rewardCoins:1000,value:()=>Number(localStorage.getItem("ludo-coins-collected")||0)},
{id:"spin2",title:"Use spin wheel 2 times",target:2,rewardCoins:500,value:s=>s.spinsUsed},
];
function readStats(){try{return {...defaults,...JSON.parse(localStorage.getItem("ludo-stats")||"{}")}}catch{return defaults}}
function readWallet(){try{return {...walletDefault,...JSON.parse(localStorage.getItem("ludo-wallet")||"{}")}}catch{return walletDefault}}
export default function MissionsPage(){
const [tab,setTab]=useState("Daily");const [stats,setStats]=useState<Stats>(defaults);const [claimed,setClaimed]=useState<string[]>([]);const [wallet,setWallet]=useState<Wallet>(walletDefault);const [message,setMessage]=useState("");
const refresh=()=>{setStats(readStats());setWallet(readWallet());try{setClaimed(JSON.parse(localStorage.getItem("ludo-claimed-missions")||"[]"))}catch{setClaimed([])}};
useEffect(()=>{refresh();window.addEventListener("ludo-stats-updated",refresh);window.addEventListener("ludo-wallet-updated",refresh);window.addEventListener("storage",refresh);return()=>{window.removeEventListener("ludo-stats-updated",refresh);window.removeEventListener("ludo-wallet-updated",refresh);window.removeEventListener("storage",refresh)}},[]);
const list=useMemo(()=>daily.map(m=>{const value=Math.min(m.target,m.value(stats));return {...m,value,complete:value>=m.target,claimed:claimed.includes(m.id)}}),[stats,claimed]);
const claim=(m:typeof list[number])=>{if(!m.complete||m.claimed)return;const next=[...claimed,m.id];const w={...wallet,coins:wallet.coins+m.rewardCoins};localStorage.setItem("ludo-claimed-missions",JSON.stringify(next));localStorage.setItem("ludo-wallet",JSON.stringify(w));window.dispatchEvent(new Event("ludo-wallet-updated"));setClaimed(next);setWallet(w);setMessage(`Reward added: ${m.rewardCoins.toLocaleString()} coins.`)};
const claimAll=()=>list.filter(m=>m.complete&&!m.claimed).forEach(claim);
return <AppFrame back="/home"><main style={page}><header style={head}><div><div style={eyebrow}>DAILY OBJECTIVES</div><h1 style={title}>Missions</h1></div><span style={targetBadge}>🎯</span></header><div style={tabs}>{["Daily","Weekly","Achievements"].map(t=><button key={t} onClick={()=>setTab(t)} style={{...tabStyle,...(tab===t?tabActive:{})}}>{t}</button>)}</div>{tab!=="Daily"?<section style={empty}><div style={{fontSize:42}}>🏆</div><h2>{tab} Missions</h2><p>More objectives are coming soon. Complete your daily missions to keep building your rewards.</p></section>:<section style={missionList}>{list.map(m=><article key={m.id} style={mission}><div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{...status,background:m.complete?"#20a64a":"#ef9b20"}}>{m.complete?"✓":"×"}</div><div style={{flex:1}}><div style={rowTop}><b>{m.title}</b><span>🪙 {m.rewardCoins.toLocaleString()}</span></div><div style={progressTrack}><div style={{...progressBar,width:`${Math.round((m.value/m.target)*100)}%`,background:m.complete?"#24b957":"#1e78e8"}}/></div><div style={rowBottom}><span>{m.value} / {m.target}</span>{m.complete&&!m.claimed&&<button onClick={()=>claim(m)} style={claimBtn}>Claim</button>}{m.claimed&&<small style={{color:"#54d57b",fontWeight:900}}>CLAIMED</small>}</div></div></div></article>)}</section>}{message&&<div style={messageBox}>✓ {message}</div>}<button onClick={claimAll} disabled={!list.some(m=>m.complete&&!m.claimed)} style={{...claimAllBtn,opacity:list.some(m=>m.complete&&!m.claimed)?1:.45}}>Claim All</button></main></AppFrame>}
const page={maxWidth:720,margin:"0 auto",paddingBottom:45};const head={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"6px 2px 12px"};const eyebrow={fontSize:12,letterSpacing:2,fontWeight:950,color:"#60a5fa"};const title={fontSize:38,margin:"4px 0 0",fontWeight:950};const targetBadge={width:42,height:42,borderRadius:12,display:"grid",placeItems:"center",background:"#0d2345",border:"1px solid #244a7d",fontSize:22};const tabs={display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:5,padding:5,borderRadius:12,background:"#07162d",border:"1px solid #17345d"};const tabStyle={border:0,borderRadius:8,padding:"10px 5px",fontSize:12,fontWeight:900,cursor:"pointer",color:"#fff",background:"#10213d"};const tabActive={background:"#1769e8"};const missionList={display:"grid",gap:8,marginTop:14};const mission={padding:"12px 13px",borderRadius:12,background:"linear-gradient(145deg,#071a35,#061124)",border:"1px solid #17345d"};const status={flex:"0 0 27px",width:27,height:27,borderRadius:"50%",display:"grid",placeItems:"center",color:"#fff",fontWeight:950};const rowTop={display:"flex",justifyContent:"space-between",gap:8,fontSize:13};const progressTrack={height:7,borderRadius:99,background:"#122641",overflow:"hidden",marginTop:8};const progressBar={height:"100%",borderRadius:99,transition:"width .3s"};const rowBottom={display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:7,fontSize:11,color:"#8fa2bd"};const claimBtn={border:0,borderRadius:8,padding:"6px 15px",background:"#5fcf27",color:"#092006",fontWeight:950,cursor:"pointer"};const claimAllBtn={width:"100%",marginTop:14,border:0,borderRadius:9,padding:"12px",background:"linear-gradient(180deg,#4edc22,#2b9d13)",color:"#fff",fontWeight:950,fontSize:15,cursor:"pointer"};const empty={marginTop:14,padding:40,background:"#07162d",borderRadius:14,textAlign:"center" as const,color:"#9fb0c9"};const messageBox={marginTop:12,padding:11,borderRadius:10,background:"#07331a",border:"1px solid #1c8d4c",color:"#7ff0a8",fontSize:12};
