import {NextRequest,NextResponse} from "next/server";
import {createHash} from "crypto";
import {pool,ensureAuthSchema} from "../../../auth/_db";
const VALID_KINDS=["play_games","win_games","roll_dice","move_tokens","send_messages","join_rooms","create_rooms","roll_sixes","move_home","complete_games"];
const DIFFICULTIES=["easy","hard","very_hard"];
async function admin(q:NextRequest){await ensureAuthSchema();const t=q.cookies.get("ludo_session")?.value;if(!t)return null;const h=createHash("sha256").update(t).digest("hex"),r=await pool.query<any>(`SELECT u.* FROM ludo_users u JOIN ludo_sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[h]),u=r.rows[0];if(!u||u.is_guest||u.is_banned)return null;const allowed=(process.env.ADMIN_EMAILS||process.env.ADMIN_EMAIL||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);return u.email&&allowed.includes(u.email.toLowerCase())?u:null}
async function setup(){
  await ensureAuthSchema();
  await pool.query(`
    CREATE TABLE IF NOT EXISTS ludo_weekly_mission_definitions(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',target INTEGER NOT NULL DEFAULT 1,reward_coins INTEGER NOT NULL DEFAULT 0,reward_gems INTEGER NOT NULL DEFAULT 0,kind TEXT NOT NULL DEFAULT 'play_games',difficulty TEXT NOT NULL DEFAULT 'easy',admin_created BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,scheduled_week DATE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    ALTER TABLE ludo_weekly_mission_definitions ADD COLUMN IF NOT EXISTS scheduled_week DATE;
    ALTER TABLE ludo_weekly_mission_definitions ADD COLUMN IF NOT EXISTS difficulty TEXT NOT NULL DEFAULT 'easy';
    ALTER TABLE ludo_weekly_mission_definitions ADD COLUMN IF NOT EXISTS admin_created BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE ludo_weekly_mission_definitions ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE ludo_weekly_mission_definitions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
    CREATE TABLE IF NOT EXISTS ludo_weekly_mission_settings(week_start DATE PRIMARY KEY,bonus_coins INTEGER NOT NULL DEFAULT 50000,bonus_gems INTEGER NOT NULL DEFAULT 100,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    ALTER TABLE ludo_weekly_mission_settings ADD COLUMN IF NOT EXISTS bonus_coins INTEGER NOT NULL DEFAULT 50000;
    ALTER TABLE ludo_weekly_mission_settings ADD COLUMN IF NOT EXISTS bonus_gems INTEGER NOT NULL DEFAULT 100;
    ALTER TABLE ludo_weekly_mission_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
  `)
}
const cleanWeek=(v:any)=>{const s=String(v||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return new Date().toISOString().slice(0,10);const d=new Date(`${s}T00:00:00Z`),day=d.getUTCDay(),diff=day===0?-6:1-day;d.setUTCDate(d.getUTCDate()+diff);return d.toISOString().slice(0,10)};
export async function GET(q:NextRequest){try{await setup();if(!await admin(q))return NextResponse.json({error:"Admin access required."},{status:403});const m=await pool.query(`SELECT * FROM ludo_weekly_mission_definitions ORDER BY scheduled_week DESC NULLS LAST,created_at DESC`),s=await pool.query(`SELECT week_start AS "weekStart",bonus_coins AS "bonusCoins",bonus_gems AS "bonusGems",updated_at AS "updatedAt" FROM ludo_weekly_mission_settings ORDER BY week_start DESC LIMIT 20`);return NextResponse.json({missions:m.rows,validKinds:VALID_KINDS,difficulties:DIFFICULTIES,bonusSettings:s.rows,defaultBonus:{coins:50000,gems:100}})}catch(e){console.error(e);return NextResponse.json({error:"Weekly mission admin unavailable."},{status:500})}}
export async function POST(q:NextRequest){try{await setup();if(!await admin(q))return NextResponse.json({error:"Admin access required."},{status:403});const b=await q.json(),action=String(b.action||"");
if(action==="create"||action==="edit"){const id=String(b.id||`admin-weekly-${Date.now()}`).toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,80),title=String(b.title||"").trim().slice(0,100),description=String(b.description||"").trim().slice(0,300),target=Math.max(1,Math.trunc(Number(b.target||1))),coins=Math.max(0,Math.trunc(Number(b.rewardCoins||0))),gems=Math.max(0,Math.trunc(Number(b.rewardGems||0))),kind=String(b.kind||"play_games"),difficulty=String(b.difficulty||"easy"),week=cleanWeek(b.scheduledWeek);if(!title)return NextResponse.json({error:"Mission title is required."},{status:400});if(!VALID_KINDS.includes(kind))return NextResponse.json({error:"Invalid mission type."},{status:400});if(!DIFFICULTIES.includes(difficulty))return NextResponse.json({error:"Invalid difficulty."},{status:400});if(action==="edit"){const r=await pool.query(`UPDATE ludo_weekly_mission_definitions SET title=$1,description=$2,target=$3,reward_coins=$4,reward_gems=$5,kind=$6,difficulty=$7,scheduled_week=$8 WHERE id=$9 AND admin_created=TRUE`,[title,description,target,coins,gems,kind,difficulty,week,id]);if(!r.rowCount)return NextResponse.json({error:"Admin weekly mission not found."},{status:404});return NextResponse.json({ok:true,id})}await pool.query(`INSERT INTO ludo_weekly_mission_definitions(id,title,description,target,reward_coins,reward_gems,kind,difficulty,admin_created,scheduled_week) VALUES($1,$2,$3,$4,$5,$6,$7,$8,TRUE,$9)`,[id,title,description,target,coins,gems,kind,difficulty,week]);return NextResponse.json({ok:true,id})}
if(action==="set_active"){await pool.query(`UPDATE ludo_weekly_mission_definitions SET active=$1 WHERE id=$2 AND admin_created=TRUE`,[Boolean(b.active),String(b.id||"")]);return NextResponse.json({ok:true})}
if(action==="delete"){await pool.query(`DELETE FROM ludo_weekly_mission_definitions WHERE id=$1 AND admin_created=TRUE`,[String(b.id||"")]);return NextResponse.json({ok:true})}
if(action==="set_bonus"){const week=cleanWeek(b.weekStart),coins=Math.max(0,Math.trunc(Number(b.bonusCoins)||0)),gems=Math.max(0,Math.trunc(Number(b.bonusGems)||0));await pool.query(`INSERT INTO ludo_weekly_mission_settings(week_start,bonus_coins,bonus_gems,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(week_start) DO UPDATE SET bonus_coins=EXCLUDED.bonus_coins,bonus_gems=EXCLUDED.bonus_gems,updated_at=NOW()`,[week,coins,gems]);return NextResponse.json({ok:true,weekStart:week,bonusCoins:coins,bonusGems:gems})}
if(action==="reset_bonus"){await pool.query(`DELETE FROM ludo_weekly_mission_settings WHERE week_start=$1`,[cleanWeek(b.weekStart)]);return NextResponse.json({ok:true})}
return NextResponse.json({error:"Unknown weekly mission admin action."},{status:400})}catch(e){console.error(e);return NextResponse.json({error:"Weekly mission admin action failed."},{status:500})}}
