"use client";

import { useEffect, useMemo, useState } from "react";
import { io, type Socket } from "socket.io-client";

type CR={code:string;title:string;hostName:string;members:number;maxMembers:number;locked:boolean;ownerId:string};
type Member={id:string;name:string;role:"owner"|"member";owner:boolean;online:boolean};
type Msg={id?:string;name:string;text:string;at:number};
type MyRoom={code:string;title:string;members:Member[];messages:Msg[]};
function getPlayerId(){let id=localStorage.getItem("ludo-player-id");if(!id){id=crypto.randomUUID();localStorage.setItem("ludo-player-id",id)}return id}
export default function Chat(){
 const[rooms,setRooms]=useState<CR[]>([]),[myRoom,setMyRoom]=useState<MyRoom|null>(null),[name,setName]=useState("PlayerOne"),[title,setTitle]=useState(""),[showCreate,setShowCreate]=useState(false),[room,setRoom]=useState<MyRoom|null>(null),[messages,setMessages]=useState<Msg[]>([]),[members,setMembers]=useState<Member[]>([]),[text,setText]=useState(""),[socket,setSocket]=useState<Socket|null>(null),[tab,setTab]=useState<"all"|"mine">("all"),[error,setError]=useState("");
 const playerId=useMemo(()=>typeof window!=="undefined"?getPlayerId():"",[]);
 useEffect(()=>{const saved=localStorage.getItem("ludo-player-name");if(saved)setName(saved);const x=io(window.location.origin,{transports:["websocket","polling"]});x.on("chat-room-list",setRooms);x.on("chat-my-room",(r:MyRoom|null)=>setMyRoom(r));x.on("chat-room-joined",(d)=>{const r:MyRoom={code:d.code,title:d.title,members:d.members||[],messages:d.messages||[]};setRoom(r);setMyRoom(r);setMembers(r.members);setMessages(r.messages);setError("")});x.on("chat-room-members",(m:Member[])=>{setMembers(m);setMyRoom(r=>r?{...r,members:m}:r);setRoom(r=>r?{...r,members:m}:r)});x.on("chat-room-message",(m:Msg)=>setMessages(p=>[...p,m]));x.on("chat-kicked",(d)=>{window.alert(d.reason||"The room owner removed you.");setRoom(null);setMessages([]);setMembers([]);x.emit("list-chat-rooms",{playerId})});x.on("chat-room-error",(m)=>setError(String(m||"Something went wrong.")));x.emit("list-chat-rooms",{playerId});setSocket(x);return()=>{x.disconnect()}},[playerId]);
 const create=()=>{if(!socket)return;setError("");localStorage.setItem("ludo-player-name",name);socket.emit("create-chat-room",{title:title||`${name}'s Chat`,name,playerId});setShowCreate(false)};
 const join=(code:string)=>{if(!socket)return;setError("");socket.emit("join-chat-room",{roomCode:code,name,playerId})};
 const send=()=>{if(!text.trim()||!socket||!room)return;socket.emit("chat-room-message",{text});setText("")};
 const kick=(id:string)=>{const me=members.find(m=>m.id===playerId);if(socket&&room&&me?.role==="owner")socket.emit("kick-chat-member",id)};
 if(room){const me=members.find(m=>m.id===playerId);return <main className="subpage"><header className="sub-head"><button onClick={()=>{setRoom(null);setMessages([]);setMembers([])}} aria-label="Back">‹</button><div><small>{me?.role==="owner"?"OWNER / ADMIN":"MEMBER"}</small><h1>{room.title}</h1></div><span>{members.length}/20</span></header><section className="chat-room-live"><div className="member-strip">{members.map(m=><span key={m.id}>{m.name} {m.role==="owner"?"👑":""}{m.id!==playerId&&me?.role==="owner"?<button onClick={()=>kick(m.id)} style={{marginLeft:6}}>Remove</button>:null}</span>)}</div><div className="chat-history">{messages.map((m,i)=><div className="bubble" key={m.id||i}><b>{m.name}</b><p>{m.text}</p><small>{new Date(m.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><div className="chat-compose"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder="Type a message…"/><button onClick={()=>setText(v=>`${v} ❤️`)}>❤️</button><button onClick={send}>➤</button></div></section></main>}
 return <main className="subpage"><header className="sub-head"><button onClick={()=>window.history.back()} aria-label="Back">‹</button><div><small>WORLD CHAT</small><h1>Chat Rooms</h1></div><span>💬</span></header><div style={{display:"flex",gap:8,margin:"12px 0"}}><button className={tab==="all"?"big-primary":""} onClick={()=>setTab("all")}>ALL ROOMS</button><button className={tab==="mine"?"big-primary":""} onClick={()=>setTab("mine")}>MY ROOM</button></div>{error?<div className="empty-big"><b>{error}</b></div>:null}{tab==="mine"?<section className="room-browser chat-browser">{myRoom?<article className="browser-room"><div className="room-avatar">👑</div><div className="room-info"><b>{myRoom.title}</b><span>Owner: {myRoom.members.find(m=>m.role==="owner")?.name||name} · {myRoom.members.length}/20 · {myRoom.code}</span></div><button onClick={()=>join(myRoom.code)}>OPEN MY ROOM</button></article>:<div className="empty-big"><div>👑</div><h2>You don't have a room</h2><p>Create a room to get your private My Room tab.</p><button className="big-primary" onClick={()=>setShowCreate(true)}>＋ CREATE CHAT ROOM</button></div>}</section>:<><p className="sub-intro">All live rooms created by you and other players. You can belong to only one room at a time.</p><button className="big-primary" onClick={()=>setShowCreate(true)}>＋ CREATE CHAT ROOM</button><section className="room-browser chat-browser">{rooms.map(r=>{const member=myRoom?.code===r.code;return <article className="browser-room" key={r.code}><div className="room-avatar">{member?"👑":"💬"}</div><div className="room-info"><b>{r.title}</b><span>{r.hostName} · {r.members}/20 · {r.code}{member?" · YOU ARE A MEMBER":""}</span></div><button disabled={r.members>=20&&!member} onClick={()=>join(r.code)}>{member?"ENTER":"JOIN"}</button></article>})}{!rooms.length?<div className="empty-big"><div>💬</div><h2>No chat rooms yet</h2><p>Create the first room and it will appear here for everyone.</p></div>:null}</section></>}</main>;
}
