"use client";
import { useEffect, useMemo, useState } from "react";
import { io, type Socket } from "socket.io-client";

type CR={code:string;title:string;hostName:string;members:number;maxMembers:number;locked:boolean;ownerId:string};
type Member={id:string;name:string;role:"owner"|"member";owner:boolean;online:boolean};
type Msg={id?:string;name:string;text:string;at:number};
type MyRoom={code:string;title:string;members:Member[];messages:Msg[]};

function getPlayerId(){let id=localStorage.getItem("ludo-player-id");if(!id){id=crypto.randomUUID();localStorage.setItem("ludo-player-id",id)}return id}

export default function Chat(){
 const [rooms,setRooms]=useState<CR[]>([]);const [myRoom,setMyRoom]=useState<MyRoom|null>(null);const [name,setName]=useState("PlayerOne");const [title,setTitle]=useState("");const [show,setShow]=useState(false);const [room,setRoom]=useState<MyRoom|null>(null);const [messages,setMessages]=useState<Msg[]>([]);const [members,setMembers]=useState<Member[]>([]);const [text,setText]=useState("");const [s,setS]=useState<Socket|null>(null);const [tab,setTab]=useState<"all"|"mine">("all");const [error,setError]=useState("");
 const playerId=useMemo(()=>typeof window!=="undefined"?getPlayerId():"",[]);
 useEffect(()=>{const n=localStorage.getItem("ludo-player-name");if(n)setName(n);const x=io(window.location.origin,{transports:["websocket","polling"]});x.on("chat-room-list",setRooms);x.on("chat-my-room",r=>setMyRoom(r));x.on("chat-room-joined",r=>{const joined={code:r.code,title:r.title,members:r.members,messages:r.messages||[]};setRoom(joined);setMyRoom(joined);setMembers(r.members);setMessages(r.messages||[]);setError("")});x.on("chat-room-members",m=>{setMembers(m);setMyRoom(prev=>prev?{...prev,members:m}:prev);setRoom(prev=>prev?{...prev,members:m}:prev)});x.on("chat-room-message",m=>setMessages(v=>[...v,m]));x.on("chat-kicked",r=>{alert(r.reason||"The room owner removed you.");setRoom(null);setMessages([]);setMembers([]);x.emit("list-chat-rooms",{playerId})});x.on("chat-room-error",e=>setError(String(e||"Something went wrong.")));x.emit("list-chat-rooms",{playerId});setS(x);return()=>{x.disconnect()}},[playerId]);
 const create=()=>{if(!s)return;setError("");s.emit("create-chat-room",{title:title||`${name}'s Chat`,name,playerId});setShow(false)};
 const join=(code:string)=>{if(!s)return;setError("");s.emit("join-chat-room",{roomCode:code,name,playerId})};
 const openMyRoom=()=>{if(myRoom)join(myRoom.code)};
 const send=()=>{if(!text.trim()||!s||!room)return;s.emit("chat-room-message",{text});const old=JSON.parse(localStorage.getItem("ludo-stats")||"{}");localStorage.setItem("ludo-stats",JSON.stringify({...old,messagesSent:(old.messagesSent||0)+1}));window.dispatchEvent(new Event("ludo-stats-updated"));setText("")};
 const kick=(id:string)=>{if(s&&room&&members.find(m=>m.id===playerId)?.role==="owner")s.emit("kick-chat-member",id)};
 const goBack=()=>{if(window.history.length>1)window.history.back();else window.location.href="/"};
 if(room)return <main className="subpage"><header className="sub-head"><button onClick={()=>setRoom(null)}>‹</button><div><small>{members.find(m=>m.id===playerId)?.role==="owner"?"OWNER / ADMIN":"MEMBER"}</small><h1>{room.title}</h1></div><span>{members.length}/20</span></header><section className="chat-room-live"><div className="member-strip">{members.map(m=><span key={m.id}>{m.name} {m.role==="owner"?"👑":""} {m.id!==playerId&&members.find(me=>me.id===playerId)?.role==="owner"?<button onClick={()=>kick(m.id)} style={{marginLeft:6}}>Remove</button>:null}</span>)}</div><div className="chat-history">{messages.map((m,i)=><div className="bubble" key={m.id||i}><b>{m.name}</b><p>{m.text}</p><small>{new Date(m.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><div className="chat-compose"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Type a message…"/><button onClick={()=>setText(t=>t+" ❤️")}>❤️</button><button onClick={send}>➤</button></div></section></main>;
 return <main className="subpage"><header className="sub-head"><button onClick={goBack}>‹</button><div><small>WORLD CHAT</small><h1>Chat Rooms</h1></div><span>💬</span></header><div style={{display:"flex",gap:8,margin:"12px 0"}}><button className={tab==="all"?"big-primary":""} onClick={()=>setTab("all")}>ALL ROOMS</button><button className={tab==="mine"?"big-primary":""} onClick={()=>setTab("mine")}>MY ROOM</button></div>{error&&<div className="empty-big"><b>{error}</b></div>}{tab==="mine"?<section className="room-browser chat-browser">{myRoom?<article className="browser-room"><div className="room-avatar">👑</div><div className="room-info"><b>{myRoom.title}</b><span>Owner: {myRoom.members.find(m=>m.role==="owner")?.name||name} · {myRoom.members.length}/20 · {myRoom.code}</span></div><button onClick={openMyRoom}>OPEN MY ROOM</button></article>:<div className="empty-big"><div>👑</div><h2>You don't have a room</h2><p>Create a room to get your private My Room tab.</p><button className="big-primary" onClick={()=>setShow(true)}>＋ CREATE CHAT ROOM</button></div>}</section>:<><p className="sub-intro">All live rooms created by you and other players. You can belong to only one room at a time.</p><button className="big-primary" onClick={()=>setShow(true)}>＋ CREATE CHAT ROOM</button><section className="room-browser chat-browser">{rooms.map(r=>{const mine=myRoom?.code===r.code;return <article className="browser-room" key={r.code}><div className="room-avatar">{mine?"👑":"💬"}</div><div className="room-info"><b>{r.title}</b><span>{r.hostName} · {r.members}/20 · {r.code} {mine?"· YOU ARE A MEMBER":""}</span></div><button disabled={r.members>=20&&!mine} onClick={()=>join(r.code)}>{mine?"ENTER":"JOIN"}</button></article>)}{!rooms.length&&<div className="empty-big"><div>💬</div><h2>No chat rooms yet</h2><p>Create the first room and it will appear here for everyone.</p></div>}</section></>}{show&&<div className="modal-backdrop"><div className="modal"><button className="modal-x" onClick={()=>setShow(false)}>×</button><h2>Create Chat Room</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Room name"/><button className="modal-primary" onClick={create}>CREATE ROOM</button></div></div>}</main>
}
