"use client";
import{useEffect,useState}from"react";import{io}from"socket.io-client";import AppFrame from"../_components/AppFrame";import LudoBoard,{BOARD_NAMES,BOARD_PALETTES,BoardThemeId}from"../_components/LudoBoardFixed";import LudoDice,{DiceSkinId}from"../_components/LudoDice";
const diceNames:Record<DiceSkinId,string>={classic:"Classic White",golden:"Golden Dice",crystal:"Crystal Blue",fire:"Fire Dice",rainbow:"Rainbow Dice",diamond:"Diamond Dice",skull:"Skull Dice",sports:"Sports Dice"};
type TokenColor="green"|"yellow"|"red"|"blue";type DemoToken={color:TokenColor;position:number;id:number};type Mode="bot"|"2p"|"4p";
const colors:TokenColor[]=["green","yellow","red","blue"];
const teamText=(c:TokenColor[])=>c.map(x=>x[0].toUpperCase()+x.slice(1)).join(" + ");
const modePlayers=(mode:Mode)=>mode==="4p"?[{name:"You",colors:["green"] as TokenColor[]},{name:"Player 2",colors:["yellow"] as TokenColor[]},{name:"Player 3",colors:["red"] as TokenColor[]},{name:"Player 4",colors:["blue"] as TokenColor[]}]:[{name:"You",colors:["green","blue"] as TokenColor[]},{name:mode==="bot"?"Bot":"Player 2",colors:["red","yellow"] as TokenColor[]}];
const initialTokens=():DemoToken[]=>colors.flatMap(color=>Array.from({length:4},(_,id)=>({color,position:0,id})));
const starts={green:0,yellow:13,red:39,blue:26} as const;const safeIndexes=new Set([0,13,26,39]);
function trackIndex(color:TokenColor,position:number){return position>=1&&position<=52?(starts[color]+position-1)%52:null}
function sameSquare(a:DemoToken,b:DemoToken){const ai=trackIndex(a.color,a.position),bi=trackIndex(b.color,b.position);return ai!==null&&bi!==null&&ai===bi}

export default function BoardPage(){
 const[theme,setTheme]=useState<BoardThemeId>("classic"),[die,setDie]=useState<DiceSkinId>("classic"),[mode,setMode]=useState<Mode>("bot"),[roll,setRoll]=useState(1),[turn,setTurn]=useState(0),[tokens,setTokens]=useState<DemoToken[]>(initialTokens),[notice,setNotice]=useState("Roll the dice to play."),[botThinking,setBotThinking]=useState(false),[gameOver,setGameOver]=useState(false),p=BOARD_PALETTES[theme]||BOARD_PALETTES.classic;
 const players=modePlayers(mode),humanColors=players[0].colors;
 useEffect(()=>{try{setTheme((localStorage.getItem("ludo-match-board")||"classic")as BoardThemeId);const ms=JSON.parse(localStorage.getItem("ludo-match-members")||"[]");setDie((ms.find((x:any)=>!x.host)?.dice||"classic")as DiceSkinId)}catch{}const room=new URLSearchParams(location.search).get("room");if(room){const s=io(location.origin,{transports:["websocket","polling"]});s.on("connect",()=>s.emit("list-rooms"));s.on("roster",(m:any[])=>{const self=m.find(x=>x.id===s.id);if(self?.dice)setDie(self.dice as DiceSkinId);const h=m.find(x=>x.host);if(h?.board)setTheme(h.board as BoardThemeId)});return()=>{s.disconnect()}}},[]);
 const resetDemo=(nextMode:Mode=mode)=>{setMode(nextMode);setTokens(initialTokens());setTurn(0);setRoll(1);setNotice(nextMode==="4p"?"4-player demo. You are Green.":nextMode==="2p"?"2-player teams: Green + Blue vs Red + Yellow.":"You + Blue vs Bot: Red + Yellow.");setBotThinking(false);setGameOver(false)};
 const legal=(t:DemoToken,n:number)=>t.position===0?n===6:t.position<58&&t.position+n<=58;
 const moveState=(current:DemoToken[],moving:DemoToken,n:number,actorColors:TokenColor[])=>{const nextPos=moving.position===0?1:moving.position+n;let next=current.map(t=>t.color===moving.color&&t.id===moving.id?{...t,position:nextPos}:t);const idx=trackIndex(moving.color,nextPos);let killed:DemoToken[]=[];if(idx!==null&&!safeIndexes.has(idx)){next=next.map(t=>{const opponent=!actorColors.includes(t.color)&&t.position>0&&sameSquare({...moving,position:nextPos},t);if(opponent){killed.push(t);return {...t,position:0}}return t})}return{next,killed,finished:nextPos===58}};
 const botTurn=(playerIndex:number)=>{setBotThinking(true);setTimeout(()=>{if(gameOver)return;const n=1+Math.floor(Math.random()*6);setRoll(n);const actorColors=players[playerIndex].colors;const owned=tokens.filter(t=>actorColors.includes(t.color));const choices=owned.filter(t=>legal(t,n));if(!choices.length){setNotice(n===6?`${players[playerIndex].name} rolled 6 but has no legal move. Roll again.`:`${players[playerIndex].name} rolled ${n}. No legal move.`);setBotThinking(false);if(n===6)setTimeout(()=>botTurn(playerIndex),650);else{const next=(playerIndex+1)%players.length;setTurn(next);if(next!==0)setTimeout(()=>botTurn(next),650)}return}const pick=choices.find(t=>t.position>0)||choices[0];const result=moveState(tokens,pick,n,actorColors);setTokens(result.next);const killedText=result.killed.length?` Captured ${result.killed.length} opponent token${result.killed.length>1?"s":""}.`:"";const won=actorColors.every(c=>result.next.filter(t=>t.color===c&&t.position===58).length===4);if(won){setGameOver(true);setBotThinking(false);setNotice(`${players[playerIndex].name} wins!`);return}setNotice(`${players[playerIndex].name} rolled ${n}.${killedText}${result.finished?" A token reached home.":""}${n===6?" Roll again.":""}`);setBotThinking(false);if(n===6)setTimeout(()=>botTurn(playerIndex),650);else{const next=(playerIndex+1)%players.length;setTurn(next);if(next!==0)setTimeout(()=>botTurn(next),650)}},650)};
 const rollDice=()=>{if(turn!==0||botThinking||gameOver)return;const n=1+Math.floor(Math.random()*6);setRoll(n);const choices=tokens.filter(t=>humanColors.includes(t.color)&&legal(t,n));if(!choices.length){setNotice(n===6?"Six! But no legal move. Roll again.":`You rolled ${n}. No legal move.`);if(n!==6){const next=1;setTurn(next);setTimeout(()=>botTurn(next),700)}return}setNotice(n===6?"Six! Choose one of your tokens.":`You rolled ${n}. Choose a token to move.`)};
 const moveToken=(color:TokenColor,id:number)=>{if(turn!==0||botThinking||gameOver||!humanColors.includes(color))return;const target=tokens.find(t=>t.color===color&&t.id===id);if(!target||!legal(target,roll)){setNotice(target?.position===0?"A token needs a 6 to leave home.":"That move would go past the center.");return}const result=moveState(tokens,target,roll,humanColors);setTokens(result.next);const killedText=result.killed.length?` Captured ${result.killed.length} opponent token${result.killed.length>1?"s":""}!`:"";const won=humanColors.every(c=>result.next.filter(t=>t.color===c&&t.position===58).length===4);if(won){setGameOver(true);setNotice("You win the game!");return}setNotice(`${color[0].toUpperCase()+color.slice(1)} token ${id+1} moved ${roll}.${killedText}${result.finished?" Token reached the center.":""}${roll===6?" Roll again.":""}`);if(roll!==6){setTurn(1);setTimeout(()=>botTurn(1),700)}};
 const teamLabel=mode==="4p"?"You: Green · Yellow · Red · Blue":`You: ${teamText(humanColors)}  ·  ${players[1].name}: ${teamText(players[1].colors)}`;
 return <AppFrame back="/dashboard"><main style={{...page,background:p.bg,"--accent":p.accent}as React.CSSProperties}><header style={top}><div><div style={eyebrow}>LIVE MATCH · DEMO</div><h1 style={title}>{BOARD_NAMES[theme]||"Ludo Board"}</h1><p style={sub}>🎲 {diceNames[die]||"Classic White"} · Standard Ludo rules</p></div><div style={playersBadge}>{gameOver?"GAME OVER":mode==="4p"?"4 PLAYERS":mode==="2p"?"2 PLAYERS":"YOU VS BOT"}</div></header><div style={modeBar}><button type="button" onClick={()=>resetDemo("bot")} style={mode==="bot"?activeMode:modeBtn}>Player vs Bot</button><button type="button" onClick={()=>resetDemo("2p")} style={mode==="2p"?activeMode:modeBtn}>2 Players</button><button type="button" onClick={()=>resetDemo("4p")} style={mode==="4p"?activeMode:modeBtn}>4 Players</button></div><div style={demoBar}><span>🟢 {turn===0&&!gameOver?<b>Your turn</b>:gameOver?<b>Finished</b>:"Bot turn"}</span><span>{teamLabel}</span><button type="button" onClick={()=>resetDemo()}>New Game</button></div><section style={boardWrap}><LudoBoard theme={theme} demoTokens={tokens} onTokenClick={moveToken}/></section><section style={controls}><div><div style={turnLabel}>{gameOver?"RESULT":turn===0?"YOUR TURN":`${players[turn]?.name||"BOT"} TURN`}</div><b style={{fontSize:20}}>{gameOver?"Game finished":turn===0&&!botThinking?"Roll the dice":"Bot is playing…"}</b><p style={{margin:"4px 0",color:"#9fb5d8"}}>{notice}</p></div><LudoDice skin={die} value={roll} size={112} onClick={rollDice}/></section><div style={status}><span>🟢 Green</span><span>🔵 Blue</span><span>🔴 Red</span><span>🟡 Yellow</span><span>⭐ Safe squares cannot be captured</span><span>💥 Landing on an opponent on an unsafe square sends it home</span></div></main></AppFrame>}
const page:React.CSSProperties={width:"100%",minHeight:"calc(100vh - 40px)",padding:"18px",boxSizing:"border-box",borderRadius:22};const top:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,flexWrap:"wrap"};const eyebrow:React.CSSProperties={fontSize:11,letterSpacing:2,color:"var(--accent)",fontWeight:950};const title:React.CSSProperties={fontSize:"clamp(28px,6vw,42px)",margin:"5px 0",fontWeight:950};const sub:React.CSSProperties={color:"#9fb5d8",margin:0};const playersBadge:React.CSSProperties={padding:"10px 14px",borderRadius:12,background:"#071a36",border:"1px solid #284b7b",fontWeight:900};const modeBar:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",marginTop:14};const modeBtn:React.CSSProperties={padding:"9px 12px",borderRadius:10,border:"1px solid #cbd5e1",background:"#fff",fontWeight:800,cursor:"pointer"};const activeMode:React.CSSProperties={...modeBtn,background:"#071a36",color:"#fff",borderColor:"#071a36"};const demoBar:React.CSSProperties={display:"flex",alignItems:"center",gap:12,flexWrap:"wrap",marginTop:10,padding:"10px 12px",borderRadius:14,background:"#f5f7fa",border:"1px solid #d8dee7",color:"#172033",fontSize:13};const boardWrap:React.CSSProperties={display:"grid",placeItems:"center",marginTop:18};const controls:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,marginTop:16,padding:16,borderRadius:18,background:"#071a36",border:"1px solid #284b7b"};const turnLabel:React.CSSProperties={fontSize:10,letterSpacing:2,color:"#60a5fa",fontWeight:900};const status:React.CSSProperties={display:"flex",gap:12,flexWrap:"wrap",marginTop:12,padding:13,borderRadius:14,background:"#071a36",color:"#cbd5e1",fontSize:12};