"use client";
import{useEffect,useMemo,useState}from"react";import{io}from"socket.io-client";import AppFrame from"../_components/AppFrame";import LudoBoard,{BOARD_NAMES,BOARD_PALETTES,BoardThemeId}from"../_components/LudoBoardFixed";import{canMove,createToken,moveToken,rollDice,type LudoColor,type LudoToken}from"../../lib/ludoMovement";

type TokenColor=LudoColor;type DemoToken=LudoToken&{id:number};type Mode="bot"|"2p"|"4p";
const colors:TokenColor[]=["green","yellow","red","blue"];
const teamText=(c:TokenColor[])=>c.map(x=>x[0].toUpperCase()+x.slice(1)).join(" + ");
const modePlayers=(mode:Mode)=>mode==="4p"?[{name:"You",colors:["green"] as TokenColor[]},{name:"Player 2",colors:["yellow"] as TokenColor[]},{name:"Player 3",colors:["red"] as TokenColor[]},{name:"Player 4",colors:["blue"] as TokenColor[]}]:[{name:"You",colors:["green","blue"] as TokenColor[]},{name:mode==="bot"?"Bot":"Player 2",colors:["red","yellow"] as TokenColor[]}];
const initialTokens=():DemoToken[]=>colors.flatMap(color=>Array.from({length:4},(_,id)=>({...createToken(color),id})));
const visualPosition=(t:DemoToken)=>t.state==="yard"?0:t.state==="finished"?57:t.steps+1;

export default function BoardPage(){
 const[theme,setTheme]=useState<BoardThemeId>("classic"),[mode,setMode]=useState<Mode>("bot"),[roll,setRoll]=useState(1),[turn,setTurn]=useState(0),[tokens,setTokens]=useState<DemoToken[]>(initialTokens),[notice,setNotice]=useState("Dice removed for a clean rebuild. Movement engine is now wired in."),[botThinking,setBotThinking]=useState(false),[gameOver,setGameOver]=useState(false),p=BOARD_PALETTES[theme]||BOARD_PALETTES.classic;
 const players=modePlayers(mode);const humanColors=players[0].colors;
 useEffect(()=>{try{setTheme((localStorage.getItem("ludo-match-board")||"classic")as BoardThemeId)}catch{}const room=new URLSearchParams(location.search).get("room");if(room){const s=io(location.origin,{transports:["websocket","polling"]});s.on("connect",()=>s.emit("list-rooms"));s.on("roster",(m:any[])=>{const h=m.find(x=>x.host);if(h?.board)setTheme(h.board as BoardThemeId)});return()=>{s.disconnect()}}},[]);
 const resetDemo=(nextMode:Mode=mode)=>{setMode(nextMode);setTokens(initialTokens());setTurn(0);setRoll(1);setNotice("Dice removed for a clean rebuild. Movement engine is now wired in.");setBotThinking(false);setGameOver(false)};
 const winner=(state:DemoToken[],actorColors:TokenColor[])=>actorColors.every(c=>state.filter(t=>t.color===c&&t.state==="finished").length===4);
 const applyEngineMove=(state:DemoToken[],moving:DemoToken,n:number,actorColors:TokenColor[])=>{const teammates=new Set(actorColors);const capturePool=state.filter(t=>t.color===moving.color||!teammates.has(t.color));const result=moveToken(moving,n,capturePool);if(!result.moved)return{state,captured:[] as DemoToken[],finished:false};const next=state.map(t=>t.color===moving.color&&t.id===moving.id?{...moving}:t);const capturedIds=new Set(result.captured);const normalized=next.map(t=>capturedIds.has(t)?{...t,state:"yard",steps:-1}:t);return{state:normalized,captured:result.captured as DemoToken[],finished:moving.state==="finished"};};
 const botTurn=(playerIndex:number)=>{setBotThinking(true);setTimeout(()=>{if(gameOver)return;const n=rollDice();setRoll(n);const actorColors=players[playerIndex].colors;const choices=tokens.filter(t=>actorColors.includes(t.color)&&canMove(t,n));if(!choices.length){setNotice(`${players[playerIndex].name} rolled ${n}. No legal move.`);setBotThinking(false);if(n===6)setTimeout(()=>botTurn(playerIndex),650);else{const next=(playerIndex+1)%players.length;setTurn(next);if(next!==0)setTimeout(()=>botTurn(next),650)}return}const moving=choices.find(t=>t.state!=="yard")||choices[0];const result=applyEngineMove(tokens,moving,n,actorColors);setTokens(result.state);if(winner(result.state,actorColors)){setGameOver(true);setBotThinking(false);setNotice(`${players[playerIndex].name} wins!`);return}setNotice(`${players[playerIndex].name} rolled ${n}.${result.captured.length?` Captured ${result.captured.length} opponent token${result.captured.length>1?"s":""}.`:""}${result.finished?" Token reached the center.":""}${n===6?" Roll again.":""}`);setBotThinking(false);if(n===6)setTimeout(()=>botTurn(playerIndex),650);else{const next=(playerIndex+1)%players.length;setTurn(next);if(next!==0)setTimeout(()=>botTurn(next),650)}},650)};
 useEffect(()=>{if(turn>0&&!gameOver&&!botThinking)setTimeout(()=>botTurn(turn),450)},[turn]);
 const moveTokenFromBoard=(color:TokenColor,id:number)=>{if(turn!==0||botThinking||gameOver||!humanColors.includes(color))return;const moving=tokens.find(t=>t.color===color&&t.id===id);if(!moving)return;if(!canMove(moving,roll)){setNotice(`Roll ${roll} is not a legal move for this token.`);return}const result=applyEngineMove(tokens,moving,roll,humanColors);setTokens(result.state);if(winner(result.state,humanColors)){setGameOver(true);setNotice("You win!");return}setNotice(`Moved ${color} token ${id+1}.${result.captured.length?` Captured ${result.captured.length} opponent token${result.captured.length>1?"s":""}.`:""}${result.finished?" Token reached the center.":""}`);if(roll===6)setNotice(prev=>`${prev} Roll again.`);else{setTurn(players.length>1?1:0)}};
 const renderedTokens=useMemo(()=>tokens.map(t=>({...t,position:visualPosition(t)})),[tokens]);
 const teamLabel=mode==="4p"?"Green · Yellow · Red · Blue":`You: ${teamText(humanColors)} · ${players[1].name}: ${teamText(players[1].colors)}`;
 return <AppFrame back="/dashboard"><main style={{...page,background:p.bg,"--accent":p.accent}as React.CSSProperties}><header style={top}><div><div style={eyebrow}>LIVE MATCH · DEMO</div><h1 style={title}>{BOARD_NAMES[theme]||"Ludo Board"}</h1><p style={sub}>Standard Ludo movement</p></div><div style={playersBadge}>{gameOver?"GAME OVER":mode==="4p"?"4 PLAYERS":mode==="2p"?"2 PLAYERS":"YOU VS BOT"}</div></header><div style={modeBar}><button type="button" onClick={()=>resetDemo("bot")} style={mode==="bot"?activeMode:modeBtn}>Player vs Bot</button><button type="button" onClick={()=>resetDemo("2p")} style={mode==="2p"?activeMode:modeBtn}>2 Players</button><button type="button" onClick={()=>resetDemo("4p")} style={mode==="4p"?activeMode:modeBtn}>4 Players</button></div><div style={demoBar}><span>🟢 {turn===0&&!gameOver?<b>Your turn</b>:gameOver?<b>Finished</b>:"Bot turn"}</span><span>{teamLabel}</span><button type="button" onClick={()=>resetDemo()}>New Game</button></div><section style={boardWrap}><LudoBoard theme={theme} demoTokens={renderedTokens} onTokenClick={moveTokenFromBoard}/></section><section style={controls}><div><div style={turnLabel}>{gameOver?"RESULT":turn===0?"YOUR TURN":`${players[turn]?.name||"BOT"} TURN`}</div><b style={{fontSize:20}}>Roll: {roll}</b><p style={{margin:"4px 0",color:"#9fb5d8"}}>{notice}</p></div></section><div style={status}><span>🟢 Green</span><span>🔵 Blue</span><span>🔴 Red</span><span>🟡 Yellow</span><span>⭐ Safe squares cannot be captured</span><span>💥 Unsafe landing captures opponents</span></div></main></AppFrame>}
const page:React.CSSProperties={width:"100%",minHeight:"calc(100vh - 40px)",padding:"18px",boxSizing:"border-box",borderRadius:22};const top:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,flexWrap:"wrap"};const eyebrow:React.CSSProperties={fontSize:11,letterSpacing:2,color:"var(--accent)",fontWeight:950};const title:React.CSSProperties={fontSize:"clamp(28px,6vw,42px)",margin:"5px 0",fontWeight:950};const sub:React.CSSProperties={color:"#9fb5d8",margin:0};const playersBadge:React.CSSProperties={padding:"10px 14px",borderRadius:12,background:"#071a36",border:"1px solid #284b7b",fontWeight:900};const modeBar:React.CSSProperties={display:"flex",gap:8,flexWrap:"wrap",marginTop:14};const modeBtn:React.CSSProperties={padding:"9px 12px",borderRadius:10,border:"1px solid #cbd5e1",background:"#fff",fontWeight:800,cursor:"pointer"};const activeMode:React.CSSProperties={...modeBtn,background:"#071a36",color:"#fff",borderColor:"#071a36"};const demoBar:React.CSSProperties={display:"flex",alignItems:"center",gap:12,flexWrap:"wrap",marginTop:10,padding:"10px 12px",borderRadius:14,background:"#f5f7fa",border:"1px solid #d8dee7",color:"#172033",fontSize:13};const boardWrap:React.CSSProperties={display:"grid",placeItems:"center",marginTop:18};const controls:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,marginTop:16,padding:16,borderRadius:18,background:"#071a36",border:"1px solid #284b7b"};const turnLabel:React.CSSProperties={fontSize:10,letterSpacing:2,color:"#60a5fa",fontWeight:900};const status:React.CSSProperties={display:"flex",gap:12,flexWrap:"wrap",marginTop:12,padding:13,borderRadius:14,background:"#071a36",color:"#cbd5e1",fontSize:12};
