"use client";
import{useEffect,useState}from"react";import type{CSSProperties,ChangeEvent}from"react";
type MissionForm={title:string;description:string;target:number;rewardCoins:number;rewardGems:number;kind:string;scheduledDate:string};
const dateToday=()=>new Date().toISOString().slice(0,10);
const blankForm=():MissionForm=>({title:"",description:"",target:1,rewardCoins:500,rewardGems:0,kind:"play_games",scheduledDate:dateToday()});
const labels:any={play_games:"Games played",win_games:"Games won",roll_dice:"Dice rolls",move_tokens:"Legal token moves",send_messages:"Messages sent",join_rooms:"Rooms joined",create_rooms:"Rooms created",roll_sixes:"Sixes rolled",move_home:"Tokens brought home",complete_games:"Games finished"};
export default function MissionAdmin(){const[open,setOpen]=useState(false),[m,setM]=useState<any[]>([]),[kinds,setKinds]=useState<string[]>(Object.keys(labels)),[form,setF]=useState<MissionForm>(blankForm),[editId,setEditId]=useState<string|null>(null),[bonusDay,setBonusDay]=useState(dateToday()),[bonusCoins,setBonusCoins]=useState(5000),[bonusGems,setBonusGems]=useState(50),[defaultBonus,setDefaultBonus]=useState({coins:5000,gems:50}),[settings,setSettings]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
const load=async()=>{try{const r=await fetch("/api/missions/admin",{cache:"no-store"}),x=await r.json();if(!r.ok)throw Error(x.error);setM(x.missions||[]);setKinds(x.validKinds||Object.keys(labels));setSettings(x.bonusSettings||[]);setDefaultBonus(x.defaultBonus||{coins:5000,gems:50});const s=(x.bonusSettings||[]).find((z:any)=>String(z.mission_day).slice(0,10)===bonusDay);if(s){setBonusCoins(Number(s.bonus_coins));setBonusGems(Number(s.bonus_gems))}else{setBonusCoins(Number(x.defaultBonus?.coins||5000));setBonusGems(Number(x.defaultBonus?.gems||50))}}catch(e){setMsg(e instanceof Error?e.message:"Mission admin unavailable.")}};
useEffect(()=>{void load()},[]);
const setField=(key:keyof MissionForm,value:string|number)=>setF(x=>({...x,[key]:value}));
const save=async()=>{setBusy(true);setMsg("");try{const r=await fetch("/api/missions/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,action:editId?"edit":"create",id:editId||undefined})}),x=await r.json();if(!r.ok)throw Error(x.error||"Save failed.");setMsg(editId?"Mission updated.":"Mission created and prioritized for its scheduled day.");setEditId(null);setF(blankForm());await load()}catch(e){setMsg(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}};
const beginEdit=(x:any)=>{setEditId(x.id);setF({title:x.title,description:x.description||"",target:Number(x.target),rewardCoins:Number(x.reward_coins),rewardGems:Number(x.reward_gems),kind:x.kind,scheduledDate:String(x.scheduled_date||dateToday()).slice(0,10)});setOpen(true)};
const toggle=async(x:any)=>{await fetch("/api/missions/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set_active",id:x.id,active:!x.active})});await load()};
const remove=async(x:any)=>{if(!confirm(`Delete admin mission “${x.title}”?`))return;await fetch("/api/missions/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id:x.id})});await load()};
const saveBonus=async()=>{setBusy(true);setMsg("");try{const r=await fetch("/api/missions/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"set_bonus",missionDay:bonusDay,bonusCoins,bonusGems})}),x=await r.json();if(!r.ok)throw Error(x.error||"Bonus save failed.");setMsg(`Overall completion prize saved for ${bonusDay}.`);await load()}catch(e){setMsg(e instanceof Error?e.message:"Bonus save failed.")}finally{setBusy(false)}};
const resetBonus=async()=>{setBusy(true);try{await fetch("/api/missions/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reset_bonus",missionDay:bonusDay})});setBonusCoins(defaultBonus.coins);setBonusGems(defaultBonus.gems);setMsg(`Default prize restored for ${bonusDay}.`);await load()}finally{setBusy(false)}};
const onDay=(value:string)=>{setBonusDay(value);const s=settings.find((z:any)=>String(z.mission_day).slice(0,10)===value);if(s){setBonusCoins(Number(s.bonus_coins));setBonusGems(Number(s.bonus_gems))}else{setBonusCoins(defaultBonus.coins);setBonusGems(defaultBonus.gems)}};
return <>{!open&&<button onClick={()=>setOpen(true)} style={fab}>🎯 Missions</button>}{open&&<div style={overlay}><section style={panel}><header style={head}><div><small style={eyebrow}>DBASE • MISSION CONTROL</small><h2 style={{margin:"4px 0"}}>🎯 Mission Manager</h2><p style={muted}>Create/edit daily missions and control the special prize awarded after all 6 missions are completed.</p></div><button onClick={()=>{setOpen(false);setEditId(null);setF(blankForm())}} style={close}>×</button></header>
<section style={card}><div style={sectionTitle}><div><b>🏆 Overall daily completion prize</b><small>Players receive this once they complete all 6 missions and claim the special reward.</small></div><span style={pill}>Default 🪙 {defaultBonus.coins.toLocaleString()} · 💎 {defaultBonus.gems}</span></div><div style={grid}><label style={field}><span>Prize date</span><input type="date" value={bonusDay} onChange={e=>onDay(e.target.value)} style={input}/></label><label style={field}><span>Bonus coins</span><input type="number" min="0" value={bonusCoins} onChange={e=>setBonusCoins(Number(e.target.value))} style={input}/></label><label style={field}><span>Bonus gems</span><input type="number" min="0" value={bonusGems} onChange={e=>setBonusGems(Number(e.target.value))} style={input}/></label></div><div style={row}><button disabled={busy} onClick={saveBonus} style={primary}>{busy?"Saving…":"SAVE DAILY PRIZE"}</button><button disabled={busy} onClick={resetBonus} style={secondary}>Use default prize</button></div></section>
<section style={card}><div style={sectionTitle}><div><b>{editId?"✏️ Edit mission":"＋ Create mission"}</b><small>Admin missions are given priority for their scheduled day. The player page remains capped at 6.</small></div></div><div style={grid}><label style={field}><span>Mission title</span><input value={form.title} onChange={e=>setField("title",e.target.value)} style={input}/></label><label style={field}><span>Mission type</span><select value={form.kind} onChange={e=>setField("kind",e.target.value)} style={input}>{kinds.map(k=><option key={k} value={k}>{labels[k]||k}</option>)}</select></label><label style={field}><span>Target</span><input type="number" min="1" value={form.target} onChange={e=>setField("target",Number(e.target.value))} style={input}/></label><label style={field}><span>Mission coins</span><input type="number" min="0" value={form.rewardCoins} onChange={e=>setField("rewardCoins",Number(e.target.value))} style={input}/></label><label style={field}><span>Mission gems</span><input type="number" min="0" value={form.rewardGems} onChange={e=>setField("rewardGems",Number(e.target.value))} style={input}/></label><label style={field}><span>Scheduled date</span><input type="date" value={form.scheduledDate} onChange={e=>setField("scheduledDate",e.target.value)} style={input}/></label></div><label style={field}><span>Description</span><textarea value={form.description} onChange={(e:ChangeEvent<HTMLTextAreaElement>)=>setField("description",e.target.value)} style={textarea}/></label><div style={row}><button disabled={busy||!form.title.trim()} onClick={save} style={primary}>{busy?"Saving…":editId?"SAVE CHANGES":"CREATE MISSION"}</button>{editId&&<button onClick={()=>{setEditId(null);setF(blankForm())}} style={secondary}>Cancel edit</button>}</div></section>
{msg&&<div style={notice}>{msg}</div>}<div style={list}>{m.slice(0,40).map(x=><article key={x.id} style={item}><div><b>{x.title}</b><small>{x.description}</small><small>{labels[x.kind]||x.kind} · Target {x.target} · 🪙 {Number(x.reward_coins).toLocaleString()} · 💎 {Number(x.reward_gems).toLocaleString()}</small></div><div style={row}><span style={pill}>{x.scheduled_date?`📅 ${String(x.scheduled_date).slice(0,10)}`:"Pool"}</span>{x.admin_created&&<button onClick={()=>beginEdit(x)} style={secondary}>Edit</button>}{x.admin_created&&<button onClick={()=>void toggle(x)} style={x.active?onBtn:offBtn}>{x.active?"Active":"Off"}</button>}{x.admin_created&&<button onClick={()=>void remove(x)} style={danger}>Delete</button>}</div></article>)}</div></section></div>}</>}
const overlay:CSSProperties={position:"fixed",inset:0,zIndex:49,background:"#020611dd",backdropFilter:"blur(10px)",padding:16,display:"grid",placeItems:"center"};const panel:CSSProperties={width:"min(920px,100%)",maxHeight:"92vh",overflow:"auto",background:"linear-gradient(145deg,#0b1d3d,#050d20)",border:"1px solid #31578f",borderRadius:20,padding:20,color:"#eaf2ff",boxShadow:"0 25px 70px #000"};const head:CSSProperties={display:"flex",justifyContent:"space-between",gap:15};const eyebrow:CSSProperties={fontSize:10,letterSpacing:2,color:"#66b5ff",fontWeight:950};const muted:CSSProperties={color:"#8fa8ca",fontSize:12};const close:CSSProperties={width:40,height:40,borderRadius:12,border:"1px solid #38557d",background:"#0a1831",color:"#fff",fontSize:25};const card:CSSProperties={marginTop:14,padding:15,borderRadius:15,background:"#07162e",border:"1px solid #203b63"};const sectionTitle:CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"};const sectionTitleSmall:CSSProperties={};const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:9,marginTop:12};const field:CSSProperties={display:"grid",gap:5,color:"#8fa8ca",fontSize:11,fontWeight:800,marginTop:8};const input:CSSProperties={background:"#07152d",border:"1px solid #2a466f",borderRadius:10,padding:11,color:"#fff",minWidth:0};const textarea:CSSProperties={...input,width:"100%",minHeight:70,resize:"vertical"};const row:CSSProperties={display:"flex",gap:8,flexWrap:"wrap",alignItems:"center",marginTop:10};const primary:CSSProperties={border:0,borderRadius:10,padding:"10px 13px",background:"linear-gradient(135deg,#1767e8,#7134ef)",color:"#fff",fontWeight:950};const secondary:CSSProperties={border:"1px solid #38557d",borderRadius:10,padding:"9px 12px",background:"#0a1831",color:"#dce9ff",fontWeight:850};const danger:CSSProperties={...secondary,background:"#681e2b",borderColor:"#b94a60"};const fab:CSSProperties={position:"fixed",right:18,bottom:76,zIndex:50,border:0,borderRadius:14,padding:"13px 17px",background:"linear-gradient(135deg,#1767e8,#7134ef)",color:"#fff",fontWeight:950,boxShadow:"0 10px 30px #0008"};const pill:CSSProperties={padding:"7px 10px",borderRadius:99,background:"#102c55",color:"#8fc5ff",fontWeight:900,fontSize:11};const notice:CSSProperties={marginTop:10,padding:10,borderRadius:10,background:"#0b321f",color:"#8af0aa",fontSize:12};const list:CSSProperties={display:"grid",gap:8,marginTop:14};const item:CSSProperties={display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",padding:12,borderRadius:13,background:"#07162e",border:"1px solid #203b63"};const onBtn:CSSProperties={...secondary,background:"#116b42",borderColor:"#31b978",color:"white"};const offBtn:CSSProperties={...secondary,background:"#5b2330",borderColor:"#b94a60",color:"white"};
