"use client";
import {useEffect,useState} from "react";
export default function Dbase(){const[d,setD]=useState<any>(null),[err,setErr]=useState(""),[busy,setBusy]=useState("");const load=()=>fetch("/api/admin",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);setD(x)}).catch(e=>setErr(e.message));useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
const act=async(body:any)=>{setBusy(body.action);try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw Error(x.error);await load()}catch(e){alert(e instanceof Error?e.message:"Action failed")}finally{setBusy("")}};
if(err)return <main style={wrap}><h1>🔐 DBASE</h1><p style={{color:"#fca5a5"}}>{err}</p><p>Admin access is controlled server-side. Set <b>ADMIN_EMAILS</b> in Railway to your administrator email.</p></main>;if(!d)return <main style={wrap}>Loading secure admin database…</main>;const s=d.stats;return <main style={wrap}><header><div><h1>🛡️ DBASE</h1><p>Administrator control center • {d.admin.email}</p></div><strong style={{color:"#86efac"}}>● LIVE</strong></header>
<section style={grid}>{[["Players",s.total], ["Online now",d.online],["Registered",s.registered],["Guests",s.guests],["Banned",s.banned],["Coins in economy",s.coins],["Gems in economy",s.gems]].map(x=><div style={card} key={x[0]}><small>{x[0]}</small><b>{Number(x[1]).toLocaleString()}</b></div>)}</section>
<section style={panel}><h2>💰 Economy Ledger</h2><p>Every admin coin/gem adjustment is recorded with before/after balances and reason.</p><div style={scroll}>{d.ledger.map((x:any)=><div style={row} key={x.id}><b>{x.username||"Deleted player"}</b><span>{x.amount>0?"+":""}{x.amount} {x.currency}</span><span>{x.balance_before} → {x.balance_after}</span><small>{x.reason} • {new Date(x.created_at).toLocaleString()}</small></div>)}</div></section>
<section style={panel}><h2>👥 Player Management</h2><div style={scroll}>{d.users.map((u:any)=><Player key={u.id} u={u} act={act} busy={busy}/>)}</div></section>
<section style={panel}><h2>📈 Daily Visitors</h2>{d.visits.map((v:any)=><div style={row} key={v.visit_date}><b>{v.visit_date}</b><span>{v.visitors.toLocaleString()} unique visitors</span></div>)}</section>
<section style={panel}><h2>🚨 Disputes / Support</h2>{d.disputes.length?d.disputes.map((x:any)=><div style={row} key={x.id}><b>#{x.id} {x.title}</b><span>{x.username||"Unknown"} • {x.status}</span><small>{x.description}</small>{x.status!=="resolved"&&<button onClick={()=>act({action:"resolve_dispute",id:x.id,status:"resolved",note:"Resolved by admin"})}>Resolve</button>}</div>):<p>No disputes reported yet.</p>}</section>
<section style={panel}><h2>🔐 Admin Audit Log</h2>{d.actions.map((x:any)=><div style={row} key={x.id}><b>{x.action}</b><span>{x.target_username||x.target_user_id||"—"}</span><small>{new Date(x.created_at).toLocaleString()} • {JSON.stringify(x.details)}</small></div>)}</section></main>}
function Player({u,act,busy}:any){const[amount,setAmount]=useState(""),[currency,setCurrency]=useState("coins"),[reason,setReason]=useState("");return <div style={row}><div><b>{u.username}</b><small>{u.email||"guest"} • {u.id}</small></div><span>🪙 {u.coins.toLocaleString()} • 💎 {u.gems.toLocaleString()}</span><span>{u.last_seen_at&&new Date(u.last_seen_at)>new Date(Date.now()-120000)?"🟢 Online":"⚪ Offline"}</span><input placeholder="± amount" value={amount} onChange={e=>setAmount(e.target.value)} style={inp}/><select value={currency} onChange={e=>setCurrency(e.target.value)} style={inp}><option value="coins">Coins</option><option value="gems">Gems</option></select><input placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)} style={inp}/><button disabled={!!busy||u.is_guest} onClick={()=>act({action:"adjust",userId:u.id,currency,amount:Number(amount),reason})}>Adjust</button>{!u.is_guest&&<><button onClick={()=>act({action:u.is_banned?"unban":"ban",userId:u.id,reason:"Admin moderation"})}>{u.is_banned?"Unban":"Ban"}</button><button onClick={()=>{if(confirm("Permanently delete this player?"))act({action:"delete",userId:u.id,confirm:"DELETE"})}}>Delete</button></>}</div>}
const wrap:any={minHeight:"100vh",background:"#050b1d",color:"#e5edff",padding:24,fontFamily:"system-ui",maxWidth:1300,margin:"auto"};const grid:any={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12,margin:"20px 0"};const card:any={background:"#0d1835",border:"1px solid #243b68",borderRadius:16,padding:18,display:"grid",gap:8};const panel:any={background:"#0b142c",border:"1px solid #20345b",borderRadius:18,padding:18,margin:"16px 0"};const row:any={display:"flex",gap:12,alignItems:"center",flexWrap:"wrap",padding:"12px 0",borderBottom:"1px solid #1b2a48"};const scroll:any={maxHeight:500,overflow:"auto"};const inp:any={background:"#071024",color:"white",border:"1px solid #29446f",borderRadius:8,padding:8};
