"use client";
import {useEffect,useMemo,useState} from "react";

type Kind="background"|"sticker";
type Yard={id:string;name:string;description:string;kind:Kind;currency:string;price:number;rarity:string;isPublished:boolean;imageUrl:string};
const css:any={panel:{position:"fixed",inset:0,zIndex:1300,background:"rgba(0,0,0,.8)",display:"flex",alignItems:"center",justifyContent:"center",padding:12},box:{background:"#07142c",color:"#e8f0ff",border:"1px solid #315078",borderRadius:18,padding:18,width:"min(1080px,100%)",maxHeight:"94vh",overflow:"auto",boxShadow:"0 25px 80px rgba(0,0,0,.55)"},input:{width:"100%",boxSizing:"border-box",background:"#071024",color:"white",border:"1px solid #2b466f",borderRadius:9,padding:10},button:{border:"1px solid #31b978",background:"#116b42",color:"white",padding:"9px 12px",borderRadius:9,fontWeight:850,cursor:"pointer"},secondary:{border:"1px solid #315b8d",background:"#0b1935",color:"#cfe2ff",padding:"9px 12px",borderRadius:9,fontWeight:800,cursor:"pointer"},danger:{border:"1px solid #9d3b4a",background:"#4a1722",color:"#ffdce2",padding:"8px 10px",borderRadius:8,fontWeight:800,cursor:"pointer"}};

export default function YardManager(){
 const[open,setOpen]=useState(false),[yards,setYards]=useState<Yard[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[editing,setEditing]=useState<Yard|null>(null);
 const[name,setName]=useState(""),[description,setDescription]=useState(""),[kind,setKind]=useState<Kind>("background"),[rarity,setRarity]=useState("COMMON"),[currency,setCurrency]=useState("coins"),[price,setPrice]=useState("0"),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState("");
 const load=async()=>{try{const r=await fetch("/api/admin/yards",{cache:"no-store"});const d=await r.json();if(r.ok)setYards(d.yards||[]);else setNotice(d.error||"Unable to load yards.")}catch{setNotice("Unable to load yards.")}};
 useEffect(()=>{if(open)void load()},[open]);
 useEffect(()=>{if(!file){setPreview("");return}const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u)},[file]);
 const reset=()=>{setEditing(null);setName("");setDescription("");setKind("background");setRarity("COMMON");setCurrency("coins");setPrice("0");setFile(null);setPreview("")};
 const startEdit=(y:Yard)=>{setEditing(y);setName(y.name);setDescription(y.description);setKind(y.kind);setRarity(y.rarity);setCurrency(y.currency);setPrice(String(y.price));setFile(null);setPreview(y.imageUrl)};
 const save=async()=>{if(!name.trim()){setNotice("Name is required.");return}setBusy(true);setNotice("");try{const f=new FormData();f.set("name",name.trim());f.set("description",description.trim());f.set("kind",kind);f.set("rarity",rarity);f.set("currency",currency);f.set("price",price);if(file)f.set("image",file);if(editing){f.set("id",editing.id);f.set("isPublished",String(editing.isPublished));}const r=await fetch("/api/admin/yards",{method:editing?"PATCH":"POST",body:f});const d=await r.json();if(!r.ok)throw Error(d.error);setYards(d.yards||[]);setNotice(editing?"Yard item updated successfully.":"Yard item published successfully.");reset()}catch(e){setNotice(e instanceof Error?e.message:"Unable to save yard.")}finally{setBusy(false)}};
 const togglePublish=async(y:Yard)=>{setBusy(true);setNotice("");try{const f=new FormData();f.set("id",y.id);f.set("name",y.name);f.set("description",y.description);f.set("rarity",y.rarity);f.set("currency",y.currency);f.set("price",String(y.price));f.set("isPublished",String(!y.isPublished));const r=await fetch("/api/admin/yards",{method:"PATCH",body:f});const d=await r.json();if(!r.ok)throw Error(d.error);setYards(d.yards||[]);setNotice(!y.isPublished?`${y.name} is live in the player shop.`:`${y.name} is now hidden from the player shop.`)}catch(e){setNotice(e instanceof Error?e.message:"Unable to change publication state.")}finally{setBusy(false)}};
 const remove=async(y:Yard)=>{if(!window.confirm(`Delete ${y.name}? This removes the artwork and shop item.`))return;setBusy(true);setNotice("");try{const r=await fetch(`/api/admin/yards?id=${encodeURIComponent(y.id)}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw Error(d.error);setYards(d.yards||[]);if(editing?.id===y.id)reset();setNotice(`${y.name} deleted.`)}catch(e){setNotice(e instanceof Error?e.message:"Unable to delete yard.")}finally{setBusy(false)}};
 const title=editing?"Edit Yard Item":"Create Yard Item";
 return <><button style={css.button} onClick={()=>setOpen(true)}>🏡 Manage Yards</button>{open&&<div style={css.panel} onClick={()=>setOpen(false)}><section style={css.box} onClick={e=>e.stopPropagation()}>
  <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 5px"}}>🏡 Yards Shop Manager</h2><p style={{margin:0,color:"#8fa5c5",fontSize:13}}>Upload full yard backgrounds or transparent backgroundless stickers. Everything is stored server-side and appears in the player's Yards category when published.</p></div><button style={css.secondary} onClick={()=>setOpen(false)}>Close</button></header>
  {notice&&<div style={{marginTop:12,padding:10,border:"1px solid #315b8d",background:"#0a1934",borderRadius:10}}>{notice}</div>}
  <div style={{marginTop:14,padding:14,border:"1px solid #20375d",borderRadius:14,background:"#091a34"}}><h3 style={{marginTop:0}}>{title}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}>
   <label>Name<input style={css.input} value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="e.g. Golden Palace"/></label>
   <label>Presentation<select style={css.input} value={kind} disabled={Boolean(editing)} onChange={e=>setKind(e.target.value as Kind)}><option value="background">Background Yard</option><option value="sticker">Backgroundless Sticker</option></select></label>
   <label>Rarity<select style={css.input} value={rarity} onChange={e=>setRarity(e.target.value)}><option>COMMON</option><option>RARE</option><option>EPIC</option><option>LEGENDARY</option></select></label>
   <label>Currency<select style={css.input} value={currency} onChange={e=>setCurrency(e.target.value)}><option value="coins">Coins</option><option value="gems">Gems</option><option value="naira">Naira</option></select></label>
   <label>Price<input style={css.input} type="number" min="0" step="1" value={price} onChange={e=>setPrice(e.target.value)}/></label>
   <label>Artwork {editing&&<span style={{color:"#8fa5c5"}}>(optional replacement)</span>}<input style={css.input} type="file" accept="image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
  </div><label style={{display:"block",marginTop:10}}>Description<textarea style={{...css.input,minHeight:70}} value={description} maxLength={500} onChange={e=>setDescription(e.target.value)}/></label>
  {kind==="sticker"&&<p style={{fontSize:12,color:"#9ec7ff",marginBottom:0}}>✨ Backgroundless stickers must contain a real alpha channel. PNG and WebP are accepted.</p>}
  {preview&&<div style={{marginTop:12}}><b>Preview on all four yards</b><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8,marginTop:8}}>{[0,1,2,3].map(i=><div key={i} style={{height:130,borderRadius:12,position:"relative",overflow:"hidden",background:"#fff",border:"1px solid #315078"}}><div style={{position:"absolute",inset:0,background:kind==="background"?`url(${preview}) center/cover`:"#fff"}}/>{kind==="sticker"&&<img src={preview} alt="" style={{position:"absolute",inset:"12%",width:"76%",height:"76%",objectFit:"contain"}}/>}<span style={{position:"absolute",left:6,top:5,fontSize:10,fontWeight:900,background:"rgba(0,0,0,.55)",color:"white",borderRadius:5,padding:"2px 5px"}}>Yard {i+1}</span></div>)}</div></div>}
  <div style={{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"}}><button style={css.button} disabled={busy} onClick={()=>void save()}>{busy?(editing?"Saving…":"Publishing…"):(editing?"Save Changes":"Publish Yard Item")}</button>{editing&&<button style={css.secondary} disabled={busy} onClick={reset}>Cancel Edit</button>}</div></div>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:18}}><h3 style={{margin:0}}>Yard catalogue ({yards.length})</h3><button style={css.secondary} disabled={busy} onClick={()=>void load()}>Refresh</button></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10,marginTop:10}}>{yards.map(y=><article key={y.id} style={{background:"#0b1935",border:"1px solid #20375d",borderRadius:12,padding:10,opacity:y.isPublished?1:.62}}><div style={{height:130,borderRadius:9,overflow:"hidden",background:"#fff",display:"grid",placeItems:"center"}}><img src={y.imageUrl} alt="" style={{width:"100%",height:"100%",objectFit:y.kind==="background"?"cover":"contain"}}/></div><div style={{marginTop:8,display:"flex",justifyContent:"space-between",gap:8}}><b>{y.name}</b><span style={{fontSize:10,padding:"3px 6px",borderRadius:6,background:y.isPublished?"#124c34":"#3c2930"}}>{y.isPublished?"LIVE":"HIDDEN"}</span></div><small style={{display:"block",color:"#8fa5c5",marginTop:3}}>{y.kind==="sticker"?"Backgroundless Sticker":"Background Yard"} • {y.rarity} • {y.currency} {y.price}</small><div style={{display:"flex",gap:6,marginTop:9,flexWrap:"wrap"}}><button style={css.secondary} disabled={busy} onClick={()=>startEdit(y)}>Edit</button><button style={css.secondary} disabled={busy} onClick={()=>void togglePublish(y)}>{y.isPublished?"Unpublish":"Publish"}</button><button style={css.danger} disabled={busy} onClick={()=>void remove(y)}>Delete</button></div></article>)}</div>
 </section></div>}</>;
}
