"use client";
import {useEffect,useState} from "react";
import AppFrame from "../_components/AppFrame";

const rewards=[["1,000","🪙"],["1,500","🪙"],["5","💎"],["2,000","🪙"],["10","💎"],["3,000","🪙"],["5,000","🪙"]];
const bonus={coins:"10,000",gems:"25"};

export default function RewardsPage(){
 const[claimed,setClaimed]=useState(false),[streak,setStreak]=useState(0),[claimedDays,setClaimedDays]=useState<number[]>([]),[bonusClaimed,setBonusClaimed]=useState(false),[bonusAwarded,setBonusAwarded]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=()=>{setLoading(true);fetch("/api/rewards",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setClaimed(d.claimed);setStreak(d.streak);setClaimedDays(d.claimedDays||[]);setBonusClaimed(Boolean(d.bonus?.claimed))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);
 const claim=async()=>{if(claimed||loading)return;setError("");setLoading(true);try{const r=await fetch("/api/rewards",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error);setClaimed(true);setStreak(d.streak);setClaimedDays(d.claimedDays||[]);setBonusAwarded(Boolean(d.bonusAwarded));setBonusClaimed(Boolean(d.bonusAwarded));window.dispatchEvent(new Event("ludo-wallet-updated"))}catch(e){setError(e instanceof Error?e.message:"Could not claim reward")}finally{setLoading(false)}};
 return <AppFrame back="/home"><div style={{maxWidth:720,margin:"0 auto"}}><section style={{textAlign:"center"}}><h1 style={{color:"#facc15",fontSize:38}}>DAILY REWARD</h1><p>Claim each day to keep your streak. Miss a day and the streak resets.</p></section><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:9}}>{rewards.map(([a,i],n)=>{const dayNumber=n+1;const isClaimed=claimedDays.includes(dayNumber);return <div key={n} style={{...day,borderColor:isClaimed?"#22c55e":"rgba(80,126,215,.28)",boxShadow:isClaimed?"0 0 0 1px rgba(34,197,94,.18),0 8px 20px rgba(34,197,94,.08)":"none"}}><strong>Day {dayNumber}</strong><div style={{fontSize:34,margin:"10px 0 3px"}}>{i}</div><span>{a}</span>{isClaimed&&<small style={{display:"block",color:"#86efac",fontWeight:900,marginTop:6}}>✓ CLAIMED</small>}</div>})}</div><div style={bonusCard}><div style={{fontSize:24,fontWeight:950}}>🎁 7-DAY FAITHFUL BONUS</div><p style={{margin:"7px 0",fontWeight:800}}>Complete all 7 consecutive daily claims and receive this bonus together with your Day 7 reward.</p><div style={{display:"flex",justifyContent:"center",gap:18,fontSize:20,fontWeight:950}}><span>🪙 {bonus.coins}</span><span>💎 {bonus.gems}</span></div>{bonusClaimed&&<small style={{display:"block",marginTop:8,color:"#86efac",fontWeight:950}}>✓ BONUS CLAIMED{bonusAwarded?" WITH DAY 7":""}</small>}</div><button onClick={claim} disabled={claimed||loading} style={{width:"100%",marginTop:18,padding:17,border:0,borderRadius:14,background:claimed?"#3f6212":"#39a51d",color:"#fff",fontWeight:950,fontSize:20}}>{loading?"LOADING…":claimed?"CLAIMED ✓":"CLAIM TODAY'S REWARD"}</button>{error&&<p style={{textAlign:"center",color:"#fca5a5"}}>{error}</p>}<p style={{textAlign:"center",color:"#64748b"}}>Your current streak: {streak}</p></div></AppFrame>}
const day={padding:"16px 8px",borderRadius:14,border:"1px solid rgba(80,126,215,.28)",textAlign:"center" as const,color:"#fff",minHeight:132,background:"#0b1c4b"};
const bonusCard={marginTop:16,padding:"18px 16px",borderRadius:16,border:"1px solid rgba(250,204,21,.55)",textAlign:"center" as const,color:"#fff",background:"linear-gradient(135deg,rgba(113,70,5,.72),rgba(23,37,84,.94))",boxShadow:"0 10px 28px rgba(250,204,21,.1)"};
