"use client";
import {useEffect,useState} from "react";import AppFrame from "../_components/AppFrame";
const rewards=[["1,000","🪙"],["1,500","🪙"],["5","💎"],["2,000","🪙"],["10","💎"],["3,000","🪙"],["5,000","🪙"]];
export default function RewardsPage(){
 const[claimed,setClaimed]=useState(false),[streak,setStreak]=useState(0),[claimedDays,setClaimedDays]=useState<number[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=()=>{setLoading(true);fetch("/api/rewards",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setClaimed(d.claimed);setStreak(d.streak);setClaimedDays(d.claimedDays||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[]);
 const claim=async()=>{if(claimed||loading)return;setError("");setLoading(true);try{const r=await fetch("/api/rewards",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error);setClaimed(true);setStreak(d.streak);setClaimedDays(d.claimedDays||[]);window.dispatchEvent(new Event("ludo-wallet-updated"))}catch(e){setError(e instanceof Error?e.message:"Could not claim reward")}finally{setLoading(false)}};
 return <AppFrame back="/home"><div style={{maxWidth:720,margin:"0 auto"}}><section style={{textAlign:"center"}}><h1 style={{color:"#facc15",fontSize:38}}>DAILY REWARD</h1><p>Claim each day to keep your streak. Miss a day and the streak resets.</p></section><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:9}}>{rewards.map(([a,i],n)=>{const dayNumber=n+1;const isClaimed=claimedDays.includes(dayNumber);return <div key={n} style={{...day,borderColor:isClaimed?"#22c55e":"rgba(80,126,215,.28)",boxShadow:isClaimed?"0 0 0 1px rgba(34,197,94,.18),0 8px 20px rgba(34,197,94,.08)":"none"}}><strong>Day {dayNumber}</strong><div style={{fontSize:34,margin:"10px 0 3px"}}>{i}</div><span>{a}</span>{isClaimed&&<small style={{display:"block",color:"#86efac",fontWeight:900,marginTop:6}}>✓ CLAIMED</small>}</div>})}</div><button onClick={claim} disabled={claimed||loading} style={{width:"100%",marginTop:18,padding:17,border:0,borderRadius:14,background:claimed?"#3f6212":"#39a51d",color:"#fff",fontWeight:950,fontSize:20}}>{loading?"LOADING…":claimed?"CLAIMED ✓":"CLAIM TODAY'S REWARD"}</button>{error&&<p style={{textAlign:"center",color:"#fca5a5"}}>{error}</p>}<p style={{textAlign:"center",color:"#64748b"}}>Your current streak: {streak}</p></div></AppFrame>}
const day={padding:"16px 8px",borderRadius:14,border:"1px solid rgba(80,126,215,.28)",textAlign:"center" as const,color:"#fff",minHeight:132,background:"#0b1c4b"};
