import { NextRequest, NextResponse } from "next/server";
import { createHash, randomUUID } from "crypto";
import { pool, ensureAuthSchema } from "../../auth/_db";

const COOKIE="ludo_session";
const CURRENCIES=["coins","gems","naira"] as const;
const RARITIES=["COMMON","RARE","EPIC","LEGENDARY"] as const;
const MIME_TYPES=new Set(["image/png","image/jpeg","image/webp"]);
const MAX_IMAGE_BYTES=1_500_000;
type Currency=(typeof CURRENCIES)[number];

async function admin(q:NextRequest){
  const token=q.cookies.get(COOKIE)?.value;if(!token)return null;
  const hash=createHash("sha256").update(token).digest("hex");
  const result=await pool.query<any>(`SELECT u.* FROM ludo_users u JOIN ludo_sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[hash]);
  const user=result.rows[0];if(!user||user.is_guest||user.is_banned)return null;
  const allowed=(process.env.ADMIN_EMAILS||process.env.ADMIN_EMAIL||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);
  return user.email&&allowed.includes(user.email.toLowerCase())?user:null;
}

async function ensureSchema(){
  await ensureAuthSchema();
  await pool.query(`CREATE TABLE IF NOT EXISTS ludo_avatar_categories(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',is_active BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pool.query(`CREATE TABLE IF NOT EXISTS ludo_shop_avatars(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',category_id TEXT REFERENCES ludo_avatar_categories(id) ON DELETE SET NULL,rarity TEXT NOT NULL DEFAULT 'COMMON',currency TEXT NOT NULL CHECK(currency IN ('coins','gems','naira')),price INTEGER NOT NULL CHECK(price>=0),is_published BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 0,icon TEXT,image_data BYTEA,image_type TEXT,created_by TEXT,is_builtin BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pool.query(`ALTER TABLE ludo_shop_avatars ADD COLUMN IF NOT EXISTS is_builtin BOOLEAN NOT NULL DEFAULT FALSE`);
  const categories=[["classic","Classic","classic","Everyday Ludo avatars."],["heroes","Heroes","heroes","Bold hero-inspired avatars."],["royal","Royal","royal","Premium royal characters."],["fantasy","Fantasy","fantasy","Magic and fantasy characters."],["sports","Sports","sports","Sports and competitive characters."],["animals","Animals","animals","Animal and creature avatars."],["funny","Funny","funny","Playful and humorous avatars."],["seasonal","Seasonal","seasonal","Limited seasonal releases."],["limited","Limited Edition","limited","Rare, time-limited releases."]];
  for(let i=0;i<categories.length;i++){const [id,name,slug,description]=categories[i];await pool.query(`INSERT INTO ludo_avatar_categories(id,name,slug,description,sort_order) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING`,[id,name,slug,description,i]);}
  const builtins=[["avatar-1","Avatar 1","🧑🏽‍🎮","gems",500,"RARE"],["avatar-2","Avatar 2","👩🏽‍🎤","gems",700,"RARE"],["avatar-3","Avatar 3","🧔🏾‍♂️","gems",1000,"EPIC"],["avatar-4","Avatar 4","👨🏽‍🚀","gems",1200,"EPIC"],["avatar-5","Avatar 5","👩🏾‍🚀","gems",1300,"EPIC"],["avatar-6","Avatar 6","🧙🏽‍♂️","gems",2000,"LEGENDARY"]];
  for(const [id,name,icon,currency,price,rarity] of builtins) await pool.query(`INSERT INTO ludo_shop_avatars(id,name,description,category_id,rarity,currency,price,is_published,icon,is_builtin) VALUES($1,$2,'Built-in Ludo avatar.','classic',$3,$4,$5,TRUE,$6,TRUE) ON CONFLICT(id) DO UPDATE SET is_builtin=TRUE,icon=EXCLUDED.icon,category_id=COALESCE(ludo_shop_avatars.category_id,'classic'),updated_at=NOW()`,[id,name,rarity,currency,price,icon]);
}

function rowAvatar(r:any){return {id:r.id,type:"avatar",name:r.name,description:r.description||"",categoryId:r.category_id||null,category:r.category_name||null,rarity:r.rarity,currency:r.currency,price:Number(r.price),isPublished:Boolean(r.is_published),sortOrder:Number(r.sort_order),hasImage:Boolean(r.image_data),imageUrl:r.image_data?`/api/shop/avatars/${encodeURIComponent(r.id)}/image`:null,icon:r.icon||null,isBuiltin:Boolean(r.is_builtin),createdAt:r.created_at,updatedAt:r.updated_at};}
async function list(){const[categories,avatars]=await Promise.all([pool.query(`SELECT id,name,slug,description,is_active AS "isActive",sort_order AS "sortOrder" FROM ludo_avatar_categories ORDER BY sort_order,name`),pool.query(`SELECT a.*,c.name AS category_name FROM ludo_shop_avatars a LEFT JOIN ludo_avatar_categories c ON c.id=a.category_id ORDER BY a.sort_order,a.created_at DESC`)]);return {categories:categories.rows,avatars:avatars.rows.map(rowAvatar)};}

function dimensions(bytes:Buffer,mime:string){
  if(mime==="image/png"&&bytes.length>=24&&bytes.toString("ascii",0,8)==="\x89PNG\r\n\x1a\n")return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};
  if(mime==="image/webp"&&bytes.length>=30&&bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP"&&bytes.toString("ascii",12,16)==="VP8X")return {width:1+(bytes[24]|bytes[25]<<8|bytes[26]<<16),height:1+(bytes[27]|bytes[28]<<8|bytes[29]<<16)};
  if(mime==="image/jpeg"&&bytes.length>4&&bytes[0]===0xff&&bytes[1]===0xd8){let p=2;while(p+9<bytes.length){if(bytes[p]!==0xff){p++;continue}const marker=bytes[p+1];p+=2;if(marker===0xd9||marker===0xda)break;const len=bytes.readUInt16BE(p);if(len<2)break;if((marker>=0xc0&&marker<=0xc3)||(marker>=0xc5&&marker<=0xc7)||(marker>=0xc9&&marker<=0xcb)||(marker>=0xcd&&marker<=0xcf))return {height:bytes.readUInt16BE(p+3),width:bytes.readUInt16BE(p+5)};p+=len;}}
  return null;
}
async function validateImage(file:File){if(!MIME_TYPES.has(file.type))throw new Error("Only PNG, JPEG and WebP images are supported.");if(file.size<=0||file.size>MAX_IMAGE_BYTES)throw new Error("Avatar image must be between 1 byte and 1.5 MB.");const bytes=Buffer.from(await file.arrayBuffer());const size=dimensions(bytes,file.type);if(!size||size.width<128||size.height<128||size.width>2048||size.height>2048||size.width!==size.height)throw new Error("Avatar artwork must be a valid square image between 128×128 and 2048×2048 pixels.");return {bytes,size};}

export async function GET(q:NextRequest){try{if(!(await admin(q)))return NextResponse.json({error:"Admin access required."},{status:403});await ensureSchema();return NextResponse.json({ok:true,...await list()},{headers:{"Cache-Control":"no-store"}});}catch(e){console.error(e);return NextResponse.json({error:"Unable to load avatar manager."},{status:500});}}

export async function POST(q:NextRequest){try{const a=await admin(q);if(!a)return NextResponse.json({error:"Admin access required."},{status:403});await ensureSchema();const form=await q.formData();
  if(String(form.get("kind")||"")==="category"){const name=String(form.get("name")||"").trim();const description=String(form.get("description")||"").trim();const slug=String(form.get("slug")||name).trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!name||name.length>60||!slug)return NextResponse.json({error:"A valid category name is required."},{status:400});const id=`cat-${slug}-${randomUUID().slice(0,8)}`;await pool.query(`INSERT INTO ludo_avatar_categories(id,name,slug,description,sort_order) VALUES($1,$2,$3,$4,(SELECT COALESCE(MAX(sort_order),-1)+1 FROM ludo_avatar_categories))`,[id,name,slug,description]);return NextResponse.json({ok:true,...await list()});}
  const name=String(form.get("name")||"").trim(),description=String(form.get("description")||"").trim(),categoryId=String(form.get("categoryId")||"").trim()||null,rarity=String(form.get("rarity")||"COMMON").toUpperCase(),currency=String(form.get("currency")||"") as Currency,price=Math.trunc(Number(form.get("price"))),file=form.get("image");
  if(!name||name.length>80)return NextResponse.json({error:"Avatar name is required and must be 80 characters or fewer."},{status:400});if(!RARITIES.includes(rarity as any)||!CURRENCIES.includes(currency)||!Number.isFinite(price)||price<0)return NextResponse.json({error:"Choose a valid rarity, currency and non-negative price."},{status:400});if(!file||!(file instanceof File))return NextResponse.json({error:"Upload a PNG, JPEG or WebP avatar image."},{status:400});
  const checked=await validateImage(file);if(categoryId){const c=await pool.query(`SELECT id FROM ludo_avatar_categories WHERE id=$1 AND is_active=TRUE`,[categoryId]);if(!c.rowCount)return NextResponse.json({error:"Avatar category not found or inactive."},{status:400});}
  const id=`avatar-${randomUUID()}`;const icon=String(form.get("icon")||"").trim()||null;const result=await pool.query(`INSERT INTO ludo_shop_avatars(id,name,description,category_id,rarity,currency,price,is_published,icon,image_data,image_type,created_by,is_builtin,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,TRUE,$8,$9,$10,$11,FALSE,(SELECT COALESCE(MAX(sort_order),-1)+1 FROM ludo_shop_avatars)) RETURNING *`,[id,name,description,categoryId,rarity,currency,price,icon,checked.bytes,file.type,a.id]);
  await pool.query(`INSERT INTO ludo_admin_actions(admin_user_id,action,target_user_id,details) VALUES($1,'avatar_create',NULL,$2)`,[a.id,JSON.stringify({id,name,categoryId,rarity,currency,price,fileType:file.type,fileBytes:file.size,dimensions:checked.size})]);return NextResponse.json({ok:true,avatar:rowAvatar(result.rows[0]),...await list()});
}catch(e:any){console.error(e);return NextResponse.json({error:e?.message||"Unable to create avatar."},{status:400});}}

export async function PATCH(q:NextRequest){try{const a=await admin(q);if(!a)return NextResponse.json({error:"Admin access required."},{status:403});await ensureSchema();let body:any={};let file:File|null=null;if(q.headers.get("content-type")?.includes("multipart/form-data")){const form=await q.formData();body=Object.fromEntries(Array.from(form.entries()).filter(([,v])=>typeof v!=="object"));const f=form.get("image");if(f instanceof File&&f.size>0)file=f;}else body=await q.json().catch(()=>({}));
  if(body.kind==="category"){const id=String(body.id||"");if(!id)return NextResponse.json({error:"Category id is required."},{status:400});const name=String(body.name||"").trim();const description=String(body.description||"").trim();const isActive=body.isActive===undefined?true:Boolean(body.isActive);const sortOrder=Number.isFinite(Number(body.sortOrder))?Math.trunc(Number(body.sortOrder)):0;if(!name)return NextResponse.json({error:"Category name is required."},{status:400});await pool.query(`UPDATE ludo_avatar_categories SET name=$2,description=$3,is_active=$4,sort_order=$5,updated_at=NOW() WHERE id=$1`,[id,name,description,isActive,sortOrder]);return NextResponse.json({ok:true,...await list()});}
  const id=String(body.id||"");if(!id)return NextResponse.json({error:"Avatar id is required."},{status:400});const existing=await pool.query(`SELECT * FROM ludo_shop_avatars WHERE id=$1`,[id]);if(!existing.rowCount)return NextResponse.json({error:"Avatar not found."},{status:404});const old=existing.rows[0];const name=String(body.name??old.name).trim(),description=String(body.description??old.description).trim(),categoryId=body.categoryId===null||body.categoryId===""?null:String(body.categoryId),rarity=String(body.rarity??old.rarity).toUpperCase(),currency=String(body.currency??old.currency) as Currency,price=Math.trunc(Number(body.price??old.price)),isPublished=body.isPublished===undefined?Boolean(old.is_published):Boolean(body.isPublished),sortOrder=Math.trunc(Number(body.sortOrder??old.sort_order));
  if(!name||name.length>80||!RARITIES.includes(rarity as any)||!CURRENCIES.includes(currency)||!Number.isFinite(price)||price<0)return NextResponse.json({error:"Valid name, rarity, currency and price are required."},{status:400});if(categoryId){const c=await pool.query(`SELECT id FROM ludo_avatar_categories WHERE id=$1 AND is_active=TRUE`,[categoryId]);if(!c.rowCount)return NextResponse.json({error:"Avatar category not found or inactive."},{status:400});}
  let result;if(file){const checked=await validateImage(file);result=await pool.query(`UPDATE ludo_shop_avatars SET name=$2,description=$3,category_id=$4,rarity=$5,currency=$6,price=$7,is_published=$8,sort_order=$9,image_data=$10,image_type=$11,updated_at=NOW() WHERE id=$1 RETURNING *`,[id,name,description,categoryId,rarity,currency,price,isPublished,Number.isFinite(sortOrder)?sortOrder:0,checked.bytes,file.type]);}else result=await pool.query(`UPDATE ludo_shop_avatars SET name=$2,description=$3,category_id=$4,rarity=$5,currency=$6,price=$7,is_published=$8,sort_order=$9,updated_at=NOW() WHERE id=$1 RETURNING *`,[id,name,description,categoryId,rarity,currency,price,isPublished,Number.isFinite(sortOrder)?sortOrder:0]);
  await pool.query(`INSERT INTO ludo_admin_actions(admin_user_id,action,target_user_id,details) VALUES($1,'avatar_update',NULL,$2)`,[a.id,JSON.stringify({id,name,categoryId,rarity,currency,price,isPublished,replacedArtwork:Boolean(file)})]);return NextResponse.json({ok:true,avatar:rowAvatar(result.rows[0]),...await list()});
}catch(e:any){console.error(e);return NextResponse.json({error:e?.message||"Unable to update avatar."},{status:400});}}

export async function DELETE(q:NextRequest){try{const a=await admin(q);if(!a)return NextResponse.json({error:"Admin access required."},{status:403});await ensureSchema();const body=await q.json().catch(()=>({}));if(body.kind==="category"){const id=String(body.id||"");if(!id)return NextResponse.json({error:"Category id is required."},{status:400});await pool.query(`DELETE FROM ludo_avatar_categories WHERE id=$1`,[id]);return NextResponse.json({ok:true,...await list()});}const id=String(body.id||"");const r=await pool.query(`DELETE FROM ludo_shop_avatars WHERE id=$1 AND is_builtin=FALSE RETURNING id,name`,[id]);if(!r.rowCount)return NextResponse.json({error:"Built-in avatars cannot be permanently deleted. Hide them instead."},{status:409});await pool.query(`INSERT INTO ludo_admin_actions(admin_user_id,action,target_user_id,details) VALUES($1,'avatar_delete',NULL,$2)`,[a.id,JSON.stringify(r.rows[0])]);return NextResponse.json({ok:true,deleted:r.rows[0],...await list()});}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete avatar."},{status:500});}}
