"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import AppFrame from "../_components/AppFrame";
import LiveSocial from "../_components/LiveSocial";
import { AccountGateModal, useAccountGate } from "../_components/AccountGate";

type Room={code:string;players:number;host:boolean;name:string};
const ROOM_KEY="ludo-room";
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function bumpStat(key:string){try{const s=JSON.parse(localStorage.getItem("ludo-stats")||"{}");s[key]=(s[key]||0)+1;localStorage.setItem("ludo-stats",JSON.stringify(s));window.dispatchEvent(new Event("ludo-stats-updated"))}catch{}}
function RoomContent(){
 const params=useSearchParams(); const action=params.get("action")||"create"; const presetCode=params.get("code")||""; const presetSize=params.get("size")||"4";
 const [room,setRoom]=useState<Room|null>(null); const [restoring,setRestoring]=useState(true); const [players,setPlayers]=useState(presetSize); const [code,setCode]=useState(presetCode.toUpperCase()); const [name,setName]=useState(""); const [notice,setNotice]=useState(""); const gate=useAccountGate();
 useEffect(()=>{let cancelled=false;(async()=>{let profileName="";try{const a=await fetch("/api/auth",{cache:"no-store"}).then(r=>r.json());profileName=String(a?.user?.username||a?.user?.nickname||"").trim()}catch{}if(cancelled)return;try{const raw=localStorage.getItem(ROOM_KEY);if(raw){const saved=JSON.parse(raw) as Room;const sameRequestedRoom=!presetCode||saved.code===presetCode.toUpperCase();const sameMode=action==="join"?!saved.host:saved.host;if(saved?.code&&sameRequestedRoom&&sameMode){const restoredName=profileName||String(saved.name||"");setRoom({...saved,name:restoredName});setPlayers(String(saved.players));setCode(saved.code);setName(restoredName)}}if(profileName)setName(profileName)}catch{}finally{if(!cancelled)setRestoring(false)}})();return()=>{cancelled=true}},[action,presetCode]);
 const create=()=>{const r={code:makeCode(),players:Number(players),host:true,name:name.trim()||"Player"};localStorage.setItem(ROOM_KEY,JSON.stringify(r));bumpStat("gameRoomsEntered");setRoom(r)};
 const join=()=>{const c=code.trim().toUpperCase();if(c.length<4){setNotice("Enter the room code.");return}const r={code:c,players:Number(players)||4,host:false,name:name.trim()||"Player"};localStorage.setItem(ROOM_KEY,JSON.stringify(r));bumpStat("gameRoomsEntered");setRoom(r)};
 const gatedAction=(fn:()=>void)=>gate.check(fn);
 const start=()=>{if(!room)return;let board="classic";try{board=String(localStorage.getItem("ludo-match-board")||"classic")}catch{}window.location.href=`/game-online?room=${encodeURIComponent(room.code)}&name=${encodeURIComponent(room.name)}${room.host?"&host=1":""}&board=${encodeURIComponent(board)}`};
 const leave=()=>{localStorage.removeItem(ROOM_KEY);setRoom(null);window.location.href="/lobby"};
 if(restoring)return <AppFrame back="/lobby"><div style={{maxWidth:520,margin:"0 auto",padding:40,textAlign:"center",color:"#94a3b8"}}>Restoring your room…</div></AppFrame>;
 if(room)return <AppFrame back="/lobby"><div style={{maxWidth:900,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h1 style={{fontSize:38,marginBottom:4}}>Room Lobby</h1><p style={{color:"#94a3b8",marginTop:0}}>Your room was restored. Share the code and wait for everyone to get ready.</p></div><div style={{textAlign:"right"}}><small style={{color:"#64748b"}}>ROOM ID</small><div style={{fontSize:30,fontWeight:950,letterSpacing:5}}>{room.code}</div><button onClick={()=>navigator.clipboard?.writeText(room.code)} style={copyBtn}>📋 Copy code</button></div></div><div style={{marginTop:18,padding:18,borderRadius:18,background:"linear-gradient(135deg,#071c45,#0b1630)",border:"1px solid rgba(59,130,246,.22)"}}><div style={{fontWeight:900,fontSize:18}}>🎙️ Live room</div><p style={{color:"#94a3b8",marginBottom:0}}>Players waiting can discover this room in Online Players. Voice chat, quick messages, readiness and host moderation are live.</p></div><LiveSocial roomCode={room.code} name={room.name} host={room.host} roomSize={room.players} onStart={start} onKicked={()=>{localStorage.removeItem(ROOM_KEY);window.location.href="/lobby"}}/><div style={{marginTop:12}}><button onClick={leave} style={leaveBtn}>Leave Room</button></div></div></AppFrame>;
 return <AppFrame back="/lobby"><div style={{maxWidth:520,margin:"0 auto"}}><h1 style={{fontSize:38}}>{action==="join"?"Join a Game":"Create a Game"}</h1><p style={{color:"#94a3b8"}}>{action==="join"?"Join an open room and take an available seat.":"Create a real room. It will immediately appear in Online Players while it has space."}</p><label style={label}>Your name<input value={name} onChange={e=>setName(e.target.value)} style={input}/></label>{action==="join"?<><label style={label}>Room code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABC123" maxLength={6} style={input}/></label><label style={label}>Players<select value={players} onChange={e=>setPlayers(e.target.value)} style={input}><option value="2">2 Players</option><option value="4">4 Players</option></select></label></>:<label style={label}>Number of players<select value={players} onChange={e=>setPlayers(e.target.value)} style={input}><option value="2">2 Players</option><option value="4">4 Players</option></select></label>}<button onClick={()=>gatedAction(action==="join"?join:create)} style={primary}>{action==="join"?"Join Room":"Create Room"}</button>{notice&&<p style={{color:"#fbbf24"}}>{notice}</p>}<div style={{marginTop:18,padding:12,borderRadius:12,background:"rgba(30,41,59,.55)",color:"#94a3b8",fontSize:12}}>🔐 A registered account is required to create or join a game. Guest mode is for exploring the app only.</div></div><AccountGateModal open={gate.open} onClose={()=>gate.setOpen(false)}/></AppFrame>;
}
export default function RoomPage(){return <Suspense fallback={<AppFrame back="/lobby"><p>Loading room…</p></AppFrame>}><RoomContent/></Suspense>}
const label={display:"grid",gap:8,marginBottom:16,color:"#cbd5e1",fontWeight:700};const input={width:"100%",boxSizing:"border-box" as const,padding:14,borderRadius:12,border:"1px solid #334155",background:"#0f172a",color:"#fff",fontSize:16};const primary={border:0,cursor:"pointer",padding:"13px 18px",borderRadius:12,background:"#22c55e",color:"#fff",fontWeight:900,fontSize:16};const copyBtn={border:"1px solid #334155",background:"#0f172a",color:"#fff",borderRadius:9,padding:"7px 10px",cursor:"pointer"};const leaveBtn={border:0,cursor:"pointer",padding:"10px 14px",borderRadius:10,background:"#7f1d1d",color:"#fff",fontWeight:800};
