import { NextRequest, NextResponse } from "next/server";
import { createHash } from "crypto";
import { pool, ensureAuthSchema } from "../../auth/_db";

async function admin(q: NextRequest) {
  const token=q.cookies.get("ludo_session")?.value;if(!token)return null;
  const hash=createHash("sha256").update(token).digest("hex");
  const r=await pool.query<any>(`SELECT u.* FROM ludo_users u JOIN ludo_sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[hash]);
  const u=r.rows[0];
  if(!u||u.is_guest||u.is_banned)return null;
  const allowed=(process.env.ADMIN_EMAILS||process.env.ADMIN_EMAIL||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);
  return u.email&&allowed.includes(u.email.toLowerCase())?u:null;
}
async function setup(){await ensureAuthSchema();await pool.query(`CREATE TABLE IF NOT EXISTS ludo_mission_definitions(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',target INTEGER NOT NULL DEFAULT 1,reward_coins INTEGER NOT NULL DEFAULT 0,reward_gems INTEGER NOT NULL DEFAULT 0,kind TEXT NOT NULL DEFAULT 'play_games',admin_created BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,scheduled_date DATE,scheduled_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE ludo_mission_definitions ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;CREATE TABLE IF NOT EXISTS ludo_daily_mission_settings(mission_day DATE PRIMARY KEY,bonus_coins INTEGER NOT NULL DEFAULT 5000,bonus_gems INTEGER NOT NULL DEFAULT 50,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`)}
const validKinds=new Set(["play_games","win_games","roll_dice","move_tokens","send_messages","join_rooms","create_rooms","roll_sixes","move_home","complete_games"]);
const cleanDay=(v:any)=>{const s=String(v||"");if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(s))return new Date().toISOString().slice(0,10);const d=new Date(`${s}T00:00:00Z`);return Number.isNaN(d.getTime())?new Date().toISOString().slice(0,10):d.toISOString().slice(0,10)};
export async function GET(q:NextRequest){try{const a=await admin(q);if(!a)return NextResponse.json({error:"Admin access required."},{status:403});await setup();const r=await pool.query(`SELECT id,title,description,target,reward_coins AS "rewardCoins",reward_gems AS "rewardGems",kind,admin_created AS "adminCreated",active,scheduled_date AS "scheduledDate",scheduled_at AS "scheduledAt",created_at AS "createdAt" FROM ludo_mission_definitions ORDER BY COALESCE(scheduled_at,created_at) DESC`);const day=cleanDay(q.nextUrl.searchParams.get("day"));const s=await pool.query(`SELECT mission_day,bonus_coins AS "bonusCoins",bonus_gems AS "bonusGems",updated_at AS "updatedAt" FROM ludo_daily_mission_settings WHERE mission_day=$1`,[day]);return NextResponse.json({missions:r.rows,dailyBonus:s.rows[0]||{missionDay:day,bonusCoins:5000,bonusGems:50},day})}catch(e){console.error(e);return NextResponse.json({error:"Mission admin unavailable."},{status:500})}}
export async function POST(q:NextRequest){try{const a=await admin(q);if(!a)return NextResponse.json({error:"Admin access required."},{status:403});await setup();const b=await q.json(),action=String(b.action||"");
if(action==="create"||action==="edit"){const id=String(b.id||`admin-mission-${Date.now()}`).toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,80),title=String(b.title||"").trim().slice(0,120),description=String(b.description||"").trim().slice(0,300),target=Math.max(1,Math.min(100000,Math.trunc(Number(b.target)||1))),coins=Math.max(0,Math.trunc(Number(b.rewardCoins)||0)),gems=Math.max(0,Math.trunc(Number(b.rewardGems)||0)),kind=String(b.kind||"play_games"),active=b.active!==false,d=b.scheduledAt?new Date(String(b.scheduledAt)):null;if(!title||!validKinds.has(kind))return NextResponse.json({error:"Title and valid mission type are required."},{status:400});if(d&&Number.isNaN(d.getTime()))return NextResponse.json({error:"Invalid mission date/time."},{status:400});const at=d?d.toISOString():null,date=d?d.toISOString().slice(0,10):null;if(action==="create")await pool.query(`INSERT INTO ludo_mission_definitions(id,title,description,target,reward_coins,reward_gems,kind,admin_created,active,scheduled_date,scheduled_at) VALUES($1,$2,$3,$4,$5,$6,$7,TRUE,$8,$9,$10,$11)`,[id,title,description,target,coins,gems,kind,active,date,at]);else {const r=await pool.query(`UPDATE ludo_mission_definitions SET title=$1,description=$2,target=$3,reward_coins=$4,reward_gems=$5,kind=$6,admin_created=TRUE,active=$7,scheduled_date=$8,scheduled_at=$9 WHERE id=$10`,[title,description,target,coins,gems,kind,active,date,at,id]);if(!r.rowCount)return NextResponse.json({error:"Mission not found."},{status:404})}return NextResponse.json({ok:true,id})}
if(action==="toggle"){const r=await pool.query(`UPDATE ludo_mission_definitions SET active=NOT active,admin_created=TRUE WHERE id=$1 RETURNING active`,[String(b.id||"")]);if(!r.rowCount)return NextResponse.json({error:"Mission not found."},{status:404});return NextResponse.json({ok:true,active:r.rows[0].active})}
if(action==="delete"){const r=await pool.query(`DELETE FROM ludo_mission_definitions WHERE id=$1`,[String(b.id||"")]);if(!r.rowCount)return NextResponse.json({error:"Mission not found."},{status:404});return NextResponse.json({ok:true})}
if(action==="set_bonus"){const day=cleanDay(b.missionDay),coins=Math.max(0,Math.trunc(Number(b.bonusCoins)||0)),gems=Math.max(0,Math.trunc(Number(b.bonusGems)||0));await pool.query(`INSERT INTO ludo_daily_mission_settings(mission_day,bonus_coins,bonus_gems,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(mission_day) DO UPDATE SET bonus_coins=EXCLUDED.bonus_coins,bonus_gems=EXCLUDED.bonus_gems,updated_at=NOW()`,[day,coins,gems]);return NextResponse.json({ok:true,missionDay:day,bonusCoins:coins,bonusGems:gems})}
if(action==="reset_bonus"){await pool.query(`DELETE FROM ludo_daily_mission_settings WHERE mission_day=$1`,[cleanDay(b.missionDay)]);return NextResponse.json({ok:true})}
return NextResponse.json({error:"Unknown mission admin action."},{status:400})}catch(e){console.error(e);return NextResponse.json({error:e instanceof Error?e.message:"Mission admin action failed."},{status:500})}}
