"use client";

import { useEffect, useMemo, useState } from "react";
import AppFrame from "../_components/AppFrame";

type Tournament={id:string;name:string;description:string;status:string;entry_fee_coins:number;entry_fee_gems:number;prize_pool_coins:number;prize_pool_gems:number;max_players:number;players_count:number;starts_at:string;ends_at:string;prize_multiplier:number;participation_reward_coins:number;joined:number};
type Row={user_id:string;username:string;points:number;wins:number;eligible:boolean;position:number};
const money=(n:number)=>Number(n||0).toLocaleString();
const time=(ms:number)=>{if(ms<=0)return "Ended";const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return d?`${d}d ${h}h ${m}m`:`${h}h ${m}m`};

export default function TournamentPage(){
 const [tournaments,setTournaments]=useState<Tournament[]>([]),[selectedId,setSelectedId]=useState(""),[leaderboard,setLeaderboard]=useState<Row[]>([]),[mine,setMine]=useState<any[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const selected=useMemo(()=>tournaments.find(t=>t.id===selectedId)||null,[tournaments,selectedId]);
 const load=async(id=selectedId)=>{try{const r=await fetch(`/api/tournaments${id?`?id=${encodeURIComponent(id)}`:""}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load tournaments");setTournaments(d.tournaments||[]);setMine(d.mine||[]);if(id){setSelectedId(id);setLeaderboard(d.leaderboard||[])}else if(!selectedId&&d.tournaments?.[0]){setSelectedId(d.tournaments[0].id)}}catch(e){setNotice(e instanceof Error?e.message:"Tournament service unavailable")}};
 useEffect(()=>{void load();const i=setInterval(()=>void load(selectedId),7000),c=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(i);clearInterval(c)}},[selectedId]);
 const open=(id:string)=>{setSelectedId(id);setNotice("");void load(id)};
 const join=async()=>{if(!selected)return;setBusy(true);setNotice("");try{const r=await fetch("/api/tournaments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"join",tournamentId:selected.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to join");setNotice("Tournament joined. Your dedicated tournament board is ready.");await load(selected.id)}catch(e){setNotice(e instanceof Error?e.message:"Unable to join tournament")}finally{setBusy(false)}};
 const leave=async()=>{if(!selected)return;setBusy(true);try{const r=await fetch("/api/tournaments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"leave",tournamentId:selected.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to leave");setNotice("You left the tournament. Tournament rewards are forfeited.");await load(selected.id)}catch(e){setNotice(e instanceof Error?e.message:"Unable to leave")}finally{setBusy(false)}};
 const mineRow=mine.find(x=>x.tournament_id===selected?.id);
 const cutoff=selected?new Date(new Date(selected.ends_at).getTime()-2*86400000).getTime():0;
 return <AppFrame back="/home"><main style={s.page}>
  <header style={s.header}><button onClick={()=>window.history.back()} style={s.icon}>←</button><div><div style={s.eyebrow}>LUDO LIVE • REWARD TOURNAMENTS</div><strong style={s.title}>Tournament</strong></div><span style={s.icon}>🏆</span></header>
  {!selected&&<section style={s.hero}><div style={s.heroEmoji}>🏆 🎲 🪙 💎</div><b style={s.heroTitle}>CHOOSE YOUR TOURNAMENT</b><p>Open a tournament first. You will see its leaderboard lobby before entering the dedicated Bot-vs-Human board.</p></section>}
  {!selected&&<div style={s.grid}>{tournaments.map(t=><button key={t.id} style={s.card} onClick={()=>open(t.id)}><div style={s.row}><div><small style={s.status}>{t.status==='live'?"🔴 LIVE":"🟢 OPEN"}</small><h2 style={s.cardTitle}>{t.name}</h2></div><b>{money(t.players_count)}/{money(t.max_players)}</b></div><p>{t.description}</p><div style={s.stats}><span>🪙 {money(t.entry_fee_coins)}</span><span>🏆 {money(t.prize_pool_coins)}</span><span>+5/win</span></div></button>)}</div>}
  {selected&&<><button style={s.backLink} onClick={()=>setSelectedId("")}>← All tournaments</button><section style={s.hero}><div style={s.heroEmoji}>🏆</div><b style={s.heroTitle}>{selected.name}</b><p>{selected.description}</p><div style={s.pills}><span>🪙 Entry {money(selected.entry_fee_coins)}</span><span>🏆 Pool {money(selected.prize_pool_coins)}</span><span>🎯 +5 points / win</span><span>🎯 50 points to qualify</span></div></section>
   <section style={s.info}><div><small>PLAYERS</small><b>{money(selected.players_count)} / {money(selected.max_players)}</b></div><div><small>JOIN UNTIL</small><b>{cutoff?new Date(cutoff).toLocaleDateString():"—"}</b></div><div><small>ENDS IN</small><b>{time(new Date(selected.ends_at).getTime()-now)}</b></div><div><small>TOP 10 MULTIPLIER</small><b>{Math.round(Number(selected.prize_multiplier||.2)*100)}%</b></div></section>
   <section style={s.tableBox}><div style={s.tableHead}><b>🥇 TOP 10 — PRIZE POSITIONS</b><span>50+ pts eligible</span></div><div style={s.table}><div style={s.tr}><b>#</b><b>PLAYER</b><b>POINTS</b><b>WINS</b></div>{leaderboard.filter(x=>x.eligible).slice(0,10).map(x=><div key={x.user_id} style={s.tr}><b>{x.position}</b><span>{x.username}</span><b>{x.points}</b><span>{x.wins}</span></div>)}{!leaderboard.filter(x=>x.eligible).length&&<p style={s.empty}>No player has reached 50 points yet.</p>}</div></section>
   <section style={s.tableBox}><div style={s.tableHead}><b>👥 PARTICIPANT TABLE</b><span>{money(selected.participation_reward_coins)} coins at finish</span></div><div style={s.table}><div style={s.tr}><b>#</b><b>PLAYER</b><b>POINTS</b><b>WINS</b></div>{leaderboard.filter(x=>!x.eligible||x.position>10).map((x,i)=><div key={x.user_id} style={s.tr}><b>{i+1}</b><span>{x.username}</span><b>{x.points}</b><span>{x.wins}</span></div>)}{!leaderboard.filter(x=>!x.eligible||x.position>10).length&&<p style={s.empty}>Players outside the Top 10 appear here.</p>}</div></section>
   <section style={s.rules}><b>TOURNAMENT RULES</b><span>• Every valid win adds 5 points.</span><span>• Points never decrease when ranking changes.</span><span>• Equal points: first player to reach the score ranks higher.</span><span>• Maximum 3 active tournaments per player.</span><span>• Leaving forfeits tournament rewards.</span><span>• New players start at 0 points.</span><span>• Entry closes on the second-to-last day.</span><span>• This board is separate from Friends → Mood.</span></section>
   {mineRow?.status==='active'?<><button style={{...s.play,background:"linear-gradient(135deg,#1e6df0,#7134ef)"}} disabled={busy} onClick={()=>window.location.href=`/game?tournament=${encodeURIComponent(selected.id)}&board=tournament`}>🎮 PLAY / RESUME TOURNAMENT BOARD</button><button style={s.leave} disabled={busy} onClick={()=>void leave()}>LEAVE TOURNAMENT</button></>:<button style={s.play} disabled={busy||selected.status==='finished'||selected.status==='cancelled'||new Date()>=new Date(cutoff)} onClick={()=>void join()}>{busy?"JOINING…":"JOIN TOURNAMENT"}</button>}
  </>}
  {notice&&<div style={s.notice}>{notice}</div>}
 </main></AppFrame>;
}
const s:any={page:{maxWidth:700,margin:"0 auto",paddingBottom:50,color:"#fff"},header:{height:66,display:"grid",gridTemplateColumns:"44px 1fr 44px",alignItems:"center"},icon:{border:0,background:"transparent",color:"#fff",fontSize:26},eyebrow:{fontSize:9,letterSpacing:2,color:"#65adff",fontWeight:950},title:{fontSize:21},hero:{padding:18,borderRadius:18,background:"radial-gradient(circle at 50% 0%,#6a2be0,#0b1737 65%)",border:"1px solid #7545df",marginBottom:12,textAlign:"center"},heroEmoji:{fontSize:30,marginBottom:6},heroTitle:{fontSize:24,color:"#ffe45b",letterSpacing:1},hero:{padding:18,borderRadius:18,background:"radial-gradient(circle at 50% 0%,#6a2be0,#0b1737 65%)",border:"1px solid #7545df",marginBottom:12,textAlign:"center"},grid:{display:"grid",gap:10},card:{textAlign:"left",padding:15,borderRadius:16,border:"1px solid #244a7d",background:"linear-gradient(145deg,#081d3c,#061329)",color:"#fff"},row:{display:"flex",justifyContent:"space-between",gap:8},status:{fontSize:9,color:"#ffe15b"},cardTitle:{fontSize:18,margin:"4px 0"},stats:{display:"flex",gap:10,flexWrap:"wrap",fontSize:11,color:"#a9c3e4"},backLink:{border:0,background:"transparent",color:"#7eb5ff",padding:"6px 0 12px"},pills:{display:"flex",justifyContent:"center",gap:6,flexWrap:"wrap",marginTop:10},info:{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8,marginBottom:10},tableBox:{border:"1px solid #244a7d",borderRadius:15,overflow:"hidden",marginBottom:10,background:"#061329"},tableHead:{display:"flex",justifyContent:"space-between",gap:8,padding:12,background:"#0b2245",fontSize:11},table:{padding:8},tr:{display:"grid",gridTemplateColumns:"40px 1fr 80px 60px",gap:8,padding:"9px 4px",borderBottom:"1px solid #132b4d",fontSize:11,alignItems:"center"},empty:{padding:10,color:"#8298b6",fontSize:11},rules:{display:"grid",gap:6,padding:13,borderRadius:14,background:"#07182f",border:"1px solid #1d3b62",fontSize:11,color:"#b9cae2",marginBottom:10},play:{width:"100%",border:0,borderRadius:12,padding:14,color:"#fff",fontWeight:950,fontSize:13,background:"linear-gradient(135deg,#1767e8,#7134ef)"},leave:{width:"100%",marginTop:8,border:"1px solid #73334b",borderRadius:12,padding:11,color:"#ffb6c8",background:"transparent",fontWeight:900},notice:{position:"sticky",bottom:12,padding:12,borderRadius:12,background:"#07182feF",border:"1px solid #3e83e7",marginTop:10,fontSize:12}
};
