import { Pool } from "pg";

const globalForDb=globalThis as unknown as {ludoPool?:Pool};
function databaseConfig(){const raw=process.env.DATABASE_URL;if(!raw)throw new Error("DATABASE_URL is not configured");let connectionString=raw;try{const u=new URL(raw);u.searchParams.delete("sslmode");u.searchParams.delete("sslcert");u.searchParams.delete("sslkey");u.searchParams.delete("sslrootcert");connectionString=u.toString()}catch{}return{connectionString,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false}}
export const pool=globalForDb.ludoPool??new Pool(databaseConfig());if(!globalForDb.ludoPool)globalForDb.ludoPool=pool;let schemaPromise:Promise<void>|null=null;
export function ensureAuthSchema(){if(!schemaPromise){schemaPromise=pool.query(`
CREATE TABLE IF NOT EXISTS ludo_users(id TEXT PRIMARY KEY,username TEXT NOT NULL,email TEXT UNIQUE,password_hash TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),coins INTEGER NOT NULL DEFAULT 1000,gems INTEGER NOT NULL DEFAULT 10,xp INTEGER NOT NULL DEFAULT 0,level INTEGER NOT NULL DEFAULT 0,is_guest BOOLEAN NOT NULL DEFAULT FALSE,is_banned BOOLEAN NOT NULL DEFAULT FALSE,banned_at TIMESTAMPTZ,ban_reason TEXT,last_seen_at TIMESTAMPTZ);
ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT FALSE;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS banned_at TIMESTAMPTZ;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS ban_reason TEXT;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS owned_boards JSONB NOT NULL DEFAULT '["classic"]'::jsonb;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS owned_dice JSONB NOT NULL DEFAULT '["classic"]'::jsonb;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS equipped_board TEXT NOT NULL DEFAULT 'classic';ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS equipped_dice TEXT NOT NULL DEFAULT 'classic';ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS owned_avatars JSONB NOT NULL DEFAULT '[]'::jsonb;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS equipped_avatar TEXT NOT NULL DEFAULT 'default';ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS owned_items JSONB NOT NULL DEFAULT '[]'::jsonb;ALTER TABLE ludo_users ADD COLUMN IF NOT EXISTS equipped_items JSONB NOT NULL DEFAULT '[]'::jsonb;
CREATE TABLE IF NOT EXISTS ludo_banned_emails(email TEXT PRIMARY KEY,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),admin_user_id TEXT);CREATE TABLE IF NOT EXISTS ludo_sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ NOT NULL);CREATE INDEX IF NOT EXISTS ludo_sessions_user_idx ON ludo_sessions(user_id);CREATE INDEX IF NOT EXISTS ludo_sessions_expiry_idx ON ludo_sessions(expires_at);
CREATE TABLE IF NOT EXISTS ludo_admin_ledger(id BIGSERIAL PRIMARY KEY,user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,admin_user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,currency TEXT NOT NULL CHECK(currency IN ('coins','gems')),amount INTEGER NOT NULL,balance_before INTEGER NOT NULL,balance_after INTEGER NOT NULL,reason TEXT NOT NULL,source TEXT NOT NULL DEFAULT 'admin',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS ludo_admin_ledger_user_idx ON ludo_admin_ledger(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS ludo_daily_visits(user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,visit_date DATE NOT NULL,PRIMARY KEY(user_id,visit_date));CREATE TABLE IF NOT EXISTS ludo_admin_actions(id BIGSERIAL PRIMARY KEY,admin_user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,action TEXT NOT NULL,target_user_id TEXT,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS ludo_admin_actions_created_idx ON ludo_admin_actions(created_at DESC);
CREATE TABLE IF NOT EXISTS ludo_disputes(id BIGSERIAL PRIMARY KEY,user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,title TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',admin_note TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),resolved_at TIMESTAMPTZ);
ALTER TABLE ludo_disputes ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'other';ALTER TABLE ludo_disputes ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'medium';ALTER TABLE ludo_disputes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE TABLE IF NOT EXISTS ludo_dispute_messages(id BIGSERIAL PRIMARY KEY,dispute_id BIGINT NOT NULL REFERENCES ludo_disputes(id) ON DELETE CASCADE,sender_type TEXT NOT NULL CHECK(sender_type IN ('user','admin')),sender_user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS ludo_dispute_messages_case_idx ON ludo_dispute_messages(dispute_id,created_at ASC);
CREATE TABLE IF NOT EXISTS ludo_shop_payments(reference TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,package_id TEXT NOT NULL,gems INTEGER NOT NULL,amount_kobo INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),credited_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS ludo_tournaments(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('draft','open','live','finished','cancelled')),entry_fee_coins INTEGER NOT NULL DEFAULT 0,entry_fee_gems INTEGER NOT NULL DEFAULT 0,prize_pool_coins INTEGER NOT NULL DEFAULT 0,prize_pool_gems INTEGER NOT NULL DEFAULT 0,max_players INTEGER NOT NULL DEFAULT 16 CHECK(max_players>=2),starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,rules JSONB NOT NULL DEFAULT '{}'::jsonb,prizes JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS ludo_tournament_entries(tournament_id TEXT NOT NULL REFERENCES ludo_tournaments(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','eliminated','winner','withdrawn')),seed INTEGER,eliminated_at TIMESTAMPTZ,PRIMARY KEY(tournament_id,user_id));CREATE TABLE IF NOT EXISTS ludo_tournament_matches(id BIGSERIAL PRIMARY KEY,tournament_id TEXT NOT NULL REFERENCES ludo_tournaments(id) ON DELETE CASCADE,round_no INTEGER NOT NULL,match_no INTEGER NOT NULL,room_code TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'waiting' CHECK(status IN ('waiting','ready','playing','finished')),player_ids JSONB NOT NULL DEFAULT '[]'::jsonb,winner_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,started_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,prize_awarded BOOLEAN NOT NULL DEFAULT FALSE,UNIQUE(tournament_id,round_no,match_no));CREATE INDEX IF NOT EXISTS ludo_tournament_matches_lookup ON ludo_tournament_matches(tournament_id,round_no,status);CREATE TABLE IF NOT EXISTS ludo_tournament_prizes(id BIGSERIAL PRIMARY KEY,tournament_id TEXT NOT NULL REFERENCES ludo_tournaments(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,place INTEGER NOT NULL,currency TEXT NOT NULL CHECK(currency IN ('coins','gems')),amount INTEGER NOT NULL,awarded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tournament_id,user_id,place));
`).then(async()=>{const count=await pool.query(`SELECT COUNT(*)::int n FROM ludo_tournaments`);if(Number(count.rows[0]?.n)!==0)return;await pool.query(`INSERT INTO ludo_tournaments(id,name,description,status,entry_fee_coins,entry_fee_gems,prize_pool_coins,prize_pool_gems,max_players,starts_at,ends_at,rules,prizes) VALUES
('grand-championship','Grand Championship','The flagship Ludo Live championship. Four-player knockout matches.','open',1000,0,100000,2000,512,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '3 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":50000,"gems":1000},{"place":2,"coins":30000,"gems":600},{"place":3,"coins":20000,"gems":400}]'),
('blitz-arena','Blitz Arena','Fast knockout tournament for players who want short matches.','open',500,0,40000,500,128,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '2 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":20000,"gems":250},{"place":2,"coins":12000,"gems":150},{"place":3,"coins":8000,"gems":100}]'),
('gem-masters','Gem Masters','Premium gem-entry championship with a diamond-heavy prize pool.','open',0,50,0,1500,64,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '4 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"gems":750},{"place":2,"gems":450},{"place":3,"gems":300}]'),
('midnight-cup','Midnight Cup','A night-themed knockout for the Midnight Live crowd.','open',250,0,20000,300,64,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '3 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":10000,"gems":150},{"place":2,"coins":6000,"gems":90},{"place":3,"coins":4000,"gems":60}]'),
('royal-rumble','Royal Rumble','High-stakes royal knockout.','open',2000,0,120000,1000,64,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '5 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":60000,"gems":500},{"place":2,"coins":36000,"gems":300},{"place":3,"coins":24000,"gems":200}]'),
('jungle-quest','Jungle Quest','Wild four-player brackets with a green theme.','open',300,0,25000,250,32,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '3 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":12500,"gems":125},{"place":2,"coins":7500,"gems":75},{"place":3,"coins":5000,"gems":50}]'),
('fire-ice','Fire & Ice Clash','Elemental tournament: hot entry, cool rewards.','open',750,0,50000,500,128,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '4 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":25000,"gems":250},{"place":2,"coins":15000,"gems":150},{"place":3,"coins":10000,"gems":100}]'),
('rookie-road','Rookie Road','Low-cost tournament built for new competitors.','open',100,0,10000,100,32,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '2 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":5000,"gems":50},{"place":2,"coins":3000,"gems":30},{"place":3,"coins":2000,"gems":20}]'),
('weekend-legends','Weekend Legends','The weekend leaderboard tournament.','open',1000,0,80000,1000,256,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '6 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":40000,"gems":500},{"place":2,"coins":24000,"gems":300},{"place":3,"coins":16000,"gems":200}]'),
('ludo-live-finals','Ludo Live Finals','Elite final bracket for serious competitors.','open',5000,100,200000,5000,128,NOW()-INTERVAL '5 minutes',NOW()+INTERVAL '7 days','{"playersPerMatch":4,"topPlaces":3,"format":"single-elimination"}','[{"place":1,"coins":100000,"gems":2500},{"place":2,"coins":60000,"gems":1500},{"place":3,"coins":40000,"gems":1000}]`)}).catch(e=>{console.error("auth schema",e);throw e})}return schemaPromise}
