import {NextRequest,NextResponse} from "next/server";
import {pool,ensureAuthSchema} from "../auth/_db";
import {currentUser} from "../../../lib/auth-session";

async function user(q:NextRequest){const u=await currentUser(q);if(!u||u.is_banned)return null;return u}

export async function GET(q:NextRequest){try{await ensureAuthSchema();const u=await user(q);if(!u)return NextResponse.json({error:"Please log in to use support."},{status:401});const id=q.nextUrl.searchParams.get("id");if(id){const r=await pool.query(`SELECT d.id,d.title,d.description,d.status,d.admin_note,d.created_at,d.updated_at FROM ludo_disputes d WHERE d.id=$1 AND d.user_id=$2`,[Number(id),u.id]);if(!r.rowCount)return NextResponse.json({error:"Support case not found."},{status:404});const m=await pool.query(`SELECT id,sender_type,message,created_at FROM ludo_dispute_messages WHERE dispute_id=$1 ORDER BY created_at ASC`,[Number(id)]);return NextResponse.json({case:r.rows[0],messages:m.rows})}const r=await pool.query(`SELECT d.id,d.title,d.description,d.status,d.admin_note,d.created_at,d.updated_at,(SELECT COUNT(*)::int FROM ludo_dispute_messages m WHERE m.dispute_id=d.id) message_count FROM ludo_disputes d WHERE d.user_id=$1 ORDER BY d.updated_at DESC,d.created_at DESC`,[u.id]);return NextResponse.json({cases:r.rows})}catch(e){console.error(e);return NextResponse.json({error:"Support service unavailable."},{status:500})}}

export async function POST(q:NextRequest){try{await ensureAuthSchema();const u=await user(q);if(!u)return NextResponse.json({error:"Please log in to use support."},{status:401});const b=await q.json(),action=String(b.action||"");if(action==="create"){const title=String(b.title||"").trim().slice(0,120),description=String(b.message||"").trim().slice(0,5000),category=String(b.category||"other").trim().slice(0,40);if(!title||!description)return NextResponse.json({error:"Subject and message are required."},{status:400});const c=await pool.connect();try{await c.query("BEGIN");const d=await c.query(`INSERT INTO ludo_disputes(user_id,title,description,status,category,priority,updated_at) VALUES($1,$2,$3,'open',$4,'medium',NOW()) RETURNING id`,[u.id,title,description,category]);const id=d.rows[0].id;await c.query(`INSERT INTO ludo_dispute_messages(dispute_id,sender_type,sender_user_id,message) VALUES($1,'user',$2,$3)`,[id,u.id,description]);await c.query("COMMIT");return NextResponse.json({ok:true,id})}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
if(action==="reply"){const id=Number(b.id),message=String(b.message||"").trim().slice(0,5000);if(!id||!message)return NextResponse.json({error:"Case and message are required."},{status:400});const d=await pool.query(`SELECT id,status FROM ludo_disputes WHERE id=$1 AND user_id=$2`,[id,u.id]);if(!d.rowCount)return NextResponse.json({error:"Support case not found."},{status:404});if(d.rows[0].status==="resolved")return NextResponse.json({error:"This case is resolved. Reopen it before replying."},{status:400});await pool.query(`INSERT INTO ludo_dispute_messages(dispute_id,sender_type,sender_user_id,message) VALUES($1,'user',$2,$3)`,[id,u.id,message]);await pool.query(`UPDATE ludo_disputes SET status='open',updated_at=NOW() WHERE id=$1`,[id]);return NextResponse.json({ok:true})}
if(action==="reopen"){const id=Number(b.id);const r=await pool.query(`UPDATE ludo_disputes SET status='open',resolved_at=NULL,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING id`,[id,u.id]);if(!r.rowCount)return NextResponse.json({error:"Support case not found."},{status:404});return NextResponse.json({ok:true})}
return NextResponse.json({error:"Unknown support action."},{status:400})}catch(e){console.error(e);return NextResponse.json({error:"Support action failed."},{status:500})}}
