"use client";

import { useMemo, useState } from "react";
import type { CSSProperties } from "react";

const COLORS = { green: "#16a34a", yellow: "#f4b400", red: "#ef233c", blue: "#2563eb" } as const;
type Color = keyof typeof COLORS;
const ORDER: Color[] = ["green", "yellow", "red", "blue"];
const BOARD_ROUTE: [number, number][] = [[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0],[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7]];
const START_INDEX: Record<Color, number> = { green: 14, yellow: 27, blue: 40, red: 1 };
const safe = new Set([12,8,21,25,34,38,47,51]);
const COLORED_EXITS: Record<string, Color> = { "6-1":"green", "1-8":"yellow", "8-13":"blue", "13-6":"red" };
const LANES: Record<Color,[number,number][]> = { red:[[13,7],[12,7],[11,7],[10,7],[9,7]], green:[[7,1],[7,2],[7,3],[7,4],[7,5]], yellow:[[1,7],[2,7],[3,7],[4,7],[5,7]], blue:[[7,9],[7,10],[7,11],[7,12],[7,13]] };
const FINAL_HOME = 57;
function routeIndexFor(color: Color, progress: number){ return (START_INDEX[color]+progress)%BOARD_ROUTE.length; }
function Home({color,className,tokens,onTokenClick}:{color:Color;className:string;tokens:number[];onTokenClick:(i:number)=>void}){return <div className={`home ${className}`} style={{background:COLORS[color]}}><div className="home-yard">{tokens.map((progress,i)=><button key={i} className="home-slot" onClick={()=>onTokenClick(i)} aria-label={`${color} token ${i+1}`}>{progress<0?<span className="token token-home" style={{background:COLORS[color]}}/>:<span className="token token-home token-hidden"/>}</button>)}</div></div>}
function Center(){return <div className="center"><div className="center-triangle center-green"/><div className="center-triangle center-yellow"/><div className="center-triangle center-red"/><div className="center-triangle center-blue"/></div>}
export default function HomePage(){
 const [turn,setTurn]=useState<Color>("green"); const [dice,setDice]=useState<number|null>(null); const [tokens,setTokens]=useState<Record<Color,number[]>>({green:[-1,-1,-1,-1],yellow:[-1,-1,-1,-1],red:[-1,-1,-1,-1],blue:[-1,-1,-1,-1]}); const [message,setMessage]=useState("Test mode: press Force 6, then tap a home token."); const [animating,setAnimating]=useState(false);
 const tokenVisuals=useMemo(()=>{const result:{color:Color;token:number;progress:number;kind:"route"|"lane"|"final";row?:number;col?:number}[]=[]; ORDER.forEach(color=>tokens[color].forEach((progress,token)=>{if(progress<0)return;if(progress<BOARD_ROUTE.length){const [row,col]=BOARD_ROUTE[routeIndexFor(color,progress)];result.push({color,token,progress,kind:"route",row,col});}else if(progress<FINAL_HOME){const lane=LANES[color][progress-BOARD_ROUTE.length];if(lane)result.push({color,token,progress,kind:"lane",row:lane[0],col:lane[1]});}else result.push({color,token,progress,kind:"final"});}));return result},[tokens]);
 function roll(value?:number){if(animating)return;const next=value??Math.floor(Math.random()*6)+1;setDice(next);setMessage(`${turn.toUpperCase()} rolled ${next}. ${next===6?"Choose a home token to enter.":"Choose a token to move."}`)}
 function finishTurn(){setDice(null);setTurn(ORDER[(ORDER.indexOf(turn)+1)%ORDER.length])}
 function animateMove(color:Color,tokenIndex:number,start:number,end:number){setAnimating(true);let progress=start;const step=()=>{progress++;setTokens(prev=>({...prev,[color]:prev[color].map((p,i)=>i===tokenIndex?progress:p)}));if(progress<end)setTimeout(step,220);else{setAnimating(false);setMessage(end===FINAL_HOME?`${color.toUpperCase()} token ${tokenIndex+1} reached FINAL HOME!`:`${color.toUpperCase()} token ${tokenIndex+1} finished moving ${end-start} spaces.`);finishTurn()}};setTimeout(step,220)}
 function moveToken(color:Color,tokenIndex:number){if(animating)return;if(color!==turn){setMessage(`It is ${turn.toUpperCase()}'s turn.`);return}if(dice===null){setMessage("Roll the dice first.");return}const current=tokens[color][tokenIndex];if(current<0){if(dice!==6){setMessage("A token needs a 6 to enter.");return}setTokens(prev=>({...prev,[color]:prev[color].map((p,i)=>i===tokenIndex?0:p)}));setMessage(`${color.toUpperCase()} token ${tokenIndex+1} entered on its colored first-exit square.`);finishTurn();return}const next=current+dice;if(next>FINAL_HOME){setMessage(`Need an exact roll to reach final home (currently ${FINAL_HOME-current} spaces away).`);return}setMessage(`${color.toUpperCase()} token ${tokenIndex+1}: counting ${dice} spaces...`);animateMove(color,tokenIndex,current,next)}
 function reset(){if(animating)return;setTokens({green:[-1,-1,-1,-1],yellow:[-1,-1,-1,-1],red:[-1,-1,-1,-1],blue:[-1,-1,-1,-1]});setTurn("green");setDice(null);setMessage("Reset. Green starts.")}
 return <main className="board-page"><section className="game-shell"><div className="game-controls"><div><strong>{turn.toUpperCase()}</strong> turn <span className="test-badge">TEST MODE</span></div><div className="dice-value">{dice??"—"}</div><button onClick={()=>roll()} className="control-button" disabled={animating}>Roll Dice</button><button onClick={()=>roll(6)} className="control-button" disabled={animating}>Force 6</button><button onClick={reset} className="control-button secondary" disabled={animating}>Reset</button></div><p className="status">{message}</p><div className="ludo-board" aria-label="Ludo board"><div className="grid">{Array.from({length:225},(_,index)=>{const row=Math.floor(index/15),col=index%15,key=`${row}-${col}`;const routeIndex=BOARD_ROUTE.findIndex(([r,c])=>r===row&&c===col);const exitColor=COLORED_EXITS[key];const laneColor=(Object.keys(LANES) as Color[]).find(color=>LANES[color].some(([r,c])=>r===row&&c===col));if(routeIndex>=0)return <div key={key} className={`cell path ${safe.has(routeIndex)?"safe":""} ${exitColor?`exit-${exitColor}`:""}`}>{safe.has(routeIndex)&&<span className="safe-star">★</span>}</div>;if(laneColor)return <div key={key} className={`cell home-lane lane-${laneColor}`}/>;return <div key={key} className="cell empty"/>})}</div>{tokenVisuals.map(t=>{if(t.kind==="final")return <div key={`${t.color}-${t.token}`} className="final-token" style={{background:COLORS[t.color]}} aria-label={`${t.color} token ${t.token+1} in final home`}/>;return <button key={`${t.color}-${t.token}`} className={`route-token ${t.kind==="lane"?"lane-token":""}`} style={{"--row":t.row,"--col":t.col,background:COLORS[t.color]} as CSSProperties} onClick={()=>moveToken(t.color,t.token)} aria-label={`Move ${t.color} token ${t.token+1}`}/>})}<Home color="green" className="home-green" tokens={tokens.green} onTokenClick={i=>moveToken("green",i)}/><Home color="yellow" className="home-yellow" tokens={tokens.yellow} onTokenClick={i=>moveToken("yellow",i)}/><Home color="red" className="home-red" tokens={tokens.red} onTokenClick={i=>moveToken("red",i)}/><Home color="blue" className="home-blue" tokens={tokens.blue} onTokenClick={i=>moveToken("blue",i)}/><Center/></div></section></main>
}
