"use client";

import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";

const COLORS = { green: "#16a34a", yellow: "#f4b400", red: "#ef233c", blue: "#2563eb" } as const;
type Color = keyof typeof COLORS;
type Mode = "bot" | "two" | "four";
const ORDER: Color[] = ["green", "yellow", "red", "blue"];
const BOARD_ROUTE: [number, number][] = [[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0],[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7]];
const START_INDEX: Record<Color, number> = { green: 14, yellow: 27, blue: 40, red: 1 };
const SAFE_SQUARES = new Set([12,8,21,25,34,38,47,51]);
const COLORED_EXITS: Record<string, Color> = { "6-1":"green", "1-8":"yellow", "8-13":"blue", "13-6":"red" };
const LANES: Record<Color,[number,number][]> = { red:[[13,7],[12,7],[11,7],[10,7],[9,7]], green:[[7,1],[7,2],[7,3],[7,4],[7,5]], yellow:[[1,7],[2,7],[3,7],[4,7],[5,7]], blue:[[7,9],[7,10],[7,11],[7,12],[7,13]] };
const LANE_START_PROGRESS = BOARD_ROUTE.length - 1;
const FINAL_HOME = LANE_START_PROGRESS + 5;
const HOME = -1;
function routeIndexFor(color: Color, progress: number){return (START_INDEX[color]+progress)%BOARD_ROUTE.length}
function isSafe(color: Color, progress: number){return progress<0||progress>=LANE_START_PROGRESS||SAFE_SQUARES.has(routeIndexFor(color,progress))}
function sameSquare(a:Color,ap:number,b:Color,bp:number){return ap>=0&&bp>=0&&ap<LANE_START_PROGRESS&&bp<LANE_START_PROGRESS&&routeIndexFor(a,ap)===routeIndexFor(b,bp)}
function sameTeam(a:Color,b:Color,mode:Mode){if(mode==="four")return a===b;if(mode==="bot"||mode==="two")return (["green","blue"] as Color[]).includes(a)===( ["green","blue"] as Color[]).includes(b);return false}
function Home({color,className,tokens,onTokenClick}:{color:Color;className:string;tokens:number[];onTokenClick:(i:number)=>void}){return <div className={`home ${className}`} style={{background:COLORS[color]}}><div className="home-yard">{tokens.map((p,i)=><button key={i} className="home-slot" onClick={()=>onTokenClick(i)}>{p===HOME?<span className="token token-home" style={{background:COLORS[color]}}/>:<span className="token token-home token-hidden"/>}</button>)}</div></div>}
function Center({tokens}:{tokens:Record<Color,number[]>}){const finished=(c:Color)=>tokens[c].filter(p=>p===FINAL_HOME);return <div className="center"><div className="center-triangle center-green"/><div className="center-triangle center-yellow"/><div className="center-triangle center-red"/><div className="center-triangle center-blue"/><div className="finished-layer"><div className="finished-zone finished-zone-green">{finished("green").map((_,i)=><span key={i} className="finished-token" style={{background:COLORS.green}}/>)}</div><div className="finished-zone finished-zone-yellow">{finished("yellow").map((_,i)=><span key={i} className="finished-token" style={{background:COLORS.yellow}}/>)}</div><div className="finished-zone finished-zone-red">{finished("red").map((_,i)=><span key={i} className="finished-token" style={{background:COLORS.red}}/>)}</div><div className="finished-zone finished-zone-blue">{finished("blue").map((_,i)=><span key={i} className="finished-token" style={{background:COLORS.blue}}/>)}</div></div></div>}
export default function HomePage(){
 const [mode,setMode]=useState<Mode>("bot");const [teamTurn,setTeamTurn]=useState<"human"|"bot"|Color>("human");const [dice,setDice]=useState<number|null>(null);const [sixStreak,setSixStreak]=useState(0);const [winner,setWinner]=useState<Color[]|null>(null);const [tokens,setTokens]=useState<Record<Color,number[]>>({green:[HOME,HOME,HOME,HOME],yellow:[HOME,HOME,HOME,HOME],red:[HOME,HOME,HOME,HOME],blue:[HOME,HOME,HOME,HOME]});const [message,setMessage]=useState("You are Red + Yellow. Roll once, then choose either color.");const [animating,setAnimating]=useState(false);
 const tokenVisuals=useMemo(()=>{const r:any[]=[];ORDER.forEach(c=>tokens[c].forEach((p,i)=>{if(p===HOME||p===FINAL_HOME)return;if(p<LANE_START_PROGRESS){const [row,col]=BOARD_ROUTE[routeIndexFor(c,p)];r.push({color:c,token:i,kind:"route",row,col})}else if(p<FINAL_HOME){const lane=LANES[c][p-LANE_START_PROGRESS];if(lane)r.push({color:c,token:i,kind:"lane",row:lane[0],col:lane[1]})}}));return r},[tokens]);
 const remaining=useMemo(()=>Object.fromEntries(ORDER.map(c=>[c,tokens[c].filter(p=>p!==FINAL_HOME).length])) as Record<Color,number>,[tokens]);
 const humanColors:Color[]=mode==="bot"?["red","yellow"]:mode==="two"?["green","blue"]:ORDER;const botColors:Color[]=mode==="bot"?["green","blue"]:[];const isHuman=(c:Color)=>humanColors.includes(c);const teamName=mode==="bot"?(teamTurn==="human"?"YOUR TEAM":"BOT TEAM"):mode==="two"?(teamTurn==="human"?"PLAYER 1":"PLAYER 2"):teamTurn.toUpperCase()+" PLAYER";
 function currentColors():Color[]{return mode==="four"?[teamTurn as Color]:(teamTurn==="human"?humanColors:botColors)}
 function nextTeam(){setDice(null);setSixStreak(0);setTeamTurn(t=>mode==="four"?ORDER[(ORDER.indexOf(t as Color)+1)%4]:t==="human"?"bot":"human")}
 function forfeitTurn(){setDice(null);setSixStreak(0);setMessage(`${teamName} rolled four 6s. Turn forfeited.`);setTeamTurn(t=>mode==="four"?ORDER[(ORDER.indexOf(t as Color)+1)%4]:t==="human"?"bot":"human")}
 function countAtRouteIndex(target:number,excludeColor?:Color){return ORDER.reduce((n,c)=>n+(c===excludeColor?0:tokens[c].filter(p=>p>=0&&p<LANE_START_PROGRESS&&routeIndexFor(c,p)===target).length),0)}
 function legalMoves(c:Color,r:number){return tokens[c].map((p,i)=>({p,i})).filter(x=>{if(x.p===HOME){if(r!==6)return false;const target=START_INDEX[c];const opponents=ORDER.filter(o=>o!==c&&!sameTeam(c,o,mode));const blocked=opponents.some(o=>tokens[o].filter(q=>q>=0&&q<LANE_START_PROGRESS&&routeIndexFor(o,q)===target).length>=2);return !blocked}if(x.p<0||x.p>=FINAL_HOME||x.p+r>FINAL_HOME)return false;for(let step=x.p+1;step<=Math.min(x.p+r,LANE_START_PROGRESS-1);step++){const idx=routeIndexFor(c,step);const blocked=ORDER.some(o=>!sameTeam(c,o,mode)&&tokens[o].filter(q=>q>=0&&q<LANE_START_PROGRESS&&routeIndexFor(o,q)===idx).length>=2);if(blocked)return false}return true}).map(x=>x.i)}
 function animateMove(c:Color,i:number,start:number,end:number,after:(landed:number)=>void){setAnimating(true);let p=start;const step=()=>{p++;setTokens(prev=>({...prev,[c]:prev[c].map((x,j)=>j===i?p:x)}));if(p<end)setTimeout(step,180);else{setAnimating(false);after(p)}};setTimeout(step,180)}
 function resolveMove(c:Color,i:number,r:number){const cur=tokens[c][i];if(cur===HOME){setTokens(prev=>({...prev,[c]:prev[c].map((x,j)=>j===i?0:x)}));setDice(null);setMessage(`${teamName} moved ${c.toUpperCase()} token onto its start.`);if(r===6){setMessage(`${teamName} rolled 6. Same team rolls again.`);return}nextTeam();return}animateMove(c,i,cur,cur+r,landed=>{let captured=0;setTokens(prev=>{const next={...prev,[c]:[...prev[c]]};for(const o of ORDER)if(o!==c&&!sameTeam(c,o,mode))next[o]=next[o].map(p=>{if(sameSquare(c,landed,o,p)&&!isSafe(c,landed)){captured++;return HOME}return p});next[c][i]=landed;return next});const team:Color[]=mode==="bot"?["red","yellow"]:mode==="two"?["green","blue"]:mode==="four"?[c]:[c];const won=team.every(x=>tokens[x].every(p=>p===FINAL_HOME));if(won){setWinner(team);setDice(null);setMessage(`🏆 ${team.map(x=>x.toUpperCase()).join(" + ")} wins!`);return}if(r===6||captured>0){setDice(null);setMessage(captured?`${teamName} captured a token. Same team rolls again.`:`${teamName} rolled 6. Same team rolls again.`);return}nextTeam()})}
 function chooseToken(c:Color,i:number){if(animating||winner)return;if(mode==="four"?c!==teamTurn:teamTurn!=="human"||!isHuman(c)){setMessage("It is not your turn or that color is not yours.");return}if(dice===null){setMessage("Roll the dice first.");return}if(!legalMoves(c,dice).includes(i)){setMessage("That token cannot move with this roll.");return}resolveMove(c,i,dice)}
 function passIfNoMoves(n:number){const colors=currentColors();if(colors.every(c=>legalMoves(c,n).length===0)){setMessage(`${teamName} has no legal move. Turn passed.`);setDice(null);setSixStreak(0);setTimeout(nextTeam,0);return true}return false}
 function roll(v?:number){if(animating||winner||dice!==null)return;if(mode!=="four"&&teamTurn!=="human")return;const n=v??Math.floor(Math.random()*6)+1;const streak=n===6?sixStreak+1:0;if(streak>=4){forfeitTurn();return}if(passIfNoMoves(n))return;setDice(n);setSixStreak(streak);setMessage(`${teamName} rolled ${n}. Choose any legal token from your team.`)}
 function botRoll(){if(mode!=="bot"||teamTurn!=="bot"||winner||dice!==null||animating)return;const n=Math.floor(Math.random()*6)+1;const streak=n===6?sixStreak+1:0;if(streak>=4){setMessage("BOT TEAM rolled four 6s. Turn forfeited. Your turn.");setDice(null);setSixStreak(0);setTeamTurn("human");return}if(passIfNoMoves(n))return;setDice(n);setSixStreak(streak);setMessage(`BOT TEAM rolled ${n}.`)}
 function botMove(){if(mode!=="bot"||teamTurn!=="bot"||dice===null||animating||winner)return;const choices=botColors.flatMap(c=>legalMoves(c,dice).map(i=>({c,i})));if(!choices.length){setMessage("Bot team has no legal move. Turn passed.");nextTeam();return}const chosen=choices.find(x=>tokens[x.c][x.i]===HOME)||choices[0];resolveMove(chosen.c,chosen.i,dice)}
 useEffect(()=>{if(mode!=="bot"||teamTurn!=="bot"||winner||animating)return;const timer=setTimeout(()=>{if(dice===null)botRoll();else botMove()},650);return()=>clearTimeout(timer)},[mode,teamTurn,dice,winner,animating,sixStreak,tokens]);
 useEffect(()=>{if(winner||animating||dice===null)return;const humanTurn=mode==="four"?true:teamTurn==="human";if(!humanTurn)return;const colors=currentColors();if(colors.every(c=>legalMoves(c,dice).length===0)){setMessage(`${teamName} has no legal move. Turn passed.`);setDice(null);setSixStreak(0);const timer=setTimeout(nextTeam,0);return()=>clearTimeout(timer)}},[mode,teamTurn,dice,winner,animating,tokens]);
 function reset(){if(animating)return;setTokens({green:[HOME,HOME,HOME,HOME],yellow:[HOME,HOME,HOME,HOME],red:[HOME,HOME,HOME,HOME],blue:[HOME,HOME,HOME,HOME]});setTeamTurn(mode==="bot"?"human":"green");setDice(null);setSixStreak(0);setWinner(null);setMessage(mode==="bot"?"You are Red + Yellow. Roll once, then choose either color.":mode==="two"?"2-player mode: Player 1 Green + Blue, Player 2 Red + Yellow.":"4-player mode: one player per color.")}
 function changeMode(next:Mode){setMode(next);setTeamTurn(next==="bot"?"human":"green");setDice(null);setSixStreak(0);setWinner(null);setTokens({green:[HOME,HOME,HOME,HOME],yellow:[HOME,HOME,HOME,HOME],red:[HOME,HOME,HOME,HOME],blue:[HOME,HOME,HOME,HOME]});setMessage(next==="bot"?"Bot mode: you are Red + Yellow. Roll once, then choose either color.":next==="two"?"2-player mode: Player 1 Green + Blue, Player 2 Red + Yellow.":"4-player mode: one player per color.")}
 const active=(c:Color)=>mode==="bot"?((teamTurn==="human"&&isHuman(c))||(teamTurn==="bot"&&!isHuman(c))):mode==="two"?((teamTurn==="human"&&(["green","blue"] as Color[]).includes(c))||(teamTurn==="bot"&&(["red","yellow"] as Color[]).includes(c))):teamTurn===c;
 return <main className="board-page"><section className="game-shell"><div className="game-controls"><div><strong>{winner?`${winner.map(c=>c.toUpperCase()).join(" + ")} WINS`:teamName}</strong>{!winner&&" turn"}</div><div className="dice-value">{dice??"—"}</div><button onClick={()=>roll()} className="control-button" disabled={animating||!!winner||dice!==null||(mode!=="four"&&teamTurn!=="human")}>Roll Dice</button><button onClick={()=>roll(6)} className="control-button" disabled={animating||!!winner||dice!==null||(mode!=="four"&&teamTurn!=="human")}>Force 6</button><button onClick={reset} className="control-button secondary" disabled={animating}>New Game</button></div><div className="mode-controls"><button className="control-button" onClick={()=>changeMode("bot")}>Me vs Bot</button><button className="control-button secondary" onClick={()=>changeMode("two")}>2 Players</button><button className="control-button secondary" onClick={()=>changeMode("four")}>4 Players</button></div><p className="status">{message}</p><div className="player-strip">{ORDER.map(c=><div key={c} className={`player-chip ${active(c)&&!winner?"active":""}`}><span className="player-dot" style={{background:COLORS[c]}}/><strong>{c.toUpperCase()}</strong><small>{remaining[c]} to home</small></div>)}</div><div className="ludo-board"><div className="grid">{Array.from({length:225},(_,idx)=>{const row=Math.floor(idx/15),col=idx%15,key=`${row}-${col}`;const ri=BOARD_ROUTE.findIndex(([r,c])=>r===row&&c===col);const exit=COLORED_EXITS[key];const lane=(Object.keys(LANES) as Color[]).find(c=>LANES[c].some(([r,c2])=>r===row&&c2===col));if(ri>=0)return <div key={key} className={`cell path ${SAFE_SQUARES.has(ri)?"safe":""} ${exit?`exit-${exit}`:""}`}>{exit&&<span className="safe-star">★</span>}</div>;if(lane)return <div key={key} className={`cell home-lane lane-${lane}`}/>;return <div key={key} className="cell empty"/>})}</div>{tokenVisuals.map(t=><button key={`${t.color}-${t.token}`} className={`route-token ${t.kind==="lane"?"lane-token":""}`} style={{"--row":t.row,"--col":t.col,background:COLORS[t.color as Color]} as CSSProperties} onClick={()=>chooseToken(t.color,t.token)}/>)}<Home color="green" className="home-green" tokens={tokens.green} onTokenClick={i=>chooseToken("green",i)}/><Home color="yellow" className="home-yellow" tokens={tokens.yellow} onTokenClick={i=>chooseToken("yellow",i)}/><Home color="red" className="home-red" tokens={tokens.red} onTokenClick={i=>chooseToken("red",i)}/><Home color="blue" className="home-blue" tokens={tokens.blue} onTokenClick={i=>chooseToken("blue",i)}/><Center tokens={tokens}/></div></section></main>}
