"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import AppFrame from "../_components/AppFrame";
import {readProgress,readBadges,xpRequiredForLevel,type Badge,STARTING_COINS,STARTING_GEMS} from "../../lib/playerProgress";

const panel={background:"linear-gradient(180deg,rgba(8,30,75,.96),rgba(4,17,43,.96))",border:"1px solid rgba(78,125,211,.28)",borderRadius:18};
const action={color:"#fff",textDecoration:"none",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"17px 18px",borderRadius:14,background:"rgba(17,48,105,.8)"};
type Wallet={coins:number;gems:number;spins:number;mystery:number}; const defaults:Wallet={coins:STARTING_COINS,gems:STARTING_GEMS,spins:0,mystery:0}; const CHANGE_COST=1000,MONTH=30*24*60*60*1000;
function playerId(){let id=localStorage.getItem("ludo-player-id");if(!id){id=crypto.randomUUID();localStorage.setItem("ludo-player-id",id)}return id}
function readWallet():Wallet{try{return {...defaults,...JSON.parse(localStorage.getItem("ludo-wallet")||"{}")}}catch{return defaults}}

export default function ProfilePage(){
 const[name,setName]=useState("PlayerOne");const[draft,setDraft]=useState("PlayerOne");const[editing,setEditing]=useState(false);const[wallet,setWallet]=useState<Wallet>(defaults);const[notice,setNotice]=useState("");const[confirmPaid,setConfirmPaid]=useState(false);const[progress,setProgress]=useState(()=>readProgress());const[badges,setBadges]=useState<Badge[]>(()=>readBadges());const total=256,won=184;
 useEffect(()=>{const n=localStorage.getItem("ludo-player-name")||"PlayerOne";setName(n);setDraft(n);setWallet(readWallet());playerId();const sync=()=>{setWallet(readWallet());setProgress(readProgress());setBadges(readBadges())};sync();window.addEventListener("ludo-wallet-updated",sync);window.addEventListener("ludo-progression-updated",sync);window.addEventListener("ludo-badges-updated",sync);return()=>{window.removeEventListener("ludo-wallet-updated",sync);window.removeEventListener("ludo-progression-updated",sync);window.removeEventListener("ludo-badges-updated",sync)}},[]);
 const required=xpRequiredForLevel(progress.level),percent=Math.min(100,(progress.xp/required)*100);
 const finishNameChange=(next:string,paid:boolean)=>{const now=Date.now();if(paid){const w={...wallet,coins:wallet.coins-CHANGE_COST};setWallet(w);localStorage.setItem("ludo-wallet",JSON.stringify(w));window.dispatchEvent(new Event("ludo-wallet-updated"))}localStorage.setItem("ludo-player-id",playerId());localStorage.setItem("ludo-player-name",next);localStorage.setItem("ludo-last-nickname-change",String(now));setName(next);setDraft(next);setEditing(false);setConfirmPaid(false);setNotice(paid?"Nickname changed for 1,000 coins.":"Nickname changed. Your next free change is available in 30 days.");window.dispatchEvent(new CustomEvent("ludo-profile-updated",{detail:{playerId:localStorage.getItem("ludo-player-id"),name:next}}));};
 const saveName=()=>{const next=draft.trim().slice(0,24);if(!next){setNotice("Nickname cannot be empty.");return}if(next===name){setEditing(false);return}const now=Date.now(),last=Number(localStorage.getItem("ludo-last-nickname-change")||0),paid=now-last<MONTH;if(paid&&wallet.coins<CHANGE_COST){setNotice("You need 1,000 coins to change your nickname now. Please buy more coins from the Store.");return}if(paid){setConfirmPaid(true);return}finishNameChange(next,false)};
 return <AppFrame back="/home"><div style={{maxWidth:760,margin:"0 auto",paddingBottom:40}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:18}}><h1 style={{margin:0,fontSize:34}}>Profile</h1><Link href="/settings" style={{color:"#fff",fontSize:25,textDecoration:"none"}}>⚙️</Link></div>
 <section style={{...panel,padding:22,display:"grid",gridTemplateColumns:"auto 1fr",gap:20,alignItems:"center"}}><div style={{width:108,height:108,borderRadius:"50%",border:"5px solid #facc15",background:"linear-gradient(145deg,#193e87,#071a45)",display:"grid",placeItems:"center",fontSize:48}}>🧑🏽‍🎮</div><div style={{minWidth:0}}>{editing?<div style={{display:"flex",gap:8}}><input value={draft} onChange={e=>setDraft(e.target.value)} maxLength={24} style={{flex:1,padding:12,borderRadius:10,background:"#071936",color:"#fff",border:"1px solid #315b9f"}}/><button onClick={saveName} style={smallBtn}>Save</button></div>:<div style={{display:"flex",gap:10,alignItems:"center"}}><strong style={{fontSize:28,overflowWrap:"anywhere"}}>{name}</strong><button onClick={()=>{setDraft(name);setEditing(true);setNotice("")}} style={iconBtn}>✎</button></div>}<div style={{marginTop:7,fontWeight:900}}>Level {progress.level}</div><div style={{color:"#f5d75d",fontWeight:900,fontSize:13,marginTop:5}}>{progress.xp.toLocaleString()} / {required.toLocaleString()} XP</div><div style={{height:13,borderRadius:20,background:"#07152f",overflow:"hidden",marginTop:7}}><div style={{width:`${percent}%`,height:"100%",background:"linear-gradient(90deg,#f59e0b,#facc15)"}}/></div><div style={{fontSize:11,color:"#94a3b8",marginTop:4}}>Earn XP to reach Level {progress.level+1} • {required-progress.xp} XP remaining</div>
 {badges.length>0&&<div style={{marginTop:12}}><div style={{fontSize:11,color:"#bfdbfe",fontWeight:900,marginBottom:6}}>BADGES</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{badges.map(b=><span key={b.id} title={`${b.label} • ${b.source}`} style={{width:34,height:34,borderRadius:10,display:"grid",placeItems:"center",background:"#071b43",border:"1px solid rgba(96,165,250,.28)",fontSize:19}}>{b.icon}</span>)}</div></div>}</div></section>
 {notice&&<div style={{marginTop:12,padding:12,borderRadius:12,background:"rgba(120,70,10,.5)",color:"#fde68a"}}>{notice} {wallet.coins<CHANGE_COST&&<Link href="/shop" style={{color:"#fff",fontWeight:800,marginLeft:8}}>BUY COINS</Link>}</div>}
 <section style={{...panel,marginTop:14,display:"grid",gridTemplateColumns:"repeat(3,1fr)"}}>{[['Total Games',total],['Games Won',won],['Win Rate',`${Math.round(won/total*100)}%`]].map(([l,v])=><div key={String(l)} style={{padding:20,textAlign:"center"}}><div style={{color:"#cbd5e1"}}>{l}</div><strong style={{display:"block",marginTop:9,fontSize:28}}>{v}</strong></div>)}</section>
 <section style={{...panel,marginTop:14,display:"grid",gridTemplateColumns:"1fr 1fr"}}><div style={{padding:20}}>🪙<div>Coins</div><strong style={{fontSize:26}}>{wallet.coins.toLocaleString()}</strong></div><div style={{padding:20}}>💎<div>Gems</div><strong style={{fontSize:26}}>{wallet.gems.toLocaleString()}</strong></div><div style={{padding:20,borderTop:"1px solid rgba(78,125,211,.18)"}}>🎟️<div>Free Rolls</div><strong style={{fontSize:26}}>{wallet.spins}</strong></div><div style={{padding:20,borderTop:"1px solid rgba(78,125,211,.18)"}}>🎁<div>Mystery Items</div><strong style={{fontSize:26}}>{wallet.mystery}</strong></div></section>
 <div style={{display:"grid",gap:10,marginTop:16}}><Link href="/achievements" style={action}>🏆 <b>Achievements</b><span>›</span></Link><Link href="/history" style={action}>📜 <b>History</b><span>›</span></Link><Link href="/shop" style={action}>🛍️ <b>Shop</b><span>›</span></Link></div>
 {confirmPaid&&<div style={{position:"fixed",inset:0,zIndex:1000,display:"grid",placeItems:"center",padding:20,background:"rgba(0,0,0,.7)"}}><div style={{...panel,maxWidth:420,width:"100%",padding:24}}><h2 style={{marginTop:0}}>Confirm nickname change</h2><p>You have already used your free nickname change this month.</p><p>Changing your nickname now will cost <b>1,000 coins</b>.</p><p>Your balance: <b>{wallet.coins.toLocaleString()} coins</b></p><div style={{display:"flex",gap:10,justifyContent:"flex-end",marginTop:20}}><button onClick={()=>setConfirmPaid(false)} style={{...smallBtn,background:"#334155"}}>CANCEL</button><button onClick={()=>finishNameChange(draft.trim().slice(0,24),true)} style={smallBtn}>CONFIRM • 1,000 COINS</button></div></div></div>}</div></AppFrame>}
const smallBtn={border:0,borderRadius:10,padding:"10px 14px",background:"#2563eb",color:"#fff",fontWeight:800};const iconBtn={border:0,background:"transparent",color:"#fff",fontSize:22};
