"use client";
import React from "react";
import LudoBoard,{BOARD_NAMES,BOARD_PALETTES,type BoardThemeId,type DemoToken} from "./LudoBoard";
import {getTokenCell} from "../../lib/canonicalLudoBoard";
export type {BoardThemeId,DemoToken};
type Props={theme?:BoardThemeId;demoTokens?:DemoToken[];onTokenClick?:(color:DemoToken["color"],id:number)=>void;legalTokenKeys?:string[]};
const YARD_CENTERS:Record<DemoToken["color"],Array<[string,string]>>={green:[["calc(13.61% + 2.85px)","calc(13.61% + 2.85px)"],["calc(26.39% - 2.85px)","calc(13.61% + 2.85px)"],["calc(13.61% + 2.85px)","calc(26.39% - 2.85px)"],["calc(26.39% - 2.85px)","calc(26.39% - 2.85px)"]],yellow:[["calc(73.61% + 2.85px)","calc(13.61% + 2.85px)"],["calc(86.39% - 2.85px)","calc(13.61% + 2.85px)"],["calc(73.61% + 2.85px)","calc(26.39% - 2.85px)"],["calc(86.39% - 2.85px)","calc(26.39% - 2.85px)"]],red:[["calc(13.61% + 2.85px)","calc(73.61% + 2.85px)"],["calc(26.39% - 2.85px)","calc(73.61% + 2.85px)"],["calc(13.61% + 2.85px)","calc(86.39% - 2.85px)"],["calc(26.39% - 2.85px)","calc(86.39% - 2.85px)"]],blue:[["calc(73.61% + 2.85px)","calc(73.61% + 2.85px)"],["calc(86.39% - 2.85px)","calc(73.61% + 2.85px)"],["calc(73.61% - 2.85px)","calc(86.39% - 2.85px)"],["calc(86.39% - 2.85px)","calc(86.39% - 2.85px)"]]};
export default function CanonicalLudoBoard({theme="classic",demoTokens=[],onTokenClick,legalTokenKeys=[]}:Props){
 const p=BOARD_PALETTES[theme]||BOARD_PALETTES.classic;
 const moving=demoTokens.filter(t=>t.state!=="yard"&&t.state!=="finished").map(t=>{const cell=getTokenCell(t.color,t.position);return cell?{...t,row:cell[0],col:cell[1]}:null}).filter(Boolean) as Array<DemoToken&{row:number;col:number}>;
 const finished=demoTokens.filter(t=>t.state==="finished");
 const legalSet=new Set(legalTokenKeys); const yardTokens=demoTokens.filter(t=>t.state==="yard");
 const yardTokenStyle=(color:DemoToken["color"],id:number,left:string,top:string,legal:boolean):React.CSSProperties=>({position:"absolute",left,top,transform:"translate(-50%,-50%)",width:"10.9%",aspectRatio:1,borderRadius:"50%",border:`3px solid ${p.accent}`,background:p[color],boxShadow:legal?`inset 0 2px 3px rgba(255,255,255,.55),0 0 0 2px ${p.accent},0 0 18px ${p.accent}`:"inset 0 2px 3px rgba(255,255,255,.55),0 2px 5px rgba(0,0,0,.25)",animation:legal?"legalYardTokenBreath 1.45s ease-in-out infinite":undefined,zIndex:30,padding:0,cursor:"pointer",fontSize:0,color:"transparent"});
 const markerStyle=(row:number,col:number):React.CSSProperties=>({position:"absolute",left:`${(col+.5)*100/15}%`,top:`${(row+.5)*100/15}%`,transform:"translate(-50%,-50%)",width:"6.8%",aspectRatio:1,borderRadius:"50%",border:`2px solid ${p.accent}`,background:"transparent",boxShadow:`0 0 0 2px ${p.accent},0 0 14px ${p.accent}`,animation:"legalMoveBreath 1.45s ease-in-out infinite",zIndex:24,padding:0,pointerEvents:"none"});
 const stackGroups=new Map<string,Array<DemoToken&{row:number;col:number}>>();
 moving.forEach(t=>{const key=`${t.row}-${t.col}`;const group=stackGroups.get(key)||[];group.push(t);stackGroups.set(key,group)});
 return <div className="canonical-ludo-frame" style={{position:"relative",width:"100%",aspectRatio:"1",touchAction:"none",overscrollBehavior:"contain",userSelect:"none",WebkitUserSelect:"none"} as React.CSSProperties} aria-label={`${BOARD_NAMES[theme]} canonical Ludo board`}>
  <style>{`.canonical-ludo-frame{isolation:isolate}.canonical-ludo-frame .shared-ludo-board{box-shadow:none!important;border:0!important;outline:none!important;filter:none!important;position:relative;z-index:1}@keyframes legalMoveBreath{0%,100%{opacity:.45;transform:translate(-50%,-50%) scale(.9)}50%{opacity:1;transform:translate(-50%,-50%) scale(1.08)}}@keyframes legalYardTokenBreath{0%,100%{transform:translate(-50%,-50%) scale(.94);filter:saturate(1)}50%{transform:translate(-50%,-50%) scale(1.08);filter:saturate(1.12)}}`}</style>
  <LudoBoard theme={theme} demoTokens={[]} onTokenClick={onTokenClick} style={{width:"100%",height:"100%"}}/>
  {yardTokens.map(t=>{const [left,top]=YARD_CENTERS[t.color][t.id]||YARD_CENTERS[t.color][0];const legal=legalSet.has(`${t.color}-${t.id}`);return <button key={`yard-${t.color}-${t.id}`} type="button" onClick={()=>onTokenClick?.(t.color,t.id)} aria-label={`${legal?"Legal move for ":""}${t.color} token`} style={yardTokenStyle(t.color,t.id,left,top,legal)} />;})}
  {[...stackGroups.entries()].map(([key,group])=>{const legalGroup=group.filter(t=>legalSet.has(`${t.color}-${t.id}`));return <React.Fragment key={`stack-${key}`}>{legalGroup.length>0&&<span aria-hidden="true" style={markerStyle(group[0].row,group[0].col)} />}{group.map((t,index)=>{const spread=group.length>1?(index-(group.length-1)/2)*2.7:0;const legal=legalSet.has(`${t.color}-${t.id}`);return <button key={`${t.color}-${t.id}`} type="button" onClick={()=>onTokenClick?.(t.color,t.id)} aria-label={`${legal?"Legal move for ":""}${t.color} token`} style={{position:"absolute",left:`calc(${(t.col+.5)*100/15}% + ${spread}px)`,top:`calc(${(t.row+.5)*100/15}% + ${spread}px)`,transform:"translate(-50%,-50%)",width:"5.1%",aspectRatio:1,borderRadius:"50%",border:"2px solid #222",background:p[t.color],zIndex:30+index,fontWeight:900,padding:0,color:"transparent",fontSize:0,cursor:legal?"pointer":"default",pointerEvents:legal?"auto":"none",filter:legal?"brightness(1.08)":"none"}} />;})}</React.Fragment>})}
  <div aria-label={`Finished tokens: ${finished.length}`} style={{position:"absolute",left:"40%",top:"40%",width:"20%",height:"20%",display:"grid",gridTemplateColumns:"repeat(4,1fr)",gridTemplateRows:"repeat(4,1fr)",gap:"2%",padding:"4%",boxSizing:"border-box",placeItems:"center",pointerEvents:"none",zIndex:40}}>{finished.map(t=><span key={`${t.color}-${t.id}`} style={{width:"92%",height:"92%",borderRadius:"50%",background:p[t.color],border:"2px solid #fff",boxShadow:"0 2px 5px rgba(0,0,0,.35)"}} />)}</div>
 </div>;
}
