"use client";
import {useEffect,useRef,useState} from "react";

type Member={id:string;playerId?:string;name:string;role?:string;online?:boolean};
declare global{interface Window{Peer?:any}}
function loadPeer(){return new Promise<any>((resolve,reject)=>{if(window.Peer)return resolve(window.Peer);const s=document.createElement("script");s.src="https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js";s.onload=()=>resolve(window.Peer);s.onerror=reject;document.head.appendChild(s)})}
const safe=(v:string)=>String(v||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,32);

export default function ChatVoice({roomCode,playerId,members}:{roomCode:string;playerId:string;members:Member[]}){
 const peerRef=useRef<any>(null),streamRef=useRef<MediaStream|null>(null),connections=useRef<Record<string,any>>({}),peerPlayers=useRef<Record<string,string>>({}),peerNames=useRef<Record<string,string>>({}),pendingCalls=useRef<Record<string,any>>({}),activityTimer=useRef<number|null>(null),selfPeer=useRef("");
 const[ready,setReady]=useState(false),[mic,setMic]=useState(false),[notice,setNotice]=useState("");
 const selfPeerId=`ludo-chat-${safe(roomCode)}-${safe(playerId)}`;
 const setAvatarSpeaking=(pid:string,on:boolean)=>{const name=peerNames.current[pid]||members.find(m=>String(m.playerId)===String(pid))?.name;if(!name)return;document.querySelectorAll<HTMLButtonElement>(".ig-avatar").forEach(b=>{if(b.getAttribute("aria-label")===name)b.classList.toggle("voice-speaking",on)})};
 const broadcastSpeaking=(on:boolean)=>Object.values(connections.current).forEach((c:any)=>{const d=c?.data;if(d?.open)try{d.send({type:"speaking",playerId:String(playerId),speaking:on})}catch{}});
 const playRemote=(peerId:string,s:MediaStream)=>{let a=document.getElementById(`chat-remote-${peerId}`) as HTMLAudioElement|null;if(!a){a=document.createElement("audio");a.id=`chat-remote-${peerId}`;a.autoplay=true;a.setAttribute("playsinline","true");a.setAttribute("aria-label",`Voice from ${peerNames.current[peerId]||"player"}`);a.style.display="none";document.body.appendChild(a)}a.srcObject=s;a.muted=false;void a.play().catch(()=>{setNotice("Tap Mic once to enable voice audio on this device.")})};
 const removePeer=(id:string)=>{const a=document.getElementById(`chat-remote-${id}`) as HTMLAudioElement|null;if(a)a.remove();setAvatarSpeaking(peerPlayers.current[id]||id,false);delete connections.current[id];delete peerNames.current[id];delete peerPlayers.current[id]};
 const callPeer=(id:string)=>{if(!streamRef.current||!peerRef.current||id===selfPeer.current)return;if(streamRef.current.getAudioTracks().every(t=>!t.enabled))return;if(connections.current[id]?.voiceCall)return;try{const call=peerRef.current.call(id,streamRef.current);if(call){connections.current[id]={...(connections.current[id]||{}),voiceCall:call};call.on("stream",(s:MediaStream)=>playRemote(id,s));call.on("close",()=>{const a=document.getElementById(`chat-remote-${id}`) as HTMLAudioElement|null;if(a)a.remove()});call.on("error",()=>{})}}catch{}};
 const connectPeer=(id:string,name:string,pid:string)=>{if(!id||id===selfPeer.current||!peerRef.current)return;peerNames.current[id]=name||"Player";peerPlayers.current[id]=pid||"";if(connections.current[id]?.data?.open||connections.current[id]?.connecting)return;try{const c=peerRef.current.connect(id,{reliable:true});connections.current[id]={...(connections.current[id]||{}),data:c,connecting:true};c.on("open",()=>{connections.current[id]={...(connections.current[id]||{}),data:c,connecting:false};if(streamRef.current)callPeer(id)});c.on("data",(m:any)=>{if(m?.type==="speaking")setAvatarSpeaking(String(m.playerId),!!m.speaking)});c.on("close",()=>removePeer(id));c.on("error",()=>{})}catch{}};
 useEffect(()=>{members.forEach(m=>{const pid=String(m.playerId||"");if(pid&&pid!==String(playerId)){connectPeer(`ludo-chat-${safe(roomCode)}-${safe(pid)}`,m.name||"Player",pid)}})},[members,ready,roomCode,playerId]);
 useEffect(()=>{let dead=false;const start=async()=>{try{const PeerClass=await loadPeer();if(dead)return;const peer=new PeerClass(selfPeerId);peerRef.current=peer;selfPeer.current=selfPeerId;peer.on("open",()=>{if(!dead){setReady(true);setNotice("");members.forEach(m=>{const pid=String(m.playerId||"");if(pid&&pid!==String(playerId))connectPeer(`ludo-chat-${safe(roomCode)}-${safe(pid)}`,m.name||"Player",pid)})}});peer.on("call",(call:any)=>{const prefix=`ludo-chat-${safe(roomCode)}-`;const pid=call.peer.startsWith(prefix)?call.peer.slice(prefix.length):call.peer;const member=members.find(m=>safe(String(m.playerId))===safe(pid));if(member){peerNames.current[call.peer]=member.name||"Player";peerPlayers.current[call.peer]=String(member.playerId||"")}pendingCalls.current[call.peer]=call;try{call.answer(streamRef.current||undefined)}catch{}call.on("stream",(s:MediaStream)=>{delete pendingCalls.current[call.peer];playRemote(call.peer,s)});call.on("close",()=>{delete pendingCalls.current[call.peer];removePeer(call.peer)});call.on("error",()=>{})});peer.on("error",(e:any)=>{console.warn("chat voice peer",e);if(!dead)setNotice(e?.type==="unavailable-id"?"Voice is reconnecting…":"Voice connection is unavailable. Try Mic again.")});peer.on("disconnected",()=>{if(!dead){setNotice("Voice reconnecting…");try{peer.reconnect()}catch{}}})}catch(e){console.warn("voice init",e);if(!dead)setNotice("Voice chat could not start.")}};start();return()=>{dead=true;setReady(false);if(activityTimer.current)window.clearInterval(activityTimer.current);broadcastSpeaking(false);Object.values(connections.current).forEach((x:any)=>{try{x.data?.close?.();x.voiceCall?.close?.()}catch{}});connections.current={};pendingCalls.current={};if(peerRef.current){try{peerRef.current.destroy()}catch{}}peerRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;document.querySelectorAll("audio[id^='chat-remote-']").forEach(a=>a.remove());document.querySelectorAll(".ig-avatar.voice-speaking").forEach(e=>e.classList.remove("voice-speaking"))}},[roomCode,playerId,selfPeerId]);
 const toggle=async()=>{if(!mic){try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setNotice("Microphone requires a secure HTTPS connection.");return}if(!peerRef.current||!ready){setNotice("Voice is still connecting…");return}const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;setMic(true);setNotice("");members.forEach(m=>{const pid=String(m.playerId||"");if(pid&&pid!==String(playerId))callPeer(`ludo-chat-${safe(roomCode)}-${safe(pid)}`)});Object.keys(pendingCalls.current).forEach(id=>{try{pendingCalls.current[id].answer(stream)}catch{}});const Ctx=window.AudioContext||(window as any).webkitAudioContext;if(Ctx){const ctx=new Ctx(),src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=512;src.connect(an);const data=new Uint8Array(an.fftSize);let last=false;activityTimer.current=window.setInterval(()=>{an.getByteTimeDomainData(data);let sum=0;for(let i=0;i<data.length;i++){const v=(data[i]-128)/128;sum+=v*v}const rms=Math.sqrt(sum/data.length),on=rms>0.055;if(on!==last){last=on;setAvatarSpeaking(String(playerId),on);broadcastSpeaking(on)}},90)}}catch(e){console.warn("microphone",e);setNotice("Microphone permission was not granted. Allow microphone access in browser settings.")}}else{if(activityTimer.current)window.clearInterval(activityTimer.current);activityTimer.current=null;setAvatarSpeaking(String(playerId),false);broadcastSpeaking(false);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setMic(false);setNotice("")}};
 return <div className="voice-control"><button type="button" onClick={toggle} aria-pressed={mic} disabled={!ready} title={notice||"Toggle microphone"} className={`voice-button ${mic?"active":""} ${!ready?"connecting":""}`}><span className="voice-icon">{mic?"🎙️":"🎤"}</span><span className="voice-label">{!ready?"Connecting":mic?"Mic On":"Mic Off"}</span><i className="voice-dot"/></button>{notice&&<span className="voice-notice" role="status">{notice}</span>}<style jsx global>{`.voice-control{width:100%;height:100%;position:relative;display:flex;align-items:center;justify-content:center}.voice-button{width:100%!important;height:100%!important;border:0!important;border-radius:16px!important;padding:0 4px!important;background:linear-gradient(145deg,#2a1b07,#100b03)!important;color:#f9e7a6!important;font:900 8px system-ui!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important;cursor:pointer!important;position:relative!important;transition:.18s ease!important}.voice-button.active{background:linear-gradient(145deg,#47330b,#171004)!important;border:1px solid rgba(245,215,110,.5)!important;box-shadow:inset 0 0 18px rgba(245,190,45,.08),0 0 14px rgba(245,190,45,.18)!important}.voice-button.connecting{opacity:.55!important;cursor:wait!important}.voice-icon{font-size:18px;line-height:18px}.voice-label{font-size:7px;letter-spacing:.25px;color:#dfcb88}.voice-dot{position:absolute;right:7px;top:7px;width:6px;height:6px;border-radius:50%;background:#766b52}.voice-button.active .voice-dot{background:#4ee184;box-shadow:0 0 7px #4ee184}.voice-notice{position:absolute;bottom:calc(100% + 10px);right:0;width:max-content;max-width:240px;padding:9px 11px;border-radius:12px;background:#180d03;border:1px solid rgba(215,185,74,.48);color:#f3df9a;font-size:10px;line-height:1.35;box-shadow:0 10px 28px rgba(0,0,0,.45);z-index:100}.voice-notice:after{content:"";position:absolute;right:24px;bottom:-5px;width:9px;height:9px;background:#180d03;border-right:1px solid rgba(215,185,74,.48);border-bottom:1px solid rgba(215,185,74,.48);transform:rotate(45deg)}.ig-avatar.voice-speaking{border-color:#f5d76e!important;box-shadow:0 0 0 2px rgba(245,215,110,.72),0 0 16px rgba(245,190,45,.95),0 0 30px rgba(245,190,45,.55)!important;animation:ludoGoldVoicePulse 900ms ease-in-out infinite}.ig-avatar.voice-speaking:after{content:"";position:absolute;inset:-5px;border:2px solid rgba(245,210,90,.5);border-radius:50%;animation:ludoGoldVoiceRing 900ms ease-out infinite;pointer-events:none}@keyframes ludoGoldVoicePulse{0%,100%{transform:scale(1);filter:brightness(1)}50%{transform:scale(1.08);filter:brightness(1.25)}}@keyframes ludoGoldVoiceRing{0%{transform:scale(.92);opacity:.85}100%{transform:scale(1.25);opacity:0}}`}</style></div>;
}