"use client";
import {useEffect,useRef,useState} from "react";

type Member={id:string;name:string;role:string;online:boolean};
declare global{interface Window{Peer?:any}}
function loadPeer(){return new Promise<any>((resolve,reject)=>{if(window.Peer)return resolve(window.Peer);const s=document.createElement("script");s.src="https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js";s.onload=()=>resolve(window.Peer);s.onerror=reject;document.head.appendChild(s)})}

export default function ChatVoice({roomCode,playerId,members}:{roomCode:string;playerId:string;members:Member[]}){
 const peerRef=useRef<any>(null),streamRef=useRef<MediaStream|null>(null),connections=useRef<Record<string,any>>({}),peerNames=useRef<Record<string,string>>({}),peerPlayers=useRef<Record<string,string>>({}),selfPeer=useRef(""),pendingCalls=useRef<Record<string,any>>({}),activityTimer=useRef<number|null>(null),speakingRef=useRef(false);
 const[ready,setReady]=useState(false),[mic,setMic]=useState(false),[notice,setNotice]=useState("");
 const owner=members.find(m=>m.role==="owner"),ownerPeer=owner?`ludo-chat-${roomCode}-${owner.id}`:"";
 const setAvatarSpeaking=(id:string,on:boolean)=>{const name=peerNames.current[id]||members.find(m=>String(m.playerId)===String(id))?.name; if(!name)return;document.querySelectorAll<HTMLButtonElement>(".ig-avatar").forEach(b=>{if(b.getAttribute("aria-label")===name)b.classList.toggle("voice-speaking",on)})};
 const broadcastSpeaking=(on:boolean)=>Object.values(connections.current).forEach((c:any)=>{if(c?.open)try{c.send({type:"speaking",playerId,speaking:on})}catch{}});
 const playRemote=(id:string,s:MediaStream)=>{let a=document.getElementById(`chat-remote-${id}`) as HTMLAudioElement|null;if(!a){a=document.createElement("audio");a.id=`chat-remote-${id}`;a.autoplay=true;a.setAttribute("playsinline","true");a.setAttribute("aria-label",`Voice from ${peerNames.current[id]||"player"}`);a.style.display="none";document.body.appendChild(a)}a.srcObject=s;a.muted=false;void a.play().catch(()=>{})};
 const answerPending=()=>{if(!peerRef.current)return;Object.entries(pendingCalls.current).forEach(([id,call]:any)=>{try{call.answer(streamRef.current||undefined);call.on("stream",(s:MediaStream)=>playRemote(id,s));delete pendingCalls.current[id]}catch{}})};
 const callPeer=(id:string)=>{if(!streamRef.current||!peerRef.current||id===selfPeer.current)return;if(streamRef.current.getAudioTracks().every(t=>!t.enabled))return;try{const call=peerRef.current.call(id,streamRef.current);call?.on("stream",(s:MediaStream)=>playRemote(id,s));call?.on("close",()=>{const a=document.getElementById(`chat-remote-${id}`) as HTMLAudioElement|null;if(a)a.remove()})}catch{}};
 const connect=(id:string)=>{if(!id||id===selfPeer.current||connections.current[id]?.open||!peerRef.current)return;try{const c=peerRef.current.connect(id,{reliable:true});connections.current[id]=c;c.on("open",()=>{if(owner?.id!==playerId&&id===ownerPeer)c.send({type:"hello",peerId:selfPeer.current,playerId,name:members.find(m=>String(m.playerId)===String(playerId))?.name||"Player"});if(streamRef.current)callPeer(id)});c.on("data",(m:any)=>{if(!m)return;if(m.type==="roster"){(m.peers||[]).forEach((p:any)=>{peerNames.current[p.id]=p.name||"Player";peerPlayers.current[p.id]=String(p.playerId||"");connect(p.id)})}if(m.type==="speaking"){setAvatarSpeaking(String(m.playerId),!!m.speaking)}});c.on("close",()=>{delete connections.current[c.peer];setAvatarSpeaking(peerPlayers.current[c.peer]||c.peer,false)})}catch{}};
 const broadcastRoster=()=>{const peers=Object.entries(peerNames.current).map(([id,name])=>({id,name,playerId:peerPlayers.current[id]}));Object.values(connections.current).forEach((c:any)=>{if(c?.open)try{c.send({type:"roster",peers})}catch{}});peers.forEach(p=>connect(p.id))};
 const bind=(c:any)=>{if(!c)return;connections.current[c.peer]=c;c.on("open",()=>{if(owner?.id===playerId)c.send({type:"hello",peerId:selfPeer.current,playerId,name:members.find(m=>String(m.playerId)===String(playerId))?.name||"Player"})});c.on("data",(m:any)=>{if(!m)return;if(m.type==="hello"&&owner?.id===playerId){peerNames.current[m.peerId]=m.name||"Player";peerPlayers.current[m.peerId]=String(m.playerId||"");broadcastRoster()}if(m.type==="roster"){(m.peers||[]).forEach((p:any)=>{peerNames.current[p.id]=p.name||"Player";peerPlayers.current[p.id]=String(p.playerId||"");connect(p.id)})}if(m.type==="speaking")setAvatarSpeaking(String(m.playerId),!!m.speaking)});c.on("close",()=>{delete connections.current[c.peer];setAvatarSpeaking(peerPlayers.current[c.peer]||c.peer,false)})};
 useEffect(()=>{let dead=false;let PeerClass:any;const start=async()=>{try{PeerClass=await loadPeer();if(dead)return;const isOwner=!!owner&&owner.id===playerId,id=isOwner?ownerPeer:`ludo-chat-${roomCode}-${playerId}-${Math.random().toString(36).slice(2,7)}`,peer=new PeerClass(id);peerRef.current=peer;selfPeer.current=id;peer.on("open",()=>{if(dead)return;setReady(true);if(!isOwner&&ownerPeer)connect(ownerPeer)});peer.on("connection",(c:any)=>bind(c));peer.on("call",(call:any)=>{if(streamRef.current){try{call.answer(streamRef.current)}catch{}}else{pendingCalls.current[call.peer]=call;try{call.answer()}catch{}}call.on("stream",(s:MediaStream)=>playRemote(call.peer,s));call.on("close",()=>{const a=document.getElementById(`chat-remote-${call.peer}`) as HTMLAudioElement|null;if(a)a.remove();delete pendingCalls.current[call.peer];setAvatarSpeaking(peerPlayers.current[call.peer]||call.peer,false)})});peer.on("error",(e:any)=>{console.warn("chat voice peer",e);if(!dead)setNotice("Voice connection is unavailable right now. Check your connection and try the mic again.")})}catch{if(!dead)setNotice("Voice chat could not start.")}};start();return()=>{dead=true;setReady(false);if(activityTimer.current)window.clearInterval(activityTimer.current);broadcastSpeaking(false);Object.values(connections.current).forEach((c:any)=>{try{c.close()}catch{}});Object.values(pendingCalls.current).forEach((c:any)=>{try{c.close()}catch{}});connections.current={};pendingCalls.current={};if(peerRef.current){try{peerRef.current.destroy()}catch{}}peerRef.current=null;if(streamRef.current)streamRef.current.getTracks().forEach(t=>t.stop());streamRef.current=null;document.querySelectorAll("audio[id^='chat-remote-']").forEach(a=>a.remove());document.querySelectorAll(".ig-avatar.voice-speaking").forEach(e=>e.classList.remove("voice-speaking"))}},[roomCode,playerId,ownerPeer]);
 useEffect(()=>{if(ready&&owner?.id===playerId){Object.entries(peerNames.current).forEach(([id])=>connect(id));broadcastRoster()}},[members,ready,owner?.id,playerId]);
 const toggle=async()=>{if(!mic){try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setNotice("Microphone requires a secure HTTPS connection.");return}const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;setMic(true);setNotice("");answerPending();Object.keys(connections.current).forEach(callPeer);const Ctx=window.AudioContext||(window as any).webkitAudioContext;if(Ctx){const ctx=new Ctx(),src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser();an.fftSize=512;src.connect(an);const data=new Uint8Array(an.fftSize);let last=false;activityTimer.current=window.setInterval(()=>{an.getByteTimeDomainData(data);let sum=0;for(let i=0;i<data.length;i++){const v=(data[i]-128)/128;sum+=v*v}const rms=Math.sqrt(sum/data.length),on=rms>0.055;if(on!==last){last=on;speakingRef.current=on;setAvatarSpeaking(playerId,on);broadcastSpeaking(on)}},90)}}catch(e){console.warn("microphone",e);setNotice("Microphone permission was not granted. Allow microphone access in your browser settings and try again.")}}else{if(activityTimer.current)window.clearInterval(activityTimer.current);activityTimer.current=null;speakingRef.current=false;setAvatarSpeaking(playerId,false);broadcastSpeaking(false);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setMic(false);setNotice("")}};
 return <div style={{display:"flex",alignItems:"center",gap:8,position:"relative"}}><button type="button" onClick={toggle} aria-pressed={mic} title={notice||"Toggle microphone"} style={{border:0,borderRadius:999,padding:"9px 12px",background:mic?"#16a34a":"#334155",color:"#fff",fontWeight:900,cursor:"pointer"}}>{mic?"🎙️ Mic On":"🎙️ Mic Off"}</button>{notice&&<span style={{position:"absolute",bottom:"calc(100% + 8px)",right:0,maxWidth:240,padding:"8px 10px",borderRadius:10,background:"#180d03",border:"1px solid rgba(215,185,74,.45)",color:"#f3df9a",fontSize:10,lineHeight:1.35,boxShadow:"0 8px 24px rgba(0,0,0,.35)"}}>{notice}</span>}<style jsx global>{`.ig-avatar.voice-speaking{border-color:#f5d76e!important;box-shadow:0 0 0 2px rgba(245,215,110,.72),0 0 16px rgba(245,190,45,.95),0 0 30px rgba(245,190,45,.55)!important;animation:ludoGoldVoicePulse 900ms ease-in-out infinite}.ig-avatar.voice-speaking:after{content:"";position:absolute;inset:-5px;border:2px solid rgba(245,210,90,.5);border-radius:50%;animation:ludoGoldVoiceRing 900ms ease-out infinite;pointer-events:none}@keyframes ludoGoldVoicePulse{0%,100%{transform:scale(1);filter:brightness(1)}50%{transform:scale(1.08);filter:brightness(1.25)}}@keyframes ludoGoldVoiceRing{0%{transform:scale(.92);opacity:.85}100%{transform:scale(1.25);opacity:0}}</style></div>;
}