"use client";
import { useEffect, useState } from "react";
import { io, type Socket } from "socket.io-client";
import AppFrame from "./AppFrame";

type Member={id:string;playerId?:string;name:string;host?:boolean;ready?:boolean;connected?:boolean};
type Props={roomCode:string;name:string;roomSize:2|4;host:boolean;onLeave:()=>void};

export default function FreePlayRoom({roomCode,name,roomSize,host,onLeave}:Props){
 const [socket,setSocket]=useState<Socket|null>(null),[members,setMembers]=useState<Member[]>([]),[ready,setReady]=useState(false),[notice,setNotice]=useState("Connecting to Free Play…"),[starting,setStarting]=useState(false);
 useEffect(()=>{const s=io(window.location.origin,{transports:["websocket","polling"],reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:300});setSocket(s);let cancelled=false;(async()=>{let playerId="";try{const a=await fetch("/api/auth",{cache:"no-store"}).then(r=>r.json());playerId=String(a?.user?.id||"")}catch{}if(cancelled||!playerId){setNotice("Please sign in before starting Free Play.");return}s.on("connect",()=>{setNotice("FREE PLAY • CONNECTED");s.emit("join-room",{roomCode,name:name||"Player",roomSize,playerId,host,board:"classic",dice:"classic"})});s.on("roster",(list:Member[])=>setMembers(list));s.on("start-error",(message:string)=>{setStarting(false);setNotice(message)});s.on("start-game",()=>{setNotice("FREE PLAY • MATCH STARTING");setStarting(true);window.location.href=`/game-online?room=${encodeURIComponent(roomCode)}&name=${encodeURIComponent(name||"Player")}${host?"&host=1":""}`});s.on("disconnect",()=>setNotice("Reconnecting…"))})();return()=>{cancelled=true;s.disconnect()}},[roomCode,name,roomSize,host]);
 const me=members.find(m=>m.playerId===name||m.name===name),isReady=Boolean(me?.ready||ready),serverHost=Boolean(members.find(m=>m.host)),canStart=host&&serverHost&&members.length===roomSize&&members.every(m=>m.ready&&m.connected!==false)&&!starting;
 const toggleReady=()=>{if(!socket?.connected){setNotice("Reconnecting to Free Play…");return}const next=!isReady;setReady(next);socket.emit("ready",{ready:next})};
 const start=()=>{if(!canStart||!socket?.connected)return;setStarting(true);setNotice("Starting Free Play…");socket.emit("start-game")};
 return <AppFrame back="/lobby"><main style={{maxWidth:760,margin:"0 auto",padding:"18px 12px",color:"#fff"}}><header style={{padding:18,borderRadius:20,background:"linear-gradient(135deg,#0f3b2a,#071b2b)",border:"1px solid rgba(74,222,128,.35)"}}><small style={{opacity:.7,fontWeight:900,letterSpacing:2}}>FREE PLAY</small><h1 style={{margin:"5px 0 4px",fontSize:30}}>🎮 No-Stakes Ludo</h1><p style={{margin:0,color:"#a7f3d0"}}>Play the normal multiplayer game without coins or stake locking.</p></header><section style={{marginTop:14,padding:16,borderRadius:18,background:"rgba(7,18,39,.92)",border:"1px solid rgba(96,165,250,.16)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><small style={{color:"#94a3b8"}}>ROOM ID</small><strong style={{display:"block",fontSize:25,letterSpacing:3}}>{roomCode}</strong></div><button type="button" onClick={()=>navigator.clipboard?.writeText(roomCode)} style={copyBtn}>📋 Copy code</button></div><div style={{marginTop:18,fontWeight:900}}>Players {members.length}/{roomSize}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginTop:10}}>{Array.from({length:roomSize},(_,i)=>members[i]).map((m,i)=>m?<div key={m.id} style={card}><div style={{fontSize:25}}>{m.host?"👑":"🧑🏽‍🎮"}</div><b>{m.name}{m.name===name?" (you)":""}</b><span style={{color:m.ready?"#4ade80":"#94a3b8",fontSize:12,fontWeight:800}}>{m.ready?"✓ Ready":"Not Ready"}</span></div>:<div key={`empty-${i}`} style={{...card,borderStyle:"dashed",opacity:.7}}>＋ Waiting for player</div>)}</div><div style={{marginTop:16,padding:12,borderRadius:12,background:"rgba(34,197,94,.08)",color:"#bbf7d0",fontSize:13}}>No coins are required. Free Play uses the same multiplayer Ludo board, dice, moves and win rules.</div><div style={{display:"flex",gap:10,marginTop:14,flexWrap:"wrap"}}><button type="button" onClick={toggleReady} style={{...readyBtn,background:isReady?"#166534":"#2563eb"}}>{isReady?"✓ Ready":"Ready"}</button><button type="button" onClick={start} disabled={!canStart} style={{...startBtn,opacity:canStart?1:.45}}>START FREE GAME</button><button type="button" onClick={onLeave} style={leaveBtn}>Leave Room</button></div><p style={{margin:"12px 0 0",color:"#cbd5e1",fontSize:12}}>{notice}</p></section></main></AppFrame>;
}
const copyBtn={border:0,cursor:"pointer",padding:"9px 12px",borderRadius:10,background:"#1e293b",color:"#fff",fontWeight:800};
const card={display:"grid",gap:4,padding:12,borderRadius:14,background:"rgba(15,23,42,.9)",border:"1px solid #334155"};
const readyBtn={border:0,cursor:"pointer",padding:"11px 16px",borderRadius:10,color:"#fff",fontWeight:900};
const startBtn={border:0,cursor:"pointer",padding:"11px 16px",borderRadius:10,background:"#22c55e",color:"#04130a",fontWeight:950};
const leaveBtn={border:0,cursor:"pointer",padding:"11px 14px",borderRadius:10,background:"#7f1d1d",color:"#fff",fontWeight:800};
