"use client";
import{useEffect,useRef,useState}from"react";
export type DiceSkinId="classic"|"golden"|"crystal"|"fire"|"rainbow"|"diamond"|"skull"|"sports";
export const DICE_STYLES:Record<DiceSkinId,string>={classic:"linear-gradient(145deg,#ffffff 0%,#edf2f7 48%,#b9c5d0 100%)",golden:"linear-gradient(145deg,#fff2a8 0%,#f1c34b 48%,#c98d15 100%)",crystal:"linear-gradient(145deg,#e8fbff 0%,#79c9ee 48%,#1685d8 100%)",fire:"linear-gradient(145deg,#ffe58a 0%,#ff8b36 48%,#e52d20 100%)",rainbow:"linear-gradient(145deg,#e6ffff 0%,#78dff4 45%,#ff6ab3 100%)",diamond:"linear-gradient(145deg,#ffffff 0%,#d9ecff 48%,#91c7ff 100%)",skull:"linear-gradient(145deg,#3b424b 0%,#171b21 50%,#05070a 100%)",sports:"linear-gradient(145deg,#ffffff 0%,#d9efd0 48%,#8bc34a 100%)"};
const pipMap:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
const FACE_ROTATION:Record<number,[number,number]>={1:[0,0],2:[-90,0],3:[0,-90],4:[0,90],5:[90,0],6:[0,180]};
type FaceProps={value:number;size:number;dark:boolean;transform:string;skin:DiceSkinId};
function Face({value,size,dark,transform,skin}:FaceProps){return <div className="dice-face" style={{width:size,height:size,transform,background:DICE_STYLES[skin]}}>{Array.from({length:9},(_,i)=><span key={i} className="dice-slot">{pipMap[value].includes(i)&&<span className="dice-pip" style={{background:dark?"#fff":"#111"}}/>}</span>)}</div>}
export default function LudoDice({skin="classic",value=1,size=112,className="",onClick}:{skin?:DiceSkinId;value?:number;size?:number;className?:string;onClick?:()=>void}){
 const[shaking,setShaking]=useState(false);const[display,setDisplay]=useState(Math.max(1,Math.min(6,value)));const rotation=useRef<[number,number]>(FACE_ROTATION[Math.max(1,Math.min(6,value))]);const cubeRef=useRef<HTMLSpanElement|null>(null);const timerRef=useRef<number|null>(null);const rafRef=useRef<number|null>(null);const shown=Math.max(1,Math.min(6,display));const dark=skin==="skull";const faceSize=size*.82;const half=faceSize/2;
 useEffect(()=>{const next=Math.max(1,Math.min(6,value));if(next===display)return;setShaking(true);const startTimer=window.setTimeout(()=>{const start=rotation.current;const base=FACE_ROTATION[next];const end:[number,number]=[base[0]+(Math.abs(base[0]-start[0])<180?720:-720),base[1]+(Math.abs(base[1]-start[1])<180?720:-720)];const started=performance.now();const duration=820;const ease=(t:number)=>1-Math.pow(1-t,3);const frame=(now:number)=>{const p=Math.min(1,(now-started)/duration);const e=ease(p);const rx=start[0]+(end[0]-start[0])*e;const ry=start[1]+(end[1]-start[1])*e;rotation.current=[rx,ry];if(cubeRef.current)cubeRef.current.style.transform=`rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${Math.sin(p*Math.PI)*7}deg)`;if(p<1){rafRef.current=requestAnimationFrame(frame)}else{rotation.current=base;if(cubeRef.current)cubeRef.current.style.transform=`rotateX(${base[0]}deg) rotateY(${base[1]}deg)`;setDisplay(next);setShaking(false)}};rafRef.current=requestAnimationFrame(frame)},320);timerRef.current=startTimer;return()=>{if(timerRef.current)window.clearTimeout(timerRef.current);if(rafRef.current)cancelAnimationFrame(rafRef.current)}},[value,display]);
 return <button type="button" aria-label={`Roll dice, showing ${shown}`} onClick={onClick} className={`ludo-dice ${shaking?"dice-shaking":""} ${className}`.trim()} style={{width:size,height:size,cursor:onClick?"pointer":"default"}}>
   <span className="dice-stage" style={{width:faceSize,height:faceSize}}><span ref={cubeRef} className="dice-cube" style={{width:faceSize,height:faceSize,transform:`rotateX(${rotation.current[0]}deg) rotateY(${rotation.current[1]}deg)`}}>
    <span className="dice-face dice-front" style={{width:faceSize,height:faceSize,transform:`translateZ(${half}px)`,background:DICE_STYLES[skin]}}>{Array.from({length:9},(_,i)=><span key={i} className="dice-slot">{pipMap[shown].includes(i)&&<span className="dice-pip" style={{background:dark?"#fff":"#111"}}/>}</span>)}</span>
    <Face value={6} size={faceSize} dark={dark} skin={skin} transform={`rotateY(180deg) translateZ(${half}px)`}/><Face value={2} size={faceSize} dark={dark} skin={skin} transform={`rotateX(90deg) translateZ(${half}px)`}/><Face value={5} size={faceSize} dark={dark} skin={skin} transform={`rotateX(-90deg) translateZ(${half}px)`}/><Face value={3} size={faceSize} dark={dark} skin={skin} transform={`rotateY(90deg) translateZ(${half}px)`}/><Face value={4} size={faceSize} dark={dark} skin={skin} transform={`rotateY(-90deg) translateZ(${half}px)`}/>
   </span></span>
   <style jsx>{`.ludo-dice{position:relative;border:0;background:transparent;padding:0;display:grid;place-items:center;perspective:1100px;filter:drop-shadow(0 12px 14px rgba(0,0,0,.3));touch-action:manipulation}.dice-stage{display:block;position:relative;perspective:1100px}.dice-cube{display:block;position:absolute;inset:0;transform-style:preserve-3d;will-change:transform}.dice-face{position:absolute;inset:0;border:3px solid #111;border-radius:19%;box-sizing:border-box;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);padding:12%;gap:2%;backface-visibility:hidden;box-shadow:inset 0 4px 4px rgba(255,255,255,.75),inset 0 -9px 12px rgba(0,0,0,.18),0 2px 4px rgba(0,0,0,.2)}.dice-slot{display:grid;place-items:center}.dice-pip{width:38%;height:38%;min-width:7px;min-height:7px;border-radius:50%;box-shadow:inset 0 2px 2px rgba(255,255,255,.4),0 2px 3px rgba(0,0,0,.3)}.dice-shaking{animation:diceVibrate .055s linear infinite}.dice-shaking .dice-cube{animation:diceWobble .14s ease-in-out infinite alternate}@keyframes diceVibrate{0%{transform:translate3d(0,0,0) rotate(-1deg)}25%{transform:translate3d(-3px,1px,0) rotate(1deg)}50%{transform:translate3d(3px,-1px,0) rotate(-1deg)}75%{transform:translate3d(-2px,-1px,0) rotate(1deg)}100%{transform:translate3d(0,0,0) rotate(-1deg)}}@keyframes diceWobble{from{scale:.98}to{scale:1.02}}@media(max-width:480px){.dice-face{border-width:2px;border-radius:18%}}`}</style>
 </button>;
}
