"use client";
import{useEffect,useState}from"react";
export type DiceSkinId="classic"|"golden"|"crystal"|"fire"|"rainbow"|"diamond"|"skull"|"sports";
export const DICE_STYLES:Record<DiceSkinId,string>={classic:"linear-gradient(145deg,#ffffff 0%,#d9e2ec 55%,#aebdca 100%)",golden:"linear-gradient(145deg,#fff0a8,#c98d15)",crystal:"linear-gradient(145deg,#dff7ff,#1685d8)",fire:"linear-gradient(145deg,#ffcf57,#e52d20)",rainbow:"linear-gradient(145deg,#5ee7ff,#ff6ab3)",diamond:"linear-gradient(145deg,#fff,#91c7ff)",skull:"linear-gradient(145deg,#20242b,#05070a)",sports:"linear-gradient(145deg,#fff,#8bc34a)"};
const pipMap:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
const rotations:Record<number,string>={1:"rotateX(0deg) rotateY(0deg)",2:"rotateX(-90deg) rotateY(0deg)",3:"rotateX(0deg) rotateY(-90deg)",4:"rotateX(0deg) rotateY(90deg)",5:"rotateX(90deg) rotateY(0deg)",6:"rotateX(0deg) rotateY(180deg)"};
function Face({value,size,dark,transform,skin}:{value:number;size:number;dark:boolean;transform:string;skin:DiceSkinId}){return <div className="dice-face" style={{width:size,height:size,transform,background:DICE_STYLES[skin],color:dark?"#fff":"#111"}}>{Array.from({length:9},(_,i)=><span key={i} className="dice-slot">{pipMap[value].includes(i)&&<span className="dice-pip" style={{background:dark?"#fff":"#111"}}/>}</span>)}</div>}
export default function LudoDice({skin="classic",value=1,size=112,className="",onClick}:{skin?:DiceSkinId;value?:number;size?:number;className?:string;onClick?:()=>void}){
 const[shaking,setShaking]=useState(false);const[display,setDisplay]=useState(Math.max(1,Math.min(6,value)));const shown=Math.max(1,Math.min(6,display)),dark=skin==="skull",style=DICE_STYLES[skin]||DICE_STYLES.classic;
 useEffect(()=>{if(value===display)return;setShaking(true);const timer=window.setTimeout(()=>{setDisplay(value);setShaking(false)},900);return()=>window.clearTimeout(timer)},[value]);
 return <button type="button" aria-label={`Roll dice, showing ${shown}`} onClick={onClick} className={`ludo-dice ${shaking?"dice-shaking":""} ${className}`.trim()} style={{width:size,height:size,cursor:onClick?"pointer":"default"}}>
   <span className="dice-stage" style={{width:size*.82,height:size*.82}}><span className="dice-cube" style={{width:size*.82,height:size*.82,transform:rotations[shown]}}>
    <span className="dice-face dice-front" style={{background:style}}>{Array.from({length:9},(_,i)=><span key={i} className="dice-slot">{pipMap[shown].includes(i)&&<span className="dice-pip" style={{background:dark?"#fff":"#111"}}/>}</span>)}</span>
    <Face value={6} size={size*.82} dark={dark} skin={skin} transform="rotateY(180deg) translateZ(1px)"/><Face value={2} size={size*.82} dark={dark} skin={skin} transform="rotateX(90deg) translateZ(1px)"/><Face value={5} size={size*.82} dark={dark} skin={skin} transform="rotateX(-90deg) translateZ(1px)"/><Face value={3} size={size*.82} dark={dark} skin={skin} transform="rotateY(90deg) translateZ(1px)"/><Face value={4} size={size*.82} dark={dark} skin={skin} transform="rotateY(-90deg) translateZ(1px)"/>
   </span></span>
   <style jsx>{`.ludo-dice{position:relative;border:0;background:transparent;padding:0;display:grid;place-items:center;perspective:1200px;filter:drop-shadow(0 10px 13px rgba(0,0,0,.28));touch-action:manipulation}.dice-stage{display:block;position:relative;perspective:1200px}.dice-cube{display:block;position:absolute;inset:0;transform-style:preserve-3d;transition:transform .28s cubic-bezier(.2,.8,.25,1)}.dice-face{position:absolute;inset:0;border:3px solid #111;border-radius:18%;box-sizing:border-box;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);padding:12%;gap:2%;backface-visibility:hidden;box-shadow:inset 0 3px 3px rgba(255,255,255,.7),inset 0 -6px 10px rgba(0,0,0,.16),0 2px 3px rgba(0,0,0,.2)}.dice-front{transform:translateZ(calc(var(--dice-half,40px)))}.dice-slot{display:grid;place-items:center}.dice-pip{width:34%;height:34%;min-width:7px;min-height:7px;border-radius:50%;box-shadow:inset 0 1px 2px rgba(255,255,255,.35),0 1px 2px rgba(0,0,0,.28)}.dice-shaking{animation:diceVibrate .075s linear infinite}.dice-shaking .dice-cube{animation:diceNaturalRoll .9s cubic-bezier(.35,.05,.25,1) 1}.@keyframes diceVibrate{0%{transform:translate(0,0)}25%{transform:translate(-2px,1px)}50%{transform:translate(2px,-1px)}75%{transform:translate(-1px,-1px)}100%{transform:translate(0,0)}}@keyframes diceNaturalRoll{0%{transform:rotateX(0deg) rotateY(0deg)}25%{transform:rotateX(70deg) rotateY(45deg)}50%{transform:rotateX(155deg) rotateY(105deg)}75%{transform:rotateX(240deg) rotateY(160deg)}100%{transform:rotateX(360deg) rotateY(180deg)}}@media(max-width:480px){.dice-face{border-width:2px;border-radius:17%}}`}</style>
 </button>;
}
