"use client";
import{useEffect,useRef,useState}from"react";
export type DiceSkinId="classic"|"golden"|"crystal"|"fire"|"rainbow"|"diamond"|"skull"|"sports"|"neon"|"galaxy"|"love";
export const DICE_STYLES:Record<DiceSkinId,string>={classic:"linear-gradient(145deg,#fff 0%,#edf2f7 48%,#b9c5d0 100%)",golden:"linear-gradient(145deg,#fff2a8 0%,#f1c34b 48%,#c98d15 100%)",crystal:"linear-gradient(145deg,#e8fbff 0%,#79c9ee 48%,#1685d8 100%)",fire:"linear-gradient(145deg,#ffe58a 0%,#ff8b36 48%,#e52d20 100%)",rainbow:"linear-gradient(145deg,#e6ffff 0%,#78dff4 45%,#ff6ab3 100%)",diamond:"linear-gradient(145deg,#fff 0%,#d9ecff 48%,#91c7ff 100%)",skull:"linear-gradient(145deg,#3b424b 0%,#171b21 50%,#05070a 100%)",sports:"linear-gradient(145deg,#fff 0%,#d9efd0 48%,#8bc34a 100%)",neon:"linear-gradient(145deg,#ff8cff 0%,#8d38ff 45%,#19eaff 100%)",galaxy:"linear-gradient(145deg,#d8c5ff 0%,#2939b8 45%,#090b3d 100%)",love:"linear-gradient(145deg,#fff0f7 0%,#ff91bd 48%,#e83c7c 100%)"};
const pipMap:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
const FACE_ROTATION:Record<number,[number,number]>={1:[0,0],2:[-90,0],3:[0,-90],4:[0,90],5:[90,0],6:[0,180]};
function Face({value,size,dark,transform,skin}:{value:number;size:number;dark:boolean;transform:string;skin:DiceSkinId}){return <div style={{position:"absolute",inset:0,width:size,height:size,transform,background:DICE_STYLES[skin],border:"3px solid #111",borderRadius:"19%",boxSizing:"border-box",display:"grid",gridTemplateColumns:"repeat(3,1fr)",gridTemplateRows:"repeat(3,1fr)",padding:"12%",gap:"2%",backfaceVisibility:"hidden",boxShadow:"inset 0 4px 4px rgba(255,255,255,.75),inset 0 -9px 12px rgba(0,0,0,.18),0 2px 4px rgba(0,0,0,.2)"}}>{Array.from({length:9},(_,i)=><span key={i} style={{display:"grid",placeItems:"center"}}>{pipMap[value].includes(i)&&<span style={{width:"38%",height:"38%",minWidth:7,minHeight:7,borderRadius:"50%",background:dark?"#fff":"#111",boxShadow:"inset 0 2px 2px rgba(255,255,255,.4),0 2px 3px rgba(0,0,0,.3)"}}/>}</span>)}</div>}
export default function LudoDice({skin="classic",value=1,size=112,className="",onClick}:{skin?:DiceSkinId;value?:number;size?:number;className?:string;onClick?:()=>void}){
 const[shaking,setShaking]=useState(false);const[display,setDisplay]=useState(Math.max(1,Math.min(6,value)));const rotation=useRef<[number,number]>(FACE_ROTATION[Math.max(1,Math.min(6,value))]);const cubeRef=useRef<HTMLSpanElement|null>(null);const timerRef=useRef<number|null>(null);const rafRef=useRef<number|null>(null);const shown=Math.max(1,Math.min(6,display));const dark=skin==="skull";const faceSize=size*.82;const half=faceSize/2;
 useEffect(()=>{const next=Math.max(1,Math.min(6,value));if(next===display)return;setShaking(true);const timer=window.setTimeout(()=>{const start=rotation.current,base=FACE_ROTATION[next],end:[number,number]=[base[0]+(Math.abs(base[0]-start[0])<180?720:-720),base[1]+(Math.abs(base[1]-start[1])<180?720:-720)],started=performance.now(),ease=(t:number)=>1-Math.pow(1-t,3);const frame=(now:number)=>{const p=Math.min(1,(now-started)/820),e=ease(p),rx=start[0]+(end[0]-start[0])*e,ry=start[1]+(end[1]-start[1])*e;rotation.current=[rx,ry];if(cubeRef.current)cubeRef.current.style.transform=`rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${Math.sin(p*Math.PI)*7}deg)`;if(p<1)rafRef.current=requestAnimationFrame(frame);else{rotation.current=base;if(cubeRef.current)cubeRef.current.style.transform=`rotateX(${base[0]}deg) rotateY(${base[1]}deg)`;setDisplay(next);setShaking(false)}};rafRef.current=requestAnimationFrame(frame)},120);timerRef.current=timer;return()=>{if(timerRef.current)window.clearTimeout(timerRef.current);if(rafRef.current)cancelAnimationFrame(rafRef.current)}},[value,display]);
 return <button type="button" aria-label={`Roll dice, showing ${shown}`} onClick={onClick} className={`ludo-dice ${shaking?"dice-shaking":""} ${className}`.trim()} style={{position:"relative",border:0,background:"transparent",padding:0,display:"grid",placeItems:"center",perspective:1100,width:size,height:size,cursor:onClick?"pointer":"default",filter:"drop-shadow(0 12px 14px rgba(0,0,0,.3))",touchAction:"manipulation"}}>
  <span style={{display:"block",position:"relative",width:faceSize,height:faceSize,perspective:1100}}><span ref={cubeRef} style={{display:"block",position:"absolute",inset:0,width:faceSize,height:faceSize,transformStyle:"preserve-3d",transform:`rotateX(${rotation.current[0]}deg) rotateY(${rotation.current[1]}deg)`,transition:shaking?"none":"transform .12s"}}><span style={{position:"absolute",inset:0,width:faceSize,height:faceSize,transform:`translateZ(${half}px)`,background:DICE_STYLES[skin],border:"3px solid #111",borderRadius:"19%",boxSizing:"border-box",display:"grid",gridTemplateColumns:"repeat(3,1fr)",gridTemplateRows:"repeat(3,1fr)",padding:"12%",gap:"2%",backfaceVisibility:"hidden",boxShadow:"inset 0 4px 4px rgba(255,255,255,.75),inset 0 -9px 12px rgba(0,0,0,.18),0 2px 4px rgba(0,0,0,.2)"}}>{Array.from({length:9},(_,i)=><span key={i} style={{display:"grid",placeItems:"center"}}>{pipMap[shown].includes(i)&&<span style={{width:"38%",height:"38%",minWidth:7,minHeight:7,borderRadius:"50%",background:dark?"#fff":"#111",boxShadow:"inset 0 2px 2px rgba(255,255,255,.4),0 2px 3px rgba(0,0,0,.3)"}}/>}</span>)}</span><Face value={6} size={faceSize} dark={dark} skin={skin} transform={`rotateY(180deg) translateZ(${half}px)`}/><Face value={2} size={faceSize} dark={dark} skin={skin} transform={`rotateX(90deg) translateZ(${half}px)`}/><Face value={5} size={faceSize} dark={dark} skin={skin} transform={`rotateX(-90deg) translateZ(${half}px)`}/><Face value={3} size={faceSize} dark={dark} skin={skin} transform={`rotateY(90deg) translateZ(${half}px)`}/><Face value={4} size={faceSize} dark={dark} skin={skin} transform={`rotateY(-90deg) translateZ(${half}px)`}/></span></span>
 </button>;
}
