"use client";

export type BoardThemeId = "classic"|"golden"|"neon"|"beach"|"galaxy"|"wood"|"dragon"|"christmas"|"football"|"candy";
type Palette={bg:string;green:string;yellow:string;red:string;blue:string;accent:string};
export type DemoToken={color:"green"|"yellow"|"red"|"blue";position:number;id:number};

export const BOARD_PALETTES:Record<BoardThemeId,Palette>={
  classic:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},golden:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},neon:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},beach:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#ef3b43",blue:"#2f6be5",accent:"#222222"},galaxy:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},wood:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},dragon:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},christmas:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},football:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"},candy:{bg:"#ffffff",green:"#18a84b",yellow:"#f5b800",red:"#f02d43",blue:"#2f6be5",accent:"#222222"}
};
export const BOARD_NAMES:Record<BoardThemeId,string>={classic:"Classic Ludo",golden:"Golden Royal",neon:"Neon Glow",beach:"Beach Vibes",galaxy:"Galaxy Space",wood:"Wooden Classic",dragon:"Dragon Theme",christmas:"Christmas Edition",football:"Football Arena",candy:"Candy Land"};
const homes=[{key:"green",row:0,col:0,color:"green"},{key:"yellow",row:0,col:9,color:"yellow"},{key:"red",row:9,col:0,color:"red"},{key:"blue",row:9,col:9,color:"blue"}] as const;
const lanes=[...Array.from({length:5},(_,i)=>({color:"yellow",row:i+1,col:7})),...Array.from({length:5},(_,i)=>({color:"blue",row:7,col:i+9})),...Array.from({length:5},(_,i)=>({color:"red",row:13-i,col:7})),...Array.from({length:5},(_,i)=>({color:"green",row:7,col:i+1}))] as const;
const stars=[{row:6,col:1,color:"green"},{row:1,col:8,color:"yellow"},{row:13,col:6,color:"red"},{row:8,col:13,color:"blue"}] as const;
const mainPath=[...Array.from({length:5},(_,i)=>[6,i+1] as const),...Array.from({length:6},(_,i)=>[5-i,6] as const),[0,7],[0,8],...Array.from({length:5},(_,i)=>[i+1,8] as const),...Array.from({length:5},(_,i)=>[6,i+9] as const),[7,13],[7,14],[8,14],...Array.from({length:5},(_,i)=>[8,13-i] as const),...Array.from({length:6},(_,i)=>[9+i,8] as const),[14,7],[14,6],...Array.from({length:5},(_,i)=>[13-i,6] as const),...Array.from({length:6},(_,i)=>[8,5-i] as const),[7,0],[6,0]];
const starts={green:0,yellow:13,red:39,blue:26} as const;
const lanePath={green:[[7,1],[7,2],[7,3],[7,4],[7,5]],yellow:[[1,7],[2,7],[3,7],[4,7],[5,7]],red:[[13,7],[12,7],[11,7],[10,7],[9,7]],blue:[[7,13],[7,12],[7,11],[7,10],[7,9]]} as const;
function tokenCell(color:DemoToken["color"],position:number){if(position<=0)return null;if(position<=52){const index=(starts[color]+position-1)%52;return mainPath[index]}if(position<=57)return lanePath[color][position-53];if(position===58)return [7,7] as const;return null}
export default function LudoBoardFixed({theme="classic",preview=false,className="",style,demoTokens=[],onTokenClick}:{theme?:BoardThemeId;preview?:boolean;className?:string;style?:React.CSSProperties;demoTokens?:DemoToken[];onTokenClick?:(color:DemoToken["color"],id:number)=>void}){
 const p=BOARD_PALETTES[theme]||BOARD_PALETTES.classic,cells=Array.from({length:225},(_,index)=>({index,row:Math.floor(index/15),col:index%15}));
 const laneAt=(row:number,col:number)=>lanes.find(l=>l.row===row&&l.col===col)?.color;const starAt=(row:number,col:number)=>stars.find(s=>s.row===row&&s.col===col);const visibleTokens=demoTokens.map(t=>{const cell=tokenCell(t.color,t.position);return cell?{...t,row:cell[0],col:cell[1]}:null}).filter(Boolean) as Array<DemoToken&{row:number;col:number}>;const isDemo=demoTokens.length>0;
 return <div className={`shared-ludo-board ${preview?"shared-ludo-board-preview":""} ${className}`.trim()} style={{...style,background:p.bg,borderColor:p.accent}} aria-label={`${BOARD_NAMES[theme]} Ludo board`}>
  {cells.map(({index,row,col})=>{const lane=laneAt(row,col),star=starAt(row,col),isHome=homes.some(h=>row>=h.row&&row<h.row+6&&col>=h.col&&col<h.col+6);return <div className={`board-cell ${!isHome?"track-cell":""} ${lane?`lane-${lane}`:""} ${star?`safe-${star.color}`:""}`} key={index} aria-hidden="true">{star&&<span className="safe-star">★</span>}</div>})}
  {homes.map(home=>{const homeTokens=isDemo?demoTokens.filter(t=>t.color===home.key&&t.position===0):[];return <div key={home.key} className={`home-area home-${home.key}`} style={{background:p[home.color]}} aria-hidden="true"><div className="token-yard">{isDemo?homeTokens.map(t=><button key={`${t.color}-${t.id}`} type="button" className={`token token-${home.key} home-token-button`} onClick={()=>onTokenClick?.(t.color,t.id)} aria-label={`${t.color} token ${t.id+1}`} style={{background:p[home.color]}}>{t.id+1}</button>):Array.from({length:4},(_,i)=><span key={i} className={`token token-${home.key}`} style={{background:p[home.color]}} />)}</div></div>})}
  <div className="center-home" aria-hidden="true"><span className="center-triangle center-green" style={{background:p.green}}/><span className="center-triangle center-yellow" style={{background:p.yellow}}/><span className="center-triangle center-red" style={{background:p.red}}/><span className="center-triangle center-blue" style={{background:p.blue}}/></div>
  {visibleTokens.map(t=><button key={`${t.color}-${t.id}`} type="button" className={`moving-token moving-${t.color}`} onClick={()=>onTokenClick?.(t.color,t.id)} aria-label={`${t.color} token ${t.id+1}`} style={{left:`${(t.col+.5)*100/15}%`,top:`${(t.row+.5)*100/15}%`,background:p[t.color]}}>{t.id+1}</button>)}
  <style jsx>{`.shared-ludo-board{width:100%;max-width:100%;aspect-ratio:1/1;position:relative;box-sizing:border-box;display:grid;grid-template-columns:repeat(15,minmax(0,1fr));grid-template-rows:repeat(15,minmax(0,1fr));background:#fff;border:3px solid #222;border-radius:0;overflow:hidden;box-shadow:none;margin:0 auto}.board-cell{min-width:0;min-height:0;box-sizing:border-box;background:#fff;border-right:1px solid #a8a8a8;border-bottom:1px solid #a8a8a8;display:flex;align-items:center;justify-content:center;position:relative}.board-cell:nth-child(15n){border-right:0}.board-cell:nth-last-child(-n+15){border-bottom:0}.track-cell{background:#fff}.lane-green{background:${p.green}}.lane-yellow{background:${p.yellow}}.lane-red{background:${p.red}}.lane-blue{background:${p.blue}}.safe-green{background:${p.green}}.safe-yellow{background:${p.yellow}}.safe-red{background:${p.red}}.safe-blue{background:${p.blue}}.safe-star{font-size:clamp(11px,2.8vw,24px);line-height:1;color:#111;position:relative;z-index:1}.home-area{position:absolute;width:40%;height:40%;box-sizing:border-box;border:3px solid #222;pointer-events:none;z-index:3;padding:5.8%}.home-green{top:0;left:0}.home-yellow{top:0;right:0}.home-red{bottom:0;left:0}.home-blue{bottom:0;right:0}.token-yard{width:100%;height:100%;box-sizing:border-box;background:#fff;border:3px solid #222;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;place-items:center;padding:5%;gap:4%;pointer-events:auto}.token{width:77%;aspect-ratio:1;border-radius:50%;border:3px solid #222;box-shadow:0 1px 1px rgba(0,0,0,.12)}.home-token-button{cursor:pointer;padding:0;font:inherit;display:block}.home-token-button:active{transform:scale(.92)}.center-home{position:absolute;left:40%;top:40%;width:20%;height:20%;z-index:5;background:#fff;border:2px solid #222;overflow:hidden}.center-triangle{position:absolute;inset:0}.center-green{clip-path:polygon(0 0,50% 50%,0 100%)}.center-yellow{clip-path:polygon(0 0,100% 0,50% 50%)}.center-red{clip-path:polygon(0 100%,100% 100%,50% 50%)}.center-blue{clip-path:polygon(100% 0,100% 100%,50% 50%)}.moving-token{position:absolute;transform:translate(-50%,-50%);width:7.5%;aspect-ratio:1;border-radius:50%;border:2px solid #222;box-shadow:0 2px 4px rgba(0,0,0,.25);z-index:8;font-size:clamp(8px,2vw,13px);font-weight:900;color:#fff;padding:0;cursor:pointer;transition:left .18s ease,top .18s ease}.moving-token:active{transform:translate(-50%,-50%) scale(.92)}.shared-ludo-board-preview{width:100%;max-width:260px;border-width:2px}@media(max-width:480px){.shared-ludo-board{width:100%;max-width:100%;border-width:2px}.token{border-width:2px}.token-yard{border-width:2px}.home-area{border-width:2px}.moving-token{border-width:2px}}`}</style>
 </div>;
}
