export type LudoColor = "red"|"yellow"|"green"|"blue";
export type BoardCell = readonly [number,number];
export type TokenLike = {color:LudoColor;id:number;position:number;state?:"yard"|"track"|"home"|"finished"};
export declare const COLORS: readonly LudoColor[];
export declare const START_INDEX: Record<LudoColor,number>;
export declare const TRACK_LENGTH: number;
export declare const PHYSICAL_TRACK_LENGTH: number;
export declare const HOME_START: number;
export declare const HOME_STRETCH: number;
export declare const FINISH: number;
export declare const MAIN_PATH: readonly BoardCell[];
export declare const HOME_LANES: Record<LudoColor,readonly BoardCell[]>;
export declare const SAFE_CELLS: readonly {row:number;col:number;color:LudoColor}[];
export declare function getTrackCell(color:LudoColor,progress:number): BoardCell|null;
export declare function getHomeCell(color:LudoColor,progress:number): BoardCell|null;
export declare function getTokenCell(color:LudoColor,progress:number): BoardCell|null;
export declare function tokenState(progress:number): "yard"|"track"|"home"|"finished";
export declare function nextProgress(position:number,dice:1|2|3|4|5|6): number|null;
export declare function isSafeProgress(color:LudoColor,progress:number): boolean;
export declare function opponentsAt(tokens:readonly TokenLike[],color:LudoColor,progress:number): TokenLike[];
export declare function canMove(tokens:readonly TokenLike[],token:TokenLike,dice:1|2|3|4|5|6): boolean;
export declare function legalMoves(tokens:readonly TokenLike[],colors:readonly LudoColor[],dice:1|2|3|4|5|6): TokenLike[];
export declare function hasLegalMove(tokens:readonly TokenLike[],colors:readonly LudoColor[],dice:1|2|3|4|5|6): boolean;
export declare function applyMove(tokens:readonly TokenLike[],token:TokenLike,dice:1|2|3|4|5|6): {tokens:TokenLike[];target:number;captured:TokenLike|null}|null;
export declare function hasWon(tokens:readonly TokenLike[],colors:readonly LudoColor[]): boolean;
export declare function winner(tokens:readonly TokenLike[],humanColors?:readonly LudoColor[],botColors?:readonly LudoColor[]): "human"|"bot"|null;
export declare function playerColorsForSeats(playerCount:number,seat:number): LudoColor[];
