import * as rules from "./ludoRules";
import type { LudoColor } from "./ludoRules";
export type DiceValue=1|2|3|4|5|6;
export type TokenLike=rules.TokenLike;
export const HUMAN_COLORS:readonly LudoColor[]=["red","yellow"];
export const BOT_COLORS:readonly LudoColor[]=["green","blue"];
export const COLORS=rules.COLORS;
export const SAFE_CELLS=rules.SAFE_CELLS;
export const START_INDEX=rules.START_INDEX;
export const TRACK_LENGTH=rules.TRACK_LENGTH;
export const HOME_STRETCH=rules.HOME_STRETCH;
export const HOME_ENTRY_STEP=rules.HOME_START;
export const STEPS_TO_FINISH=rules.FINISH;
export const FINISH_PROGRESS=rules.FINISH;
export const getBoardPosition=(token:TokenLike)=>{if(token.position<=0||token.position>=rules.FINISH)return null;const cell=rules.getTokenCell(token.color,token.position);return cell?{zone:token.position>=rules.HOME_START?"home":"track",index:token.position}:null};
export const isSafeSquare=(trackIndex:number)=>rules.SAFE_CELLS.some(s=>s.row===Math.floor(trackIndex/15)&&s.col===trackIndex%15);
export const canMove=rules.canMove;
export const legalMoves=rules.legalMoves;
export const moveToken=(token:TokenLike,dice:DiceValue,allTokens:TokenLike[])=>{const result=rules.applyMove(allTokens,token,dice);return result?{moved:true,token:result.tokens.find(t=>t.color===token.color&&t.id===token.id)||token,captured:result.captured?[result.captured]:[]}:{moved:false,token,captured:[]};};
export const hasLegalMove=rules.hasLegalMove;
export const nextProgress=rules.nextProgress;
export const applyMove=(tokens:readonly TokenLike[],token:TokenLike,dice:DiceValue)=>{const result=rules.applyMove(tokens,token,dice);return result?.tokens||null;};
export const hasWon=rules.hasWon;
export const winner=(tokens:readonly TokenLike[])=>rules.winner(tokens,HUMAN_COLORS,BOT_COLORS);
export const isDice=(value:number):value is DiceValue=>Number.isInteger(value)&&value>=1&&value<=6;
export const rollDice=()=>((Math.floor(Math.random()*6)+1) as DiceValue);
export const playerColorsForSeats=rules.playerColorsForSeats;
