const { canMove, hasLegalMove, hasWon, playerColorsForSeats, tokenState, nextProgress, applyMove, FINISH } = require("./ludoRules");
const COLORS=["red","yellow","green","blue"]; const TOKEN_COUNT=4;
function createTokens(players){const tokens={};const count=players.length===2?2:4;for(const p of players){const pid=String(p.playerId);tokens[pid]={};for(const color of playerColorsForSeats(count,p.seat))for(let id=0;id<TOKEN_COUNT;id++)tokens[pid][`${color}:${id}`]={position:0};}return tokens;}
function flattenTokens(state){const out=[];for(const [playerId,pt] of Object.entries(state.tokens||{}))for(const [key,value] of Object.entries(pt||{})){const [color,idText]=key.split(":");const id=Number(idText);if(!COLORS.includes(color)||!Number.isInteger(id)||id<0||id>=TOKEN_COUNT)continue;const position=Number(value?.position??0);out.push({playerId,color,id,position,state:tokenState(position)});}return out;}
function writeTokens(state,flat){const next={};for(const t of flat){next[t.playerId] ||= {};next[t.playerId][`${t.color}:${t.id}`]={position:t.position};}state.tokens=next;}
function playerFor(state,pid){return(state.players||[]).find(p=>String(p.playerId)===String(pid))||null;}
function colorsFor(state,pid){const p=playerFor(state,pid);return p?(p.colors?.length?p.colors:playerColorsForSeats(state.players.length===2?2:4,p.seat)):[];}
function nextPlayerId(state){const i=state.players.findIndex(p=>String(p.playerId)===String(state.currentPlayerId));if(i<0||!state.players.length)return null;return state.players[(i+1)%state.players.length]?.playerId||null;}
function createGame(players){const normalized=players.map((p,seat)=>({playerId:String(p.playerId),name:String(p.name||"Player"),seat,colors:p.colors?.length?p.colors:playerColorsForSeats(players.length===2?2:4,seat),level:Math.max(1,Number(p.level)||1),avatar:String(p.avatar||""),coins:Math.max(0,Number(p.coins)||0)}));return{status:"playing",currentPlayerId:normalized[0]?.playerId||null,dice:null,pendingMove:null,sixStreak:0,players:normalized,tokens:createTokens(normalized),winnerId:null,stateRevision:0};}
function finishTurn(state,pid,dice,moveInfo,forcePass=false){if(moveInfo&&hasWon(flattenTokens(state),colorsFor(state,pid))){state.status="finished";state.winnerId=pid;state.currentPlayerId=null;}else if(forcePass){state.currentPlayerId=nextPlayerId(state);state.sixStreak=0;}else{state.sixStreak=dice===6?state.sixStreak+1:0;if(dice!==6||state.sixStreak>=3){state.currentPlayerId=nextPlayerId(state);state.sixStreak=0;}}state.pendingMove=null;state.dice=null;state.stateRevision++;return{ok:true,...(moveInfo||{}),stateRevision:state.stateRevision};}
function roll(state,pid,random=Math.random){if(state.status!=="playing")return{ok:false,reason:"game_not_playing"};if(String(state.currentPlayerId)!==String(pid))return{ok:false,reason:"not_your_turn"};if(state.pendingMove!==null)return{ok:false,reason:"finish_current_move"};const value=1+Math.floor(random()*6);state.dice=value;state.pendingMove=value;const colors=colorsFor(state,pid),all=flattenTokens(state);if(!hasLegalMove(all,colors,value)){const passed=finishTurn(state,pid,value,null,true);return{ok:true,value,stateRevision:passed.stateRevision,autoPassed:true,nextPlayerId:state.currentPlayerId};}state.stateRevision++;return{ok:true,value,stateRevision:state.stateRevision,autoPassed:false};}
function move(state,pid,tokenId){if(state.status!=="playing")return{ok:false,reason:"game_not_playing"};if(String(state.currentPlayerId)!==String(pid))return{ok:false,reason:"not_your_turn"};if(state.pendingMove===null)return{ok:false,reason:"roll_first"};const dice=Number(state.pendingMove),colors=colorsFor(state,pid),all=flattenTokens(state);if(tokenId==="__skip__"){if(hasLegalMove(all,colors,dice))return{ok:false,reason:"legal_move_exists"};return finishTurn(state,pid,dice,null,true);}const [color,idText]=String(tokenId||"").split(":");const id=Number(idText);const player=playerFor(state,pid);if(!player||!colors.includes(color)||!Number.isInteger(id))return{ok:false,reason:"not_your_token"};const token=all.find(t=>String(t.playerId)===String(pid)&&t.color===color&&t.id===id);if(!token)return{ok:false,reason:"token_not_found"};if(!canMove(all,token,dice))return{ok:false,reason:"illegal_move"};const result=applyMove(all,token,dice);if(!result)return{ok:false,reason:"illegal_move"};const target=Number(result.target),captured=result.captured||null;writeTokens(state,result.tokens);state.stateRevision++;const moveInfo={tokenId,from:Number(token.position),target,captureProgress:captured?target:null,finalTo:captured?FINISH:target,captured:captured?{playerId:String(captured.playerId||""),color:captured.color,id:Number(captured.id)}:null,captureToCenter:Boolean(captured),stateRevision:state.stateRevision};return{...finishTurn(state,pid,dice,moveInfo),playerId:pid,tokenId};}
function snapshot(state){return{status:state.status,currentPlayerId:state.currentPlayerId,dice:state.dice,pendingMove:state.pendingMove,sixStreak:state.sixStreak,players:state.players,tokens:state.tokens,winnerId:state.winnerId,stateRevision:state.stateRevision};}
module.exports={createGame,roll,move,snapshot,flattenTokens};
