"use client";
import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import AppFrame from "../_components/AppFrame";

type EventItem={id:string;icon:string;title:string;description:string;reward:string;ends:number;color:string};
const events:EventItem[]=[
{id:"login",icon:"📅",title:"Login & Win",description:"Login everyday & win rewards!",reward:"🎁",ends:Date.now()+3*86400000+14*3600000,color:"purple"},
{id:"dice",icon:"⚄",title:"Dice Challenge",description:"Win matches to earn points!",reward:"🧰",ends:Date.now()+1*86400000+10*3600000,color:"purple"},
{id:"coins",icon:"🪙",title:"Weekend Bonanza",description:"Extra coins on weekends!",reward:"🎁",ends:Date.now()+2*86400000+10*3600000,color:"blue"},
{id:"gems",icon:"💎",title:"Gem Rush",description:"Collect gems in special modes!",reward:"🎁",ends:Date.now()+5*86400000+14*3600000,color:"blue"}
];
function left(ms:number){const s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/86400)}d ${Math.floor(s%86400/3600)}h`}
export default function EventsPage(){const [tab,setTab]=useState("Live Events"),[now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);const live=useMemo(()=>events.filter(e=>e.ends>now),[now]);return <AppFrame back=""><main style={page}><header style={header}><button onClick={()=>history.back()} style={back}>←</button><div style={headerTitle}>Events</div><div/></header><div style={tabs}>{["Live Events","Upcoming"].map(t=><button key={t} onClick={()=>setTab(t)} style={{...tabStyle,...(tab===t?tabActive:{})}}>{t}</button>)}</div>{tab==="Live Events"?<section style={list}>{live.map(e=><article key={e.id} style={{...card,background:e.color==="purple"?"linear-gradient(110deg,#341079,#54168b)":"linear-gradient(110deg,#07336e,#084e99)"}}><div style={icon}>{e.icon}</div><div style={body}><strong style={title}>{e.title}</strong><div style={desc}>{e.description}</div><div style={ends}>Ends in: {left(e.ends-now)}</div></div><div style={reward}>{e.reward}</div></article>)}</section>:<section style={empty}><div style={{fontSize:40}}>📆</div><h2>Upcoming Events</h2><p>New challenges and reward events will appear here before they go live.</p></section>}<button style={calendar}><span>▦</span> Event Calendar</button></main></AppFrame>}
const page:CSSProperties={maxWidth:650,margin:"0 auto",paddingBottom:45};const header:CSSProperties={height:52,display:"grid",gridTemplateColumns:"44px 1fr 44px",alignItems:"center",marginBottom:8};const back:CSSProperties={border:0,background:"transparent",color:"#fff",fontSize:32,cursor:"pointer",textAlign:"left",lineHeight:1};const headerTitle:CSSProperties={textAlign:"center",fontSize:20,fontWeight:950};const tabs:CSSProperties={display:"grid",gridTemplateColumns:"1fr 1fr",gap:4,padding:4,borderRadius:9,background:"#06152b",border:"1px solid #12345c"};const tabStyle:CSSProperties={border:0,borderRadius:7,padding:"11px",background:"#0a1d38",color:"#dbe8f8",fontSize:13,fontWeight:900};const tabActive:CSSProperties={background:"linear-gradient(180deg,#277cf0,#1762d1)",color:"#fff"};const list:CSSProperties={display:"grid",gap:7,marginTop:12};const card:CSSProperties={display:"flex",alignItems:"center",gap:12,minHeight:102,padding:"14px 12px",borderRadius:10,border:"1px solid rgba(120,70,190,.55)",boxShadow:"inset 0 0 18px rgba(255,255,255,.05)"};const icon:CSSProperties={width:62,textAlign:"center",fontSize:43,filter:"drop-shadow(0 2px 3px #000)"};const body:CSSProperties={flex:1,minWidth:0};const title:CSSProperties={fontSize:18};const desc:CSSProperties={marginTop:7,color:"#d8def0",fontSize:13};const ends:CSSProperties={marginTop:8,color:"#fff",fontSize:12,fontWeight:700};const reward:CSSProperties={fontSize:40,filter:"drop-shadow(0 2px 4px #000)"};const calendar:CSSProperties={width:"100%",marginTop:16,padding:14,border:0,borderRadius:7,background:"linear-gradient(180deg,#247bea,#145ec8)",color:"#fff",fontSize:16,fontWeight:950};const empty:CSSProperties={marginTop:12,padding:45,background:"#07172d",borderRadius:12,border:"1px solid #17385f",textAlign:"center",color:"#9db0c8"};
