"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Player, PlayerColor, ALL_COLORS } from "@/lib/engine";
import { BASE_ZONE, BASE_COORDS, GLOBAL_PATH_COORDS, HOME_STRETCH_COORDS, CENTER_COORD, ENTRY_COORDS, COLOR_BG_SOLID, getSafeCoordSet, getRenderCoord } from "@/lib/engine/layout";
import Token from "./Token";
const BOARD_SIZE=15, STEP_DURATION_MS=180;
const STACK_OFFSETS: Record<number,{x:number;y:number}[]>={1:[{x:0,y:0}],2:[{x:-14,y:-22},{x:14,y:22}],3:[{x:-14,y:-22},{x:14,y:-22},{x:0,y:22}],4:[{x:-14,y:-22},{x:14,y:-22},{x:-14,y:22},{x:14,y:22}]};
const HOME_ARROW:Record<PlayerColor,string>={RED:"→",GREEN:"↓",YELLOW:"←",BLUE:"↑"};
type Pos=number|"YARD"; type CellType="yard"|"path"|"home"|"center"|"empty";
interface Cell{type:CellType;color?:PlayerColor;safe?:boolean;entryColor?:PlayerColor;yardSlot?:boolean;homeIndex?:number}
interface BoardProps{players:Player[];selectableTokenIds:Set<string>;onTokenClick:(id:string)=>void;onMoveAnimationComplete?:()=>void;playerNames?:Partial<Record<PlayerColor,string>>;playerAvatars?:Partial<Record<PlayerColor,string|undefined>>;emptyColors?:Set<PlayerColor>;disconnectedColors?:Set<PlayerColor>;currentTurnColors?:Set<PlayerColor>;onCapture?:(info:{tokenId:string;color:PlayerColor})=>void;showTapHint?:boolean}
interface Flash{id:string;color:PlayerColor;row:number;col:number}
const key=(r:number,c:number)=>`${r},${c}`;
function buildBoard(){const cells:Record<string,Cell>={};for(let r=0;r<BOARD_SIZE;r++)for(let c=0;c<BOARD_SIZE;c++)cells[key(r,c)]={type:"empty"};for(const color of ALL_COLORS){const z=BASE_ZONE[color];for(let r=z.rowStart;r<z.rowStart+6;r++)for(let c=z.colStart;c<z.colStart+6;c++)cells[key(r,c)]={type:"yard",color};BASE_COORDS[color].forEach(p=>cells[key(p.row,p.col)]={type:"yard",color,yardSlot:true})}const safe=getSafeCoordSet();GLOBAL_PATH_COORDS.forEach(p=>cells[key(p.row,p.col)]={type:"path",safe:safe.has(key(p.row,p.col))});for(const color of ALL_COLORS){const e=ENTRY_COORDS[color];cells[key(e.row,e.col)]={...cells[key(e.row,e.col)],entryColor:color};HOME_STRETCH_COORDS[color].forEach((p,i)=>cells[key(p.row,p.col)]={type:"home",color,homeIndex:i})}cells[key(CENTER_COORD.row,CENTER_COORD.col)]={type:"center"};return cells}
const BOARD_CELLS=buildBoard();
function BoardToken({color,position,selectable,offset,onClick}:{id:string;color:PlayerColor;position:Pos;selectable:boolean;offset:{x:number;y:number};onClick:()=>void}){return <div className="absolute inset-0 z-20 pointer-events-none" style={{transform:`translate(${offset.x}%,${offset.y}%)`}}><div className="relative h-full w-full pointer-events-none"><Token color={color} resting={position==="YARD"} selectable={selectable} onClick={onClick}/></div></div>}
export default function Board({players,selectableTokenIds,onTokenClick,onMoveAnimationComplete,playerNames,playerAvatars,emptyColors,disconnectedColors,currentTurnColors,onCapture,showTapHint=false}:BoardProps){
 const [displayPositions,setDisplayPositions]=useState<Record<string,Pos>>(()=>{const x:Record<string,Pos>={};players.forEach(p=>p.tokens.forEach(t=>x[t.id]=t.position));return x});
 const previous=useRef(displayPositions),complete=useRef(onMoveAnimationComplete),capture=useRef(onCapture),[flashes,setFlashes]=useState<Flash[]>([]),flashId=useRef(0);
 useEffect(()=>{complete.current=onMoveAnimationComplete},[onMoveAnimationComplete]);useEffect(()=>{capture.current=onCapture},[onCapture]);
 useEffect(()=>{const next:Record<string,Pos>={};const colors:Record<string,PlayerColor>={};players.forEach(p=>p.tokens.forEach(t=>{next[t.id]=t.position;colors[t.id]=t.color}));const prev=previous.current,timers:ReturnType<typeof setTimeout>[]=[];let animations=0,changed=false;const finish=()=>{animations--;if(animations===0)complete.current?.()};const animate=(id:string,from:number,to:number)=>{animations++;let step=from;const tick=()=>{step++;setDisplayPositions(cur=>({...cur,[id]:step}));if(step<to)timers.push(setTimeout(tick,STEP_DURATION_MS));else finish()};timers.push(setTimeout(tick,STEP_DURATION_MS))};const nf:Flash[]=[];Object.entries(next).forEach(([id,np])=>{const op=prev[id];if(op===np)return;changed=true;if(op==="YARD"&&typeof np==="number"){setDisplayPositions(cur=>({...cur,[id]:0}));if(np!==0)animate(id,0,np);return}if(typeof op==="number"&&typeof np==="number"&&np>op){animate(id,op,np);return}if(typeof op==="number"&&np==="YARD"){const color=colors[id],coord=getRenderCoord(color,op,0);flashId.current++;nf.push({id:`${id}-${flashId.current}`,color,row:coord.row,col:coord.col});capture.current?.({tokenId:id,color})}setDisplayPositions(cur=>({...cur,[id]:np}))});previous.current=next;if(nf.length){setFlashes(cur=>[...cur,...nf]);const ids=new Set(nf.map(f=>f.id));timers.push(setTimeout(()=>setFlashes(cur=>cur.filter(f=>!ids.has(f.id))),650))}if(changed&&animations===0)timers.push(setTimeout(()=>complete.current?.(),0));return()=>timers.forEach(clearTimeout)},[players]);
 const tokensByCell=useMemo(()=>{const g:Record<string,{id:string;color:PlayerColor;position:Pos}[]>={};players.forEach(p=>p.tokens.forEach((t,i)=>{const position=displayPositions[t.id]??t.position,coord=getRenderCoord(t.color,position,i),k=key(coord.row,coord.col);(g[k]??=[]).push({id:t.id,color:t.color,position})}));return g},[players,displayPositions]);
 const hint=useMemo(()=>{const id=Array.from(selectableTokenIds)[0];if(!id)return null;for(const p of players){const t=p.tokens.find(x=>x.id===id);if(t){const pos=displayPositions[id]??t.position;return getRenderCoord(t.color,pos,0)}}return null},[selectableTokenIds,players,displayPositions]);
 return <div dir="ltr" className="relative isolate grid w-full max-w-[720px] aspect-square mx-auto overflow-hidden rounded-[22px] border-[5px] border-slate-950 bg-white shadow-2xl" style={{gridTemplateColumns:`repeat(${BOARD_SIZE},minmax(0,1fr))`,gridTemplateRows:`repeat(${BOARD_SIZE},minmax(0,1fr))`}} aria-label="Ludo board">
 {Array.from({length:BOARD_SIZE*BOARD_SIZE}).map((_,i)=>{const row=Math.floor(i/BOARD_SIZE),col=i%BOARD_SIZE,cell=BOARD_CELLS[key(row,col)],tokens=tokensByCell[key(row,col)]||[],center=row>=6&&row<=8&&col>=6&&col<=8,isCenter=row===CENTER_COORD.row&&col===CENTER_COORD.col,isHome=cell.type==="home",homeIndex=cell.homeIndex??-1,bg=cell.type==="yard"||isHome?COLOR_BG_SOLID[cell.color!]:cell.type==="path"&&cell.entryColor?COLOR_BG_SOLID[cell.entryColor]:"bg-white";return <div key={key(row,col)} style={{gridRow:row+1,gridColumn:col+1}} className={`relative flex items-center justify-center ${center?"bg-transparent":bg} ${cell.type!=="yard"&&!center?"border border-slate-300":""}`}>{cell.yardSlot&&tokens.length===0&&<div className="absolute w-[72%] h-[72%] rounded-full border-[3px] border-white/75 bg-black/10"/>}{cell.type==="path"&&cell.safe&&<span className="absolute font-black text-amber-500" style={{fontSize:"min(3.5vw,17px)"}}>★</span>}{isHome&&homeIndex===2&&<span className="absolute z-[2] text-white/80 font-black pointer-events-none" style={{fontSize:"min(2.8vw,13px)"}}>{HOME_ARROW[cell.color!]}</span>}{tokens.map((t,j)=>{const n=Math.min(tokens.length,4),raw=STACK_OFFSETS[n]?.[j]??{x:0,y:0},offset=t.position==="YARD"?{x:0,y:0}:raw;return <BoardToken key={t.id} id={t.id} color={t.color} position={t.position} selectable={selectableTokenIds.has(t.id)} offset={offset} onClick={()=>onTokenClick(t.id)}/>})}{isCenter&&<div className="absolute inset-0 z-[3] overflow-hidden"><div className={`absolute inset-0 ${COLOR_BG_SOLID.RED}`} style={{clipPath:"polygon(0 0,100% 0,50% 50%)"}}/><div className={`absolute inset-0 ${COLOR_BG_SOLID.GREEN}`} style={{clipPath:"polygon(100% 0,100% 100%,50% 50%)"}}/><div className={`absolute inset-0 ${COLOR_BG_SOLID.YELLOW}`} style={{clipPath:"polygon(100% 100%,0 100%,50% 50%)"}}/><div className={`absolute inset-0 ${COLOR_BG_SOLID.BLUE}`} style={{clipPath:"polygon(0 100%,0 0,50% 50%)"}}/><div className="absolute inset-0 flex items-center justify-center"><div className="w-[70%] h-[70%] flex items-center justify-center rounded-lg bg-blue-700 text-white font-black text-[min(4vw,20px)]">LUDO</div></div></div>}</div>})}
 {ALL_COLORS.map(color=>{const z=BASE_ZONE[color],name=playerNames?.[color]??color.toLowerCase(),avatar=playerAvatars?.[color],empty=emptyColors?.has(color)??false,dis=disconnectedColors?.has(color)??false,turn=currentTurnColors?.has(color)??false;return <div key={color} className="absolute z-[8] pointer-events-none flex items-center justify-center" style={{top:`${((z.rowStart+2)/BOARD_SIZE)*100}%`,left:`${((z.colStart+2)/BOARD_SIZE)*100}%`,width:`${(2/BOARD_SIZE)*100}%`,height:`${(2/BOARD_SIZE)*100}%`}}>{empty?<div className="w-full h-full rounded-full border-2 border-dashed border-white/70 bg-black/20 flex items-center justify-center text-white font-black text-lg">+</div>:<div className={`relative w-full h-full rounded-full overflow-hidden border-[3px] border-white shadow-lg ${turn?"ring-4 ring-amber-300":""} ${dis?"opacity-40 grayscale":""}`} title={name}>{avatar?<img src={avatar} alt={name} className="w-full h-full object-cover"/>:<div className={`w-full h-full ${COLOR_BG_SOLID[color]} flex items-center justify-center text-white font-black`}>{name.charAt(0).toUpperCase()}</div>}</div>}</div>})}
 {showTapHint&&hint&&<div className="absolute z-[50] pointer-events-none" style={{top:`${((hint.row+.5)/BOARD_SIZE)*100}%`,left:`${((hint.col+.5)/BOARD_SIZE)*100}%`}}><div className="text-4xl leading-none drop-shadow-xl animate-[tapHint_1.4s_ease-in-out_infinite]">👆</div></div>}{flashes.map(f=><div key={f.id} className="absolute z-[30] pointer-events-none" style={{top:`${((f.row+.5)/BOARD_SIZE)*100}%`,left:`${((f.col+.5)/BOARD_SIZE)*100}%`,transform:"translate(-50%,-50%)"}}><div className={`w-10 h-10 rounded-full ${COLOR_BG_SOLID[f.color]} animate-ping opacity-80`}/></div>)}<style jsx>{`@keyframes tapHint{0%,100%{transform:translate(-12%,-8%) scale(1)}45%{transform:translate(-12%,10%) scale(.88)}60%{transform:translate(-12%,-8%) scale(1)}}`}</style></div>
}