import {NextRequest,NextResponse} from "next/server";
import {randomUUID} from "crypto";
import {pool,ensureAuthSchema} from "../../auth/_db";
import {currentUser} from "../../../../lib/auth-session";
import {getShopItem} from "../catalog";
import {CATALOG} from "../../../../lib/customization-catalog";

const ITEMS:Record<string,{name:string;price:number;currency:"gems";kind:"item"|"avatar"}>={"shield":{name:"Shield",price:500,currency:"gems",kind:"item"},"trail":{name:"Trail",price:500,currency:"gems",kind:"item"},"crown":{name:"Crown",price:500,currency:"gems",kind:"item"},"golden-dice":{name:"Golden Dice",price:500,currency:"gems",kind:"item"},"avatar-1":{name:"Avatar 1",price:500,currency:"gems",kind:"avatar"},"avatar-2":{name:"Avatar 2",price:700,currency:"gems",kind:"avatar"},"avatar-3":{name:"Avatar 3",price:1000,currency:"gems",kind:"avatar"},"avatar-4":{name:"Avatar 4",price:1200,currency:"gems",kind:"avatar"},"avatar-5":{name:"Avatar 5",price:1300,currency:"gems",kind:"avatar"},"avatar-6":{name:"Avatar 6",price:2000,currency:"gems",kind:"avatar"}};
const clean=(v:unknown)=>Array.isArray(v)?v.map(String):[];
const levelRequired=(level:number)=>10+Math.max(0,level)*5;

async function ensureShopAccountingSchema(){
 await pool.query(`CREATE TABLE IF NOT EXISTS ludo_admin_wallets(id TEXT PRIMARY KEY,revenue_gems BIGINT NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);
 await pool.query(`INSERT INTO ludo_admin_wallets(id,revenue_gems) VALUES('platform',0) ON CONFLICT(id) DO NOTHING;`);
 await pool.query(`CREATE TABLE IF NOT EXISTS ludo_admin_wallet_ledger(id BIGSERIAL PRIMARY KEY,wallet_to TEXT NOT NULL,currency TEXT NOT NULL CHECK(currency IN ('coins','gems')),amount BIGINT NOT NULL,reason TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);
 await pool.query(`ALTER TABLE ludo_admin_ledger ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'unknown';`);
}

async function setShopWalletContext(client:any,userId:string,reason:string,req:NextRequest){
 const requestId=String(req.headers.get("x-request-id")||randomUUID());
 const ip=String(req.headers.get("x-forwarded-for")||req.headers.get("x-real-ip")||"").split(",")[0].trim();
 const ua=String(req.headers.get("user-agent")||"");
 const sourceRef=`shop:${userId}:${requestId}`;
 await client.query(`SELECT set_config('ludo.wallet_source',$1,true),set_config('ludo.wallet_source_ref',$2,true),set_config('ludo.wallet_actor',$3,true),set_config('ludo.wallet_actor_type','user',true),set_config('ludo.wallet_request_id',$4,true),set_config('ludo.wallet_ip',$5,true),set_config('ludo.wallet_user_agent',$6,true),set_config('ludo.wallet_reason',$7,true)`,["shop",sourceRef,String(userId),requestId,ip,ua,reason]);
}

export async function POST(req:NextRequest){const client=await pool.connect();let tx=false;try{await ensureAuthSchema();await ensureShopAccountingSchema();const user=await currentUser(req);if(!user||user.is_guest)return NextResponse.json({error:"A registered account is required."},{status:403});const body=await req.json(),id=String(body.id||""),type=String(body.type||"");
 let catalogItem=await getShopItem(type,id);
 if(catalogItem&&(type==="coin_package"||type==="gem_package")){const base=(CATALOG as any[]).find(x=>x.type===type&&x.id===id);if(base){catalogItem={...base,...catalogItem,reward:catalogItem.reward==null?base.reward:catalogItem.reward,rewardCurrency:catalogItem.rewardCurrency||base.rewardCurrency};}}
 if(catalogItem && (type==="coin_package"||type==="gem_package")){if(catalogItem.currency==="naira")return NextResponse.json({error:"This package uses Naira. Continue through the payment checkout."},{status:400});const price=Math.max(0,Number(catalogItem.price)||0),reward=Math.max(0,Number((catalogItem as any).reward)||0),rewardCurrency=String((catalogItem as any).rewardCurrency||"") as "coins"|"gems";if(!reward||!price||!['coins','gems'].includes(catalogItem.currency)||!['coins','gems'].includes(rewardCurrency))return NextResponse.json({error:"Package pricing is not configured correctly."},{status:500});await client.query("BEGIN");tx=true;const r=await client.query<any>("SELECT coins,gems,xp,level FROM ludo_users WHERE id=$1 FOR UPDATE",[user.id]);const row=r.rows[0];if(!row)throw new Error("Account not found.");const beforeCoins=Number(row.coins)||0,beforeGems=Number(row.gems)||0,balance=catalogItem.currency==="coins"?beforeCoins:beforeGems;if(balance<price){await client.query("ROLLBACK");tx=false;return NextResponse.json({error:`Not enough ${catalogItem.currency}.`},{status:400});}const afterCoins=catalogItem.currency==="coins"?beforeCoins-price:beforeCoins;const afterGems=catalogItem.currency==="gems"?beforeGems-price:beforeGems;let xp=Math.max(0,Number(row.xp)||0),level=Math.max(0,Number(row.level)||0);if(rewardCurrency==="gems"){xp+=15;while(xp>=levelRequired(level)){xp-=levelRequired(level);level+=1;}}const finalCoins=rewardCurrency==="coins"?afterCoins+reward:afterCoins,finalGems=rewardCurrency==="gems"?afterGems+reward:afterGems;await setShopWalletContext(client,user.id,`Shop purchase: ${catalogItem.name}`,req);await client.query("UPDATE ludo_users SET coins=$1,gems=$2,xp=$3,level=$4 WHERE id=$5",[finalCoins,finalGems,xp,level,user.id]);const debitAmount=-price;const before=catalogItem.currency==="coins"?beforeCoins:beforeGems;const after=catalogItem.currency==="coins"?afterCoins:afterGems;await client.query("INSERT INTO ludo_admin_ledger(user_id,currency,amount,balance_before,balance_after,reason,source) VALUES($1,$2,$3,$4,$5,$6,'shop')",[user.id,catalogItem.currency,debitAmount,before,after,`Purchased ${catalogItem.name}`]);if(catalogItem.currency==="gems"){await client.query("UPDATE ludo_admin_wallets SET revenue_gems=revenue_gems+$1,updated_at=NOW() WHERE id='platform'",[price]);await client.query("INSERT INTO ludo_admin_wallet_ledger(wallet_to,currency,amount,reason) VALUES('revenue','gems',$1,$2)",[price,`Shop: purchased ${catalogItem.name}`]);}await client.query("COMMIT");tx=false;return NextResponse.json({ok:true,coins:finalCoins,gems:finalGems,xp,level,package:catalogItem});}
 const item=ITEMS[id];if(!item)return NextResponse.json({error:"Shop item not found."},{status:404});await client.query("BEGIN");tx=true;const r=await client.query<any>("SELECT coins,gems,owned_avatars,owned_items FROM ludo_users WHERE id=$1 FOR UPDATE",[user.id]);const row=r.rows[0];if(!row)throw new Error("Account not found.");const coins=Number(row.coins)||0,gems=Number(row.gems)||0;const owned=item.kind==="avatar"?clean(row.owned_avatars):clean(row.owned_items);if(owned.includes(id)){await client.query("ROLLBACK");tx=false;return NextResponse.json({error:"You already own this item."},{status:409});}if(gems<item.price){await client.query("ROLLBACK");tx=false;return NextResponse.json({error:"Not enough gems."},{status:400});}const nextGems=gems-item.price;await setShopWalletContext(client,user.id,`Shop purchase: ${item.name}`,req);if(item.kind==="avatar")await client.query("UPDATE ludo_users SET gems=$1,owned_avatars=owned_avatars || jsonb_build_array($2) WHERE id=$3",[nextGems,id,user.id]);else await client.query("UPDATE ludo_users SET gems=$1,owned_items=owned_items || jsonb_build_array($2) WHERE id=$3",[nextGems,id,user.id]);await client.query("INSERT INTO ludo_admin_ledger(user_id,currency,amount,balance_before,balance_after,reason,source) VALUES($1,'gems',$2,$3,$4,$5,'shop')",[user.id,-item.price,gems,nextGems,`Purchased ${item.name}`]);await client.query("UPDATE ludo_admin_wallets SET revenue_gems=revenue_gems+$1,updated_at=NOW() WHERE id='platform'",[item.price]);await client.query("INSERT INTO ludo_admin_wallet_ledger(wallet_to,currency,amount,reason) VALUES('revenue','gems',$1,$2)",[item.price,`Shop: ${item.name}`]);await client.query("COMMIT");tx=false;return NextResponse.json({ok:true,coins,gems:nextGems,item});}catch(e){if(tx)await client.query("ROLLBACK").catch(()=>{});console.error(e);return NextResponse.json({error:"Unable to complete purchase."},{status:500});}finally{client.release();}}
