import{NextRequest,NextResponse}from"next/server";import{createHash}from"crypto";import{pool,ensureAuthSchema}from"../../auth/_db";
const COOKIE="ludo_session";const VALID_KINDS=["play_games","win_games","roll_dice","move_tokens","send_messages","join_rooms","create_rooms","roll_sixes","move_home","complete_games"];
async function admin(q:NextRequest){await ensureAuthSchema();const t=q.cookies.get(COOKIE)?.value;if(!t)return null;const h=createHash("sha256").update(t).digest("hex"),r=await pool.query<any>(`SELECT u.* FROM ludo_users u JOIN ludo_sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[h]),u=r.rows[0];if(!u||u.is_guest||u.is_banned)return null;const allowed=(process.env.ADMIN_EMAILS||process.env.ADMIN_EMAIL||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);return u.email&&allowed.includes(u.email.toLowerCase())?u:null}
async function setup(){await ensureAuthSchema();await pool.query(`CREATE TABLE IF NOT EXISTS ludo_mission_definitions(id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',target INTEGER NOT NULL DEFAULT 1,reward_coins INTEGER NOT NULL DEFAULT 0,reward_gems INTEGER NOT NULL DEFAULT 0,kind TEXT NOT NULL DEFAULT 'play_games',admin_created BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,scheduled_date DATE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE ludo_mission_definitions ADD COLUMN IF NOT EXISTS scheduled_date DATE;ALTER TABLE ludo_mission_definitions ADD COLUMN IF NOT EXISTS admin_created BOOLEAN NOT NULL DEFAULT FALSE;ALTER TABLE ludo_mission_definitions ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;CREATE TABLE IF NOT EXISTS ludo_daily_mission_settings(mission_day DATE PRIMARY KEY,bonus_coins INTEGER NOT NULL DEFAULT 5000,bonus_gems INTEGER NOT NULL DEFAULT 50,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`)}
const cleanDate=(value:any)=>{const s=String(value||"");return/^\d{4}-\d{2}-\d{2}$/.test(s)?s:new Date().toISOString().slice(0,10)};
export async function GET(q:NextRequest){try{await setup();if(!await admin(q))return NextResponse.json({error:"Admin access required."},{status:403});const r=await pool.query(`SELECT * FROM ludo_mission_definitions ORDER BY scheduled_date DESC NULLS LAST,admin_created DESC,created_at DESC`),s=await pool.query(`SELECT * FROM ludo_daily_mission_settings ORDER BY mission_day DESC LIMIT 30`);return NextResponse.json({missions:r.rows,validKinds:VALID_KINDS,bonusSettings:s.rows,defaultBonus:{coins:5000,gems:50}})}catch(e){console.error("daily mission admin",e);return NextResponse.json({error:"Mission admin unavailable."},{status:500})}}
export async function POST(q:NextRequest){try{await setup();if(!await admin(q))return NextResponse.json({error:"Admin access required."},{status:403});const b=await q.json(),action=String(b.action||"");
if(action==="create"||action==="edit"){const id=String(b.id||`admin-${Date.now()}`).toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,64),title=String(b.title||"").trim().slice(0,100),description=String(b.description||"").trim().slice(0,300),target=Math.max(1,Math.trunc(Number(b.target||1))),coins=Math.max(0,Math.trunc(Number(b.rewardCoins??b.reward_coins??0))),gems=Math.max(0,Math.trunc(Number(b.rewardGems??b.reward_gems??0))),kind=String(b.kind||"play_games").trim(),date=cleanDate(b.scheduledDate||b.missionDay);if(!title)return NextResponse.json({error:"Mission title is required."},{status:400});if(!VALID_KINDS.includes(kind))return NextResponse.json({error:"Invalid mission type."},{status:400});if(action==="edit"){const r=await pool.query(`UPDATE ludo_mission_definitions SET title=$1,description=$2,target=$3,reward_coins=$4,reward_gems=$5,kind=$6,scheduled_date=$7,active=$8 WHERE id=$9 AND admin_created=TRUE`,[title,description,target,coins,gems,kind,date,b.active!==false,id]);if(!r.rowCount)return NextResponse.json({error:"Admin mission not found."},{status:404});return NextResponse.json({ok:true,id})}await pool.query(`INSERT INTO ludo_mission_definitions(id,title,description,target,reward_coins,reward_gems,kind,admin_created,active,scheduled_date) VALUES($1,$2,$3,$4,$5,$6,$7,TRUE,$8,$9)`,[id,title,description,target,coins,gems,kind,b.active!==false,date]);return NextResponse.json({ok:true,id})}
if(action==="toggle"||action==="set_active"){await pool.query(`UPDATE ludo_mission_definitions SET active=$1 WHERE id=$2`,[action==="toggle"?undefined:Boolean(b.active),String(b.id||"")]);if(action==="toggle"){const r=await pool.query(`SELECT active FROM ludo_mission_definitions WHERE id=$1`,[String(b.id||"")]);await pool.query(`UPDATE ludo_mission_definitions SET active=$1 WHERE id=$2`,[!Boolean(r.rows[0]?.active),String(b.id||"")])}return NextResponse.json({ok:true})}
if(action==="delete"){await pool.query(`DELETE FROM ludo_mission_definitions WHERE id=$1 AND admin_created=TRUE`,[String(b.id||"")]);return NextResponse.json({ok:true})}
if(action==="set_bonus"){const day=cleanDate(b.missionDay),coins=Math.max(0,Math.trunc(Number(b.bonusCoins||0))),gems=Math.max(0,Math.trunc(Number(b.bonusGems||0)));await pool.query(`INSERT INTO ludo_daily_mission_settings(mission_day,bonus_coins,bonus_gems,updated_at) VALUES($1,$2,$3,NOW()) ON CONFLICT(mission_day) DO UPDATE SET bonus_coins=EXCLUDED.bonus_coins,bonus_gems=EXCLUDED.bonus_gems,updated_at=NOW()`,[day,coins,gems]);return NextResponse.json({ok:true,missionDay:day,bonusCoins:coins,bonusGems:gems})}
if(action==="reset_bonus"){await pool.query(`DELETE FROM ludo_daily_mission_settings WHERE mission_day=$1`,[cleanDate(b.missionDay)]);return NextResponse.json({ok:true})}
return NextResponse.json({error:"Unknown mission admin action."},{status:400})}catch(e){console.error("daily mission admin action",e);return NextResponse.json({error:"Mission admin action failed."},{status:500})}}
