"use client";
import { useEffect, useMemo, useState } from "react";
import CanonicalLudoBoard, { type BoardThemeId, type DemoToken } from "../_components/CanonicalLudoBoard";
import { BOARD_PALETTES } from "../_components/LudoBoard";
import DemoDice from "../_components/DemoDice";
import { canMove, hasLegalMove, applyMove, winner as getWinner, nextProgress, FINISH_PROGRESS, HUMAN_COLORS, BOT_COLORS, type DiceValue } from "../../lib/ludoEngine";

type Color="green"|"yellow"|"red"|"blue";
type Face=DiceValue;
type SavedState={theme:BoardThemeId;roll:Face;turn:number;notice:string;tokens:DemoToken[];pendingRoll:Face|null;sixStreak:number;matchOver:boolean;winner:string|null;winnerIsHuman:boolean};
const COLORS:Color[]=["green","yellow","red","blue"];
const initialTokens=():DemoToken[]=>COLORS.flatMap(color=>Array.from({length:4},(_,id)=>({color,id,position:0,state:"yard" as const})));
const emitAudio=(kind:"dice"|"move"|"capture"|"safe"|"home"|"win")=>{if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("ludo-audio",{detail:kind}))};
type Props={themeOverride?:BoardThemeId};
export default function GameBoardContent({themeOverride}:Props){
 const [theme,setTheme]=useState<BoardThemeId>(themeOverride||"classic"),[roll,setRoll]=useState<Face>(1),[turn,setTurn]=useState(0),[notice,setNotice]=useState("Your turn — roll the dice."),[botThinking,setBotThinking]=useState(false),[botRolling,setBotRolling]=useState(false),[tokens,setTokens]=useState<DemoToken[]>(initialTokens),[pendingRoll,setPendingRoll]=useState<Face|null>(null),[animating,setAnimating]=useState(false),[sixStreak,setSixStreak]=useState(0),[restored,setRestored]=useState(false),[matchOver,setMatchOver]=useState(false),[winner,setWinner]=useState<string|null>(null),[winnerIsHuman,setWinnerIsHuman]=useState(false);
 const SAVE_KEY="ludo-canonical-bot-v2";const p=BOARD_PALETTES[theme]||BOARD_PALETTES.classic;const currentColors=turn===0?HUMAN_COLORS:BOT_COLORS;
 useEffect(()=>{if(themeOverride)setTheme(themeOverride)},[themeOverride]);
 useEffect(()=>{try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const s=JSON.parse(raw) as SavedState;if(Array.isArray(s.tokens)){setTheme(s.theme||themeOverride||"classic");setRoll(s.roll||1);setTurn(s.turn||0);setTokens(s.tokens);setPendingRoll(s.pendingRoll??null);setSixStreak(s.sixStreak||0);setMatchOver(!!s.matchOver);setWinner(s.winner??null);setWinnerIsHuman(!!s.winnerIsHuman);setNotice(s.notice||"Match restored — continue playing.")}}}catch{}finally{setRestored(true)}},[]);
 useEffect(()=>{if(!restored)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify({theme,roll,turn,notice,tokens,pendingRoll,sixStreak,matchOver,winner,winnerIsHuman}))}catch{}},[restored,theme,roll,turn,notice,tokens,pendingRoll,sixStreak,matchOver,winner,winnerIsHuman]);
 const finishTurn=(rolled:Face,actor:string)=>{if(matchOver)return;if(rolled===6){const streak=sixStreak+1;if(streak>=3){setSixStreak(0);setPendingRoll(null);setTurn(turn===0?1:0);setNotice(`${actor} rolled three 6s. ${turn===0?"Bot":"Your"} turn.`);return}setSixStreak(streak);setPendingRoll(null);setNotice(`${actor} rolled 6 — bonus roll.`);return}setSixStreak(0);setPendingRoll(null);setTurn(turn===0?1:0);setNotice(`${actor} rolled ${rolled}. ${turn===0?"Bot":"Your"} turn.`)};
 const declareWinner=(isHuman:boolean)=>{setMatchOver(true);setWinner(isHuman?"You":"Bot");setWinnerIsHuman(isHuman);setBotThinking(false);setBotRolling(false);setPendingRoll(null);setAnimating(false);setNotice(isHuman?"You won the match!":"The Bot won the match.");emitAudio("win")};
 const moveToken=(token:DemoToken,dice:Face,actor:string)=>{if(animating||matchOver||!currentColors.includes(token.color)||!canMove(tokens,token,dice))return;const target=nextProgress(token.position,dice);if(target===null)return;setAnimating(true);setPendingRoll(null);let step=token.position;const timer=window.setInterval(()=>{if(step>=target){window.clearInterval(timer);const result=applyMove(tokens,token,dice);if(!result){setAnimating(false);return}const captured=result.some(t=>t.state==="yard"&&tokens.find(x=>x.color===t.color&&x.id===t.id)?.state!=="yard");setTokens(result as DemoToken[]);const w=getWinner(result as DemoToken[]);if(w){declareWinner(w==="human");return}if(captured)emitAudio("capture");else if(target===FINISH_PROGRESS)emitAudio("home");else emitAudio("move");setAnimating(false);finishTurn(dice,actor);return}step+=1;setTokens(prev=>prev.map(t=>t.color===token.color&&t.id===token.id?{...t,position:step,state:step>=FINISH_PROGRESS?"finished":step>51?"home":"track"}:t));emitAudio("move")},220)};
 const chooseToken=(color:Color,id:number)=>{if(pendingRoll===null||turn!==0||animating||matchOver)return;const token=tokens.find(t=>t.color===color&&t.id===id);if(token)moveToken(token,pendingRoll,"You")};
 const performBotMove=(dice:Face)=>{if(matchOver)return;const candidates=tokens.filter(t=>BOT_COLORS.includes(t.color)&&canMove(tokens,t,dice));if(!candidates.length){finishTurn(dice,"Bot");return}const candidate=candidates.find(t=>t.position===0)||candidates.find(t=>nextProgress(t.position,dice)===FINISH_PROGRESS)||candidates[0];moveToken(candidate,dice,"Bot")};
 useEffect(()=>{if(!restored||turn!==1||animating||pendingRoll!==null||matchOver)return;let cancelled=false;let rollTimer:number|undefined;setBotThinking(true);setBotRolling(false);setNotice("Bot's turn — preparing roll…");const prepare=window.setTimeout(()=>{if(cancelled)return;setBotRolling(true);setNotice("Bot is rolling…");rollTimer=window.setTimeout(()=>{if(cancelled)return;const n=(Math.floor(Math.random()*6)+1) as Face;setRoll(n);setBotRolling(false);setBotThinking(false);emitAudio("dice");setPendingRoll(n);setNotice(`Bot rolled ${n}.`);window.setTimeout(()=>{if(!cancelled)performBotMove(n)},650)},850)},650);return()=>{cancelled=true;window.clearTimeout(prepare);if(rollTimer!==undefined)window.clearTimeout(rollTimer)}},[restored,turn,animating,pendingRoll,matchOver,tokens]);
 const handleHumanRoll=(n:Face)=>{if(botThinking||animating||pendingRoll!==null||turn!==0||matchOver)return;setRoll(n);emitAudio("dice");if(!hasLegalMove(tokens,HUMAN_COLORS,n)){setNotice(`You rolled ${n}. No legal move.`);finishTurn(n,"You");return}setPendingRoll(n);setNotice(`You rolled ${n}. Select a legal token to move.`)};
 const playAgain=()=>{localStorage.removeItem(SAVE_KEY);setTokens(initialTokens());setRoll(1);setTurn(0);setNotice("Your turn — roll the dice.");setPendingRoll(null);setSixStreak(0);setBotThinking(false);setBotRolling(false);setAnimating(false);setMatchOver(false);setWinner(null);setWinnerIsHuman(false)};const quit=()=>{localStorage.removeItem(SAVE_KEY);window.location.href="/"};
 const legalTokenKeys=useMemo(()=>pendingRoll===null?[]:tokens.filter(t=>currentColors.includes(t.color)&&canMove(tokens,t,pendingRoll)).map(t=>`${t.color}-${t.id}`),[tokens,pendingRoll,currentColors]);const diceDisabled=botThinking||animating||pendingRoll!==null||turn!==0||matchOver;
 return <><section style={boardWrap}><div style={boardShell}><CanonicalLudoBoard theme={theme} demoTokens={tokens} onTokenClick={chooseToken} legalTokenKeys={legalTokenKeys}/></div></section><section style={{...controls,borderColor:p.accent,background:"rgba(3,14,31,.78)",boxShadow:p.shadow}} aria-label="Dice and turn controls"><div style={{minWidth:0}}><div style={{...turnLabel,color:p.accent}}>{turn===0?"YOUR TURN":"BOT TURN"}</div><b style={{fontSize:20}}>Roll the dice</b><p style={{margin:"4px 0",color:"#9fb5d8"}}>{notice}</p></div><DemoDice value={roll} onRoll={handleHumanRoll} disabled={diceDisabled} botRolling={botRolling}/></section>{matchOver&&<div style={overlay}><div style={{...resultCard,borderColor:p.accent,boxShadow:`0 0 45px ${p.accent}`}}><div style={{fontSize:54,marginBottom:8}}>{winnerIsHuman?"🏆":"🤖"}</div><h2 style={{margin:"0 0 8px",fontSize:30}}>{winnerIsHuman?"YOU WIN!":"YOU LOSE"}</h2><p style={{margin:"0 0 22px",color:"#b9c9e5"}}>{winner}</p><div style={{display:"flex",gap:12}}><button onClick={playAgain} style={{...actionButton,background:p.accent}}>PLAY AGAIN</button><button onClick={quit} style={secondaryButton}>QUIT</button></div></div></div>}</>;
}
const boardWrap:React.CSSProperties={display:"grid",placeItems:"center",marginTop:0};const boardShell:React.CSSProperties={width:"100%",maxWidth:620,position:"relative"};const controls:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,margin:"14px auto 0",width:"100%",maxWidth:620,padding:16,borderRadius:18,border:"1px solid",boxSizing:"border-box",backdropFilter:"blur(12px)"};const turnLabel:React.CSSProperties={fontSize:10,letterSpacing:2,fontWeight:900};const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:9999,display:"grid",placeItems:"center",padding:20,background:"rgba(2,7,18,.72)",backdropFilter:"blur(7px)"};const resultCard:React.CSSProperties={width:"min(92vw,420px)",padding:"34px 26px",borderRadius:26,border:"2px solid",background:"rgba(7,17,35,.96)",textAlign:"center"};const actionButton:React.CSSProperties={border:0,borderRadius:12,padding:"13px 18px",fontWeight:900,color:"#07111f",cursor:"pointer",flex:1};const secondaryButton:React.CSSProperties={border:"1px solid rgba(255,255,255,.25)",borderRadius:12,padding:"13px 18px",fontWeight:900,color:"#fff",background:"transparent",cursor:"pointer",flex:1};
