"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { io, type Socket } from "socket.io-client";
import LudoBoard, { type BoardThemeId, type DemoToken } from "../_components/LudoBoardMultiplayer";
import DemoDice from "../_components/DemoDice";
import { canMove, FINISH_PROGRESS, type DiceValue, nextProgress } from "../../lib/ludoEngine";
import { playerColorsForSeats } from "../../lib/ludoRules";

type Color = "red" | "yellow" | "green" | "blue";
type Player = { playerId:string; name:string; seat:number; level?:number; avatar?:string; colors?:Color[] };
type TokenMap = Record<string,Record<string,{position:number}>>;
type GameState = { status:string; currentPlayerId:string|null; dice:DiceValue|null; pendingMove:DiceValue|null; sixStreak:number; players:Player[]; tokens:TokenMap; winnerId?:string|null; stateRevision?:number };

const COLORS:Color[]=["red","yellow","green","blue"];
const initialTokens=():DemoToken[]=>COLORS.flatMap(color=>Array.from({length:4},(_,id)=>({color,id,position:0,state:"yard" as const})));
const normalizeTokens=(serverTokens:TokenMap):DemoToken[]=>COLORS.flatMap(color=>Array.from({length:4},(_,id)=>{const raw=serverTokens?.[color]?.[String(id)]?.position;const position=typeof raw==="number"&&Number.isFinite(raw)?raw:0;return {color,id,position,state:position===0?"yard" as const:position===FINISH?"finished" as const:position>51?"home" as const:"track" as const};}));

function PlayerAvatar({src,fallback}:{src?:string;fallback:string}){const image=src&&(src.startsWith("http")||src.startsWith("/")||src.startsWith("data:"));return image?<img src={src} alt="Player avatar" className="mp-avatar-img"/>:<span>{src||fallback}</span>}

export default function MultiplayerGameCanonical(){
 const [theme]=useState<BoardThemeId>("classic"); const [socket,setSocket]=useState<Socket|null>(null); const [me,setMe]=useState(""); const [avatar,setAvatar]=useState(""); const [game,setGame]=useState<GameState|null>(null); const [tokens,setTokens]=useState<DemoToken[]>(initialTokens); const [roll,setRoll]=useState<DiceValue>(6); const [pending,setPending]=useState<DiceValue|null>(null); const [animating,setAnimating]=useState(false); const [roomCode,setRoomCode]=useState("W100NB");
 const revision=useRef(-1);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("room"))setRoomCode(p.get("room")!);},[]);
 const players=useMemo(()=>game?.players?.length?game.players:[{playerId:me||"1",name:"Bambiii",level:24,avatar:avatar||"👑",seat:0},{playerId:"2",name:"Adaugo",level:18,avatar:"🎮",seat:1}], [game?.players,me,avatar]);
 const mine=players.find(p=>String(p.playerId)===String(me))||players[0]; const opponent=players.find(p=>String(p.playerId)!==String(mine.playerId))||players[1];
 const myColors=useMemo(()=>mine?.colors?.length?mine.colors:playerColorsForSeats(players.length===2?2:4,mine?.seat??0) as Color[],[mine,players.length]);
 const myTurn=game?game.currentPlayerId===me:true;
 const legal=useMemo(()=>pending===null||!myTurn?[]:tokens.filter(t=>myColors.includes(t.color)&&canMove(tokens,t,pending)).map(t=>`${t.color}:${t.id}`),[pending,myTurn,tokens,myColors]);
 const apply=useCallback((next:GameState)=>{const r=Number(next.stateRevision??-1);if(r>=0&&revision.current>=0&&r<revision.current)return false;if(r>=0)revision.current=r;setGame(next);setTokens(normalizeTokens(next.tokens||{}));return true;},[]);
 useEffect(()=>{let mounted=true;let s:Socket|null=null;(async()=>{let id="",name="Bambiii",av="";try{const r=await fetch("/api/auth",{cache:"no-store"});const d=await r.json();id=String(d?.user?.id||"");name=String(d?.user?.username||"Bambiii");av=String(d?.user?.avatar||d?.user?.image||"")}catch{}if(!mounted)return;if(id)setMe(id);if(av)setAvatar(av);const p=new URLSearchParams(window.location.search);const room=p.get("room")||roomCode;s=io(window.location.origin,{transports:["websocket","polling"],reconnection:true});setSocket(s);s.on("connect",()=>{if(room&&id)s?.emit("join-room",{roomCode:room,name,avatar:av,roomSize:Number(p.get("size")||2),playerId:id})});s.on("roster",(m:Player[])=>setGame(g=>g?{...g,players:m}:g));s.on("game-state",(n:GameState)=>{if(mounted&&apply(n)){if(n.dice!==null)setRoll(n.dice);setPending(n.currentPlayerId===id?n.pendingMove:null)}})})();return()=>{mounted=false;s?.disconnect()}},[apply,roomCode]);
 const choose=useCallback((color:Color,id:number)=>{if(!socket||!game||!myTurn||pending===null||animating)return;const t=tokens.find(x=>x.color===color&&x.id===id);if(!t||!myColors.includes(color)||!canMove(tokens,t,pending))return;const target=nextProgress(t.position,pending);if(target===null)return;setPending(null);setAnimating(true);socket.emit("game-move",{tokenId:`${color}:${id}`,to:target});setTimeout(()=>setAnimating(false),500)},[socket,game,myTurn,pending,animating,tokens,myColors]);
 const rollDice=useCallback(()=>{if(!socket||!game){setRoll((Math.floor(Math.random()*6)+1)as DiceValue);return}if(myTurn&&pending===null&&!animating)socket.emit("game-roll")},[socket,game,myTurn,pending,animating]);
 return <main className="mp-root"><header className="mp-header" aria-label="Multiplayer players"><div className="mp-player"><div className="mp-avatar"><PlayerAvatar src={mine?.avatar} fallback="👑"/></div><div><strong>{mine?.name||"Player"}</strong><span>★ {mine?.level||24}</span><small>● YOUR TURN</small></div></div><div className="mp-player mp-opponent"><div><strong>{opponent?.name||"Opponent"}</strong><span>★ {opponent?.level||18}</span><small>● IN MATCH</small></div><div className="mp-avatar"><PlayerAvatar src={opponent?.avatar} fallback="🎮"/></div></div></header><section className="mp-board"><LudoBoard theme={theme} demoTokens={tokens} onTokenClick={choose} legalTokenKeys={legal} animateUpdates finishSound/></section><section className="mp-controls"><div>Room ID: {roomCode}</div><button type="button" onClick={rollDice}>🎲 Roll {roll}</button></section><style jsx global>{`html,body{margin:0!important;padding:0!important;background:#000!important}.mp-root{min-height:100vh;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:#000;position:relative;z-index:0}.mp-header{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px;width:100%;min-height:92px;padding:12px 14px;box-sizing:border-box;background:#101010;border-bottom:1px solid rgba(255,255,255,.12);position:relative!important;z-index:1000!important;visibility:visible!important;opacity:1!important}.mp-player{display:flex;align-items:center;gap:10px;min-width:0;color:#fff}.mp-opponent{justify-content:flex-end;text-align:right}.mp-avatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#222;overflow:hidden;flex:0 0 auto;font-size:28px}.mp-avatar-img{width:100%;height:100%;object-fit:cover}.mp-player strong,.mp-player span,.mp-player small{display:block}.mp-player strong{font-size:16px}.mp-player span{font-size:12px;opacity:.8;margin-top:3px}.mp-player small{font-size:10px;margin-top:5px}.mp-board{min-height:0;position:relative;z-index:1;display:grid;place-items:center}.mp-controls{position:relative;z-index:2;min-height:64px;display:flex;align-items:center;justify-content:space-between;padding:10px 14px;color:#fff;background:#111}.mp-controls button{padding:10px 16px;border:0;border-radius:10px;cursor:pointer}@media(max-width:520px){.mp-header{min-height:76px;padding:8px;gap:6px}.mp-avatar{width:46px;height:46px}.mp-player strong{font-size:13px}.mp-player span{font-size:10px}.mp-player small{font-size:8px}}`}</style></main>;
}