"use client";

import MultiplayerGameCanonical from "./MultiplayerGameCanonical";

export default function MultiplayerGame() {
  return <div className="premium-multiplayer-route"><MultiplayerGameCanonical/><style jsx global>{`
    html,body{margin:0!important;background:#050301!important;overflow:hidden!important}
    .premium-multiplayer-route{width:100%;height:100dvh;background:#050301!important;color:#fff!important}
    .premium-multiplayer-route .lux-game{width:100%!important;height:100dvh!important;min-height:100dvh!important;background:radial-gradient(circle at 50% -8%,rgba(222,177,58,.12),transparent 30%),linear-gradient(180deg,#080604 0%,#020202 100%)!important;overflow:hidden!important}
    .premium-multiplayer-route .lux-shell{width:min(100%,760px)!important;height:100dvh!important;margin:0 auto!important;padding:10px 10px max(10px,env(safe-area-inset-bottom))!important;box-sizing:border-box!important;display:flex!important;flex-direction:column!important;gap:10px!important;overflow-y:auto!important;overflow-x:hidden!important;scrollbar-width:none!important}
    .premium-multiplayer-route .lux-shell::-webkit-scrollbar{display:none!important}
    .premium-multiplayer-route .lux-header{position:relative!important;flex:0 0 100px!important;min-height:100px!important;width:100%!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;padding:7px 8px!important;box-sizing:border-box!important;border:1px solid rgba(224,184,76,.72)!important;border-radius:28px!important;background:linear-gradient(145deg,rgba(27,20,9,.97),rgba(5,5,4,.99))!important;box-shadow:0 8px 28px rgba(0,0,0,.55),inset 0 1px rgba(255,232,151,.13)!important;overflow:hidden!important}
    .premium-multiplayer-route .lux-player-strip{display:flex!important;align-items:center!important;gap:7px!important;width:calc(100% - 125px)!important;height:100%!important;overflow:hidden!important}
    .premium-multiplayer-route .lux-player{position:relative!important;flex:0 1 50%!important;width:50%!important;min-width:0!important;height:82px!important;padding:6px 8px!important;display:flex!important;align-items:center!important;gap:8px!important;box-sizing:border-box!important;border:1px solid rgba(211,166,55,.55)!important;border-radius:22px!important;background:linear-gradient(145deg,#19140b,#080806)!important;color:#fff!important;box-shadow:inset 0 1px rgba(255,235,164,.08),0 6px 16px rgba(0,0,0,.3)!important;overflow:hidden!important}
    .premium-multiplayer-route .lux-player.active{border-color:#f1d36c!important;box-shadow:0 0 18px rgba(225,184,69,.23),inset 0 0 18px rgba(225,184,69,.06)!important}
    .premium-multiplayer-route .lux-avatar{position:relative!important;flex:0 0 52px!important;width:52px!important;height:52px!important;display:grid!important;place-items:center!important}
    .premium-multiplayer-route .lux-online{position:absolute!important;right:0!important;bottom:2px!important;width:11px!important;height:11px!important;border-radius:50%!important;background:#20d878!important;border:2px solid #111!important;box-shadow:0 0 10px rgba(32,216,120,.7)!important}
    .premium-multiplayer-route .lux-player-copy{min-width:0!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:center!important;gap:4px!important}
    .premium-multiplayer-route .lux-player-copy b{display:block!important;max-width:100%!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;font-size:15px!important;font-weight:900!important}
    .premium-multiplayer-route .lux-player-copy small{font-size:8px!important;letter-spacing:1.7px!important;font-weight:900!important;color:#a79b7c!important}
    .premium-multiplayer-route .lux-player.active .lux-player-copy small{color:#f2d264!important}
    .premium-multiplayer-route .lux-crown{display:none!important}
    .premium-multiplayer-route .lux-logo{position:absolute!important;left:50%!important;top:50%!important;transform:translate(-50%,-50%)!important;z-index:4!important;width:82px!important;height:82px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;line-height:.78!important;pointer-events:none!important;text-align:center!important;text-shadow:0 3px 12px #000,0 0 14px rgba(241,194,60,.55)!important}
    .premium-multiplayer-route .lux-logo span{font-size:22px!important;color:#f5d56e!important}.premium-multiplayer-route .lux-logo strong{font-family:Georgia,serif!important;font-size:20px!important;letter-spacing:1px!important;color:#f4d36b!important}.premium-multiplayer-route .lux-logo small{font-size:12px!important;letter-spacing:3px!important;color:#e7bd43!important;font-weight:1000!important}
    .premium-multiplayer-route .lux-menu{position:relative!important;z-index:8!important;flex:0 0 50px!important;width:50px!important;height:54px!important;display:grid!important;place-items:center!important;border:1px solid rgba(211,166,55,.75)!important;border-radius:17px!important;background:linear-gradient(145deg,#191309,#070706)!important;color:#f3c943!important;font-size:27px!important;line-height:1!important}
    .premium-multiplayer-route .lux-shell>section:first-of-type{flex:0 0 auto!important;width:100%!important;min-height:0!important;margin:0!important;padding:0!important;display:flex!important;justify-content:center!important;align-items:flex-start!important;overflow:visible!important}
    .premium-multiplayer-route .lux-shell>section:first-of-type>div{width:min(calc(100vw - 20px),700px)!important;max-width:100%!important;aspect-ratio:1/1!important;height:auto!important;margin:0 auto!important}
    .premium-multiplayer-route .lux-shell>section:first-of-type canvas,.premium-multiplayer-route .lux-shell>section:first-of-type svg{max-width:100%!important}
    .premium-multiplayer-route .lux-shell>section:nth-of-type(2){position:relative!important;flex:0 0 auto!important;width:100%!important;min-height:230px!important;margin:0!important;padding:14px!important;box-sizing:border-box!important;border:1px solid rgba(224,184,76,.66)!important;border-radius:26px!important;background:linear-gradient(145deg,rgba(25,19,8,.97),rgba(5,5,4,.99))!important;box-shadow:0 -4px 26px rgba(0,0,0,.35),inset 0 1px rgba(255,231,148,.1)!important;overflow:visible!important}
    .premium-multiplayer-route [class*="voice-notice"],.premium-multiplayer-route [class*="voiceNotice"]{display:none!important}
    @media(max-width:700px){.premium-multiplayer-route .lux-shell{padding:7px 8px max(9px,env(safe-area-inset-bottom))!important;gap:8px!important}.premium-multiplayer-route .lux-header{flex-basis:88px!important;min-height:88px!important;border-radius:24px!important;padding:5px 7px!important}.premium-multiplayer-route .lux-player-strip{width:calc(100% - 105px)!important;gap:6px!important}.premium-multiplayer-route .lux-player{height:74px!important;border-radius:19px!important;padding:5px 6px!important;gap:6px!important}.premium-multiplayer-route .lux-avatar{flex-basis:46px!important;width:46px!important;height:46px!important}.premium-multiplayer-route .lux-player-copy b{font-size:13px!important}.premium-multiplayer-route .lux-player-copy small{font-size:7px!important;letter-spacing:1.3px!important}.premium-multiplayer-route .lux-logo{width:70px!important;height:70px!important}.premium-multiplayer-route .lux-logo span{font-size:18px!important}.premium-multiplayer-route .lux-logo strong{font-size:17px!important}.premium-multiplayer-route .lux-logo small{font-size:9px!important;letter-spacing:2px!important}.premium-multiplayer-route .lux-menu{flex-basis:44px!important;width:44px!important;height:46px!important;border-radius:14px!important;font-size:23px!important}.premium-multiplayer-route .lux-shell>section:first-of-type>div{width:calc(100vw - 16px)!important}.premium-multiplayer-route .lux-shell>section:nth-of-type(2){min-height:205px!important;padding:10px!important;border-radius:22px!important}}
    @media(max-width:420px){.premium-multiplayer-route .lux-shell{padding:5px 6px max(8px,env(safe-area-inset-bottom))!important;gap:6px!important}.premium-multiplayer-route .lux-header{flex-basis:78px!important;min-height:78px!important;border-radius:21px!important}.premium-multiplayer-route .lux-player{height:64px!important;border-radius:17px!important}.premium-multiplayer-route .lux-avatar{flex-basis:40px!important;width:40px!important;height:40px!important}.premium-multiplayer-route .lux-player-copy b{font-size:11px!important}.premium-multiplayer-route .lux-player-copy small{font-size:6px!important}.premium-multiplayer-route .lux-logo{width:60px!important;height:60px!important}.premium-multiplayer-route .lux-logo strong{font-size:14px!important}.premium-multiplayer-route .lux-logo span{font-size:15px!important}.premium-multiplayer-route .lux-logo small{font-size:8px!important}.premium-multiplayer-route .lux-menu{flex-basis:39px!important;width:39px!important;height:41px!important;font-size:21px!important}.premium-multiplayer-route .lux-shell>section:first-of-type>div{width:calc(100vw - 12px)!important}.premium-multiplayer-route .lux-shell>section:nth-of-type(2){min-height:190px!important;border-radius:20px!important;padding:8px!important}}
  `}</style></div>;
}
