"use client";
import { useEffect, useMemo, useState } from "react";
import { io, type Socket } from "socket.io-client";
import AppFrame from "../_components/AppFrame";
import LudoBoard, { BOARD_NAMES, BOARD_PALETTES, type BoardThemeId, type DemoToken } from "../_components/LudoBoardGame";
import DemoDice from "../_components/DemoDice";

type Color = "red"|"yellow"|"green"|"blue";
type Face = 1|2|3|4|5|6;
type ServerPlayer = { playerId:string; name:string; seat:number };
type GameState = { status:string; currentPlayerId:string|null; dice:Face|null; pendingMove:Face|null; sixStreak:number; players:ServerPlayer[]; tokens:Record<string,Record<string,{position:number}>> };
const COLORS:Color[]=["red","yellow","green","blue"];
const STEP_COUNT=56;
const initialTokens=():DemoToken[]=>COLORS.flatMap(color=>Array.from({length:4},(_,id)=>({color,id,position:0,state:"yard" as const})));
const playerColors=(players:ServerPlayer[], pid:string):Color[]=>{const seat=players.find(p=>p.playerId===pid)?.seat??0;return players.length===2?(seat===0?["red","yellow"]:["green","blue"]):[COLORS[seat]||"red"]};

export default function MultiplayerGame(){
 const [theme,setTheme]=useState<BoardThemeId>("classic");const [socket,setSocket]=useState<Socket|null>(null);const [me,setMe]=useState("");const [room,setRoom]=useState("");const [game,setGame]=useState<GameState|null>(null);const [tokens,setTokens]=useState<DemoToken[]>(initialTokens);const [roll,setRoll]=useState<Face>(1);const [pending,setPending]=useState<Face|null>(null);const [remoteRolling,setRemoteRolling]=useState(false);const [notice,setNotice]=useState("Connecting to the match…");const [animating,setAnimating]=useState(false);
 const players=game?.players||[];const myColors=useMemo(()=>playerColors(players,me),[players,me]);const currentId=game?.currentPlayerId||"";const myTurn=currentId===me;
 useEffect(()=>{let alive=true;const params=new URLSearchParams(location.search);const r=params.get("room")||"";setRoom(r);(async()=>{let pid="";try{const a=await fetch("/api/auth",{cache:"no-store"}).then(x=>x.json());pid=String(a?.user?.id||"")}catch{}if(!alive)return;setMe(pid);const s=io(location.origin,{transports:["websocket","polling"]});setSocket(s);s.on("connect",()=>setNotice("Connected. Waiting for the match state…"));s.on("game-state",(g:GameState)=>{if(!alive)return;setGame(g);setPending(g.currentPlayerId===pid?g.pendingMove:null);setRoll(g.dice||1);setNotice(g.currentPlayerId===pid?(g.pendingMove?`You rolled ${g.pendingMove}. Select a legal token to move.`:"Your turn — roll the dice."):`${g.players.find(p=>p.playerId===g.currentPlayerId)?.name||"Player"}'s turn.`)});s.on("game-dice",({playerId,value}:{playerId:string;value:Face})=>{setRoll(value);if(playerId===pid){setPending(value);setNotice(`You rolled ${value}. Select a legal token to move.`)}else{setRemoteRolling(true);setNotice(`${players.find(p=>p.playerId===playerId)?.name||"Player"} rolled.`);window.setTimeout(()=>setRemoteRolling(false),950)}});s.on("game-moved",({playerId,tokenId,to}:{playerId:string;tokenId:string;to:number})=>{const [colorRaw,idRaw]=String(tokenId).split(":");const color=colorRaw as Color;const tokenIdNum=Number(idRaw);setAnimating(true);setTokens(prev=>prev.map(t=>t.color===color&&t.id===tokenIdNum?{...t,position:to,state:to===STEP_COUNT?"finished":to>51?"home":to===0?"yard":"track"}:t));window.setTimeout(()=>setAnimating(false),350);setPending(null)});s.on("disconnect",()=>setNotice("Connection lost. Reconnecting…"));return()=>{alive=false;s.disconnect()}})();return()=>{alive=false}},[]);
 const chooseToken=(color:Color,id:number)=>{if(!socket||!game||!myTurn||pending==null||animating||!myColors.includes(color))return;const t=tokens.find(x=>x.color===color&&x.id===id);if(!t)return;const target=t.position===0?(pending===6?1:-1):t.position+pending;if(target<0||target>STEP_COUNT)return;setPending(null);socket.emit("game-move",{tokenId:`${color}:${id}`,to:target});setNotice("Move sent. Waiting for the match to update…")};
 const handleRoll=()=>{if(!socket||!game||!myTurn||pending!==null||animating)return;socket.emit("game-roll")};
 useEffect(()=>{try{const saved=localStorage.getItem("ludo-match-board");if(saved&&saved in BOARD_PALETTES)setTheme(saved as BoardThemeId)}catch{}},[]);const p=BOARD_PALETTES[theme]||BOARD_PALETTES.classic;
 return <AppFrame back="/lobby"><main style={{...page,background:p.bg,"--accent":p.accent} as React.CSSProperties}><header style={top}><div><div style={eyebrow}>LIVE MULTIPLAYER</div><h1 style={title}>{BOARD_NAMES[theme]||"Ludo Board"}</h1><p style={sub}>Shared game · synchronized turn</p></div><div style={badge}>{room?`ROOM ${room}`:"MATCH"}</div></header><div style={bar}>{players.map(pl=><span key={pl.playerId} style={{fontWeight:pl.playerId===currentId?950:700}}>{pl.playerId===currentId?"🎯 ":""}{pl.name} · {players.length===2?playerColors(players,pl.playerId).map(c=>c[0].toUpperCase()+c.slice(1)).join(" + "):playerColors(players,pl.playerId)[0]}</span>)}</div><section style={boardWrap}><div style={boardShell}><LudoBoard theme={theme} demoTokens={tokens} onTokenClick={chooseToken}/></div></section><section style={controls}><div><div style={turnLabel}>{myTurn?"YOUR TURN":"WAITING FOR OTHER PLAYER"}</div><b style={{fontSize:20}}>{notice}</b><p style={sub2}>{pending!==null?"Select one of your legal tokens.":"Only the player whose turn it is can roll."}</p></div><DemoDice value={roll} onRoll={handleRoll} disabled={!myTurn||pending!==null||animating||!game} botRolling={remoteRolling}/></section></main></AppFrame>}
const page:React.CSSProperties={width:"100%",minHeight:"calc(100vh - 40px)",padding:18,boxSizing:"border-box",borderRadius:22};const top:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,flexWrap:"wrap"};const eyebrow:React.CSSProperties={fontSize:11,letterSpacing:2,color:"var(--accent)",fontWeight:950};const title:React.CSSProperties={fontSize:"clamp(28px,6vw,42px)",margin:"5px 0",fontWeight:950};const sub:React.CSSProperties={color:"#9fb5d8",margin:0};const sub2:React.CSSProperties={color:"#9fb5d8",margin:"4px 0"};const badge:React.CSSProperties={padding:"10px 14px",borderRadius:12,background:"#071a36",border:"1px solid #284b7b",fontWeight:900};const bar:React.CSSProperties={display:"flex",gap:14,flexWrap:"wrap",marginTop:14,padding:10,borderRadius:14,background:"#f5f7fa",border:"1px solid #d8dee7",color:"#172033",fontSize:13};const boardWrap:React.CSSProperties={display:"grid",placeItems:"center",marginTop:18};const boardShell:React.CSSProperties={width:"100%",maxWidth:620,position:"relative"};const controls:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,marginTop:16,padding:16,borderRadius:18,background:"#071a36",border:"1px solid #284b7b"};const turnLabel:React.CSSProperties={fontSize:10,letterSpacing:2,color:"#60a5fa",fontWeight:900};
