"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import GameBoardContent from "./GameBoardContent";
import MultiplayerGame from "./MultiplayerGame";
import BotSessionExpiry from "./BotSessionExpiry";
import { BOARD_PALETTES, type BoardThemeId } from "../_components/LudoBoardGame";

type SkinHeader={icon:string;title:string;subtitle:string;eyebrow:string};
const SKIN_HEADERS:Record<string,SkinHeader>={classic:{icon:"👑",eyebrow:"TIMELESS CLASSIC",title:"CLASSIC LUDO",subtitle:"The original board • Pure Ludo tradition"},golden:{icon:"🏆",eyebrow:"ROYAL COLLECTION",title:"GOLDEN ROYAL",subtitle:"Luxury gold • Play like a champion"},neon:{icon:"⚡",eyebrow:"AFTER DARK",title:"NEON GLOW",subtitle:"Electric lights • Neon energy"},beach:{icon:"🌴",eyebrow:"TROPICAL ESCAPE",title:"BEACH VIBES",subtitle:"Sun • Sand • Sea • Let the game begin"},galaxy:{icon:"🌌",eyebrow:"DEEP SPACE",title:"GALAXY SPACE",subtitle:"Starlight journey • Beyond the board"},wood:{icon:"🪵",eyebrow:"NATURAL COLLECTION",title:"WOOD CLASSIC",subtitle:"Warm timber • Crafted for the table"},dragon:{icon:"🐉",eyebrow:"LEGENDARY REALM",title:"DRAGON",subtitle:"Ancient power • Enter the realm"},christmas:{icon:"🎄",eyebrow:"HOLIDAY EDITION",title:"CHRISTMAS",subtitle:"Festive lights • Merry moves"},football:{icon:"⚽",eyebrow:"MATCH DAY",title:"FOOTBALL",subtitle:"Kick off • Every move counts"},candy:{icon:"🍭",eyebrow:"SWEET WORLD",title:"CANDY LAND",subtitle:"Sugar rush • Colorful fun"},marble:{icon:"💎",eyebrow:"LUXE COLLECTION",title:"MARBLE LUXE",subtitle:"Polished style • Premium play"},nature:{icon:"🌿",eyebrow:"WILD & NATURAL",title:"NATURE WOOD",subtitle:"Forest calm • Natural strategy"},space:{icon:"🚀",eyebrow:"COSMIC FLIGHT",title:"SPACE GALAXY",subtitle:"Launch into orbit • Own the stars"},crystal:{icon:"❄️",eyebrow:"FROZEN COLLECTION",title:"CRYSTAL ICE",subtitle:"Frozen brilliance • Cool precision"},fireice:{icon:"🔥❄️",eyebrow:"ELEMENTAL",title:"FIRE & ICE",subtitle:"Two forces • One battlefield"},jungle:{icon:"🌿",eyebrow:"WILD ADVENTURE",title:"JUNGLE QUEST",subtitle:"Untamed paths • Hunt for victory"},love:{icon:"💗",eyebrow:"HEART COLLECTION",title:"LOVE EDITION",subtitle:"Hearts • Romance • Play with feeling"},night:{icon:"🌃",eyebrow:"CITY AFTER DARK",title:"NIGHT CITY",subtitle:"Midnight lights • Own the night"},arabian:{icon:"🏜️",eyebrow:"ROYAL DESERT",title:"ARABIAN PALACE",subtitle:"Golden sands • Palace of strategy"},"midnight-live":{icon:"🌙",eyebrow:"LUDO LIVE EXCLUSIVE",title:"MIDNIGHT LIVE",subtitle:"Live after dark • Your game, your night"}};
const resolveTheme=(value:unknown):BoardThemeId=>{const id=String(value||"");return id==="midnight-live"?"night":id in BOARD_PALETTES?(id as BoardThemeId):"classic"};

export default function GamePage(){
 const searchParams=useSearchParams();const isTournament=searchParams.has("tournament")&&searchParams.has("match");const[theme,setTheme]=useState<BoardThemeId>("classic");const[skinId,setSkinId]=useState("classic");
 useEffect(()=>{if(isTournament)return;let active=true;const load=async()=>{try{const saved=localStorage.getItem("ludo-match-board");if(saved&&(saved==="midnight-live"||saved in BOARD_PALETTES)){setSkinId(saved);setTheme(resolveTheme(saved))}}catch{}try{const r=await fetch("/api/customization",{cache:"no-store"});if(!r.ok)return;const d=await r.json();const equipped=String(d?.equippedBoard||"");if(active&&equipped&&(equipped==="midnight-live"||equipped in BOARD_PALETTES)){setSkinId(equipped);setTheme(resolveTheme(equipped));try{localStorage.setItem("ludo-match-board",equipped)}catch{}}}catch{}};load();return()=>{active=false}},[isTournament]);
 const palette=BOARD_PALETTES[theme]||BOARD_PALETTES.classic;useEffect(()=>{if(isTournament)return;const old=document.body.style.background;document.body.style.background=palette.bg;return()=>{document.body.style.background=old}},[isTournament,palette.bg]);if(isTournament)return <MultiplayerGame/>;const header=SKIN_HEADERS[skinId]||SKIN_HEADERS[theme]||SKIN_HEADERS.classic;
 return <main className="game-shell" style={{"--accent":palette.accent,"--bg":palette.bg,"--pattern":palette.pattern} as React.CSSProperties}><BotSessionExpiry/><div className="ambient"/><div className="game-stage"><div className="minimal-top"><div className="brand"><span className="brand-mark">{header.icon}</span><div><span className="eyebrow">{header.eyebrow}</span><h1>{header.title}</h1></div></div><div className="live"><i/> LIVE</div></div><div className="board-area"><GameBoardContent themeOverride={theme}/></div></div><style jsx global>{`
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden!important}body{background:var(--bg);touch-action:manipulation}.game-shell{position:fixed;inset:0;overflow:hidden;background:var(--bg);color:#fff;isolation:isolate}.ambient{position:absolute;inset:0;pointer-events:none;background-image:var(--pattern);background-size:560px;opacity:.18}.ambient:after{content:"";position:absolute;left:50%;top:-260px;transform:translateX(-50%);width:min(900px,150vw);height:560px;border-radius:50%;background:var(--accent);opacity:.2;filter:blur(110px)}.game-stage{position:relative;z-index:1;width:min(100%,760px);height:100%;margin:auto;padding:clamp(10px,2.2vh,22px) clamp(10px,3vw,28px) clamp(8px,1.8vh,18px);display:flex;flex-direction:column}.minimal-top{height:clamp(48px,7vh,66px);flex:0 0 auto;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 4px}.brand{display:flex;align-items:center;gap:10px;min-width:0}.brand-mark{width:42px;height:42px;flex:0 0 42px;display:grid;place-items:center;border-radius:13px;background:color-mix(in srgb,var(--accent) 15%,rgba(0,0,0,.28));border:1px solid color-mix(in srgb,var(--accent) 55%,white 20%);box-shadow:0 6px 20px color-mix(in srgb,var(--accent) 18%,transparent);font-size:21px}.eyebrow{display:block;font-size:7px;line-height:1;letter-spacing:2.2px;font-weight:900;color:color-mix(in srgb,var(--accent) 76%,white 24%);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.brand h1{margin:4px 0 0;font-size:clamp(15px,4vw,20px);line-height:1;font-weight:1000;letter-spacing:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.live{display:flex;align-items:center;gap:6px;padding:7px 10px;border:1px solid color-mix(in srgb,var(--accent) 48%,white 15%);border-radius:999px;background:rgba(0,0,0,.16);font-size:8px;font-weight:950;letter-spacing:1.4px;flex:0 0 auto}.live i{width:7px;height:7px;border-radius:50%;background:var(--accent);box-shadow:0 0 12px var(--accent)}.board-area{width:100%;min-height:0;flex:1;display:flex;justify-content:center;align-items:flex-start;overflow:hidden}.board-area>section{width:100%;min-width:0}.board-area>section:first-child{width:100%;max-width:620px;margin:0 auto}.board-area>section:first-child>div{width:100%!important;max-width:none!important}.board-area section[aria-label="Dice and turn controls"]{width:100%;max-width:620px;margin:clamp(7px,1.5vh,14px) auto 0!important;flex:0 0 auto}
@media(max-width:430px){.game-stage{padding-left:8px;padding-right:8px}.brand-mark{width:38px;height:38px;flex-basis:38px;font-size:19px}.minimal-top{height:54px}.live{padding:6px 8px}.board-area>section:first-child{max-width:none}.board-area section[aria-label="Dice and turn controls"]{margin-top:7px!important}}
@media(max-width:360px){.minimal-top{height:48px}.brand-mark{width:34px;height:34px;flex-basis:34px;font-size:17px}.eyebrow{font-size:6px;letter-spacing:1.6px}.brand h1{font-size:14px}.live{font-size:7px;padding:5px 7px}.board-area section[aria-label="Dice and turn controls"]{margin-top:5px!important}}
@media(max-height:620px){.minimal-top{height:44px}.brand-mark{width:34px;height:34px;flex-basis:34px}.brand h1{font-size:14px}.eyebrow{font-size:6px}.board-area section[aria-label="Dice and turn controls"]{margin-top:4px!important}}
`}</style></main>;
}
