"use client";
import {useEffect,useRef,useState} from "react";
import AppFrame from "../_components/AppFrame";
import LudoBoard,{type BoardThemeId,type DemoToken} from "../_components/LudoBoardGame";
import DemoDice from "../_components/DemoDice";
import {getTokenCell,SAFE_CELLS} from "../../lib/ludoBoardCore";

type Color="green"|"yellow"|"red"|"blue"; type Face=1|2|3|4|5|6;
const colors:Color[]=["green","yellow","red","blue"],human:Color[]=["red","yellow"],bot:Color[]=["green","blue"],STEP_COUNT=56,HOME_ENTRY=51;
const initial=():DemoToken[]=>colors.flatMap(color=>Array.from({length:4},(_,id)=>({color,id,position:0,state:"yard" as const})));
const sameCell=(a:readonly number[]|null,b:readonly number[]|null)=>!!a&&!!b&&a[0]===b[0]&&a[1]===b[1];
const isSafeCell=(cell:readonly number[]|null)=>SAFE_CELLS.some(s=>sameCell(cell,[s.row,s.col]));
const emitAudio=(kind:"roll"|"win")=>{if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("ludo-audio",{detail:kind}))};
type Winner="human"|"bot";
type SavedState={theme:BoardThemeId;roll:Face;turn:number;notice:string;tokens:DemoToken[];pendingRoll:Face|null;sixStreak:number;botRollKey:number;winner:Winner|null;winRecorded:boolean};

export default function TournamentBotGame(){
 const params=typeof window!=="undefined"?new URLSearchParams(location.search):new URLSearchParams(),tournamentId=params.get("tournament")||"";
 const[token,setToken]=useState(""),[name,setName]=useState("Tournament"),[theme,setTheme]=useState<BoardThemeId>("classic"),[roll,setRoll]=useState<Face>(1),[turn,setTurn]=useState(0),[notice,setNotice]=useState("Loading your tournament board…"),[botThinking,setBotThinking]=useState(false),[botRolling,setBotRolling]=useState(false),[botRollKey,setBotRollKey]=useState(0),[tokens,setTokens]=useState<DemoToken[]>(initial),[pendingRoll,setPendingRoll]=useState<Face|null>(null),[animating,setAnimating]=useState(false),[sixStreak,setSixStreak]=useState(0),[restored,setRestored]=useState(false),[serverRestored,setServerRestored]=useState(false),[ready,setReady]=useState(false),[snapRestored,setSnapRestored]=useState(false),[winner,setWinner]=useState<Winner|null>(null),[winRecorded,setWinRecorded]=useState(false);
 const winnerRef=useRef<Winner|null>(null),winRecordBusyRef=useRef(false);
 const save=async(next:DemoToken[],nextTurn=turn,nextPending=pendingRoll,nextRoll=roll,nextSix=sixStreak,nextBotKey=botRollKey,nextWinner=winner,nextWinRecorded=winRecorded)=>{if(!token)return;try{await fetch("/api/tournaments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_board",tournamentId,boardToken:token,state:{tokens:next,turn:nextTurn,roll:nextRoll,pendingRoll:nextPending,sixStreak:nextSix,botRollKey:nextBotKey,winner:nextWinner,winRecorded:nextWinRecorded}})})}catch{}};
 const persist=(next:DemoToken[],nextTurn=turn,nextPending=pendingRoll,nextRoll=roll,nextSix=sixStreak,nextBotKey=botRollKey,nextWinner=winner,nextWinRecorded=winRecorded,nextNotice=notice)=>{try{localStorage.setItem(`ludo-tournament-board:${tournamentId}`,JSON.stringify({theme,roll:nextRoll,turn:nextTurn,notice:nextNotice,tokens:next,pendingRoll:nextPending,sixStreak:nextSix,botRollKey:nextBotKey,winner:nextWinner,winRecorded:nextWinRecorded}))}catch{};void save(next,nextTurn,nextPending,nextRoll,nextSix,nextBotKey,nextWinner,nextWinRecorded)};
 useEffect(()=>{let alive=true;(async()=>{try{const[r1,r2]=await Promise.all([fetch(`/api/tournaments?id=${encodeURIComponent(tournamentId)}`,{cache:"no-store"}),fetch(`/api/tournaments/board-state?tournament=${encodeURIComponent(tournamentId)}`,{cache:"no-store"})]);const d=await r1.json(),b=await r2.json();if(!alive)return;if(d?.myBoardToken)setToken(String(d.myBoardToken));if(d?.selected?.name)setName(String(d.selected.name));if(b?.state&&Array.isArray(b.state.tokens)){const s=b.state;setTokens(s.tokens);setTurn(Number(s.turn)||0);setRoll((Number(s.roll)||1) as Face);setPendingRoll(s.pendingRoll??null);setSixStreak(Number(s.sixStreak)||0);setBotRollKey(Number(s.botRollKey)||0);const restoredWinner=(s.winner==="human"||s.winner==="bot")?s.winner:null;setWinner(restoredWinner);winnerRef.current=restoredWinner;setWinRecorded(Boolean(s.winRecorded));setServerRestored(true);setSnapRestored(true);setNotice(restoredWinner==="human"?"🎉 You won this tournament match. +5 points awarded.":restoredWinner==="bot"?"Tournament Bot won this match.":"Tournament match restored — continue playing.")}setReady(true);if(!b?.state?.tokens)setNotice("Your dedicated tournament board is ready.")}catch{setReady(true);setNotice("Tournament board ready.")}})();return()=>{alive=false}},[tournamentId]);
 useEffect(()=>{if(!ready||serverRestored)return;try{const raw=localStorage.getItem(`ludo-tournament-board:${tournamentId}`);if(raw){const s=JSON.parse(raw) as SavedState;if(s&&Array.isArray(s.tokens)){setTheme(s.theme||"classic");setRoll(s.roll||1);setTurn(s.turn||0);setTokens(s.tokens);setPendingRoll(s.pendingRoll??null);setSixStreak(s.sixStreak||0);setBotRollKey(s.botRollKey||0);const restoredWinner=(s.winner==="human"||s.winner==="bot")?s.winner:null;setWinner(restoredWinner);winnerRef.current=restoredWinner;setWinRecorded(Boolean(s.winRecorded));setNotice(s.notice||"Tournament match restored — continue playing.");setSnapRestored(true)}}}catch{}finally{setRestored(true)}},[ready,serverRestored,tournamentId]);
 useEffect(()=>{if(serverRestored)setRestored(true)},[serverRestored]);
 useEffect(()=>{if(!restored)return;try{const s:SavedState={theme,roll,turn,notice,tokens,pendingRoll,sixStreak,botRollKey,winner,winRecorded};localStorage.setItem(`ludo-tournament-board:${tournamentId}`,JSON.stringify(s))}catch{}},[restored,theme,roll,turn,notice,tokens,pendingRoll,sixStreak,botRollKey,winner,winRecorded,tournamentId]);
 useEffect(()=>{if(!snapRestored)return;const timer=window.setTimeout(()=>setSnapRestored(false),0);return()=>window.clearTimeout(timer)},[snapRestored]);
 const recordWin=async()=>{if(winner!=="human"||winRecorded||!token||winRecordBusyRef.current)return;winRecordBusyRef.current=true;try{const r=await fetch("/api/tournaments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"record_win",tournamentId,boardToken:token})});if(r.ok){setWinRecorded(true);persist(tokens,turn,null,roll,0,botRollKey,"human",true,"🎉 You won this tournament match. +5 points awarded.");}else{setNotice("🎉 You won! Your +5 tournament points are syncing…");}}catch{setNotice("🎉 You won! Your +5 tournament points are syncing…");}finally{winRecordBusyRef.current=false}};
 useEffect(()=>{if(winner==="human"&&!winRecorded&&token)void recordWin()},[winner,winRecorded,token]);
 const nextTurn=()=>turn===0?1:0;
 const finishTurn=(rolled:Face,actorName:string)=>{if(winnerRef.current)return;if(rolled===6){const streak=sixStreak+1;if(streak>=3){const next=nextTurn();setSixStreak(0);setPendingRoll(null);setTurn(next);setNotice(`${actorName} rolled three 6s. ${next===0?"Your":"Tournament Bot's"} turn.`);persist(tokens,next,null,rolled,0,botRollKey);return}const nextKey=turn===1?botRollKey+1:botRollKey;setSixStreak(streak);setNotice(`${actorName} rolled 6 — bonus roll.`);if(turn===1)setBotRollKey(nextKey);persist(tokens,turn,null,rolled,streak,nextKey);return}const next=nextTurn();setSixStreak(0);setPendingRoll(null);setNotice(`${actorName} rolled ${rolled}. ${next===0?"Your":"Tournament Bot's"} turn.`);setTurn(next);persist(tokens,next,null,rolled,0,botRollKey)};
 const legalMove=(t:DemoToken,n:Face,owners:Color[])=>{if(!owners.includes(t.color)||t.state==="finished")return false;if(t.state==="yard")return n===6;const target=t.position+n;if(target>STEP_COUNT)return false;for(let step=t.position+1;step<=Math.min(target,HOME_ENTRY);step++){const cell=getTokenCell(t.color,step);if(!cell)return false;const occupants=tokens.filter(x=>x.state!=="yard"&&x.state!=="finished"&&x.position===step&&sameCell(getTokenCell(x.color,x.position),cell));if(occupants.filter(x=>!owners.includes(x.color)).length>=2)return false}if(target===STEP_COUNT)return true;const cell=getTokenCell(t.color,target);if(!cell)return false;const occupants=tokens.filter(x=>x.state!=="yard"&&x.state!=="finished"&&sameCell(getTokenCell(x.color,x.position),cell));return occupants.filter(x=>!owners.includes(x.color)).length<2};
 const applyLandingRules=(color:Color,id:number,target:number,owners:Color[])=>{const targetCell=getTokenCell(color,target);if(!targetCell||target>HOME_ENTRY)return;const opponents=tokens.filter(t=>t.state!=="yard"&&t.state!=="finished"&&!owners.includes(t.color)&&sameCell(getTokenCell(t.color,t.position),targetCell));if(opponents.length===1&&!isSafeCell(targetCell))setTokens(prev=>prev.map(t=>t.color===opponents[0].color&&t.id===opponents[0].id?{...t,position:0,state:"yard"}:t))};
 const declareWinner=(nextTokens:DemoToken[],kind:Winner)=>{if(winnerRef.current)return;winnerRef.current=kind;setWinner(kind);setPendingRoll(null);setBotThinking(false);setBotRolling(false);setSixStreak(0);const nextNotice=kind==="human"?"🎉 You won this tournament match. +5 points awarded.":"Tournament Bot won this match.";setNotice(nextNotice);persist(nextTokens,turn,null,roll,0,botRollKey,kind,kind==="bot",nextNotice);if(kind==="human")void recordWin()};
 const checkWinner=(nextTokens:DemoToken[])=>{const humanDone=nextTokens.filter(t=>human.includes(t.color)).every(t=>t.state==="finished");const botDone=nextTokens.filter(t=>bot.includes(t.color)).every(t=>t.state==="finished");if(humanDone){declareWinner(nextTokens,"human");return true}if(botDone){declareWinner(nextTokens,"bot");return true}return false};
 const animateToken=(color:Color,id:number,n:Face,actorName:string,owners:Color[])=>{if(animating||winnerRef.current)return;const current=tokens.find(t=>t.color===color&&t.id===id);if(!current||!legalMove(current,n,owners))return;const start=current.position,target=start===0?1:start+n;setAnimating(true);setPendingRoll(null);let step=start;const timer=window.setInterval(()=>{if(step>=target){window.clearInterval(timer);const finished=target===STEP_COUNT;const nextTokens:DemoToken[]=tokens.map(t=>t.color===color&&t.id===id?{...t,position:target,state:(finished?"finished":target>HOME_ENTRY?"home":"track") as DemoToken["state"]}:t);setTokens(nextTokens);if(!finished)applyLandingRules(color,id,target,owners);setAnimating(false);if(checkWinner(nextTokens))return;finishTurn(n,actorName);return}step+=1;setTokens(prev=>prev.map(t=>t.color===color&&t.id===id?{...t,position:step,state:(step>HOME_ENTRY?"home":"track") as DemoToken["state"]}:t))},280)};
 const chooseToken=(color:Color,id:number)=>{if(pendingRoll==null||animating||turn!==0||winnerRef.current)return;animateToken(color,id,pendingRoll,"You",human)};
 const performBotMove=(n:Face)=>{if(winnerRef.current)return;const candidate=tokens.find(t=>legalMove(t,n,bot));if(!candidate){finishTurn(n,"Tournament Bot");return}animateToken(candidate.color,candidate.id,n,"Tournament Bot",bot)};
 useEffect(()=>{if(!restored||turn!==1||animating||pendingRoll!==null||winnerRef.current)return;let cancelled=false;setBotThinking(true);setBotRolling(false);setNotice("Tournament Bot's turn — preparing roll…");const rollTimer=window.setTimeout(()=>{if(cancelled||winnerRef.current)return;setBotRolling(true);setNotice("Tournament Bot is rolling…");const moveTimer=window.setTimeout(()=>{if(cancelled||winnerRef.current)return;const n=(Math.floor(Math.random()*6)+1) as Face;emitAudio("roll");setRoll(n);setBotRolling(false);setBotThinking(false);persist(tokens,1,null,n,sixStreak,botRollKey);window.setTimeout(()=>{if(!cancelled&&!winnerRef.current)performBotMove(n)},120)},900);return()=>window.clearTimeout(moveTimer)},700);return()=>{cancelled=true;window.clearTimeout(rollTimer)}},[restored,turn,botRollKey,winner]);
 const handleHumanRoll=(n:Face)=>{if(botThinking||animating||pendingRoll!==null||turn!==0||winnerRef.current)return;emitAudio("roll");setRoll(n);setPendingRoll(n);const hasLegal=tokens.some(t=>legalMove(t,n,human));if(!hasLegal){setPendingRoll(null);finishTurn(n,"You");return}setNotice(`You rolled ${n}. Select a legal token to move.`);persist(tokens,0,n,n,sixStreak,botRollKey)};
 const diceDisabled=!restored||botThinking||animating||pendingRoll!==null||turn!==0||!!winnerRef.current;
 return <AppFrame back={`/tournament?id=${encodeURIComponent(tournamentId)}`}><main style={styles.page}><header style={styles.header}><div><div style={styles.eyebrow}>TOURNAMENT • BOT VS HUMAN</div><h1 style={styles.title}>{name}</h1><div style={styles.sub}>Dedicated board • isolated tournament token</div></div><span style={styles.live}>🏆</span></header><section style={styles.board}><LudoBoard theme={theme} demoTokens={tokens} onTokenClick={(c,id)=>chooseToken(c as Color,id)} snapOnUpdate={snapRestored} finishSound/></section><section style={styles.controls}><div><b style={styles.turn}>{winner==="human"?"🏆 YOU WIN":winner==="bot"?"TOURNAMENT BOT WINS":turn===0?"YOUR TURN":"TOURNAMENT BOT"}</b><p>{notice}</p></div><DemoDice value={roll} onRoll={handleHumanRoll} disabled={diceDisabled} botRolling={botRolling}/></section><div style={styles.meta}><span>+5 points per win</span><span>50 points qualifies for Top 10</span><span>Each tournament has its own board state</span></div></main></AppFrame>;
}
const styles:any={page:{maxWidth:720,margin:"0 auto",paddingBottom:40,color:"#fff"},header:{padding:"14px 0",display:"flex",justifyContent:"space-between",gap:12},eyebrow:{fontSize:9,letterSpacing:2,color:"#65adff",fontWeight:950},title:{fontSize:22,margin:"4px 0"},sub:{fontSize:11,color:"#9eb3d0"},live:{fontSize:30},board:{width:"100%"},controls:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,padding:15,borderRadius:16,border:"1px solid #3478d6",background:"#07182fee"},turn:{fontSize:11,letterSpacing:1,color:"#75b6ff"},meta:{display:"flex",gap:8,flexWrap:"wrap",marginTop:10,fontSize:10,color:"#a9c3e4"}};
