"use client";

import { useEffect, useMemo, useState } from "react";
import AppFrame from "../_components/AppFrame";
import LudoBoard, { BOARD_PALETTES, type BoardThemeId, type DemoToken } from "../_components/LudoBoardGame";
import DemoDice from "../_components/DemoDice";
import { getTokenCell } from "../../lib/ludoBoardCore";

type Color="green"|"yellow"|"red"|"blue"; type Face=1|2|3|4|5|6;
const colors:Color[]=["green","yellow","red","blue"], STEP=56, HOME=51;
const initial=():DemoToken[]=>colors.flatMap(color=>Array.from({length:4},(_,id)=>({color,id,position:0,state:"yard" as const})));
const legal=(t:DemoToken,n:Face,tokens:DemoToken[],mine:Color[])=>{if(!mine.includes(t.color)||t.state==="finished")return false;if(t.state==="yard")return n===6;const target=t.position+n;if(target>STEP)return false;return true};

export default function TournamentBotGame(){
 const params=typeof window!=="undefined"?new URLSearchParams(location.search):new URLSearchParams();
 const tournamentId=params.get("tournament")||"";
 const [token,setToken]=useState(""); const [name,setName]=useState("Tournament"); const [theme,setTheme]=useState<BoardThemeId>("classic");
 const [tokens,setTokens]=useState<DemoToken[]>(initial),[turn,setTurn]=useState(0),[roll,setRoll]=useState<Face>(1),[pending,setPending]=useState<Face|null>(null),[thinking,setThinking]=useState(false),[notice,setNotice]=useState("Loading your tournament board…"),[animating,setAnimating]=useState(false),[ready,setReady]=useState(false);
 const mine:Color[]=useMemo(()=>["red","yellow"],[ ]);
 const save=async(next:DemoToken[]=tokens)=>{if(!token)return;try{await fetch("/api/tournaments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_board",tournamentId,boardToken:token,state:{tokens:next,turn,roll,pendingRoll:pending}})});}catch{}};
 useEffect(()=>{let alive=true;(async()=>{try{const r=await fetch(`/api/tournaments?id=${encodeURIComponent(tournamentId)}`,{cache:"no-store"}),d=await r.json();if(!alive)return;if(d?.myBoardToken)setToken(String(d.myBoardToken));if(d?.selected?.name)setName(String(d.selected.name));if(d?.myBoardState?.tokens)setTokens(d.myBoardState.tokens);if(d?.myBoardState?.turn!==undefined)setTurn(Number(d.myBoardState.turn)||0);setReady(true);setNotice("Your tournament board is ready. You play against the Tournament Bot.");}catch{setReady(true);setNotice("Tournament board ready. Play against the Tournament Bot.")}})();return()=>{alive=false}},[tournamentId]);
 useEffect(()=>{if(!ready||!token)return;const key=`ludo-tournament-board:${tournamentId}`;try{const raw=localStorage.getItem(key);if(raw){const s=JSON.parse(raw);if(Array.isArray(s.tokens)){setTokens(s.tokens);setTurn(Number(s.turn)||0);setNotice("Tournament match restored.")}}}catch{}},[ready,token,tournamentId]);
 const finishTurn=(n:Face)=>{if(n===6){setPending(null);setNotice(turn===0?"You rolled 6 — roll again.":"Bot rolled 6 — bot rolls again.");return}setPending(null);setTurn(x=>x===0?1:0);};
 const move=(color:Color,id:number,n:Face)=>{const t=tokens.find(x=>x.color===color&&x.id===id);if(!t||!legal(t,n,tokens,mine)||animating)return;const target=t.state==="yard"?1:t.position+n;setAnimating(true);let step=t.position;const timer=window.setInterval(()=>{if(step>=target){window.clearInterval(timer);const next=tokens.map(x=>x.color===color&&x.id===id?{...x,position:target,state:target>=STEP?"finished":target>HOME?"home":"track"}:x);setTokens(next);setAnimating(false);if(next.filter(x=>mine.includes(x.color)&&x.state==="finished").length===4){void win(next);return;}finishTurn(n);void persist(next);return;}step+=1;setTokens(prev=>prev.map(x=>x.color===color&&x.id===id?{...x,position:step,state:step>HOME?"home":"track"}:x))},90)};
 const persist=(next:DemoToken[])=>{try{localStorage.setItem(`ludo-tournament-board:${tournamentId}`,JSON.stringify({tokens:next,turn,roll,pendingRoll:pending}))}catch{};void save(next)};
 const win=async(next:DemoToken[])=>{setNotice("🏆 Match won — recording +5 tournament points…");try{const r=await fetch("/api/tournaments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"record_win",tournamentId,boardToken:token})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to record win");setNotice(`🏆 WIN! +5 points • ${d.points} tournament points total.`);const reset=initial();setTokens(reset);setTurn(0);setPending(null);void persist(reset);}catch(e){setNotice(e instanceof Error?e.message:"Win recorded locally; sync failed.")}};
 const humanRoll=(n:Face)=>{if(!ready||thinking||animating||turn!==0||pending!==null)return;setRoll(n);const legalMove=tokens.some(t=>legal(t,n,tokens,mine));if(!legalMove){finishTurn(n);setNotice(n===6?"No legal move — bonus roll.":"No legal move — bot turn.");return;}setPending(n);setNotice(`You rolled ${n}. Pick a token.`)};
 useEffect(()=>{if(!ready||turn!==1||thinking||animating||pending!==null)return;setThinking(true);setNotice("Tournament Bot is thinking…");const timer=window.setTimeout(()=>{const n=(Math.floor(Math.random()*6)+1) as Face;setRoll(n);const bot:[Color,Color]=["green","blue"];const candidate=tokens.find(t=>bot.includes(t.color)&&legal(t,n,tokens,bot));setThinking(false);if(candidate){move(candidate.color,candidate.id,n)}else{finishTurn(n);setNotice(n===6?"Bot rolled 6 but has no legal move — bonus roll.":"Bot turn passes.")}},800);return()=>clearTimeout(timer)},[ready,turn,thinking,animating,pending,tokens]);
 return <AppFrame back={`/tournament?id=${encodeURIComponent(tournamentId)}`}><main style={styles.page}><header style={styles.header}><div><div style={styles.eyebrow}>TOURNAMENT • BOT VS HUMAN</div><h1 style={styles.title}>{name}</h1><div style={styles.sub}>This board is isolated from Friends → Mood and from every other tournament.</div></div><span style={styles.live}>🏆</span></header><section style={styles.board}><LudoBoard theme={theme} demoTokens={tokens} onTokenClick={(c,id)=>{if(pending!==null)move(c as Color,id,pending)}}/></section><section style={styles.controls}><div><b style={styles.turn}>{turn===0?"YOUR TURN":"TOURNAMENT BOT"}</b><p>{notice}</p></div><DemoDice value={roll} onRoll={humanRoll} disabled={!ready||thinking||animating||turn!==0||pending!==null} botRolling={thinking}/></section><div style={styles.meta}><span>+5 points per win</span><span>50 points qualifies for Top 10</span><span>Board token protected</span></div></main></AppFrame>;
}
const styles:any={page:{maxWidth:720,margin:"0 auto",paddingBottom:40,color:"#fff"},header:{padding:"14px 0",display:"flex",justifyContent:"space-between",gap:12},eyebrow:{fontSize:9,letterSpacing:2,color:"#65adff",fontWeight:950},title:{fontSize:22,margin:"4px 0"},sub:{fontSize:11,color:"#9eb3d0"},live:{fontSize:30},board:{width:"100%"},controls:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,padding:15,borderRadius:16,border:"1px solid #3478d6",background:"#07182fee"},turn:{fontSize:11,letterSpacing:1,color:"#75b6ff"},controlsP:{fontSize:12},meta:{display:"flex",gap:8,flexWrap:"wrap",marginTop:10,fontSize:10,color:"#a9c3e4"}};
