import { Pool, PoolClient } from "pg";
import { randomUUID } from "crypto";
type Db=Pool|PoolClient;

export function requestMeta(request:{headers:{get(name:string):string|null}}){const forwarded=request.headers.get("x-forwarded-for")||request.headers.get("x-real-ip")||"";return{ip:forwarded.split(",")[0].trim(),userAgent:request.headers.get("user-agent")||""}}

export async function ensureWalletAudit(client:Db){await client.query(`CREATE TABLE IF NOT EXISTS ludo_wallet_audit(id BIGSERIAL PRIMARY KEY,user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,currency TEXT NOT NULL CHECK(currency IN ('coins','gems')),amount BIGINT NOT NULL,balance_before BIGINT NOT NULL,balance_after BIGINT NOT NULL,source TEXT NOT NULL DEFAULT 'unknown',source_ref TEXT,actor_user_id TEXT REFERENCES ludo_users(id) ON DELETE SET NULL,actor_type TEXT NOT NULL DEFAULT 'user',request_id TEXT,ip_address TEXT,user_agent TEXT,status TEXT NOT NULL DEFAULT 'verified',reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE ludo_wallet_audit ADD COLUMN IF NOT EXISTS actor_type TEXT NOT NULL DEFAULT 'user';CREATE INDEX IF NOT EXISTS ludo_wallet_audit_user_idx ON ludo_wallet_audit(user_id,created_at DESC);CREATE INDEX IF NOT EXISTS ludo_wallet_audit_created_idx ON ludo_wallet_audit(created_at DESC);CREATE INDEX IF NOT EXISTS ludo_wallet_audit_status_idx ON ludo_wallet_audit(status,created_at DESC);CREATE OR REPLACE FUNCTION ludo_capture_wallet_change() RETURNS trigger AS $$ DECLARE c TEXT; old_balance BIGINT; new_balance BIGINT; src TEXT; ref TEXT; actor TEXT; actor_kind TEXT; req TEXT; ip TEXT; ua TEXT; stat TEXT; why TEXT; BEGIN FOREACH c IN ARRAY ARRAY['coins','gems'] LOOP old_balance:=COALESCE((to_jsonb(OLD)->>c)::BIGINT,0);new_balance:=COALESCE((to_jsonb(NEW)->>c)::BIGINT,0);IF old_balance<>new_balance THEN src:=NULLIF(current_setting('ludo.wallet_source',true),'');ref:=NULLIF(current_setting('ludo.wallet_source_ref',true),'');actor:=NULLIF(current_setting('ludo.wallet_actor',true),'');actor_kind:=COALESCE(NULLIF(current_setting('ludo.wallet_actor_type',true),''),CASE WHEN actor IS NOT NULL THEN 'user' ELSE 'system' END);req:=NULLIF(current_setting('ludo.wallet_request_id',true),'');ip:=NULLIF(current_setting('ludo.wallet_ip',true),'');ua:=NULLIF(current_setting('ludo.wallet_user_agent',true),'');why:=NULLIF(current_setting('ludo.wallet_reason',true),'');IF src IS NULL OR ref IS NULL OR req IS NULL OR why IS NULL OR (actor IS NULL AND actor_kind<>'system') THEN RAISE EXCEPTION 'Wallet change requires source, source_ref, request_id, reason and actor metadata';END IF;stat:='verified';INSERT INTO ludo_wallet_audit(user_id,currency,amount,balance_before,balance_after,source,source_ref,actor_user_id,actor_type,request_id,ip_address,user_agent,status,reason)VALUES(NEW.id,c,new_balance-old_balance,old_balance,new_balance,src,ref,actor,actor_kind,req,ip,ua,stat,why);END IF;END LOOP;RETURN NEW;END;$$ LANGUAGE plpgsql;DROP TRIGGER IF EXISTS ludo_wallet_audit_trigger ON ludo_users;CREATE TRIGGER ludo_wallet_audit_trigger AFTER UPDATE OF coins,gems ON ludo_users FOR EACH ROW EXECUTE FUNCTION ludo_capture_wallet_change();`)}

export async function markWalletContext(client:Db,input:{source:string;sourceRef?:string;actorUserId?:string;actorType?:"user"|"system";requestId?:string;ip?:string;userAgent?:string;reason?:string}){const requestId=input.requestId||randomUUID();const actorType=input.actorType||(input.actorUserId?"user":"system");if(!input.source||!input.sourceRef||!input.reason||(!input.actorUserId&&actorType!=="system"))throw new Error("Wallet metadata requires source, sourceRef, reason and actor.");await client.query(`SELECT set_config('ludo.wallet_source',$1,true),set_config('ludo.wallet_source_ref',$2,true),set_config('ludo.wallet_actor',$3,true),set_config('ludo.wallet_actor_type',$4,true),set_config('ludo.wallet_request_id',$5,true),set_config('ludo.wallet_ip',$6,true),set_config('ludo.wallet_user_agent',$7,true),set_config('ludo.wallet_reason',$8,true)`,[input.source,input.sourceRef,String(input.actorUserId||''),actorType,requestId,input.ip||'',input.userAgent||'',input.reason]);return requestId}

export async function adjustWallet(pool:Pool,userId:string,currency:"coins"|"gems",amount:number,meta:{source:string;sourceRef?:string;actorUserId?:string;actorType?:"user"|"system";reason?:string;ip?:string;userAgent?:string}){if(!Number.isSafeInteger(amount)||amount===0)throw new Error("Invalid wallet amount.");const client=await pool.connect();try{await client.query("BEGIN");await ensureWalletAudit(client);const r=await client.query(`SELECT coins,gems FROM ludo_users WHERE id=$1 FOR UPDATE`,[userId]);if(!r.rows[0])throw new Error("Account not found.");const before=Number(r.rows[0][currency])||0,after=before+amount;if(!Number.isSafeInteger(after)||after<0)throw new Error("Wallet balance cannot be negative or exceed the supported limit.");const requestId=await markWalletContext(client,meta);await client.query(`UPDATE ludo_users SET ${currency}=$1 WHERE id=$2`,[after,userId]);await client.query("COMMIT");return{before,after,amount,currency,requestId}}catch(e){await client.query("ROLLBACK").catch(()=>{});throw e}finally{client.release()}}
