"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import "./shop.css";

type Item = Record<string, any>;

const CATEGORIES = [["all","All Shop","🛍️"],["coin_package","Coin Packs","🪙"],["gem_package","Gem Packs","💎"],["board","Boards","🎯"],["dice","Dice","🎲"],["avatar","Avatars","🧑‍🎮"],["item","Yards & Stickers","✨"]] as const;
const money = (v:any) => Number(v||0).toLocaleString();
const label = (x:Item) => x.currency === "naira" ? `₦${money(x.price)}` : `${x.currency === "gems" ? "💎" : "🪙"} ${money(x.price)}`;

function Visual({item}:{item:Item}) { const [broken,setBroken]=useState(false); return <div className="shop-visual">{item.imageUrl&&!broken?<img src={item.imageUrl} alt="" onError={()=>setBroken(true)}/>:<span>{item.icon||(item.type==="avatar"?"🧑‍🎮":"✨")}</span>}</div>; }

export default function AdminShopPage(){
 const [items,setItems]=useState<Item[]>([]),[visualItems,setVisualItems]=useState<Item[]>([]),[category,setCategory]=useState("all"),[search,setSearch]=useState(""),[editing,setEditing]=useState<Item|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/admin/shop",{cache:"no-store"}),data=await r.json();if(!r.ok)throw new Error(data?.error||"Unable to load shop");setItems(data.items||[]);setVisualItems(data.visualItems||[]);}catch(e:any){setMessage(e?.message||"Unable to load shop")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const all=useMemo(()=>[...items,...visualItems.map(x=>({...x,type:"item",isVisual:true,isActive:x.is_published!==false}))],[items,visualItems]);
 const filtered=useMemo(()=>all.filter(x=>{const q=search.trim().toLowerCase();return (category==="all"||x.type===category)&&(!q||`${x.name} ${x.id} ${x.description||""}`.toLowerCase().includes(q))}),[all,category,search]);
 const grouped=useMemo(()=>CATEGORIES.filter(x=>x[0]!=="all").map(([key,title,icon])=>({key,title,icon,rows:filtered.filter(x=>x.type===key)})).filter(x=>x.rows.length),[filtered]);
 const save=async()=>{if(!editing)return;setSaving(true);setMessage("");try{const action=editing.isVisual?(editing.id?"edit_visual":"create_visual"):"save";const body=editing.isVisual?{...editing,action}:{...editing,action:"save",stockQuantity:editing.stockQuantity??-1,isActive:editing.isActive!==false};const r=await fetch("/api/admin/shop",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw new Error(data?.error||"Save failed");setEditing(null);setMessage("Shop updated successfully.");await load()}catch(e:any){setMessage(e?.message||"Save failed")}finally{setSaving(false)}};
 const toggleVisual=async(id:string)=>{await fetch("/api/admin/shop",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"toggle_visual",id})});await load()};
 const openNew=()=>setEditing({isVisual:true,name:"New sticker",description:"",kind:"sticker",rarity:"COMMON",currency:"gems",price:50,stockQuantity:-1,requiredLevel:0,icon:"✨",imageUrl:""});
 const openEdit=(x:Item)=>setEditing({...x,isVisual:Boolean(x.isVisual),stockQuantity:x.stockQuantity??-1,isActive:x.isActive!==false});
 const stockText=(x:Item)=>x.stockQuantity===-1||x.stockQuantity===undefined?"Unlimited stock":`${money(x.stockQuantity)} in stock`;
 return <div className="shop-admin">
  <div className="shop-topbar"><div className="shop-title"><Link href="/dbase" className="back">← Dashboard</Link><div className="eyebrow">LIVE SHOP CONTROL</div><h1>Shop Management</h1><p>Organize every item into clear categories, control pricing and stock, and give each item a proper visual.</p></div><button className="add-button" onClick={openNew}>＋ Add sticker / background</button></div>
  <div className="shop-stats"><div><span>CATALOG</span><b>{all.length}</b><small>items in the shop</small></div><div><span>VISUALS</span><b>{all.filter(x=>x.imageUrl||x.icon).length}</b><small>with image or sticker</small></div><div><span>LIMITED STOCK</span><b>{all.filter(x=>x.stockQuantity!==-1&&x.stockQuantity!==undefined).length}</b><small>stock-controlled items</small></div><div><span>ACTIVE</span><b>{all.filter(x=>x.isActive!==false).length}</b><small>currently visible</small></div></div>
  <div className="shop-toolbar"><div className="category-tabs">{CATEGORIES.map(([key,title,icon])=><button key={key} className={category===key?"active":""} onClick={()=>setCategory(key)}><span>{icon}</span>{title}</button>)}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search shop items..."/></div>
  {message&&<div className="shop-message">{message}</div>}
  {loading?<div className="shop-loading">Loading live shop catalogue…</div>:grouped.length===0?<div className="shop-empty">No shop items match this filter.</div>:grouped.map(group=><section className="shop-section" key={group.key}><div className="section-heading"><div><span>{group.icon}</span><div><h2>{group.title}</h2><p>{group.rows.length} item{group.rows.length===1?"":"s"}</p></div></div><button onClick={()=>setCategory(group.key)}>View category →</button></div><div className="shop-grid">{group.rows.map((x,i)=><article className="shop-card" key={`${x.type}-${x.id}-${i}`}><div className="card-image"><Visual item={x}/><span className={`rarity ${String(x.rarity||"COMMON").toLowerCase()}`}>{x.rarity||"COMMON"}</span>{x.isActive===false&&<span className="hidden-badge">HIDDEN</span>}</div><div className="card-body"><div className="card-name"><h3>{x.name||x.id}</h3><span>{x.description||x.yardKind||x.type}</span></div><div className="card-price"><b>{label(x)}</b><small>{stockText(x)}</small></div><div className="card-actions"><button onClick={()=>openEdit(x)}>Edit</button>{x.isVisual?<button className={x.isActive===false?"good":"danger"} onClick={()=>toggleVisual(x.id)}>{x.isActive===false?"Restore":"Delete"}</button>:<button className={x.isActive===false?"good":"danger"} onClick={()=>openEdit({...x,isActive:x.isActive===false})}>{x.isActive===false?"Restore":"Hide"}</button>}</div></div></article>)}</div></section>)}
  {editing&&<div className="editor-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setEditing(null)}><div className="shop-editor"><div className="editor-title"><div><span>{editing.isVisual?"VISUAL SHOP ITEM":"CATALOG ITEM"}</span><h2>{editing.id?"Edit item":"Add item"}</h2></div><button onClick={()=>setEditing(null)}>✕</button></div><div className="editor-preview"><Visual item={editing}/><div><b>{editing.name||"New item"}</b><span>{editing.imageUrl?"Image URL connected":"Emoji/sticker fallback active"}</span></div></div><div className="form-grid"><label>Name<input value={editing.name||""} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Icon / sticker<input value={editing.icon||""} onChange={e=>setEditing({...editing,icon:e.target.value})}/></label><label className="wide">Image URL<input value={editing.imageUrl||""} onChange={e=>setEditing({...editing,imageUrl:e.target.value})} placeholder="https://..."/></label><label className="wide">Description<textarea value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/></label>{editing.isVisual&&<label>Type<select value={editing.kind||"sticker"} onChange={e=>setEditing({...editing,kind:e.target.value})}><option value="sticker">Sticker</option><option value="background">Background</option></select></label>}<label>Currency<select value={editing.currency||"coins"} onChange={e=>setEditing({...editing,currency:e.target.value})}><option value="coins">Coins</option><option value="gems">Gems</option><option value="naira">Naira</option></select></label><label>Price<input type="number" min="0" value={editing.price??0} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><label>Stock<input type="number" min="-1" value={editing.stockQuantity??-1} onChange={e=>setEditing({...editing,stockQuantity:Number(e.target.value)})}/><small>-1 = unlimited</small></label><label>Unlock level<input type="number" min="0" value={editing.requiredLevel??0} onChange={e=>setEditing({...editing,requiredLevel:Number(e.target.value)})}/></label>{editing.isVisual&&<label>Rarity<select value={editing.rarity||"COMMON"} onChange={e=>setEditing({...editing,rarity:e.target.value})}><option>COMMON</option><option>RARE</option><option>EPIC</option><option>LEGENDARY</option></select></label>}{!editing.isVisual&&<label>Category<input value={editing.category||""} onChange={e=>setEditing({...editing,category:e.target.value})} placeholder="Boards, Dice, Avatars..."/></label>}{!editing.isVisual&&<label className="toggle"><input type="checkbox" checked={editing.isActive!==false} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/> Visible in player shop</label>}</div><button className="save-button" disabled={saving} onClick={save}>{saving?"Saving…":"Save shop changes"}</button></div></div>}
 </div>;
}
