"use client";
import {useEffect,useState} from "react";
import AppFrame from "../_components/AppFrame";

type Case={id:number;title:string;description:string;status:string;admin_note:string|null;created_at:string;updated_at:string};
type Message={id:number;sender_type:"user"|"admin";message:string;created_at:string};

export default function Support(){
 const[cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState<Case|null>(null),[messages,setMessages]=useState<Message[]>([]),[subject,setSubject]=useState(""),[category,setCategory]=useState("other"),[text,setText]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async(id?:number)=>{try{const r=await fetch(id?`/api/support?id=${id}`:"/api/support",{cache:"no-store"});const x=await r.json();if(!r.ok)throw Error(x.error);if(id){setSelected(x.case);setMessages(x.messages||[])}else{setCases(x.cases||[]);if(selected){const found=(x.cases||[]).find((c:Case)=>c.id===selected.id);if(found)setSelected(found)}}}catch(e){setNotice(e instanceof Error?e.message:"Unable to load support.")}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(()=>{load(selected?.id)},8000);return()=>clearInterval(t)},[selected?.id]);
 const submit=async(action:string,body:any)=>{setBusy(true);setNotice("");try{const r=await fetch("/api/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body})});const x=await r.json();if(!r.ok)throw Error(x.error);setNotice(action==="create"?"Support case created. Admin can now reply here.":"Message sent.");if(action==="create"){setSubject("");setText("");await load();if(x.id)await load(x.id)}else{setText("");await load(selected?.id)}}catch(e){setNotice(e instanceof Error?e.message:"Support request failed.")}finally{setBusy(false)}};
 return <AppFrame back="/settings"><div style={{maxWidth:820,margin:"0 auto"}}><h1>💬 Help & Support</h1><p style={{color:"#94a3b8"}}>Contact the Ludo Live team directly. Your conversation stays attached to your support case.</p>{notice&&<p style={{color:notice.includes("failed")||notice.includes("Unable")?"#fca5a5":"#86efac"}}>{notice}</p>}{!selected?<><section style={panel}><h2>Start a support case</h2><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject" style={input}/><select value={category} onChange={e=>setCategory(e.target.value)} style={input}><option value="game">Game problem</option><option value="payment">Payment / wallet</option><option value="event">Event</option><option value="tournament">Tournament</option><option value="account">Account</option><option value="other">Other</option></select><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe the issue" rows={6} style={input}/><button disabled={busy} onClick={()=>submit("create",{title:subject,message:text,category})} style={button}>{busy?"Sending…":"Send request"}</button></section><section style={panel}><h2>Your support cases</h2>{loading?<p style={muted}>Loading…</p>:cases.length?cases.map(c=><button key={c.id} onClick={()=>load(c.id)} style={caseBtn}><div><b>#{c.id} {c.title}</b><small>{c.category||"other"} • {c.status}</small></div><span>→</span></button>):<p style={muted}>No support cases yet.</p>}</section></>:<section style={panel}><button onClick={()=>{setSelected(null);setMessages([])}} style={ghost}>← All cases</button><h2 style={{marginBottom:4}}>#{selected.id} {selected.title}</h2><p style={muted}>{selected.status.toUpperCase()} • {selected.category||"other"}</p><div style={thread}>{messages.map(m=><div key={m.id} style={{...bubble,...(m.sender_type==="admin"?adminBubble:userBubble)}}><b>{m.sender_type==="admin"?"Ludo Live Support":"You"}</b><div>{m.message}</div><small>{new Date(m.created_at).toLocaleString()}</small></div>)}</div>{selected.status==="resolved"?<><p style={{color:"#86efac"}}>This case is resolved.</p><button disabled={busy} onClick={()=>submit("reopen",{id:selected.id})} style={button}>Reopen case</button></>:<div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Reply to support…" rows={4} style={input}/><button disabled={busy} onClick={()=>submit("reply",{id:selected.id,message:text})} style={button}>{busy?"Sending…":"Send reply"}</button></div>}</section>}</div></AppFrame>}
const panel:any={marginTop:18,padding:20,borderRadius:18,background:"linear-gradient(180deg,#061b42,#04132f)",border:"1px solid rgba(78,125,211,.25)"};const input:any={width:"100%",boxSizing:"border-box",marginBottom:12,padding:13,borderRadius:10,border:"1px solid #24436e",background:"#07172d",color:"#fff"};const button:any={width:"100%",padding:14,border:0,borderRadius:10,background:"#1976e8",color:"#fff",fontWeight:900,cursor:"pointer"};const ghost:any={padding:"9px 12px",borderRadius:10,border:"1px solid #35527f",background:"#0a1731",color:"#fff",fontWeight:800};const caseBtn:any={width:"100%",display:"flex",justifyContent:"space-between",textAlign:"left",margin:"8px 0",padding:14,borderRadius:12,border:"1px solid #213c66",background:"#091b38",color:"#fff",cursor:"pointer"};const muted:any={color:"#94a3b8"};const thread:any={display:"grid",gap:10,maxHeight:460,overflow:"auto",margin:"18px 0"};const bubble:any={padding:12,borderRadius:12,display:"grid",gap:5};const adminBubble:any={background:"#102d57",border:"1px solid #2e5c96"};const userBubble:any={background:"#112a25",border:"1px solid #28624e"};
