import {NextRequest,NextResponse} from "next/server";
import {createHash,randomBytes,scrypt as scryptCallback,timingSafeEqual} from "crypto";
import {promisify} from "util";
import {pool,ensureAuthSchema} from "../_db";
import {currentUser} from "../../../lib/auth-session";

const scrypt=promisify(scryptCallback),SESSION_COOKIE="ludo_session";
async function hashPassword(p:string){const salt=randomBytes(16).toString("hex"),d=await scrypt(p,salt,64) as Buffer;return `${salt}:${d.toString("hex")}`}
async function verifyPassword(p:string,s:string){const [salt,hex]=String(s||"").split(":");if(!salt||!hex)return false;const d=await scrypt(p,salt,64) as Buffer,e=Buffer.from(hex,"hex");return e.length===d.length&&timingSafeEqual(e,d)}
function tokenHash(t:string){return createHash("sha256").update(t).digest("hex")}
async function resetSchema(){await pool.query(`CREATE TABLE IF NOT EXISTS ludo_password_resets(id BIGSERIAL PRIMARY KEY,user_id TEXT NOT NULL REFERENCES ludo_users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS ludo_password_resets_user_idx ON ludo_password_resets(user_id);CREATE INDEX IF NOT EXISTS ludo_password_resets_expiry_idx ON ludo_password_resets(expires_at);`)}
async function sendResetEmail(email:string,username:string,token:string){const key=process.env.RESEND_API_KEY,from=process.env.EMAIL_FROM;if(!key||!from)throw new Error("Password reset email service is not configured.");const base=(process.env.NEXT_PUBLIC_APP_URL||"https://ludo-live.up.railway.app").replace(/\/$/,"");const url=`${base}/reset-password?token=${encodeURIComponent(token)}`;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","User-Agent":"Ludo Live/1.0"},body:JSON.stringify({from,to:[email],subject:"Reset your Ludo Live password",html:`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto"><h2>Ludo Live password reset</h2><p>Hi ${username||"player"},</p><p>We received a request to reset your Ludo Live password.</p><p><a href="${url}" style="display:inline-block;padding:12px 18px;background:#1769e8;color:#fff;text-decoration:none;border-radius:8px">Reset password</a></p><p>This link expires in 30 minutes and can only be used once.</p><p>If you did not request this, you can safely ignore this email.</p></div>`})});if(!r.ok){const text=await r.text();console.error("Password reset email failed",text);throw new Error("Unable to send password reset email.")}}

export async function POST(q:NextRequest){try{await ensureAuthSchema();await resetSchema();const b=await q.json(),action=String(b?.action||"");
if(action==="change_password"){const u=await currentUser(q);if(!u||u.is_guest)return NextResponse.json({error:"Please log in to change your password."},{status:401});const current=String(b.currentPassword||""),next=String(b.newPassword||""),confirm=String(b.confirmPassword||"");if(next.length<6)return NextResponse.json({error:"New password must be at least 6 characters."},{status:400});if(next!==confirm)return NextResponse.json({error:"Passwords do not match."},{status:400});if(!(await verifyPassword(current,u.password_hash||"")))return NextResponse.json({error:"Current password is incorrect."},{status:401});const ph=await hashPassword(next);await pool.query("UPDATE ludo_users SET password_hash=$1 WHERE id=$2",[ph,u.id]);return NextResponse.json({ok:true,message:"Password changed successfully."})}
if(action==="request_reset"){const email=String(b.email||"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return NextResponse.json({error:"Enter a valid email address."},{status:400});const ures=await pool.query<any>("SELECT id,username,email,is_guest,is_banned FROM ludo_users WHERE LOWER(email)=LOWER($1) LIMIT 1",[email]);const u=ures.rows[0];if(u&&!u.is_guest&&!u.is_banned){await pool.query("UPDATE ludo_password_resets SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL",[u.id]);const token=randomBytes(32).toString("hex");await pool.query("INSERT INTO ludo_password_resets(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[u.id,tokenHash(token)]);try{await sendResetEmail(email,u.username,token)}catch(e){console.error(e);return NextResponse.json({error:"Password reset email service is not configured yet."},{status:503})}}return NextResponse.json({ok:true,message:"If an account exists for that email, a password reset link has been sent."})}
if(action==="reset_password"){const token=String(b.token||""),next=String(b.newPassword||""),confirm=String(b.confirmPassword||"");if(!token)return NextResponse.json({error:"This password reset link is invalid."},{status:400});if(next.length<6)return NextResponse.json({error:"New password must be at least 6 characters."},{status:400});if(next!==confirm)return NextResponse.json({error:"Passwords do not match."},{status:400});const r=await pool.query<any>("SELECT * FROM ludo_password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW() LIMIT 1",[tokenHash(token)]),reset=r.rows[0];if(!reset)return NextResponse.json({error:"This password reset link is invalid or has expired."},{status:400});const ph=await hashPassword(next);await pool.query("UPDATE ludo_users SET password_hash=$1 WHERE id=$2",[ph,reset.user_id]);await pool.query("UPDATE ludo_password_resets SET used_at=NOW() WHERE id=$1",[reset.id]);await pool.query("DELETE FROM ludo_sessions WHERE user_id=$1",[reset.user_id]);return NextResponse.json({ok:true,message:"Password reset successfully. Please sign in again."})}
return NextResponse.json({error:"Unknown password action."},{status:400})}catch(e){console.error("Password auth error",e);return NextResponse.json({error:"Password service is temporarily unavailable."},{status:500})}}
