"use client";
import { useEffect, useRef, useState } from "react";
import AppFrame from "../_components/AppFrame";

type Prize={id:string;label:string;icon:string;kind:"coins"|"gems"|"spins"|"mystery";amount:number};
const prizes:Prize[]=[{id:"coins1000",label:"1,000",icon:"🪙",kind:"coins",amount:1000},{id:"gems5",label:"5",icon:"💎",kind:"gems",amount:5},{id:"coins2000",label:"2,000",icon:"🪙",kind:"coins",amount:2000},{id:"gems10",label:"10",icon:"💎",kind:"gems",amount:10},{id:"coins5000a",label:"5,000",icon:"🪙",kind:"coins",amount:5000},{id:"gems15",label:"15",icon:"💎",kind:"gems",amount:15},{id:"coins5000b",label:"5,000",icon:"🪙",kind:"coins",amount:5000},{id:"coins3000",label:"3,000",icon:"🪙",kind:"coins",amount:3000},{id:"mystery",label:"MYSTERY",icon:"🎁",kind:"mystery",amount:1},{id:"freeRoll",label:"FREE",icon:"🎟️",kind:"spins",amount:1}];
const colors=["#6b38d8","#1977d5","#8a38b6","#efad18","#2aa05a","#1977d5","#efad18","#6b38d8","#d63a2f","#2aa05a"];
type Wallet={coins:number;gems:number;spins:number;mystery:number};const defaultWallet:Wallet={coins:25680,gems:320,spins:0,mystery:0};
function readWallet():Wallet{try{return {...defaultWallet,...JSON.parse(localStorage.getItem("ludo-wallet")||"{}")}}catch{return defaultWallet}}
function saveWallet(w:Wallet){localStorage.setItem("ludo-wallet",JSON.stringify(w));localStorage.setItem("ludo-spin-credits",String(w.spins));window.dispatchEvent(new Event("ludo-wallet-updated"))}
function bumpSpinStats(){try{const s=JSON.parse(localStorage.getItem("ludo-stats")||"{}");localStorage.setItem("ludo-stats",JSON.stringify({...s,spinsUsed:(s.spinsUsed||0)+1}));window.dispatchEvent(new Event("ludo-stats-updated"))}catch{}}
function grantDailyFreeSpin():Wallet{const w=readWallet();const today=new Date().toISOString().slice(0,10);if(localStorage.getItem("ludo-daily-spin-date")===today)return w;const next={...w,spins:w.spins+1};localStorage.setItem("ludo-daily-spin-date",today);saveWallet(next);return next}
export default function SpinPage(){const [spinning,setSpinning]=useState(false);const [rotation,setRotation]=useState(0);const [result,setResult]=useState<Prize|null>(null);const [wallet,setWallet]=useState<Wallet>(defaultWallet);const rotationRef=useRef(0);const timer=useRef<number|null>(null);useEffect(()=>{setWallet(grantDailyFreeSpin());return()=>{if(timer.current)window.clearTimeout(timer.current)}},[]);const spin=()=>{if(spinning||wallet.spins<1)return;const winner=Math.floor(Math.random()*prizes.length);const segment=360/prizes.length;const landing=360-(winner*segment+segment/2);const next=rotationRef.current+360*7+landing;rotationRef.current=next;const after={...wallet,spins:wallet.spins-1};saveWallet(after);setWallet(after);setResult(null);setSpinning(true);requestAnimationFrame(()=>requestAnimationFrame(()=>setRotation(next)));timer.current=window.setTimeout(()=>{const p=prizes[winner];const earned={...after};earned[p.kind]+=p.amount;saveWallet(earned);setWallet(earned);setSpinning(false);setResult(p);bumpSpinStats()},6000)};
return <AppFrame back="/home"><main style={page}><header style={top}><span>‹</span><b>Spin Wheel</b><span>ⓘ</span></header><div style={eyebrow}>LUCKY WHEEL</div><h1 style={title}>Spin Wheel</h1><section style={wheelWrap}><div style={pointer}/><div style={{...wheel,transform:`rotate(${rotation}deg)`,transition:spinning?"transform 5.9s cubic-bezier(.08,.72,.12,1)":"none"}}><div style={segments}>{prizes.map((p,i)=>{const a=i*36+18;return <div key={p.id} style={{position:"absolute",left:"50%",top:"50%",width:0,height:0,transform:`rotate(${a}deg)`,transformOrigin:"0 0"}}><div style={{position:"absolute",left:"-52px",top:"-145px",width:104,height:70,display:"flex",justifyContent:"center",alignItems:"center",transform:`rotate(${-a}deg)`,textAlign:"center" as const,color:"#fff",fontSize:11,fontWeight:950,lineHeight:1.05,textShadow:"0 2px 3px #000",whiteSpace:"nowrap"}}>{p.icon}<br/>{p.label}</div></div>})}</div><div style={hub}><b>SPIN</b></div></div></section><div style={timerRow}>Daily Free Spin: <b>{wallet.spins}</b><span>◷ 23:59:59</span></div><button onClick={spin} disabled={spinning||wallet.spins<1} style={{...spinBtn,opacity:spinning?0.7:1}}>{spinning?"Spinning…":"Spin Now"}</button><div style={balances}><span>🎟️ {wallet.spins}</span><span>🪙 {wallet.coins.toLocaleString()}</span><span>💎 {wallet.gems.toLocaleString()}</span></div>{result&&<div style={resultBox}>🎉 <b>You won {result.icon} {result.label}{result.kind==="coins"?" COINS":result.kind==="gems"?" GEMS":result.kind==="spins"?" SPIN":""}</b><small>Added to your player inventory.</small></div>}</main></AppFrame>}
const page:React.CSSProperties={maxWidth:650,margin:"0 auto",paddingBottom:45,textAlign:"center"};const top:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"0 4px 14px",fontSize:18};const eyebrow:React.CSSProperties={fontSize:12,letterSpacing:2,fontWeight:950,color:"#f5cf43"};const title:React.CSSProperties={fontSize:32,margin:"6px 0 12px",fontWeight:950};const wheelWrap:React.CSSProperties={position:"relative",width:"min(86vw,430px)",aspectRatio:"1",margin:"8px auto 12px"};const pointer:React.CSSProperties={position:"absolute",zIndex:30,left:"50%",top:-4,transform:"translateX(-50%)",width:0,height:0,borderLeft:"22px solid transparent",borderRight:"22px solid transparent",borderTop:"42px solid #ffdf55",filter:"drop-shadow(0 3px 2px #000)"};const wheel:React.CSSProperties={position:"absolute",inset:8,borderRadius:"50%",padding:7,background:"linear-gradient(145deg,#ffea6b,#a76609 35%,#f5bf2d 58%,#7d4705)",boxShadow:"0 0 0 3px #3a2105,0 8px 28px #0008"};const segments:React.CSSProperties={position:"relative",width:"100%",height:"100%",borderRadius:"50%",overflow:"hidden",background:`conic-gradient(${colors.map((c,i)=>`${c} ${i*36}deg ${(i+1)*36}deg`).join(",")})`,border:"4px solid #3a2105",boxShadow:"inset 0 0 0 2px #f7df70,inset 0 0 30px #0008"};const hub:React.CSSProperties={position:"absolute",left:"50%",top:"50%",transform:"translate(-50%,-50%)",width:88,height:88,borderRadius:"50%",display:"grid",placeItems:"center",background:"radial-gradient(circle at 35% 30%,#b7ff73,#43a92b 55%,#14610d)",border:"6px solid #4a2904",boxShadow:"0 4px 12px #0009",color:"#fff",fontSize:20};const timerRow:React.CSSProperties={margin:"7px auto 10px",padding:12,borderRadius:10,background:"#231244",color:"#ddd5ed",fontSize:12,display:"flex",justifyContent:"center",gap:12};const spinBtn:React.CSSProperties={width:"100%",maxWidth:420,border:0,borderRadius:7,padding:13,background:"linear-gradient(180deg,#43d923,#1e9c10)",color:"#fff",fontWeight:950,fontSize:17};const balances:React.CSSProperties={display:"flex",justifyContent:"center",gap:8,flexWrap:"wrap",marginTop:12};const resultBox:React.CSSProperties={marginTop:12,padding:12,borderRadius:10,background:"#082c18",border:"1px solid #2ab55d",display:"grid",gap:4};
